"""Event schemas package — re-exports all schemas for backward compatibility."""

from .core import (
    BookingOptionCreateIn,
    BookingOptionOut,
    BookingOptionUpdateIn,
    ChoiceOut,
    EventCreateIn,
    EventDetailOut,
    EventListOut,
    EventLocationCreateIn,
    EventLocationOut,
    EventLocationUpdateIn,
    EventPhase,
    EventUpdateIn,
    GenerateInvitationIn,
    GenerateInvitationOut,
    InvitationCountsOut,
    InvitationStatusOut,
    InviteGroupIn,
    OptionStatsOut,
    PaginatedEventListOut,
    PaginatedInvitationStatusOut,
    PaginatedLocationOut,
    PaginatedParticipantOut,
    PaginatedPersonOut,
    ParticipantOut,
    ParticipantStatsOut,
    ParticipantUpdateIn,
    PersonCreateIn,
    PersonOut,
    PersonUpdateIn,
    RegisterIn,
    RegisterPersonIn,
    RegistrationOut,
    ResponsiblePersonOut,
    UserRegistrationOut,
)
from .custom_fields import (
    CustomFieldCreateIn,
    CustomFieldOut,
    CustomFieldUpdateIn,
    CustomFieldValueOut,
    CustomFieldValueSetIn,
    CustomFieldValuesIn,
)
from .day_slots import (
    EventDaySlotCreateIn,
    EventDaySlotOut,
    EventDaySlotUpdateIn,
)
from .export import (
    ExportColumnOut,
    ExportConfigIn,
    ExportFilterIn,
)
from .labels import (
    LabelAssignIn,
    LabelCreateIn,
    LabelOut,
    LabelUpdateIn,
)
from .mail import (
    FailedRecipientOut,
    MailCreateIn,
    MailFilterIn,
    MailResultOut,
)
from .payment import (
    PaymentCreateIn,
    PaymentOut,
)
from .stats import (
    StatsOut,
)
from .timeline import TimelineEntryOut

__all__ = [
    "BookingOptionCreateIn",
    "BookingOptionOut",
    "BookingOptionUpdateIn",
    "ChoiceOut",
    "CustomFieldCreateIn",
    "CustomFieldOut",
    "CustomFieldUpdateIn",
    "CustomFieldValueOut",
    "CustomFieldValueSetIn",
    "CustomFieldValuesIn",
    "EventCreateIn",
    "EventDaySlotCreateIn",
    "EventDaySlotOut",
    "EventDaySlotUpdateIn",
    "EventDetailOut",
    "EventListOut",
    "EventLocationCreateIn",
    "EventLocationOut",
    "EventLocationUpdateIn",
    "EventPhase",
    "EventUpdateIn",
    "ExportColumnOut",
    "ExportConfigIn",
    "ExportFilterIn",
    "GenerateInvitationIn",
    "GenerateInvitationOut",
    "InvitationCountsOut",
    "InvitationStatusOut",
    "InviteGroupIn",
    "LabelAssignIn",
    "LabelCreateIn",
    "LabelOut",
    "LabelUpdateIn",
    "MailCreateIn",
    "MailFilterIn",
    "MailResultOut",
    "FailedRecipientOut",
    "OptionStatsOut",
    "PaginatedEventListOut",
    "PaginatedInvitationStatusOut",
    "PaginatedLocationOut",
    "PaginatedParticipantOut",
    "PaginatedPersonOut",
    "ParticipantOut",
    "ParticipantStatsOut",
    "ParticipantUpdateIn",
    "PaymentCreateIn",
    "PaymentOut",
    "PersonCreateIn",
    "PersonOut",
    "PersonUpdateIn",
    "RegisterIn",
    "RegisterPersonIn",
    "RegistrationOut",
    "ResponsiblePersonOut",
    "StatsOut",
    "TimelineEntryOut",
    "UserRegistrationOut",
]
