# Generated by Django 5.2.12 on 2026-03-24 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0002_userprofile_is_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                ("location", models.CharField(blank=True, default="", max_length=200, verbose_name="Ort")),
                ("start_date", models.DateTimeField(blank=True, null=True, verbose_name="Startdatum")),
                ("end_date", models.DateTimeField(blank=True, null=True, verbose_name="Enddatum")),
                ("registration_deadline", models.DateTimeField(blank=True, null=True, verbose_name="Anmeldeschluss")),
                ("registration_start", models.DateTimeField(blank=True, null=True, verbose_name="Anmeldestart")),
                ("is_public", models.BooleanField(default=False, verbose_name="Öffentlich")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "invited_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invited_events",
                        to="profiles.usergroup",
                        verbose_name="Eingeladene Gruppen",
                    ),
                ),
                (
                    "invited_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invited_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eingeladene Benutzer",
                    ),
                ),
                (
                    "responsible_persons",
                    models.ManyToManyField(
                        blank=True,
                        related_name="managed_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verantwortliche",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veranstaltung",
                "verbose_name_plural": "Veranstaltungen",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="BookingOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="Preis")),
                (
                    "max_participants",
                    models.IntegerField(default=0, help_text="0 = unbegrenzt", verbose_name="Max. Teilnehmer"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_options",
                        to="event.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buchungsoption",
                "verbose_name_plural": "Buchungsoptionen",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scout_name", models.CharField(blank=True, default="", max_length=100, verbose_name="Pfadfindername")),
                ("first_name", models.CharField(max_length=100, verbose_name="Vorname")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nachname")),
                ("address", models.CharField(blank=True, default="", max_length=200, verbose_name="Adresse")),
                ("zip_code", models.CharField(blank=True, default="", max_length=10, verbose_name="PLZ")),
                ("email", models.EmailField(blank=True, default="", max_length=254, verbose_name="E-Mail")),
                ("birthday", models.DateField(blank=True, null=True, verbose_name="Geburtstag")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Männlich"),
                            ("female", "Weiblich"),
                            ("diverse", "Divers"),
                            ("no_answer", "Keine Angabe"),
                        ],
                        default="no_answer",
                        max_length=20,
                        verbose_name="Geschlecht",
                    ),
                ),
                (
                    "eat_habits",
                    models.CharField(
                        choices=[("vegetarian", "Vegetarisch"), ("vegan", "Vegan"), ("all", "Alles")],
                        default="all",
                        max_length=20,
                        verbose_name="Essgewohnheiten",
                    ),
                ),
                (
                    "is_owner",
                    models.BooleanField(
                        default=False,
                        help_text="True wenn diese Person den Benutzer selbst repräsentiert",
                        verbose_name="Eigenes Profil",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Personen",
                "ordering": ["-is_owner", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="event.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anmeldung",
                "verbose_name_plural": "Anmeldungen",
                "unique_together": {("user", "event")},
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scout_name", models.CharField(blank=True, default="", max_length=100, verbose_name="Pfadfindername")),
                ("first_name", models.CharField(max_length=100, verbose_name="Vorname")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nachname")),
                ("address", models.CharField(blank=True, default="", max_length=200, verbose_name="Adresse")),
                ("zip_code", models.CharField(blank=True, default="", max_length=10, verbose_name="PLZ")),
                ("email", models.EmailField(blank=True, default="", max_length=254, verbose_name="E-Mail")),
                ("birthday", models.DateField(blank=True, null=True, verbose_name="Geburtstag")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Männlich"),
                            ("female", "Weiblich"),
                            ("diverse", "Divers"),
                            ("no_answer", "Keine Angabe"),
                        ],
                        default="no_answer",
                        max_length=20,
                        verbose_name="Geschlecht",
                    ),
                ),
                (
                    "eat_habits",
                    models.CharField(
                        choices=[("vegetarian", "Vegetarisch"), ("vegan", "Vegan"), ("all", "Alles")],
                        default="all",
                        max_length=20,
                        verbose_name="Essgewohnheiten",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Bezahlt")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participants",
                        to="event.bookingoption",
                        verbose_name="Buchungsoption",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participations",
                        to="event.person",
                        verbose_name="Originalperson",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="event.registration",
                        verbose_name="Anmeldung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teilnehmer",
                "verbose_name_plural": "Teilnehmer",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
