# Generated by Django 5.2.12 on 2026-07-13 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Preis')),
                ('max_participants', models.IntegerField(default=0, help_text='0 = unbegrenzt', verbose_name='Max. Teilnehmer')),
                ('is_system', models.BooleanField(default=False, help_text='Automatisch erstellte Option, nicht editierbar', verbose_name='System-Option')),
                ('bookable_from', models.DateTimeField(blank=True, help_text='Leer = sofort buchbar', null=True, verbose_name='Buchbar ab')),
                ('bookable_till', models.DateTimeField(blank=True, help_text='Leer = bis zum Anmeldeschluss buchbar', null=True, verbose_name='Buchbar bis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Buchungsoption',
                'verbose_name_plural': 'Buchungsoptionen',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Die Frage oder das Feldlabel', max_length=255, verbose_name='Label')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('select', 'Auswahl'), ('checkbox', 'Checkbox'), ('date', 'Datum'), ('number', 'Zahl')], max_length=20, verbose_name='Feldtyp')),
                ('options', models.JSONField(blank=True, help_text='Liste von Strings für Auswahl-Felder', null=True, verbose_name='Optionen')),
                ('is_required', models.BooleanField(default=False, verbose_name='Pflichtfeld')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Benutzerdefiniertes Feld',
                'verbose_name_plural': 'Benutzerdefinierte Felder',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventDaySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Startzeit')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Endzeit')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notizen')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Objekt-ID')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tagesplan-Eintrag',
                'verbose_name_plural': 'Tagesplan-Einträge',
                'ordering': ['date', 'sort_order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('street', models.CharField(blank=True, default='', max_length=200, verbose_name='Straße')),
                ('zip_code', models.CharField(blank=True, default='', max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Stadt')),
                ('state', models.CharField(blank=True, default='', max_length=100, verbose_name='Bundesland')),
                ('country', models.CharField(blank=True, default='Deutschland', max_length=100, verbose_name='Land')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Breitengrad')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Längengrad')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veranstaltungsort',
                'verbose_name_plural': 'Veranstaltungsorte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeetingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('street', models.CharField(blank=True, default='', max_length=200, verbose_name='Straße')),
                ('zip_code', models.CharField(blank=True, default='', max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Stadt')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Breitengrad')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Längengrad')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Treffpunkt',
                'verbose_name_plural': 'Treffpunkte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('subject', models.CharField(blank=True, default='', help_text='Nur für E-Mail relevant', max_length=200, verbose_name='Betreff')),
                ('body', models.TextField(verbose_name='Inhalt')),
                ('is_system', models.BooleanField(default=False, verbose_name='System-Vorlage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nachrichtenvorlage',
                'verbose_name_plural': 'Nachrichtenvorlagen',
                'ordering': ['-is_system', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ParentAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('email', models.CharField(blank=True, default='', max_length=254, verbose_name='E-Mail-Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('expires_at', models.DateTimeField(verbose_name='Gültig bis')),
            ],
            options={
                'verbose_name': 'Elternzugangs-Token',
                'verbose_name_plural': 'Elternzugangs-Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scout_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Pfadfindername')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='Adresse')),
                ('zip_code', models.CharField(blank=True, default='', max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Stadt')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-Mail')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefonnummer')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Geburtstag')),
                ('gender', models.CharField(choices=[('male', 'Männlich'), ('female', 'Weiblich'), ('diverse', 'Divers'), ('no_answer', 'Keine Angabe')], default='no_answer', max_length=20, verbose_name='Geschlecht')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teilnehmer',
                'verbose_name_plural': 'Teilnehmer',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('color', models.CharField(default='#4CAF50', help_text='Hex-Farbcode, z.B. #FF5733', max_length=7, verbose_name='Farbe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Teilnehmer-Label',
                'verbose_name_plural': 'Teilnehmer-Labels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Betrag')),
                ('method', models.CharField(choices=[('bar', 'Bar'), ('paypal', 'PayPal'), ('ueberweisung', 'Überweisung'), ('sonstige', 'Sonstige')], max_length=20, verbose_name='Zahlungsmethode')),
                ('received_at', models.DateTimeField(verbose_name='Empfangen am')),
                ('location', models.CharField(blank=True, default='', help_text='Wo wurde das Geld empfangen', max_length=200, verbose_name='Ort')),
                ('note', models.TextField(blank=True, default='', verbose_name='Notiz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scout_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Pfadfindername')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='Adresse')),
                ('zip_code', models.CharField(blank=True, default='', max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Stadt')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-Mail')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefonnummer')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Geburtstag')),
                ('gender', models.CharField(choices=[('male', 'Männlich'), ('female', 'Weiblich'), ('diverse', 'Divers'), ('no_answer', 'Keine Angabe')], default='no_answer', max_length=20, verbose_name='Geschlecht')),
                ('is_owner', models.BooleanField(default=False, verbose_name='Ist Eigentümer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personen',
                'ordering': ['-is_owner', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Gelöscht am')),
                ('deleted_reason', models.CharField(blank=True, choices=[('duplicate', 'Duplikat'), ('error', 'Fehler'), ('cancel', 'Stornierung'), ('other', 'Sonstiges')], default='', max_length=20, verbose_name='Löschgrund')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anmeldung',
                'verbose_name_plural': 'Anmeldungen',
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('capacity', models.IntegerField(default=0, help_text='0 = unbegrenzt', verbose_name='Kapazität')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sortierung')),
            ],
            options={
                'verbose_name': 'Zimmereinteilung',
                'verbose_name_plural': 'Zimmereinteilungen',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('registered', 'Angemeldet'), ('unregistered', 'Abgemeldet'), ('payment_received', 'Zahlung erhalten'), ('payment_removed', 'Zahlung entfernt'), ('booking_changed', 'Buchungsoption geändert'), ('label_added', 'Label hinzugefügt'), ('label_removed', 'Label entfernt'), ('custom_field_updated', 'Benutzerdefiniertes Feld aktualisiert'), ('mail_sent', 'E-Mail gesendet'), ('participant_updated', 'Teilnehmer aktualisiert'), ('attendance_check_in', 'Eingecheckt'), ('attendance_check_out', 'Ausgecheckt'), ('participants_imported', 'Teilnehmer importiert'), ('whatsapp_sent', 'WhatsApp gesendet')], max_length=30, verbose_name='Aktionstyp')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadaten')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Timeline-Eintrag',
                'verbose_name_plural': 'Timeline-Einträge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Benachrichtigt am')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgelaufen am')),
            ],
            options={
                'verbose_name': 'Wartelisten-Eintrag',
                'verbose_name_plural': 'Wartelisten-Einträge',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=255, verbose_name='Telefonnummer')),
                ('session_db_name', models.CharField(blank=True, default='', help_text='Name der neonize-Session in PostgreSQL', max_length=100, verbose_name='Session DB Name')),
                ('connected_at', models.DateTimeField(blank=True, null=True, verbose_name='Verbunden seit')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktiv')),
                ('total_messages_sent', models.PositiveIntegerField(default=0, verbose_name='Gesendete Nachrichten gesamt')),
                ('privacy_consent_given_at', models.DateTimeField(blank=True, null=True, verbose_name='Datenschutz-Einwilligung')),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True, verbose_name='Letzter Health Check')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp-Verbindung',
                'verbose_name_plural': 'WhatsApp-Verbindungen',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('connected', 'Verbunden'), ('disconnected', 'Getrennt'), ('health_check_ok', 'Health Check OK'), ('health_check_failed', 'Health Check fehlgeschlagen'), ('reconnect_success', 'Reconnect erfolgreich'), ('reconnect_failed', 'Reconnect fehlgeschlagen'), ('test_sent', 'Test gesendet'), ('test_failed', 'Test fehlgeschlagen')], max_length=30, verbose_name='Ereignistyp')),
                ('message', models.TextField(blank=True, default='', verbose_name='Nachricht')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WhatsApp-Verbindungslog',
                'verbose_name_plural': 'WhatsApp-Verbindungslogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('sent', 'Gesendet'), ('delivered', 'Zugestellt'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesendet am')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Fehlermeldung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WhatsApp-Nachricht',
                'verbose_name_plural': 'WhatsApp-Nachrichten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Eingecheckt am')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Ausgecheckt am')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_check_ins', to=settings.AUTH_USER_MODEL, verbose_name='Eingecheckt von')),
            ],
            options={
                'verbose_name': 'Anwesenheit',
                'verbose_name_plural': 'Anwesenheiten',
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Beschreibung')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Betrag')),
                ('category', models.CharField(choices=[('material', 'Material'), ('food', 'Verpflegung'), ('transport', 'Transport'), ('venue', 'Unterkunft'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Kategorie')),
                ('is_expense', models.BooleanField(default=True, verbose_name='Ist Ausgabe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_items', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Budget-Posten',
                'verbose_name_plural': 'Budget-Posten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='', verbose_name='Wert')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='event.customfield', verbose_name='Feld')),
            ],
            options={
                'verbose_name': 'Feldwert',
                'verbose_name_plural': 'Feldwerte',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('color', models.CharField(choices=[('slate', 'Schiefergrau'), ('red', 'Rot'), ('orange', 'Orange'), ('amber', 'Bernstein'), ('yellow', 'Gelb'), ('lime', 'Limette'), ('green', 'Grün'), ('emerald', 'Smaragd'), ('teal', 'Türkis'), ('cyan', 'Cyan'), ('blue', 'Blau'), ('violet', 'Violett'), ('purple', 'Lila'), ('pink', 'Pink'), ('rose', 'Rosa')], default='blue', max_length=20, verbose_name='Farbe')),
                ('icon', models.CharField(choices=[('tent', 'Zelt'), ('flame', 'Feuer'), ('compass', 'Kompass'), ('map', 'Karte'), ('mountain', 'Berg'), ('tree-pine', 'Baum'), ('sun', 'Sonne'), ('moon', 'Mond'), ('star', 'Stern'), ('heart', 'Herz'), ('flag', 'Flagge'), ('users', 'Gruppe'), ('music', 'Musik'), ('book', 'Buch'), ('utensils', 'Besteck'), ('backpack', 'Rucksack'), ('flashlight', 'Taschenlampe'), ('binoculars', 'Fernglas'), ('anchor', 'Anker'), ('shield', 'Schild'), ('award', 'Auszeichnung'), ('crown', 'Krone'), ('zap', 'Blitz'), ('cloud', 'Wolke'), ('snowflake', 'Schneeflocke'), ('umbrella', 'Regenschirm'), ('leaf', 'Blatt'), ('fish', 'Fisch'), ('bird', 'Vogel'), ('map-pin', 'Kartennadel'), ('calendar', 'Kalender'), ('home', 'Haus'), ('coffee', 'Kaffee'), ('palette', 'Palette'), ('sparkles', 'Funken'), ('rocket', 'Rakete')], default='tent', max_length=30, verbose_name='Icon')),
                ('is_template', models.BooleanField(default=False, help_text='Event als Vorlage verwenden (wird nicht veröffentlicht)', verbose_name='Vorlage')),
                ('manual_phase', models.CharField(blank=True, choices=[('draft', 'Entwurf'), ('pre_registration', 'Vor der Anmeldung'), ('registration', 'Anmeldung offen'), ('pre_event', 'Vor dem Event'), ('running', 'Event läuft'), ('completed', 'Abgeschlossen')], help_text='Überschreibt die automatisch berechnete Phase', max_length=20, null=True, verbose_name='Manuelle Phase')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Ort')),
                ('invitation_text', models.TextField(blank=True, default='', verbose_name='Einladungstext')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Startdatum')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Enddatum')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Anmeldeschluss')),
                ('registration_start', models.DateTimeField(blank=True, null=True, verbose_name='Anmeldestart')),
                ('is_public', models.BooleanField(default=False, verbose_name='Öffentlich')),
                ('guest_registration_enabled', models.BooleanField(default=False, help_text='Erlaubt Anmeldung ohne Account per Link', verbose_name='Gastregistrierung')),
                ('participant_visibility', models.CharField(choices=[('none', 'Nicht sichtbar'), ('total_only', 'Nur Gesamtzahl'), ('per_option', 'Zahlen pro Buchungsoption'), ('with_names', 'Zahlen und Vornamen')], default='none', help_text='Was eingeladene Teilnehmende über Anmeldezahlen sehen dürfen', max_length=20, verbose_name='Teilnehmer-Sichtbarkeit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Veranstaltung',
                'verbose_name_plural': 'Veranstaltungen',
                'ordering': ['-start_date'],
            },
        ),
    ]
