# Generated by Django 5.2.12 on 2026-04-06 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="Preis")),
                (
                    "max_participants",
                    models.IntegerField(default=0, help_text="0 = unbegrenzt", verbose_name="Max. Teilnehmer"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Buchungsoption",
                "verbose_name_plural": "Buchungsoptionen",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="EventDaySlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Datum")),
                ("start_time", models.TimeField(blank=True, null=True, verbose_name="Startzeit")),
                ("end_time", models.TimeField(blank=True, null=True, verbose_name="Endzeit")),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notizen")),
                ("object_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="Objekt-ID")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sortierung")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tagesplan-Eintrag",
                "verbose_name_plural": "Tagesplan-Eintraege",
                "ordering": ["date", "sort_order", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="EventLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("street", models.CharField(blank=True, default="", max_length=200, verbose_name="Straße")),
                ("zip_code", models.CharField(blank=True, default="", max_length=10, verbose_name="PLZ")),
                ("city", models.CharField(blank=True, default="", max_length=100, verbose_name="Stadt")),
                ("state", models.CharField(blank=True, default="", max_length=100, verbose_name="Bundesland")),
                ("country", models.CharField(blank=True, default="Deutschland", max_length=100, verbose_name="Land")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Veranstaltungsort",
                "verbose_name_plural": "Veranstaltungsorte",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scout_name", models.CharField(blank=True, default="", max_length=100, verbose_name="Pfadfindername")),
                ("first_name", models.CharField(max_length=100, verbose_name="Vorname")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nachname")),
                ("address", models.CharField(blank=True, default="", max_length=200, verbose_name="Adresse")),
                ("zip_code", models.CharField(blank=True, default="", max_length=10, verbose_name="PLZ")),
                ("city", models.CharField(blank=True, default="", max_length=100, verbose_name="Stadt")),
                ("email", models.EmailField(blank=True, default="", max_length=254, verbose_name="E-Mail")),
                ("birthday", models.DateField(blank=True, null=True, verbose_name="Geburtstag")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Männlich"),
                            ("female", "Weiblich"),
                            ("diverse", "Divers"),
                            ("no_answer", "Keine Angabe"),
                        ],
                        default="no_answer",
                        max_length=20,
                        verbose_name="Geschlecht",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Bezahlt")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Teilnehmer",
                "verbose_name_plural": "Teilnehmer",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scout_name", models.CharField(blank=True, default="", max_length=100, verbose_name="Pfadfindername")),
                ("first_name", models.CharField(max_length=100, verbose_name="Vorname")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nachname")),
                ("address", models.CharField(blank=True, default="", max_length=200, verbose_name="Adresse")),
                ("zip_code", models.CharField(blank=True, default="", max_length=10, verbose_name="PLZ")),
                ("city", models.CharField(blank=True, default="", max_length=100, verbose_name="Stadt")),
                ("email", models.EmailField(blank=True, default="", max_length=254, verbose_name="E-Mail")),
                ("birthday", models.DateField(blank=True, null=True, verbose_name="Geburtstag")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Männlich"),
                            ("female", "Weiblich"),
                            ("diverse", "Divers"),
                            ("no_answer", "Keine Angabe"),
                        ],
                        default="no_answer",
                        max_length=20,
                        verbose_name="Geschlecht",
                    ),
                ),
                ("is_owner", models.BooleanField(default=False, verbose_name="Ist Eigentümer")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Personen",
                "ordering": ["-is_owner", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Anmeldung",
                "verbose_name_plural": "Anmeldungen",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                ("location", models.CharField(blank=True, default="", max_length=200, verbose_name="Ort")),
                ("invitation_text", models.TextField(blank=True, default="", verbose_name="Einladungstext")),
                ("start_date", models.DateTimeField(blank=True, null=True, verbose_name="Startdatum")),
                ("end_date", models.DateTimeField(blank=True, null=True, verbose_name="Enddatum")),
                ("registration_deadline", models.DateTimeField(blank=True, null=True, verbose_name="Anmeldeschluss")),
                ("registration_start", models.DateTimeField(blank=True, null=True, verbose_name="Anmeldestart")),
                ("is_public", models.BooleanField(default=False, verbose_name="Öffentlich")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veranstaltung",
                "verbose_name_plural": "Veranstaltungen",
                "ordering": ["-start_date"],
            },
        ),
    ]
