# Generated by Django 5.2.12 on 2026-03-24 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="invitation_text",
            field=models.TextField(blank=True, default="", verbose_name="Einladungstext"),
        ),
        migrations.CreateModel(
            name="EventLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("street", models.CharField(blank=True, default="", max_length=200, verbose_name="Straße")),
                ("zip_code", models.CharField(blank=True, default="", max_length=10, verbose_name="PLZ")),
                ("city", models.CharField(blank=True, default="", max_length=100, verbose_name="Stadt")),
                ("state", models.CharField(blank=True, default="", max_length=100, verbose_name="Bundesland")),
                ("country", models.CharField(blank=True, default="Deutschland", max_length=100, verbose_name="Land")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_locations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veranstaltungsort",
                "verbose_name_plural": "Veranstaltungsorte",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="event_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="event.eventlocation",
                verbose_name="Veranstaltungsort",
            ),
        ),
    ]
