# Generated by Django 5.2.12 on 2026-04-06 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("event", "0001_initial"),
        ("packinglist", "0002_initial"),
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="invited_groups",
            field=models.ManyToManyField(
                blank=True, related_name="invited_events", to="profiles.usergroup", verbose_name="Eingeladene Gruppen"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="invited_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="invited_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eingeladene Benutzer",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="packing_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="packinglist.packinglist",
                verbose_name="Packliste",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="responsible_persons",
            field=models.ManyToManyField(
                blank=True, related_name="managed_events", to=settings.AUTH_USER_MODEL, verbose_name="Verantwortliche"
            ),
        ),
        migrations.AddField(
            model_name="bookingoption",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_options",
                to="event.event",
                verbose_name="Event",
            ),
        ),
        migrations.AddField(
            model_name="eventdayslot",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_day_slots",
                to="contenttypes.contenttype",
                verbose_name="Inhaltstyp",
            ),
        ),
        migrations.AddField(
            model_name="eventdayslot",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_day_slots",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AddField(
            model_name="eventdayslot",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day_slots",
                to="event.event",
                verbose_name="Event",
            ),
        ),
        migrations.AddField(
            model_name="eventlocation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_locations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="event.eventlocation",
                verbose_name="Veranstaltungsort",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="booking_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participants",
                to="event.bookingoption",
                verbose_name="Buchungsoption",
            ),
        ),
    ]
