# Generated by Django 5.2.12 on 2026-03-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_event_invitation_text_eventlocation_and_more"),
        ("idea", "0011_merge_materialunit_into_measuringunit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Person",
                "verbose_name_plural": "Personen",
            },
        ),
        migrations.RemoveField(
            model_name="participant",
            name="eat_habits",
        ),
        migrations.RemoveField(
            model_name="person",
            name="eat_habits",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_owner",
        ),
        migrations.AddField(
            model_name="participant",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Stadt"),
        ),
        migrations.AddField(
            model_name="participant",
            name="nutritional_tags",
            field=models.ManyToManyField(
                blank=True, related_name="participants", to="idea.nutritionaltag", verbose_name="Ernährungstags"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Stadt"),
        ),
        migrations.AddField(
            model_name="person",
            name="nutritional_tags",
            field=models.ManyToManyField(
                blank=True, related_name="persons", to="idea.nutritionaltag", verbose_name="Ernährungstags"
            ),
        ),
    ]
