# Generated by Django 5.2.12 on 2026-04-06 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0002_initial"),
        ("supply", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="nutritional_tags",
            field=models.ManyToManyField(
                blank=True, related_name="participants", to="supply.nutritionaltag", verbose_name="Ernährungstags"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="nutritional_tags",
            field=models.ManyToManyField(
                blank=True, related_name="persons", to="supply.nutritionaltag", verbose_name="Ernährungstags"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="persons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Benutzer",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participations",
                to="event.person",
                verbose_name="Originalperson",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="event.event",
                verbose_name="Event",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_registrations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Benutzer",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="event.registration",
                verbose_name="Anmeldung",
            ),
        ),
        migrations.AddIndex(
            model_name="eventdayslot",
            index=models.Index(fields=["event", "date"], name="eventdayslot_event_date_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("user", "event")},
        ),
    ]
