# Generated by Django 5.2.12 on 2026-07-13 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_initial'),
        ('supply', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='nutritional_tags',
            field=models.ManyToManyField(blank=True, related_name='participants', to='supply.nutritionaltag', verbose_name='Ernährungstags'),
        ),
        migrations.AddField(
            model_name='parentaccesstoken',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_tokens', to='event.participant', verbose_name='Teilnehmer'),
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='event.participant', verbose_name='Teilnehmer'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='event.participant', verbose_name='Teilnehmer'),
        ),
        migrations.AddField(
            model_name='participantlabel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_labels', to='event.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='participant',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='participants', to='event.participantlabel', verbose_name='Labels'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='Erfasst von'),
        ),
        migrations.AddField(
            model_name='payment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='event.participant', verbose_name='Teilnehmer'),
        ),
        migrations.AddField(
            model_name='person',
            name='nutritional_tags',
            field=models.ManyToManyField(blank=True, related_name='persons', to='supply.nutritionaltag', verbose_name='Ernährungstags'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AddField(
            model_name='participant',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='event.person', verbose_name='Originalperson'),
        ),
        migrations.AddField(
            model_name='registration',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Gelöscht von'),
        ),
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='event.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AddField(
            model_name='participant',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='event.registration', verbose_name='Anmeldung'),
        ),
        migrations.AddField(
            model_name='roomassignment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='event.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='roomassignment',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='room_assignments', to='event.participant', verbose_name='Teilnehmer'),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='event.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_entries', to='event.participant', verbose_name='Teilnehmer'),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Der Benutzer, der die Aktion ausgeführt hat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_timeline_entries', to=settings.AUTH_USER_MODEL, verbose_name='Akteur'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='booking_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='event.bookingoption', verbose_name='Buchungsoption'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='event.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='event.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AddField(
            model_name='whatsappconnection',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_connection', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AddField(
            model_name='whatsappconnectionlog',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='event.whatsappconnection', verbose_name='Verbindung'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='event.whatsappconnection', verbose_name='Verbindung'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='event.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='event.participant', verbose_name='Teilnehmer'),
        ),
        migrations.AddConstraint(
            model_name='bookingoption',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('event',), name='unique_system_booking_option_per_event'),
        ),
        migrations.AddIndex(
            model_name='eventdayslot',
            index=models.Index(fields=['event', 'date'], name='eventdayslot_event_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_public', 'is_template', 'start_date'], name='event_public_landing_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together={('custom_field', 'participant')},
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('user', 'event')},
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(fields=['event', '-created_at'], name='timeline_event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(fields=['event', 'action_type'], name='timeline_event_action_idx'),
        ),
    ]
