# Generated by Django 5.2.12 on 2026-04-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_alter_person_options_remove_participant_eat_habits_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["-is_owner", "last_name", "first_name"],
                "verbose_name": "Person",
                "verbose_name_plural": "Personen",
            },
        ),
        migrations.AddField(
            model_name="person",
            name="is_owner",
            field=models.BooleanField(default=False, verbose_name="Ist Eigentümer"),
        ),
    ]
