# Generated by Django 5.2.12 on 2026-08-08 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_initial'),
        ('planner', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMealPlanRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_relations', to='event.event', verbose_name='Veranstaltung')),
                ('meal_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_relation', to='planner.mealplan', verbose_name='Essensplan')),
            ],
            options={
                'verbose_name': 'Event-Essensplan-Verknüpfung',
                'verbose_name_plural': 'Event-Essensplan-Verknüpfungen',
                'indexes': [models.Index(fields=['event', 'meal_plan'], name='event_event_event_i_6d74fe_idx')],
            },
        ),
    ]
