# Generated by Django 5.2.12 on 2026-04-06 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="is_paid",
        ),
        migrations.CreateModel(
            name="CustomField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "label",
                    models.CharField(help_text="Die Frage oder das Feldlabel", max_length=255, verbose_name="Label"),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("select", "Auswahl"),
                            ("checkbox", "Checkbox"),
                            ("date", "Datum"),
                            ("number", "Zahl"),
                        ],
                        max_length=20,
                        verbose_name="Feldtyp",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True, help_text="Liste von Strings für Auswahl-Felder", null=True, verbose_name="Optionen"
                    ),
                ),
                ("is_required", models.BooleanField(default=False, verbose_name="Pflichtfeld")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Reihenfolge")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="event.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benutzerdefiniertes Feld",
                "verbose_name_plural": "Benutzerdefinierte Felder",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ParticipantLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "color",
                    models.CharField(
                        default="#4CAF50", help_text="Hex-Farbcode, z.B. #FF5733", max_length=7, verbose_name="Farbe"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_labels",
                        to="event.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teilnehmer-Label",
                "verbose_name_plural": "Teilnehmer-Labels",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="participant",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="participants", to="event.participantlabel", verbose_name="Labels"
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7, verbose_name="Betrag")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("bar", "Bar"),
                            ("paypal", "PayPal"),
                            ("ueberweisung", "Überweisung"),
                            ("sonstige", "Sonstige"),
                        ],
                        max_length=20,
                        verbose_name="Zahlungsmethode",
                    ),
                ),
                ("received_at", models.DateTimeField(verbose_name="Empfangen am")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Wo wurde das Geld empfangen",
                        max_length=200,
                        verbose_name="Ort",
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="Notiz")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erfasst von",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="event.participant",
                        verbose_name="Teilnehmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zahlung",
                "verbose_name_plural": "Zahlungen",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.TextField(blank=True, default="", verbose_name="Wert")),
                (
                    "custom_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="event.customfield",
                        verbose_name="Feld",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="event.participant",
                        verbose_name="Teilnehmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feldwert",
                "verbose_name_plural": "Feldwerte",
                "unique_together": {("custom_field", "participant")},
            },
        ),
        migrations.CreateModel(
            name="TimelineEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("registered", "Angemeldet"),
                            ("unregistered", "Abgemeldet"),
                            ("payment_received", "Zahlung erhalten"),
                            ("payment_removed", "Zahlung entfernt"),
                            ("booking_changed", "Buchungsoption geändert"),
                            ("label_added", "Label hinzugefügt"),
                            ("label_removed", "Label entfernt"),
                            ("custom_field_updated", "Benutzerdefiniertes Feld aktualisiert"),
                            ("mail_sent", "E-Mail gesendet"),
                            ("participant_updated", "Teilnehmer aktualisiert"),
                        ],
                        max_length=30,
                        verbose_name="Aktionstyp",
                    ),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadaten")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_entries",
                        to="event.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline_entries",
                        to="event.participant",
                        verbose_name="Teilnehmer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Der Benutzer, der die Aktion ausgeführt hat",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_timeline_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Akteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timeline-Eintrag",
                "verbose_name_plural": "Timeline-Einträge",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["event", "-created_at"], name="timeline_event_created_idx"),
                    models.Index(fields=["event", "action_type"], name="timeline_event_action_idx"),
                ],
            },
        ),
    ]
