# Generated by Django 5.2.12 on 2026-04-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_remove_participant_is_paid_customfield_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventdayslot",
            options={
                "ordering": ["date", "sort_order", "start_time"],
                "verbose_name": "Tagesplan-Eintrag",
                "verbose_name_plural": "Tagesplan-Einträge",
            },
        ),
    ]
