# Generated by Django 5.2.12 on 2026-04-03 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_alter_person_options_person_is_owner"),
        ("packinglist", "0002_packingitem_is_checked_packinglist_is_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="packing_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="packinglist.packinglist",
                verbose_name="Packliste",
            ),
        ),
    ]
