# Generated by Django 5.2.12 on 2026-04-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_alter_eventdayslot_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingoption",
            name="is_system",
            field=models.BooleanField(
                default=False, help_text="Automatisch erstellte Option, nicht editierbar", verbose_name="System-Option"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_system", True)),
                fields=("event",),
                name="unique_system_booking_option_per_event",
            ),
        ),
    ]
