# Generated by Django 5.2.12 on 2026-08-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_migrate_event_mealplan_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='meal_plan',
        ),
    ]
