# Generated by Django 5.2.12 on 2026-04-07 21:14

from decimal import Decimal

from django.db import migrations


def create_system_booking_options(apps, schema_editor):
    """Create a system BookingOption for every existing event that doesn't have one."""
    Event = apps.get_model("event", "Event")
    BookingOption = apps.get_model("event", "BookingOption")

    events_without_system = Event.objects.exclude(booking_options__is_system=True)
    options_to_create = [
        BookingOption(
            event=event,
            name="Kostenlos (Organisator)",
            description="",
            price=Decimal("0.00"),
            max_participants=0,
            is_system=True,
        )
        for event in events_without_system
    ]
    BookingOption.objects.bulk_create(options_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0006_add_is_system_to_booking_option"),
    ]

    operations = [
        migrations.RunPython(
            create_system_booking_options,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
