# Generated by Django 5.2.12 on 2026-04-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_create_system_booking_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="participant_visibility",
            field=models.CharField(
                choices=[
                    ("none", "Nicht sichtbar"),
                    ("total_only", "Nur Gesamtzahl"),
                    ("per_option", "Zahlen pro Buchungsoption"),
                    ("with_names", "Zahlen und Vornamen"),
                ],
                default="none",
                help_text="Was eingeladene Teilnehmende über Anmeldezahlen sehen dürfen",
                max_length=20,
                verbose_name="Teilnehmer-Sichtbarkeit",
            ),
        ),
    ]
