# Generated by Django 5.2.12 on 2026-04-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0008_event_participant_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingoption",
            name="bookable_from",
            field=models.DateTimeField(
                blank=True, help_text="Leer = sofort buchbar", null=True, verbose_name="Buchbar ab"
            ),
        ),
        migrations.AddField(
            model_name="bookingoption",
            name="bookable_till",
            field=models.DateTimeField(
                blank=True, help_text="Leer = bis zum Anmeldeschluss buchbar", null=True, verbose_name="Buchbar bis"
            ),
        ),
    ]
