# Generated by Django 5.2.12 on 2026-04-09 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0009_bookingoption_bookable_from_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Gelöscht am"),
        ),
        migrations.AddField(
            model_name="registration",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_registrations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gelöscht von",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="deleted_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("duplicate", "Duplikat"),
                    ("error", "Fehler"),
                    ("cancel", "Stornierung"),
                    ("other", "Sonstiges"),
                ],
                default="",
                max_length=20,
                verbose_name="Löschgrund",
            ),
        ),
    ]
