# Generated by Django 5.2.12 on 2026-04-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_registration_deleted_at_registration_deleted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="guest_registration_enabled",
            field=models.BooleanField(
                default=False, help_text="Erlaubt Anmeldung ohne Account per Link", verbose_name="Gastregistrierung"
            ),
        ),
    ]
