# Generated by Django 5.2.12 on 2026-04-09 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0011_event_guest_registration_enabled"),
        ("profiles", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingPoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("street", models.CharField(blank=True, default="", max_length=200, verbose_name="Straße")),
                ("zip_code", models.CharField(blank=True, default="", max_length=10, verbose_name="PLZ")),
                ("city", models.CharField(blank=True, default="", max_length=100, verbose_name="Stadt")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_meeting_points",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_points",
                        to="profiles.usergroup",
                        verbose_name="Gruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Treffpunkt",
                "verbose_name_plural": "Treffpunkte",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="meeting_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_as_meeting_point",
                to="event.meetingpoint",
                verbose_name="Treffpunkt",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="pickup_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_as_pickup_point",
                to="event.meetingpoint",
                verbose_name="Abholpunkt",
            ),
        ),
    ]
