# Generated by Django 5.2.12 on 2026-04-11 11:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0012_meetingpoint_event_meeting_point_event_pickup_point"),
        ("planner", "0005_mealevent_update_related_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="color",
            field=models.CharField(
                choices=[
                    ("slate", "Schiefergrau"),
                    ("red", "Rot"),
                    ("orange", "Orange"),
                    ("amber", "Bernstein"),
                    ("yellow", "Gelb"),
                    ("lime", "Limette"),
                    ("green", "Grün"),
                    ("emerald", "Smaragd"),
                    ("teal", "Türkis"),
                    ("cyan", "Cyan"),
                    ("blue", "Blau"),
                    ("violet", "Violett"),
                    ("purple", "Lila"),
                    ("pink", "Pink"),
                    ("rose", "Rosa"),
                ],
                default="blue",
                max_length=20,
                verbose_name="Farbe",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="icon",
            field=models.CharField(
                choices=[
                    ("tent", "Zelt"),
                    ("flame", "Feuer"),
                    ("compass", "Kompass"),
                    ("map", "Karte"),
                    ("mountain", "Berg"),
                    ("tree-pine", "Baum"),
                    ("sun", "Sonne"),
                    ("moon", "Mond"),
                    ("star", "Stern"),
                    ("heart", "Herz"),
                    ("flag", "Flagge"),
                    ("users", "Gruppe"),
                    ("music", "Musik"),
                    ("book", "Buch"),
                    ("utensils", "Besteck"),
                    ("backpack", "Rucksack"),
                    ("flashlight", "Taschenlampe"),
                    ("binoculars", "Fernglas"),
                    ("anchor", "Anker"),
                    ("shield", "Schild"),
                    ("award", "Auszeichnung"),
                    ("crown", "Krone"),
                    ("zap", "Blitz"),
                    ("cloud", "Wolke"),
                    ("snowflake", "Schneeflocke"),
                    ("umbrella", "Regenschirm"),
                    ("leaf", "Blatt"),
                    ("fish", "Fisch"),
                    ("bird", "Vogel"),
                    ("map-pin", "Kartennadel"),
                    ("calendar", "Kalender"),
                    ("home", "Haus"),
                    ("coffee", "Kaffee"),
                    ("palette", "Palette"),
                    ("sparkles", "Funken"),
                    ("rocket", "Rakete"),
                ],
                default="tent",
                max_length=30,
                verbose_name="Icon",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_template",
            field=models.BooleanField(
                default=False,
                help_text="Event als Vorlage verwenden (wird nicht veröffentlicht)",
                verbose_name="Vorlage",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="manual_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Entwurf"),
                    ("pre_registration", "Vor der Anmeldung"),
                    ("registration", "Anmeldung offen"),
                    ("pre_event", "Vor dem Event"),
                    ("running", "Event läuft"),
                    ("completed", "Abgeschlossen"),
                ],
                help_text="Überschreibt die automatisch berechnete Phase",
                max_length=20,
                null=True,
                verbose_name="Manuelle Phase",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="meal_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="planner.mealevent",
                verbose_name="Essensplan",
            ),
        ),
        migrations.AddField(
            model_name="eventlocation",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Breitengrad"),
        ),
        migrations.AddField(
            model_name="eventlocation",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Längengrad"),
        ),
        migrations.AddField(
            model_name="meetingpoint",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Breitengrad"),
        ),
        migrations.AddField(
            model_name="meetingpoint",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Längengrad"),
        ),
        migrations.AlterField(
            model_name="timelineentry",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("registered", "Angemeldet"),
                    ("unregistered", "Abgemeldet"),
                    ("payment_received", "Zahlung erhalten"),
                    ("payment_removed", "Zahlung entfernt"),
                    ("booking_changed", "Buchungsoption geändert"),
                    ("label_added", "Label hinzugefügt"),
                    ("label_removed", "Label entfernt"),
                    ("custom_field_updated", "Benutzerdefiniertes Feld aktualisiert"),
                    ("mail_sent", "E-Mail gesendet"),
                    ("participant_updated", "Teilnehmer aktualisiert"),
                    ("attendance_check_in", "Eingecheckt"),
                    ("attendance_check_out", "Ausgecheckt"),
                    ("participants_imported", "Teilnehmer importiert"),
                ],
                max_length=30,
                verbose_name="Aktionstyp",
            ),
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checked_in_at", models.DateTimeField(blank=True, null=True, verbose_name="Eingecheckt am")),
                ("checked_out_at", models.DateTimeField(blank=True, null=True, verbose_name="Ausgecheckt am")),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_check_ins",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eingecheckt von",
                    ),
                ),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="event.participant",
                        verbose_name="Teilnehmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anwesenheit",
                "verbose_name_plural": "Anwesenheiten",
            },
        ),
        migrations.CreateModel(
            name="BudgetItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=200, verbose_name="Beschreibung")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7, verbose_name="Betrag")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("material", "Material"),
                            ("food", "Verpflegung"),
                            ("transport", "Transport"),
                            ("venue", "Unterkunft"),
                            ("other", "Sonstiges"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Kategorie",
                    ),
                ),
                ("is_expense", models.BooleanField(default=True, verbose_name="Ist Ausgabe")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_budget_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_items",
                        to="event.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget-Posten",
                "verbose_name_plural": "Budget-Posten",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParentAccessToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Token")),
                ("email", models.CharField(blank=True, default="", max_length=254, verbose_name="E-Mail-Adresse")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("expires_at", models.DateTimeField(verbose_name="Gültig bis")),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_tokens",
                        to="event.participant",
                        verbose_name="Teilnehmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elternzugangs-Token",
                "verbose_name_plural": "Elternzugangs-Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("capacity", models.IntegerField(default=0, help_text="0 = unbegrenzt", verbose_name="Kapazität")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sortierung")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_assignments",
                        to="event.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True, related_name="room_assignments", to="event.participant", verbose_name="Teilnehmer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zimmereinteilung",
                "verbose_name_plural": "Zimmereinteilungen",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("notified_at", models.DateTimeField(blank=True, null=True, verbose_name="Benachrichtigt am")),
                ("expired_at", models.DateTimeField(blank=True, null=True, verbose_name="Abgelaufen am")),
                (
                    "booking_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="event.bookingoption",
                        verbose_name="Buchungsoption",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="event.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waitlist_entries",
                        to="event.person",
                        verbose_name="Person",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wartelisten-Eintrag",
                "verbose_name_plural": "Wartelisten-Einträge",
                "ordering": ["created_at"],
            },
        ),
    ]
