# Generated by Django 5.2.12 on 2026-04-12 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0013_event_color_event_icon_event_is_template_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Telefonnummer"),
        ),
        migrations.AddField(
            model_name="person",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Telefonnummer"),
        ),
        migrations.AlterField(
            model_name="timelineentry",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("registered", "Angemeldet"),
                    ("unregistered", "Abgemeldet"),
                    ("payment_received", "Zahlung erhalten"),
                    ("payment_removed", "Zahlung entfernt"),
                    ("booking_changed", "Buchungsoption geändert"),
                    ("label_added", "Label hinzugefügt"),
                    ("label_removed", "Label entfernt"),
                    ("custom_field_updated", "Benutzerdefiniertes Feld aktualisiert"),
                    ("mail_sent", "E-Mail gesendet"),
                    ("participant_updated", "Teilnehmer aktualisiert"),
                    ("attendance_check_in", "Eingecheckt"),
                    ("attendance_check_out", "Ausgecheckt"),
                    ("participants_imported", "Teilnehmer importiert"),
                    ("whatsapp_sent", "WhatsApp gesendet"),
                ],
                max_length=30,
                verbose_name="Aktionstyp",
            ),
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nur für E-Mail relevant",
                        max_length=200,
                        verbose_name="Betreff",
                    ),
                ),
                ("body", models.TextField(verbose_name="Inhalt")),
                ("is_system", models.BooleanField(default=False, verbose_name="System-Vorlage")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nachrichtenvorlage",
                "verbose_name_plural": "Nachrichtenvorlagen",
                "ordering": ["-is_system", "title"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(blank=True, default="", max_length=20, verbose_name="Telefonnummer")),
                (
                    "session_db_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name der neonize-Session in PostgreSQL",
                        max_length=100,
                        verbose_name="Session DB Name",
                    ),
                ),
                ("connected_at", models.DateTimeField(blank=True, null=True, verbose_name="Verbunden seit")),
                ("is_active", models.BooleanField(default=False, verbose_name="Aktiv")),
                (
                    "total_messages_sent",
                    models.PositiveIntegerField(default=0, verbose_name="Gesendete Nachrichten gesamt"),
                ),
                (
                    "privacy_consent_given_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Datenschutz-Einwilligung"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_connection",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp-Verbindung",
                "verbose_name_plural": "WhatsApp-Verbindungen",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("sent", "Gesendet"),
                            ("delivered", "Zugestellt"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Gesendet am")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="Fehlermeldung")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="event.whatsappconnection",
                        verbose_name="Verbindung",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_messages",
                        to="event.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_messages",
                        to="event.participant",
                        verbose_name="Teilnehmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp-Nachricht",
                "verbose_name_plural": "WhatsApp-Nachrichten",
                "ordering": ["-created_at"],
            },
        ),
    ]
