# Generated by Django 5.2.12 on 2026-04-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_whatsapp_phone_number_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconnection',
            name='last_health_check_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzter Health Check'),
        ),
        migrations.AlterField(
            model_name='whatsappconnection',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='event.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='event.participant', verbose_name='Teilnehmer'),
        ),
        migrations.CreateModel(
            name='WhatsAppConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('connected', 'Verbunden'), ('disconnected', 'Getrennt'), ('health_check_ok', 'Health Check OK'), ('health_check_failed', 'Health Check fehlgeschlagen'), ('reconnect_success', 'Reconnect erfolgreich'), ('reconnect_failed', 'Reconnect fehlgeschlagen'), ('test_sent', 'Test gesendet'), ('test_failed', 'Test fehlgeschlagen')], max_length=30, verbose_name='Ereignistyp')),
                ('message', models.TextField(blank=True, default='', verbose_name='Nachricht')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='event.whatsappconnection', verbose_name='Verbindung')),
            ],
            options={
                'verbose_name': 'WhatsApp-Verbindungslog',
                'verbose_name_plural': 'WhatsApp-Verbindungslogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
