# Generated by Django 5.2.12 on 2026-04-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MealDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Datum")),
            ],
            options={
                "verbose_name": "Essenstag",
                "verbose_name_plural": "Essenstage",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                ("norm_portions", models.IntegerField(default=10, verbose_name="Norm-Portionen")),
                ("activity_factor", models.FloatField(default=1.5, verbose_name="Aktivitätsfaktor (PAL)")),
                ("reserve_factor", models.FloatField(default=1.1, verbose_name="Reservefaktor")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Essensplan",
                "verbose_name_plural": "Essenspläne",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Planner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Montag"),
                            (1, "Dienstag"),
                            (2, "Mittwoch"),
                            (3, "Donnerstag"),
                            (4, "Freitag"),
                            (5, "Samstag"),
                            (6, "Sonntag"),
                        ],
                        default=4,
                        verbose_name="Wochentag",
                    ),
                ),
                ("time", models.TimeField(default="18:00", verbose_name="Uhrzeit")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Planer",
                "verbose_name_plural": "Planer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlannerCollaborator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("editor", "Editor"), ("viewer", "Viewer")], default="viewer", max_length=10
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Mitarbeiter",
                "verbose_name_plural": "Mitarbeiter",
            },
        ),
        migrations.CreateModel(
            name="PlannerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Datum")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notizen")),
                (
                    "status",
                    models.CharField(
                        choices=[("planned", "Geplant"), ("cancelled", "Fällt aus")],
                        default="planned",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Planereintrag",
                "verbose_name_plural": "Planereinträge",
                "ordering": ["date", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Frühstück"),
                            ("lunch", "Mittagessen"),
                            ("dinner", "Abendessen"),
                            ("snack", "Snack"),
                            ("dessert", "Dessert"),
                        ],
                        max_length=10,
                        verbose_name="Mahlzeittyp",
                    ),
                ),
                ("time_start", models.TimeField(blank=True, null=True, verbose_name="Startzeit")),
                ("time_end", models.TimeField(blank=True, null=True, verbose_name="Endzeit")),
                (
                    "day_part_factor",
                    models.FloatField(
                        default=0.3,
                        help_text="Anteil am Tagesbedarf (z.B. Frühstück=0.25, Mittag=0.35)",
                        verbose_name="Tagesanteil",
                    ),
                ),
                (
                    "meal_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="planner.mealday",
                        verbose_name="Essenstag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahlzeit",
                "verbose_name_plural": "Mahlzeiten",
                "ordering": ["meal_type"],
            },
        ),
        migrations.CreateModel(
            name="MealItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("factor", models.FloatField(default=1.0, verbose_name="Skalierungsfaktor")),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="planner.meal",
                        verbose_name="Mahlzeit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahlzeit-Rezept",
                "verbose_name_plural": "Mahlzeit-Rezepte",
                "ordering": ["id"],
            },
        ),
    ]
