# Generated by Django 5.2.12 on 2026-07-13 20:13

import django.db.models.deletion
import planner.models.meal_plan
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Menge für Einzelzutat', max_digits=10, null=True, verbose_name='Menge')),
                ('display_name', models.CharField(blank=True, help_text='Überschreibt den automatischen Rezept-/Zutatennamen', max_length=200, null=True, verbose_name='Anzeigename')),
                ('factor', models.FloatField(default=1.0, verbose_name='Skalierungsfaktor')),
                ('active_recipe_item_ids', models.JSONField(blank=True, default=list, verbose_name='Aktive Rezept-Zutaten')),
                ('variant_group_id', models.UUIDField(blank=True, default=None, null=True, verbose_name='Varianten-Gruppe')),
            ],
            options={
                'verbose_name': 'Mahlzeit-Eintrag',
                'verbose_name_plural': 'Mahlzeit-Einträge',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MealItemOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_override', models.DecimalField(blank=True, decimal_places=2, help_text='Überschreibt die Original-Menge, null = Original beibehalten', max_digits=10, null=True, verbose_name='Menge-Override')),
                ('excluded', models.BooleanField(default=False, help_text='Zutat wird aus Einkaufsliste/Nährwertberechnung entfernt', verbose_name='Ausgeschlossen')),
            ],
            options={
                'verbose_name': 'Zutat-Override',
                'verbose_name_plural': 'Zutat-Overrides',
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('norm_portions', models.FloatField(default=10.0, verbose_name='Norm-Portionen')),
                ('previous_norm_portions', models.FloatField(default=10.0, verbose_name='Vorherige Norm-Portionen')),
                ('reserve_factor', models.FloatField(default=1.1, verbose_name='Reservefaktor')),
                ('activity_factor', models.FloatField(default=1.5, verbose_name='Aktivitätsfaktor (PAL)')),
                ('start_datetime', models.DateTimeField(verbose_name='Startdatum/-zeit')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Enddatum/-zeit')),
                ('visibility', models.CharField(choices=[('private', 'Privat'), ('group', 'Gruppe'), ('public', 'Öffentlich'), ('draft', 'Entwurf')], default='private', help_text='private = nur ich, group = meine Gruppe, public = für alle sichtbar, draft = Entwurf', max_length=10, verbose_name='Sichtbarkeit')),
                ('budget_per_person_per_day', models.DecimalField(blank=True, decimal_places=2, help_text='Maximales Budget in Euro pro Person und Tag', max_digits=8, null=True, verbose_name='Budget pro Person/Tag')),
                ('day_part_factors', models.JSONField(default=planner.models.meal_plan.default_day_part_factors, help_text='Gewichtung der Mahlzeittypen für diesen Plan', verbose_name='Tagesanteile')),
                ('meal_default_times', models.JSONField(default=planner.models.meal_plan.default_meal_default_times, help_text="Standard Start-/Endzeiten pro Mahlzeittyp (Format: {'breakfast': ['08:00', '09:00']})", verbose_name='Standard-Uhrzeiten')),
                ('is_template', models.BooleanField(default=False, help_text="Nur Admins können setzen. Referenz-Pläne erscheinen im Tab 'Referenz-Vorlagen' für alle Nutzer.", verbose_name='Referenz-Vorlage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Essensplan',
                'verbose_name_plural': 'Essenspläne',
                'db_table': 'planner_mealplan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Betrachter'), ('editor', 'Bearbeiter'), ('admin', 'Admin')], default='viewer', max_length=10, verbose_name='Rolle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Essensplan-Mitglied',
                'verbose_name_plural': 'Essensplan-Mitglieder',
                'ordering': ['role', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Alter')),
                ('gender', models.CharField(choices=[('male', 'Männlich'), ('female', 'Weiblich'), ('no_answer', 'Keine Angabe')], default='no_answer', max_length=10, verbose_name='Geschlecht')),
                ('synced_from_event', models.BooleanField(default=False, verbose_name='Aus Event synchronisiert')),
                ('date_ranges', models.JSONField(blank=True, default=list, verbose_name='Datumsbereiche')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gruppenmitglied',
                'verbose_name_plural': 'Gruppenmitglieder',
                'db_table': 'planner_mealplangroupmember',
                'ordering': ['age', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Essensplan-Tag',
                'verbose_name_plural': 'Essensplan-Tags',
            },
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('weekday', models.IntegerField(choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag'), (6, 'Sonntag')], default=4, verbose_name='Wochentag')),
                ('time', models.TimeField(default='18:00', verbose_name='Uhrzeit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Planer',
                'verbose_name_plural': 'Planer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannerCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mitarbeiter',
                'verbose_name_plural': 'Mitarbeiter',
            },
        ),
        migrations.CreateModel(
            name='PlannerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notizen')),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('cancelled', 'Fällt aus')], default='planned', max_length=10, verbose_name='Status')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Planereintrag',
                'verbose_name_plural': 'Planereinträge',
                'ordering': ['date', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Startzeit')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Endzeit')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Frühstück'), ('lunch', 'Mittagessen'), ('dinner', 'Abendessen'), ('snack', 'Snack')], max_length=10, verbose_name='Mahlzeittyp')),
                ('day_part_factor', models.FloatField(default=0.3, help_text='Anteil am Tagesbedarf (z.B. Frühstück=0.25, Mittag=0.35)', verbose_name='Tagesanteil')),
                ('override_portions', models.IntegerField(blank=True, help_text='Überschreibt norm_portions des Plans für diese Mahlzeit (z.B. Tagesgäste)', null=True, verbose_name='Portionen-Override')),
                ('is_external', models.BooleanField(default=False, help_text='Wenn True, wird diese Mahlzeit als extern (z.B. Restaurant) behandelt', verbose_name='Externe Mahlzeit')),
                ('external_energy_kcal', models.FloatField(blank=True, help_text='Manuell eingegebener Energiewert für externe Mahlzeiten', null=True, verbose_name='Externe Energie (kcal)')),
                ('external_cost_per_person', models.FloatField(blank=True, help_text='Fixpreis pro Person für externe Mahlzeiten', null=True, verbose_name='Externe Kosten pro Person')),
                ('note', models.TextField(blank=True, default='', verbose_name='Notiz')),
                ('note_is_published', models.BooleanField(default=False, help_text='Wenn True, erscheint die Notiz im PDF/Ausdruck', verbose_name='Notiz sichtbar')),
                ('display_name', models.CharField(blank=True, default='', help_text="Benutzerdefinierter Name (z.B. 'Kaffee', 'Saft')", max_length=200, verbose_name='Anzeigename')),
                ('is_reference', models.BooleanField(default=False, help_text='Wenn True, dient diese Mahlzeit als Template für andere Meals gleichen Typs', verbose_name='Ist Referenz-Mahlzeit')),
                ('is_synced', models.BooleanField(default=False, help_text='Wenn True, werden Änderungen am RefMeal auf dieses Meal übertragen', verbose_name='Synchronisiert')),
                ('ref_meal', models.ForeignKey(blank=True, help_text='Verknüpfung zum RefMeal-Template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_meals', to='planner.meal', verbose_name='Referenz-Mahlzeit')),
            ],
            options={
                'verbose_name': 'Mahlzeit',
                'verbose_name_plural': 'Mahlzeiten',
                'ordering': ['start_datetime'],
            },
        ),
    ]
