# Generated by Django 5.2.12 on 2026-07-13 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0003_initial'),
        ('planner', '0001_initial'),
        ('profiles', '0001_initial'),
        ('recipe', '0001_initial'),
        ('session', '0001_initial'),
        ('supply', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='ingredient',
            field=models.ForeignKey(blank=True, help_text='Alternative zu Rezept — Einzelzutat im Plan', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='supply.ingredient', verbose_name='Zutat'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.meal', verbose_name='Mahlzeit'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='measuring_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_items', to='supply.measuringunit', verbose_name='Einheit'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='recipe.recipe', verbose_name='Rezept'),
        ),
        migrations.AddField(
            model_name='mealitemoverride',
            name='meal_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='planner.mealitem', verbose_name='Mahlzeit-Eintrag'),
        ),
        migrations.AddField(
            model_name='mealitemoverride',
            name='recipe_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_overrides', to='recipe.recipeitem', verbose_name='Rezept-Zutat'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_plans', to='event.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='nutritional_tags',
            field=models.ManyToManyField(blank=True, related_name='meal_plans', to='supply.nutritionaltag', verbose_name='Ernährungseinschränkungen'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Null = Inspi-verifiziert, gesetzt = persönlicher Plan', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_meal_plans', to=settings.AUTH_USER_MODEL, verbose_name='Besitzer'),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_plan',
            field=models.ForeignKey(db_column='meal_plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='planner.mealplan', verbose_name='Essensplan'),
        ),
        migrations.AddField(
            model_name='mealplancollaborator',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='planner.mealplan', verbose_name='Essensplan'),
        ),
        migrations.AddField(
            model_name='mealplancollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_collaborations', to=settings.AUTH_USER_MODEL, verbose_name='Nutzer'),
        ),
        migrations.AddField(
            model_name='mealplangroupmember',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='planner.mealplan', verbose_name='Essensplan'),
        ),
        migrations.AddField(
            model_name='mealplangroupmember',
            name='nutritional_tags',
            field=models.ManyToManyField(blank=True, related_name='group_members', to='supply.nutritionaltag', verbose_name='Allergien / Besonderheiten'),
        ),
        migrations.AddField(
            model_name='mealplangroupmember',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_plan_group_members', to='event.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='mealplantag',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='planner.mealplan', verbose_name='Essensplan'),
        ),
        migrations.AddField(
            model_name='planner',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planners', to='profiles.usergroup', verbose_name='Gruppe'),
        ),
        migrations.AddField(
            model_name='planner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plannercollaborator',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='planner.planner'),
        ),
        migrations.AddField(
            model_name='plannercollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_planners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plannerentry',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='planner.planner'),
        ),
        migrations.AddField(
            model_name='plannerentry',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_entries', to='session.groupsession'),
        ),
        migrations.AddConstraint(
            model_name='mealitem',
            constraint=models.CheckConstraint(condition=models.Q(('ingredient__isnull', False), ('recipe__isnull', False), _negated=True), name='meal_item_recipe_xor_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='mealitem',
            constraint=models.UniqueConstraint(condition=models.Q(('ingredient__isnull', False)), fields=('meal', 'ingredient'), name='unique_ingredient_per_meal'),
        ),
        migrations.AlterUniqueTogether(
            name='mealitemoverride',
            unique_together={('meal_item', 'recipe_item')},
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['owner', 'visibility'], name='planner_mea_owner_i_f27fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['start_datetime'], name='planner_mea_start_d_b3c634_idx'),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference', True)), fields=('meal_plan', 'meal_type'), name='unique_ref_meal_per_plan_and_type'),
        ),
        migrations.AlterUniqueTogether(
            name='mealplancollaborator',
            unique_together={('meal_plan', 'user')},
        ),
        migrations.AddIndex(
            model_name='mealplangroupmember',
            index=models.Index(fields=['meal_plan'], name='planner_mea_meal_pl_3e852e_idx'),
        ),
        migrations.AddConstraint(
            model_name='mealplantag',
            constraint=models.UniqueConstraint(fields=('meal_plan', 'name'), name='unique_tag_per_meal_plan'),
        ),
        migrations.AlterUniqueTogether(
            name='plannercollaborator',
            unique_together={('planner', 'user')},
        ),
    ]
