# Generated by Django 5.2.12 on 2026-04-06 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0002_initial"),
        ("planner", "0001_initial"),
        ("profiles", "0001_initial"),
        ("recipe", "0001_initial"),
        ("session", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mealitem",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_items",
                to="recipe.recipe",
                verbose_name="Rezept",
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meal_plans",
                to="event.event",
                verbose_name="Event",
            ),
        ),
        migrations.AddField(
            model_name="mealday",
            name="meal_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="planner.mealplan",
                verbose_name="Essensplan",
            ),
        ),
        migrations.AddField(
            model_name="planner",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planners",
                to="profiles.usergroup",
                verbose_name="Gruppe",
            ),
        ),
        migrations.AddField(
            model_name="planner",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="planners", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="plannercollaborator",
            name="planner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="collaborators", to="planner.planner"
            ),
        ),
        migrations.AddField(
            model_name="plannercollaborator",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="shared_planners", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="plannerentry",
            name="planner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="planner.planner"
            ),
        ),
        migrations.AddField(
            model_name="plannerentry",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planner_entries",
                to="session.groupsession",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mealday",
            unique_together={("meal_plan", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="plannercollaborator",
            unique_together={("planner", "user")},
        ),
    ]
