# Generated by Django 5.2.12 on 2026-04-03 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
        ("profiles", "0005_remove_userprofile_eat_habits_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planner",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planners",
                to="profiles.usergroup",
                verbose_name="Gruppe",
            ),
        ),
        migrations.AddField(
            model_name="planner",
            name="time",
            field=models.TimeField(default="18:00", verbose_name="Uhrzeit"),
        ),
        migrations.AddField(
            model_name="planner",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (0, "Montag"),
                    (1, "Dienstag"),
                    (2, "Mittwoch"),
                    (3, "Donnerstag"),
                    (4, "Freitag"),
                    (5, "Samstag"),
                    (6, "Sonntag"),
                ],
                default=4,
                verbose_name="Wochentag",
            ),
        ),
        migrations.AddField(
            model_name="plannerentry",
            name="status",
            field=models.CharField(
                choices=[("planned", "Geplant"), ("cancelled", "Fällt aus")],
                default="planned",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
