# Generated by Django 5.2.12 on 2026-04-03 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_alter_person_options_remove_participant_eat_habits_and_more"),
        ("idea", "0012_recipehint_retailsection_ingredient_child_score_and_more"),
        ("planner", "0002_planner_group_planner_time_planner_weekday_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Datum")),
            ],
            options={
                "verbose_name": "Essenstag",
                "verbose_name_plural": "Essenstage",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Frühstück"),
                            ("lunch", "Mittagessen"),
                            ("dinner", "Abendessen"),
                            ("snack", "Snack"),
                            ("dessert", "Dessert"),
                        ],
                        max_length=10,
                        verbose_name="Mahlzeittyp",
                    ),
                ),
                ("time_start", models.TimeField(blank=True, null=True, verbose_name="Startzeit")),
                ("time_end", models.TimeField(blank=True, null=True, verbose_name="Endzeit")),
                (
                    "day_part_factor",
                    models.FloatField(
                        default=0.3,
                        help_text="Anteil am Tagesbedarf (z.B. Frühstück=0.25, Mittag=0.35)",
                        verbose_name="Tagesanteil",
                    ),
                ),
                (
                    "meal_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="planner.mealday",
                        verbose_name="Essenstag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahlzeit",
                "verbose_name_plural": "Mahlzeiten",
                "ordering": ["meal_type"],
            },
        ),
        migrations.CreateModel(
            name="MealItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("factor", models.FloatField(default=1.0, verbose_name="Skalierungsfaktor")),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="planner.meal",
                        verbose_name="Mahlzeit",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_items",
                        to="idea.idea",
                        verbose_name="Rezept",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahlzeit-Rezept",
                "verbose_name_plural": "Mahlzeit-Rezepte",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                ("norm_portions", models.IntegerField(default=10, verbose_name="Norm-Portionen")),
                ("activity_factor", models.FloatField(default=1.5, verbose_name="Aktivitätsfaktor (PAL)")),
                ("reserve_factor", models.FloatField(default=1.1, verbose_name="Reservefaktor")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_plans",
                        to="event.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Essensplan",
                "verbose_name_plural": "Essenspläne",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mealday",
            name="meal_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="planner.mealplan",
                verbose_name="Essensplan",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mealday",
            unique_together={("meal_plan", "date")},
        ),
    ]
