# Generated by Django 5.2.12 on 2026-08-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='event',
        ),
    ]
