# Generated by Django 5.2.12 on 2026-09-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0003_remove_mealplan_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="norm_portions_manual",
            field=models.BooleanField(
                default=False,
                help_text="Verhindert die automatische Neuberechnung aus Gruppenmitgliedern",
                verbose_name="Norm-Portionen manuell festgelegt",
            ),
        ),
    ]
