# Generated by Django 5.2.12 on 2026-04-03 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_mealday_meal_mealitem_mealplan_mealday_meal_plan_and_more"),
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealitem",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_items",
                to="recipe.recipe",
                verbose_name="Rezept",
            ),
        ),
    ]
