# Generated by Django 5.2.12 on 2026-04-08 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_event_participant_visibility"),
        ("planner", "0004_mealevent_meal_datetime_refactor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealevent",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AlterField(
            model_name="mealevent",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meal_events",
                to="event.event",
                verbose_name="Event",
            ),
        ),
    ]
