# Generated by Django 5.2.12 on 2026-09-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0004_mealplan_norm_portions_manual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Frühstück"),
                    ("lunch", "Mittagessen"),
                    ("dinner", "Abendessen"),
                    ("snack", "Snack"),
                    ("drinks", "Getränke"),
                ],
                max_length=10,
                verbose_name="Mahlzeittyp",
            ),
        ),
    ]
