# Generated by Django 5.2.12 on 2026-09-27 11:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0014_aiinteraction_structured_retry"),
        ("planner", "0005_alter_meal_meal_type"),
        ("recipe", "0010_recipe_source_servings"),
        ("supply", "0019_merge_portion_versions_and_data_quality"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuffetTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                (
                    "meal_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Liste von Mahlzeitentypen, z. B. ["lunch", "dinner"]',
                        verbose_name="Mahlzeitentypen",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Reihenfolge")),
            ],
            options={
                "verbose_name": "Buffet-Vorlage",
                "verbose_name_plural": "Buffet-Vorlagen",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="meal",
            name="buffet_role_amounts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Überschriebene Mengen pro Person je Rollen-Slug",
                verbose_name="Buffet-Mengen pro Rolle",
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="buffet_role",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Rollen-Slug, wenn der Eintrag vom Buffet-Builder stammt",
                max_length=50,
                verbose_name="Buffet-Rolle",
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="buffet_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meals",
                to="planner.buffettemplate",
                verbose_name="Buffet-Vorlage",
            ),
        ),
        migrations.CreateModel(
            name="BuffetTemplateRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "amount_per_person",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.1)], verbose_name="Menge pro Person"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("g", "Gramm"), ("ml", "Milliliter")],
                        default="g",
                        max_length=2,
                        verbose_name="Einheit",
                    ),
                ),
                ("enabled_by_default", models.BooleanField(default=True, verbose_name="Standardmäßig aktiv")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Reihenfolge")),
                (
                    "default_ingredients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="buffet_template_roles",
                        to="supply.ingredient",
                        verbose_name="Standard-Zutaten",
                    ),
                ),
                (
                    "default_recipes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="buffet_template_roles",
                        to="recipe.recipe",
                        verbose_name="Standard-Rezepte",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        limit_choices_to={"group": "buffet"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buffet_template_roles",
                        to="content.tag",
                        verbose_name="Rolle",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="planner.buffettemplate",
                        verbose_name="Vorlage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buffet-Rolle",
                "verbose_name_plural": "Buffet-Rollen",
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("template", "role"), name="unique_role_per_buffet_template")
                ],
            },
        ),
    ]
