# Generated by Django 5.2.12 on 2026-05-26 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0006_rename_mealevent_to_mealplan"),
        ("recipe", "0009_simple_meal_type"),
        ("supply", "0007_seed_unit_conversions"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealItemOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "quantity_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Überschreibt die Original-Menge, null = Original beibehalten",
                        max_digits=10,
                        null=True,
                        verbose_name="Menge-Override",
                    ),
                ),
                (
                    "excluded",
                    models.BooleanField(
                        default=False,
                        help_text="Zutat wird aus Einkaufsliste/Nährwertberechnung entfernt",
                        verbose_name="Ausgeschlossen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zutat-Override",
                "verbose_name_plural": "Zutat-Overrides",
            },
        ),
        migrations.AlterModelOptions(
            name="mealitem",
            options={
                "ordering": ["id"],
                "verbose_name": "Mahlzeit-Eintrag",
                "verbose_name_plural": "Mahlzeit-Einträge",
            },
        ),
        migrations.AddField(
            model_name="meal",
            name="note",
            field=models.TextField(blank=True, default="", verbose_name="Notiz"),
        ),
        migrations.AddField(
            model_name="meal",
            name="note_is_published",
            field=models.BooleanField(
                default=False, help_text="Wenn True, erscheint die Notiz im PDF/Ausdruck", verbose_name="Notiz sichtbar"
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="override_portions",
            field=models.IntegerField(
                blank=True,
                help_text="Überschreibt norm_portions des Plans für diese Mahlzeit (z.B. Tagesgäste)",
                null=True,
                verbose_name="Portionen-Override",
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Überschreibt den automatischen Rezept-/Zutatennamen",
                max_length=200,
                null=True,
                verbose_name="Anzeigename",
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="ingredient",
            field=models.ForeignKey(
                blank=True,
                help_text="Alternative zu Rezept — Einzelzutat im Plan",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_items",
                to="supply.ingredient",
                verbose_name="Zutat",
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="measuring_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meal_items",
                to="supply.measuringunit",
                verbose_name="Einheit",
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Menge für Einzelzutat",
                max_digits=10,
                null=True,
                verbose_name="Menge",
            ),
        ),
        migrations.AlterField(
            model_name="mealitem",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_items",
                to="recipe.recipe",
                verbose_name="Rezept",
            ),
        ),
        migrations.AddConstraint(
            model_name="mealitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("ingredient__isnull", True), ("recipe__isnull", False)),
                    models.Q(("ingredient__isnull", False), ("recipe__isnull", True)),
                    _connector="OR",
                ),
                name="meal_item_recipe_xor_ingredient",
            ),
        ),
        migrations.AddField(
            model_name="mealitemoverride",
            name="meal_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overrides",
                to="planner.mealitem",
                verbose_name="Mahlzeit-Eintrag",
            ),
        ),
        migrations.AddField(
            model_name="mealitemoverride",
            name="recipe_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_overrides",
                to="recipe.recipeitem",
                verbose_name="Rezept-Zutat",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mealitemoverride",
            unique_together={("meal_item", "recipe_item")},
        ),
    ]
