# Generated by Django 5.2.12 on 2026-09-27 19:46, hand-edited: adds data
# cleanup and a pre-flight conflict check before the new constraints.

import django.db.models.functions.datetime
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import TruncDate


def clear_reference_meal_datetimes(apps, schema_editor):
    """Reference meals are templates and must not carry a date; the field was
    fachlich unused but some rows had it set from earlier code paths."""
    Meal = apps.get_model("planner", "Meal")
    Meal.objects.filter(is_reference=True).exclude(start_datetime__isnull=True, end_datetime__isnull=True).update(
        start_datetime=None, end_datetime=None
    )


def noop(apps, schema_editor):
    pass


def check_no_duplicate_regular_meals(apps, schema_editor):
    """Abort with a clear list instead of letting AddConstraint fail with an
    opaque IntegrityError, in case a plan already has two regular meals of the
    same type on the same day (should be prevented by Meal.clean(), but old
    data or a bulk update could have bypassed it)."""
    Meal = apps.get_model("planner", "Meal")
    conflicts = list(
        Meal.objects.filter(is_reference=False)
        .exclude(meal_type="snack")
        .annotate(day=TruncDate("start_datetime"))
        .values("meal_plan_id", "day", "meal_type")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    if conflicts:
        details = "\n".join(
            f"  meal_plan={c['meal_plan_id']} day={c['day']} meal_type={c['meal_type']} ({c['n']}x)" for c in conflicts
        )
        raise RuntimeError(
            "Migration 0007 abgebrochen: doppelte reguläre Mahlzeiten gefunden, die die neue "
            f"UniqueConstraint verletzen würden. Bitte zuerst manuell bereinigen:\n{details}"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0006_buffet_templates"),
    ]

    operations = [
        migrations.RunPython(clear_reference_meal_datetimes, noop),
        migrations.RunPython(check_no_duplicate_regular_meals, noop),
        migrations.AddConstraint(
            model_name="meal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_reference", False),
                    models.Q(("end_datetime__isnull", True), ("start_datetime__isnull", True)),
                    _connector="OR",
                ),
                name="meal_reference_without_datetime",
                violation_error_message="Eine Referenz-Mahlzeit darf kein Datum haben.",
            ),
        ),
        migrations.AddConstraint(
            model_name="meal",
            constraint=models.UniqueConstraint(
                django.db.models.functions.datetime.TruncDate("start_datetime"),
                models.F("meal_plan"),
                models.F("meal_type"),
                condition=models.Q(("is_reference", False), models.Q(("meal_type", "snack"), _negated=True)),
                name="unique_regular_meal_per_day_and_type",
                violation_error_message="Es existiert bereits eine Mahlzeit dieses Typs an diesem Tag.",
            ),
        ),
    ]
