# Generated by Django 5.2.12 on 2026-05-28 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0007_meal_enhancements"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPlanCollaborator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("viewer", "Betrachter"), ("editor", "Bearbeiter"), ("admin", "Admin")],
                        default="viewer",
                        max_length=10,
                        verbose_name="Rolle",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborators",
                        to="planner.mealplan",
                        verbose_name="Essensplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plan_collaborations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Essensplan-Mitglied",
                "verbose_name_plural": "Essensplan-Mitglieder",
                "ordering": ["role", "user__username"],
                "unique_together": {("meal_plan", "user")},
            },
        ),
    ]
