# Generated by Django 5.2.12 on 2026-09-30 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0007_meal_meal_reference_without_datetime_and_more"),
        ("supply", "0021_ingredient_package_suggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealitem",
            name="portion",
            field=models.ForeignKey(
                blank=True,
                help_text="Gewählte Portion der Einzelzutat; dann ist die Menge die Anzahl Portionen pro Person",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meal_items",
                to="supply.portion",
                verbose_name="Portion",
            ),
        ),
    ]
