# Generated by Django 5.2.12 on 2026-05-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0008_mealplancollaborator"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Enddatum/-zeit"),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="start_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Startdatum/-zeit"),
        ),
    ]
