# Generated by Django 5.2.12 on 2026-10-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0008_mealitem_portion"),
        ("recipe", "0010_recipe_source_servings"),
        ("supply", "0022_buffet_data_proposal"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mealitem",
            name="unique_ingredient_per_meal",
        ),
        migrations.AddField(
            model_name="mealitem",
            name="buffet_share_percent",
            field=models.FloatField(
                blank=True,
                help_text="Item-Anteil innerhalb der Buffet-Rolle in Prozent",
                null=True,
                verbose_name="Buffet-Anteil",
            ),
        ),
        migrations.AddConstraint(
            model_name="mealitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ingredient__isnull", False)),
                fields=("meal", "ingredient", "buffet_role"),
                name="unique_ingredient_role_per_meal",
            ),
        ),
        migrations.AddConstraint(
            model_name="mealitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("buffet_share_percent__isnull", True),
                    models.Q(("buffet_share_percent__gte", 0), ("buffet_share_percent__lte", 100)),
                    _connector="OR",
                ),
                name="meal_item_buffet_share_percent_range",
            ),
        ),
    ]
