# Generated by Django 5.2.12 on 2026-10-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0009_remove_mealitem_unique_ingredient_per_meal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="breakfast_profile",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="Frühstücksvariante"),
        ),
    ]
