# Generated by Django 5.2.12 on 2026-05-28 20:46

from django.db import migrations


def populate_datetimes(apps, schema_editor):
    """Populate start_datetime/end_datetime from existing Meals."""
    MealPlan = apps.get_model("planner", "MealPlan")
    Meal = apps.get_model("planner", "Meal")

    for plan in MealPlan.objects.filter(start_datetime__isnull=True):
        meals = Meal.objects.filter(meal_plan=plan).order_by("start_datetime")
        if meals.exists():
            plan.start_datetime = meals.first().start_datetime
            plan.end_datetime = meals.last().end_datetime
            plan.save(update_fields=["start_datetime", "end_datetime"])


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0009_add_mealplan_start_end_datetime"),
    ]

    operations = [
        migrations.RunPython(populate_datetimes, migrations.RunPython.noop),
    ]
