# Generated by Django 5.2.12 on 2026-10-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0010_meal_breakfast_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealitem",
            name="is_breakfast_assistant",
            field=models.BooleanField(
                default=False,
                help_text="Kennzeichnet vom Frühstückswizard verwaltete Einträge.",
                verbose_name="Vom Frühstücksassistenten",
            ),
        ),
    ]
