# Generated by Django 5.2.12 on 2026-05-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0010_populate_mealplan_datetimes"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="budget_per_person_per_day",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximales Budget in Euro pro Person und Tag",
                max_digits=8,
                null=True,
                verbose_name="Budget pro Person/Tag",
            ),
        ),
    ]
