# Generated by Django 5.2.12 on 2026-05-31 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0011_add_budget_per_person_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="is_reference",
            field=models.BooleanField(
                default=False,
                help_text="Wenn True, dient diese Mahlzeit als Template für andere Meals gleichen Typs",
                verbose_name="Ist Referenz-Mahlzeit",
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="is_synced",
            field=models.BooleanField(
                default=False,
                help_text="Wenn True, werden Änderungen am RefMeal auf dieses Meal übertragen",
                verbose_name="Synchronisiert",
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="ref_meal",
            field=models.ForeignKey(
                blank=True,
                help_text="Verknüpfung zum RefMeal-Template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="synced_meals",
                to="planner.meal",
                verbose_name="Referenz-Mahlzeit",
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Endzeit"),
        ),
        migrations.AlterField(
            model_name="meal",
            name="start_datetime",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Startzeit"),
        ),
    ]
