# Generated by Django 5.2.12 on 2026-10-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0011_mealitem_is_breakfast_assistant"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="age_groups",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste aus: toddlers, children, teens, adults. Leer = aus Gruppenmitgliedern ableiten.",
                verbose_name="Altersgruppen",
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="cooking_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste aus: stove_oven, gas_burner, campfire, grill, none",
                verbose_name="Kochmöglichkeiten",
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="cooling",
            field=models.CharField(
                blank=True,
                choices=[("fridge", "Kühlschrank"), ("cooler_box", "Kühlbox"), ("none", "Keine Kühlung")],
                default="",
                max_length=20,
                verbose_name="Kühlmöglichkeit",
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="season_hint",
            field=models.CharField(
                blank=True,
                choices=[("hot", "Heiß"), ("mild", "Mild"), ("cold", "Kalt")],
                default="",
                help_text="Leer = aus dem Startdatum ableiten",
                max_length=10,
                verbose_name="Jahreszeit/Wetter",
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="setting",
            field=models.CharField(
                blank=True,
                choices=[
                    ("camp", "Zeltlager"),
                    ("house_trip", "Hausfahrt"),
                    ("day_event", "Tagesaktion"),
                    ("group_meeting", "Gruppenstunde"),
                    ("hike", "Wanderung"),
                    ("other", "Sonstiges"),
                ],
                default="",
                max_length=20,
                verbose_name="Veranstaltungsart",
            ),
        ),
    ]
