# Generated by Django 5.2.12 on 2026-10-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0012_mealplan_suggestion_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealitem",
            name="note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Freitext-Notiz zum Eintrag, z. B. 'ohne Zwiebeln'",
                max_length=500,
                verbose_name="Notiz",
            ),
        ),
    ]
