# Generated by Django 5.2.12 on 2026-05-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0012_ref_meal_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="meal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_reference", True)),
                fields=("meal_plan", "meal_type"),
                name="unique_ref_meal_per_plan_and_type",
            ),
        ),
    ]
