# Generated by Django 5.2.12 on 2026-06-03 20:01

import planner.models.meal_plan
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0013_ref_meal_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="external_energy_kj",
            field=models.FloatField(
                blank=True,
                help_text="Manuell eingegebener Energiewert für externe Mahlzeiten",
                null=True,
                verbose_name="Externe Energie (kJ)",
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="is_external",
            field=models.BooleanField(
                default=False,
                help_text="Wenn True, wird diese Mahlzeit als extern (z.B. Restaurant) behandelt",
                verbose_name="Externe Mahlzeit",
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="day_part_factors",
            field=models.JSONField(
                default=planner.models.meal_plan.default_day_part_factors,
                help_text="Gewichtung der Mahlzeittypen für diesen Plan",
                verbose_name="Tagesanteile",
            ),
        ),
    ]
