# Generated by Django 5.2.12 on 2026-06-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0014_meal_external_energy_kj_meal_is_external_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mealplan",
            name="activity_factor",
        ),
    ]
