# Generated by Django 5.2.12 on 2026-06-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0015_remove_mealplan_activity_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="external_cost_per_person",
            field=models.FloatField(
                blank=True,
                help_text="Fixpreis pro Person für externe Mahlzeiten",
                null=True,
                verbose_name="Externe Kosten pro Person",
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Frühstück"),
                    ("lunch", "Mittagessen"),
                    ("dinner", "Abendessen"),
                    ("snack", "Snack"),
                    ("dessert", "Dessert"),
                    ("drinks", "Getränke"),
                ],
                max_length=10,
                verbose_name="Mahlzeittyp",
            ),
        ),
    ]
