# Generated by Django 5.2.12 on 2026-06-04 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0017_remove_dessert_meal_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={"ordering": ["start_datetime"], "verbose_name": "Mahlzeit", "verbose_name_plural": "Mahlzeiten"},
        ),
    ]
