# Generated by Django 5.2.12 on 2026-06-07 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0017_event_public_landing_idx"),
        ("planner", "0018_alter_meal_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = Inspi-verifiziert, gesetzt = persönlicher Plan",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_meal_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Besitzer",
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Privat"), ("public", "Öffentlich")],
                default="private",
                help_text="private = nur ich, public = für alle sichtbar",
                max_length=10,
                verbose_name="Sichtbarkeit",
            ),
        ),
        migrations.AddIndex(
            model_name="mealplan",
            index=models.Index(fields=["owner", "visibility"], name="planner_mea_owner_i_f27fa3_idx"),
        ),
        migrations.AddIndex(
            model_name="mealplan",
            index=models.Index(fields=["start_datetime"], name="planner_mea_start_d_b3c634_idx"),
        ),
    ]
