# Generated by Django 5.2.12 on 2026-06-07 13:58

import planner.models.meal_plan
from django.db import migrations, models


def convert_drinks_to_snacks(apps, schema_editor):
    Meal = apps.get_model("planner", "Meal")
    Meal.objects.filter(meal_type="drinks").update(
        meal_type="snack",
        display_name="Getränke",
        day_part_factor=0.00,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0020_backfill_mealplan_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="display_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Benutzerdefinierter Name (z.B. 'Kaffee', 'Saft')",
                max_length=200,
                verbose_name="Anzeigename",
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="meal_default_times",
            field=models.JSONField(
                default=planner.models.meal_plan.default_meal_default_times,
                help_text="Standard Start-/Endzeiten pro Mahlzeittyp (Format: {'breakfast': ['08:00', '09:00']})",
                verbose_name="Standard-Uhrzeiten",
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Frühstück"),
                    ("lunch", "Mittagessen"),
                    ("dinner", "Abendessen"),
                    ("snack", "Snack"),
                ],
                max_length=10,
                verbose_name="Mahlzeittyp",
            ),
        ),
        migrations.RunPython(convert_drinks_to_snacks, migrations.RunPython.noop),
    ]
