# Generated by Django 5.2.12 on 2026-06-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0021_meal_display_name_mealplan_meal_default_times_and_more"),
        ("supply", "0027_alter_ingredient_standalone_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="allergen_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="meal_plans",
                to="supply.nutritionaltag",
                verbose_name="Allergen-Einschränkungen",
            ),
        ),
    ]
