# Generated by Django 5.2.12 on 2026-06-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0022_mealplan_allergen_tags"),
        ("supply", "0027_alter_ingredient_standalone_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealplan",
            name="allergen_tags",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_dangerous": True},
                related_name="meal_plans",
                to="supply.nutritionaltag",
                verbose_name="Allergen-Einschränkungen",
            ),
        ),
    ]
