# Generated by Django 5.2.12 on 2026-06-07 19:24
# Manually modified: RenameField + state update for limit_choices_to removal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0024_remove_meal_external_energy_kj_and_more"),
        ("supply", "0029_ingredient_camp_suitable_ingredient_cooking_factor_and_more"),
    ]

    operations = [
        # Rename the field and its through table in one operation
        migrations.RenameField(
            model_name="mealplan",
            old_name="allergen_tags",
            new_name="nutritional_tags",
        ),
        # Update the field definition to remove limit_choices_to
        migrations.AlterField(
            model_name="mealplan",
            name="nutritional_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="meal_plans",
                to="supply.nutritionaltag",
                verbose_name="Ernährungseinschränkungen",
            ),
        ),
    ]
