# Generated by Django 5.2.12 on 2026-06-18 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0025_remove_mealplan_allergen_tags_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE planner_meal RENAME COLUMN meal_event_id TO meal_plan_id",
                    reverse_sql="ALTER TABLE planner_meal RENAME COLUMN meal_plan_id TO meal_event_id",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="meal",
                    name="meal_plan",
                    field=models.ForeignKey(
                        db_column="meal_plan_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="planner.mealplan",
                        verbose_name="Essensplan",
                    ),
                ),
            ],
        ),
    ]
