# Generated by Django 5.2.12 on 2026-06-19 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0017_event_public_landing_idx"),
        ("planner", "0026_rename_meal_plan_fk_column"),
        ("supply", "0031_material_is_deleted_alter_ingredient_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mealplan",
            name="planner_mea_owner_i_f27fa3_idx",
        ),
        migrations.RemoveField(
            model_name="mealplan",
            name="visibility",
        ),
        migrations.AddField(
            model_name="mealplan",
            name="status",
            field=models.CharField(
                choices=[("draft", "Entwurf"), ("verified", "Verifiziert")],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="mealplan",
            index=models.Index(fields=["created_by", "status"], name="planner_mea_created_40af1a_idx"),
        ),
    ]
