# Generated by Django 5.2.12 on 2026-06-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0027_remove_mealplan_planner_mea_owner_i_f27fa3_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mealplan",
            old_name="norm_portions",
            new_name="portions",
        ),
        migrations.RenameField(
            model_name="meal",
            old_name="override_portions",
            new_name="portions_override",
        ),
        migrations.AlterUniqueTogether(
            name="plannercollaborator",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="plannercollaborator",
            name="planner",
        ),
        migrations.RemoveField(
            model_name="plannercollaborator",
            name="user",
        ),
        migrations.DeleteModel(
            name="MealPlanCollaborator",
        ),
        migrations.DeleteModel(
            name="PlannerCollaborator",
        ),
    ]
