# Generated by Django 5.2.12 on 2026-06-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0028_rename_portions_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="portions_override",
            field=models.IntegerField(
                blank=True,
                help_text="Überschreibt portions des Plans für diese Mahlzeit (z.B. Tagesgäste)",
                null=True,
                verbose_name="Portionen-Override",
            ),
        ),
    ]
