# Generated by Django 5.2.12 on 2026-06-21 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0017_event_public_landing_idx"),
        ("planner", "0029_rename_status_to_visibility"),
        ("supply", "0036_migrate_standalone_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mealplan",
            name="planner_mea_created_40af1a_idx",
        ),
        migrations.AddIndex(
            model_name="mealplan",
            index=models.Index(fields=["owner", "visibility"], name="planner_mea_owner_i_f27fa3_idx"),
        ),
    ]
