from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0030_remove_mealplan_planner_mea_created_40af1a_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS "planner_plannercollaborator" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "role" varchar(10) NOT NULL,
                "invited_at" timestamp with time zone NOT NULL,
                "planner_id" bigint NOT NULL,
                "user_id" integer NOT NULL
            );
            CREATE INDEX IF NOT EXISTS "planner_plannercollaborator_planner_id_xxx"
                ON "planner_plannercollaborator" ("planner_id");
            CREATE INDEX IF NOT EXISTS "planner_plannercollaborator_user_id_xxx"
                ON "planner_plannercollaborator" ("user_id");
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS "planner_plannercollaborator" CASCADE;
            """,
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS "planner_mealplancollaborator" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "role" varchar(10) NOT NULL,
                "created_at" timestamp with time zone NOT NULL,
                "meal_plan_id" bigint NOT NULL,
                "user_id" integer NOT NULL
            );
            CREATE INDEX IF NOT EXISTS "planner_mealplancollaborator_meal_plan_id_xxx"
                ON "planner_mealplancollaborator" ("meal_plan_id");
            CREATE INDEX IF NOT EXISTS "planner_mealplancollaborator_user_id_xxx"
                ON "planner_mealplancollaborator" ("user_id");
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS "planner_mealplancollaborator" CASCADE;
            """,
        ),
    ]
