# Generated by Django 5.2.12 on 2026-06-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0031_create_missing_collaborator_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealplan",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Privat"), ("group", "Gruppe"), ("public", "Öffentlich"), ("draft", "Entwurf")],
                default="private",
                help_text="private = nur ich, group = meine Gruppe, public = für alle sichtbar, draft = Entwurf",
                max_length=10,
                verbose_name="Sichtbarkeit",
            ),
        ),
    ]
