# Generated by Django 5.2.12 on 2026-06-23 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0032_alter_mealplan_visibility"),
        ("planner", "0032_mealplan_is_template"),
    ]

    operations = []
