# Generated by Django 5.2.12 on 2026-06-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0034_mealitemsplit"),
        ("recipe", "0045_recipeitem_exchange_position_recipeitem_is_optional_and_more"),
        ("supply", "0040_seed_system_portions"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mealitem",
            name="meal_item_recipe_xor_ingredient",
        ),
        migrations.AddConstraint(
            model_name="mealitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("ingredient__isnull", False), ("recipe__isnull", False), _negated=True),
                name="meal_item_recipe_xor_ingredient",
            ),
        ),
    ]
