# Generated by Django 5.2.12 on 2026-06-27 16:11

from django.db import migrations, models
from django.db.models import Min


def cleanup_duplicate_meal_items(apps, schema_editor):
    MealItem = apps.get_model("planner", "MealItem")
    db_alias = schema_editor.connection.alias

    # Remove duplicate recipes per meal — keep lowest id
    dup_recipes = (
        MealItem.objects.using(db_alias)
        .filter(recipe__isnull=False)
        .values("meal_id", "recipe_id")
        .annotate(min_id=Min("id"))
    )
    for dup in dup_recipes:
        MealItem.objects.using(db_alias).filter(meal_id=dup["meal_id"], recipe_id=dup["recipe_id"]).exclude(
            id=dup["min_id"]
        ).delete()

    # Remove duplicate ingredients per meal — keep lowest id
    dup_ingredients = (
        MealItem.objects.using(db_alias)
        .filter(ingredient__isnull=False)
        .values("meal_id", "ingredient_id")
        .annotate(min_id=Min("id"))
    )
    for dup in dup_ingredients:
        MealItem.objects.using(db_alias).filter(meal_id=dup["meal_id"], ingredient_id=dup["ingredient_id"]).exclude(
            id=dup["min_id"]
        ).delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("planner", "0035_relax_mealitem_constraint"),
        ("recipe", "0045_recipeitem_exchange_position_recipeitem_is_optional_and_more"),
        ("supply", "0040_seed_system_portions"),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicate_meal_items, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="mealitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recipe__isnull", False)), fields=("meal", "recipe"), name="unique_recipe_per_meal"
            ),
        ),
        migrations.AddConstraint(
            model_name="mealitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ingredient__isnull", False)),
                fields=("meal", "ingredient"),
                name="unique_ingredient_per_meal",
            ),
        ),
    ]
