# Generated by Django 5.2.12 on 2026-06-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0036_mealitem_unique_recipe_per_meal_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mealitem",
            name="unique_recipe_per_meal",
        ),
        migrations.AddField(
            model_name="mealitem",
            name="active_recipe_item_ids",
            field=models.JSONField(blank=True, default=list, verbose_name="Aktive Rezept-Zutaten"),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="variant_group_id",
            field=models.UUIDField(blank=True, default=None, null=True, verbose_name="Varianten-Gruppe"),
        ),
    ]
