# Generated by Django 5.2.12 on 2026-06-27 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0037_remove_mealitem_unique_recipe_per_meal_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MealItemSplit",
        ),
    ]
