# Generated by Django 5.2.12 on 2026-07-09 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0040_alter_mealplan_start_datetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPlanTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Tag")),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="planner.mealplan",
                        verbose_name="Essensplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Essensplan-Tag",
                "verbose_name_plural": "Essensplan-Tags",
                "constraints": [models.UniqueConstraint(fields=("meal_plan", "name"), name="unique_tag_per_meal_plan")],
            },
        ),
    ]
