# Generated by Django 5.2.12 on 2026-07-11 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0017_event_public_landing_idx"),
        ("planner", "0041_mealplantag"),
        ("supply", "0060_populate_usage_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="activity_factor",
            field=models.FloatField(default=1.5, verbose_name="Aktivitätsfaktor (PAL)"),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="previous_norm_portions",
            field=models.FloatField(default=10.0, verbose_name="Vorherige Norm-Portionen"),
        ),
        migrations.AlterField(
            model_name="mealplan",
            name="norm_portions",
            field=models.FloatField(default=10.0, verbose_name="Norm-Portionen"),
        ),
        migrations.CreateModel(
            name="MealPlanGroupMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=200, null=True, verbose_name="Name")),
                ("age", models.IntegerField(verbose_name="Alter")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Männlich"), ("female", "Weiblich"), ("no_answer", "Keine Angabe")],
                        default="no_answer",
                        max_length=10,
                        verbose_name="Geschlecht",
                    ),
                ),
                ("synced_from_event", models.BooleanField(default=False, verbose_name="Aus Event synchronisiert")),
                ("date_ranges", models.JSONField(blank=True, default=list, verbose_name="Datumsbereiche")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_members",
                        to="planner.mealplan",
                        verbose_name="Essensplan",
                    ),
                ),
                (
                    "nutritional_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="group_members",
                        to="supply.nutritionaltag",
                        verbose_name="Allergien / Besonderheiten",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_plan_group_members",
                        to="event.person",
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gruppenmitglied",
                "verbose_name_plural": "Gruppenmitglieder",
                "db_table": "planner_mealplangroupmember",
                "ordering": ["age", "name"],
                "indexes": [models.Index(fields=["meal_plan"], name="planner_mea_meal_pl_3e852e_idx")],
            },
        ),
    ]
