"""Supply schemas package — re-exports all schemas for backward compatibility."""

from .materials import (
    ContentMaterialItemIn,
    ContentMaterialItemOut,
    MaterialCreateIn,
    MaterialListOut,
    MaterialOut,
    MaterialUpdateIn,
    PaginatedMaterialOut,
)
from .reference import (
    DgeReferenceOut,
    MeasuringUnitOut,
    NutritionalTagIn,
    NutritionalTagOut,
    NutritionalTagUpdateIn,
    RetailSectionIn,
    RetailSectionOut,
    RetailSectionUpdateIn,
)
from .ingredients import (
    AliasCreateIn,
    IngredientAiCreateIn,
    IngredientAliasOut,
    IngredientCreateIn,
    IngredientDetailOut,
    IngredientListOut,
    IngredientSuggestAllOut,
    IngredientUpdateIn,
    PaginatedIngredientOut,
    PortionCreateIn,
    PortionOut,
    PortionSuggestionOut,
    PortionUpdateIn,
)
from .norm_person import (
    DgeReferencePointOut,
    NormPersonCurvePointOut,
    NormPersonCurvesOut,
    NormPersonReferenceOut,
    NormPersonResultOut,
)

__all__ = [
    "AliasCreateIn",
    "ContentMaterialItemIn",
    "ContentMaterialItemOut",
    "DgeReferenceOut",
    "DgeReferencePointOut",
    "IngredientAiCreateIn",
    "IngredientAliasOut",
    "IngredientCreateIn",
    "IngredientDetailOut",
    "IngredientListOut",
    "IngredientSuggestAllOut",
    "IngredientUpdateIn",
    "MaterialCreateIn",
    "MaterialListOut",
    "MaterialOut",
    "MaterialUpdateIn",
    "MeasuringUnitOut",
    "NormPersonCurvePointOut",
    "NormPersonCurvesOut",
    "NormPersonReferenceOut",
    "NormPersonResultOut",
    "NutritionalTagIn",
    "NutritionalTagOut",
    "NutritionalTagUpdateIn",
    "PaginatedIngredientOut",
    "PaginatedMaterialOut",
    "PortionCreateIn",
    "PortionOut",
    "PortionSuggestionOut",
    "PortionUpdateIn",
    "RetailSectionIn",
    "RetailSectionOut",
    "RetailSectionUpdateIn",
]
