/**
 * Step 5: Buchungsoptionen — add/remove options with price, max participants, bookable period.
 */
import { useState, useEffect } from 'react';
import { useEventWizardStore } from '@/store/eventWizardStore';
import type { WizardBookingOption } from '@/schemas/eventWizard';

const emptyOption: WizardBookingOption = {
  name: '',
  description: '',
  price: '0.00',
  max_participants: 0,
  bookable_from: null,
  bookable_till: null,
};

export default function StepBookingOptions() {
  const { data, updateStep5, setStepValid } = useEventWizardStore();
  const [editing, setEditing] = useState<WizardBookingOption>({ ...emptyOption });
  const [showForm, setShowForm] = useState(false);
  const [editIndex, setEditIndex] = useState<number | null>(null);

  const options = data.booking_options || [];

  // Always valid (optional step)
  useEffect(() => {
    setStepValid(4, true);
  }, [setStepValid]);

  const handleAdd = () => {
    if (!editing.name.trim()) return;
    updateStep5({
      booking_options: [...options, { ...editing, _isAutoGenerated: false }],
    });
    setEditing({ ...emptyOption });
    setShowForm(false);
  };

  const handleRemove = (index: number) => {
    updateStep5({
      booking_options: options.filter((_, i) => i !== index),
    });
  };

  const handleEdit = (index: number) => {
    setEditIndex(index);
    setEditing({ ...options[index] });
    setShowForm(true);
  };

  const handleSaveEdit = () => {
    if (editIndex === null || !editing.name.trim()) return;
    const updated = [...options];
    updated[editIndex] = { ...editing, _isAutoGenerated: false };
    updateStep5({ booking_options: updated });
    setEditing({ ...emptyOption });
    setEditIndex(null);
    setShowForm(false);
  };

  const handleCancel = () => {
    setShowForm(false);
    setEditIndex(null);
    setEditing({ ...emptyOption });
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-lg font-bold mb-1">Buchungsoptionen</h2>
        <p className="text-sm text-muted-foreground mb-4">
          Lege Buchungsoptionen an (z.B. Tagesticket, Wochenende, mit Übernachtung).
          Du kannst diesen Schritt überspringen.
        </p>
      </div>

      {/* Existing options */}
      {options.length > 0 && (
        <div className="space-y-2">
          {options.map((opt, idx) => (
            <div
              key={idx}
              className="flex items-center justify-between border rounded-lg px-4 py-3"
            >
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium">{opt.name}</span>
                  <span className="text-sm text-muted-foreground">{opt.price}&euro;</span>
                  {opt.max_participants && opt.max_participants > 0 && (
                    <span className="text-xs text-muted-foreground">
                      (max. {opt.max_participants})
                    </span>
                  )}
                  {opt._isAutoGenerated && (
                    <span className="text-xs text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-950/30 px-1.5 py-0.5 rounded">
                      automatisch
                    </span>
                  )}
                </div>
                {opt.description && (
                  <p className="text-xs text-muted-foreground mt-0.5">{opt.description}</p>
                )}
              </div>
              <div className="flex items-center gap-2 shrink-0 ml-2">
                <button
                  type="button"
                  onClick={() => handleEdit(idx)}
                  className="text-primary hover:underline text-xs"
                >
                  Bearbeiten
                </button>
                <button
                  type="button"
                  onClick={() => handleRemove(idx)}
                  className="text-destructive hover:underline text-xs"
                >
                  Entfernen
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Auto-generated info */}
      {options.some((o) => o._isAutoGenerated) && (
        <div className="border rounded-lg p-3 bg-blue-50/50 dark:bg-blue-950/20 text-sm">
          <div className="flex items-start gap-2">
            <span className="material-symbols-outlined text-blue-500 text-[18px] mt-0.5">auto_awesome</span>
            <p className="text-blue-900 dark:text-blue-200">
              Der Buchungstyp wurde automatisch basierend auf der Event-Dauer berechnet (15&euro;/Tag). Du kannst ihn bearbeiten oder entfernen.
            </p>
          </div>
        </div>
      )}

      {/* Add option */}
      {!showForm ? (
        <button
          type="button"
          onClick={() => setShowForm(true)}
          className="flex items-center gap-1.5 text-sm text-primary hover:underline"
        >
          <span className="material-symbols-outlined text-[18px]">add</span>
          Buchungsoption hinzufügen
        </button>
      ) : (
        <div className="border rounded-lg p-4 space-y-3 bg-card">
          <h4 className="text-sm font-semibold">
            {editIndex !== null ? 'Option bearbeiten' : 'Neue Option'}
          </h4>
          <input
            type="text"
            placeholder="Name der Option *"
            value={editing.name}
            onChange={(e) => setEditing({ ...editing, name: e.target.value })}
            className="w-full px-3 py-2 rounded-md border text-sm bg-background"
            autoFocus
          />
          <input
            type="text"
            placeholder="Beschreibung (optional)"
            value={editing.description || ''}
            onChange={(e) => setEditing({ ...editing, description: e.target.value })}
            className="w-full px-3 py-2 rounded-md border text-sm bg-background"
          />
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs text-muted-foreground mb-1">Preis (&euro;)</label>
              <input
                type="number"
                value={editing.price || '0.00'}
                onChange={(e) => setEditing({ ...editing, price: e.target.value })}
                step="0.01"
                min="0"
                className="w-full px-3 py-2 rounded-md border text-sm bg-background"
              />
            </div>
            <div>
              <label className="block text-xs text-muted-foreground mb-1">
                Max. Teilnehmer (0=unbegrenzt)
              </label>
              <input
                type="number"
                value={editing.max_participants || 0}
                onChange={(e) =>
                  setEditing({ ...editing, max_participants: Number(e.target.value) })
                }
                min="0"
                className="w-full px-3 py-2 rounded-md border text-sm bg-background"
              />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs text-muted-foreground mb-1">Buchbar ab</label>
              <input
                type="datetime-local"
                value={editing.bookable_from || ''}
                onChange={(e) =>
                  setEditing({ ...editing, bookable_from: e.target.value || null })
                }
                className="w-full px-3 py-2 rounded-md border text-sm bg-background"
              />
            </div>
            <div>
              <label className="block text-xs text-muted-foreground mb-1">Buchbar bis</label>
              <input
                type="datetime-local"
                value={editing.bookable_till || ''}
                onChange={(e) =>
                  setEditing({ ...editing, bookable_till: e.target.value || null })
                }
                className="w-full px-3 py-2 rounded-md border text-sm bg-background"
              />
            </div>
          </div>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={editIndex !== null ? handleSaveEdit : handleAdd}
              disabled={!editing.name.trim()}
              className="px-4 py-2 bg-primary text-primary-foreground rounded-md text-sm disabled:opacity-50 flex items-center gap-1.5"
            >
              <span className="material-symbols-outlined text-[18px]">
                {editIndex !== null ? 'check' : 'add'}
              </span>
              {editIndex !== null ? 'Speichern' : 'Hinzufügen'}
            </button>
            <button
              type="button"
              onClick={handleCancel}
              className="px-4 py-2 border rounded-md text-sm hover:bg-muted"
            >
              Abbrechen
            </button>
          </div>
        </div>
      )}

      {/* Hint if no options */}
      {options.length === 0 && !showForm && (
        <div className="border rounded-lg p-3 bg-blue-50/50 dark:bg-blue-950/20 text-sm">
          <div className="flex items-start gap-2">
            <span className="material-symbols-outlined text-blue-500 text-[18px] mt-0.5">info</span>
            <p className="text-blue-900 dark:text-blue-200">
              Ohne Buchungsoptionen können sich Teilnehmer direkt anmelden. Du kannst jederzeit
              Optionen im Dashboard hinzufügen.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
