# Generated by Django 5.2.12 on 2026-07-13 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcollaborator',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_collaborations', to='profiles.usergroup', verbose_name='Gruppe'),
        ),
        migrations.AddField(
            model_name='contentcollaborator',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_collaborations', to=settings.AUTH_USER_MODEL, verbose_name='Nutzer'),
        ),
        migrations.AddField(
            model_name='contentcomment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_comments', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contentcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content.contentcomment'),
        ),
        migrations.AddField(
            model_name='contentcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentemotion',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_emotions', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contentemotion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_emotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentlink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_content_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentlink',
            name='source_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contentlink',
            name='target_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contentview',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_views', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contentview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duplicatedismissal',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duplicatedismissal',
            name='source_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dup_source', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='duplicatedismissal',
            name='target_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dup_target', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='embeddingfeedback',
            name='content_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='content.contentlink'),
        ),
        migrations.AddField(
            model_name='embeddingfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embedding_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_entries', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='featuredcontent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_search_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.tag'),
        ),
        migrations.AddField(
            model_name='tagsuggestion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='content.tag'),
        ),
        migrations.AddField(
            model_name='tagsuggestion',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_tag_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiinteraction',
            index=models.Index(fields=['context'], name='aiinteraction_context_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinteraction',
            index=models.Index(fields=['user'], name='aiinteraction_user_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinteraction',
            index=models.Index(fields=['created_at'], name='aiinteraction_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinteraction',
            index=models.Index(fields=['vote'], name='aiinteraction_vote_idx'),
        ),
        migrations.AddIndex(
            model_name='approvallog',
            index=models.Index(fields=['content_type', 'object_id'], name='approvallog_ct_oid_idx'),
        ),
        migrations.AddIndex(
            model_name='changeauditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='content_cha_content_80e94b_idx'),
        ),
        migrations.AddIndex(
            model_name='changeauditlog',
            index=models.Index(fields=['changed_at'], name='content_cha_changed_c4ed46_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcollaborator',
            index=models.Index(fields=['content_type', 'object_id'], name='collab_content_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcollaborator',
            index=models.Index(fields=['user'], name='collab_user_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcollaborator',
            index=models.Index(fields=['group'], name='collab_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentcollaborator',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('group__isnull', False), _connector='OR'), name='collab_user_or_group_required'),
        ),
        migrations.AddConstraint(
            model_name='contentcollaborator',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'user', 'group'), name='unique_collab'),
        ),
        migrations.AddIndex(
            model_name='contentcomment',
            index=models.Index(fields=['content_type', 'object_id'], name='contentcomment_ct_oid_idx'),
        ),
        migrations.AddIndex(
            model_name='contentemotion',
            index=models.Index(fields=['content_type', 'object_id'], name='contentemotion_ct_oid_idx'),
        ),
        migrations.AddIndex(
            model_name='contentlink',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='contentlink_src_ct_oid_idx'),
        ),
        migrations.AddIndex(
            model_name='contentlink',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='contentlink_tgt_ct_oid_idx'),
        ),
        migrations.AddIndex(
            model_name='contentview',
            index=models.Index(fields=['content_type', 'object_id'], name='contentview_ct_oid_idx'),
        ),
        migrations.AddIndex(
            model_name='duplicatedismissal',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='content_dup_source__00a3ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='duplicatedismissal',
            unique_together={('source_content_type', 'source_object_id', 'target_content_type', 'target_object_id')},
        ),
        migrations.AddIndex(
            model_name='featuredcontent',
            index=models.Index(fields=['content_type', 'object_id'], name='featuredcontent_ct_oid_idx'),
        ),
    ]
