# Generated by Django 5.2.12 on 2026-08-08 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffFoodAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('endpoint', models.CharField(max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['resource_type', 'object_id'], name='content_sta_resourc_d365e7_idx'), models.Index(fields=['user', 'accessed_at'], name='content_sta_user_id_adfcf0_idx')],
            },
        ),
    ]
