# Generated by Django 5.2.12 on 2026-09-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_stafffoodaccesslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiinteraction",
            name="context",
            field=models.CharField(
                choices=[
                    ("improve_text", "Text verbessern"),
                    ("suggest_tags", "Tags vorschlagen"),
                    ("refurbish", "Inhalt aufbereiten"),
                    ("image_generation", "Bild generieren"),
                    ("suggest_materials", "Materialien vorschlagen"),
                    ("suggest_recipe_supplies", "Rezeptmaterialien vorschlagen"),
                    ("ingredient_ai_create", "Zutat erstellen"),
                    ("ingredient_ai_suggest_all", "Zutatenfelder vorschlagen"),
                    ("ingredient_suggest_all", "Zutatenfelder vorschlagen"),
                    ("ingredient_ai_fill_missing", "Zutatenfelder ergänzen"),
                    ("ingredient_url_import", "Zutat aus URL importieren"),
                    ("ingredient_assignment_suggestion", "Zutatenzuordnung vorschlagen"),
                    ("ingredient_enrichment", "Zutat anreichern"),
                    ("ingredient_parser", "Zutaten parsen"),
                    ("recipe_ai_create", "Rezept erstellen"),
                    ("recipe_suggest_all", "Rezeptmetadaten vorschlagen"),
                    ("recipe_suggestions", "Rezeptvorschläge"),
                    ("ai_ingredients", "Rezeptzutaten vorschlagen"),
                    ("ai_quantity_estimation", "Mengen schätzen"),
                    ("recipe_step_generation", "Schritte generieren"),
                    ("recipe_step_improve", "Schritt verbessern"),
                    ("recipe_markdown_conversion", "Markdown konvertieren"),
                    ("recipe_smart_input", "Smart Input"),
                    ("meal_plan_ai_suggest", "Essensplan vorschlagen"),
                    ("intelligent_suggestions_rerank", "Intelligente Vorschläge"),
                    ("packing_list_suggestions", "Packlistenvorschläge"),
                    ("generate_invitation", "Einladung generieren"),
                    ("document_text_generation", "Dokumententext generieren"),
                    ("url_import_matching", "URL-Import Zuordnung"),
                    ("url_import_metadata", "URL-Import Metadaten"),
                    ("url_import_grounding_fallback", "URL-Import Grounding"),
                    ("batch_generate_default_portions", "Standardportionen generieren"),
                    ("classify_ingredients", "Zutaten klassifizieren"),
                    ("clean_ingredient_descriptions_batch", "Beschreibungen bereinigen"),
                    ("embedding", "Embedding"),
                    ("enrich_recipe_metadata", "Rezeptmetadaten anreichern"),
                    ("fix_ingredient_fill", "Zutat reparieren (Felder)"),
                    ("fix_ingredient_name", "Zutat reparieren (Name)"),
                    ("normalize_portions", "Portionen normalisieren"),
                    ("rename_rewe_batch", "REWE umbenennen"),
                ],
                max_length=50,
            ),
        ),
    ]
