# Generated by Django 5.2.12 on 2026-06-07 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_pgvector_extension"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "verbose_name": "Änderungseintrag",
                "verbose_name_plural": "Änderungseinträge",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(fields=["content_type", "object_id"], name="content_cha_content_80e94b_idx"),
                    models.Index(fields=["changed_at"], name="content_cha_changed_c4ed46_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DuplicateDismissal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_object_id", models.PositiveIntegerField()),
                ("target_object_id", models.PositiveIntegerField()),
                ("dismissed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dup_source",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dup_target",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Duplikat-Ausblendung",
                "verbose_name_plural": "Duplikat-Ausblendungen",
                "indexes": [
                    models.Index(
                        fields=["source_content_type", "source_object_id"], name="content_dup_source__00a3ce_idx"
                    )
                ],
                "unique_together": {
                    ("source_content_type", "source_object_id", "target_content_type", "target_object_id")
                },
            },
        ),
    ]
