# Generated by Django 5.2.12 on 2026-06-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_changeauditlog_duplicatedismissal"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    "CREATE INDEX IF NOT EXISTS supply_ingredient_embedding_ivfflat "
                    "ON supply_ingredient "
                    "USING ivfflat (embedding vector_cosine_ops) "
                    "WITH (lists = 82);"
                ),
                (
                    "CREATE INDEX IF NOT EXISTS recipe_recipe_embedding_ivfflat "
                    "ON recipe_recipe "
                    "USING ivfflat (embedding vector_cosine_ops) "
                    "WITH (lists = 11);"
                ),
                (
                    "CREATE INDEX IF NOT EXISTS blog_blog_embedding_ivfflat "
                    "ON blog_blog "
                    "USING ivfflat (embedding vector_cosine_ops) "
                    "WITH (lists = 1);"
                ),
                (
                    "CREATE INDEX IF NOT EXISTS session_groupsession_embedding_ivfflat "
                    "ON session_groupsession "
                    "USING ivfflat (embedding vector_cosine_ops) "
                    "WITH (lists = 1);"
                ),
                (
                    "CREATE INDEX IF NOT EXISTS game_game_embedding_ivfflat "
                    "ON game_game "
                    "USING ivfflat (embedding vector_cosine_ops) "
                    "WITH (lists = 1);"
                ),
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS supply_ingredient_embedding_ivfflat;",
                "DROP INDEX IF EXISTS recipe_recipe_embedding_ivfflat;",
                "DROP INDEX IF EXISTS blog_blog_embedding_ivfflat;",
                "DROP INDEX IF EXISTS session_groupsession_embedding_ivfflat;",
                "DROP INDEX IF EXISTS game_game_embedding_ivfflat;",
            ],
        ),
    ]
