# Generated by Django 5.2.12 on 2026-06-19 06:47

from django.db import migrations


def migrate_status_forward(apps, schema_editor):
    """approved/published → verified; submitted/rejected/archived → draft"""
    # Only the main content models (not child models like RecipeItem)
    content_model_map = {
        ("session", "groupsession"),
        ("blog", "blog"),
        ("game", "game"),
        ("recipe", "recipe"),
    }
    for app_label, model_name in content_model_map:
        try:
            model = apps.get_model(app_label, model_name)
            model.objects.filter(status="approved").update(status="verified")
            model.objects.filter(status="published").update(status="verified")
            model.objects.filter(status="submitted").update(status="draft")
            model.objects.filter(status="rejected").update(status="draft")
            model.objects.filter(status="archived").update(status="draft")
        except LookupError:
            continue


def migrate_status_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_contentcollaborator"),
        ("session", "0003_groupsession_is_deleted_alter_groupsession_status"),
        ("blog", "0004_blog_is_deleted_alter_blog_status"),
        ("game", "0004_game_is_deleted_alter_game_status"),
        ("recipe", "0034_remove_recipe_recipe_owner_vis_status_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_status_forward, migrate_status_reverse),
    ]
