# Generated by Django 5.2.12 on 2026-06-21 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_migrate_content_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContentCollaborator",
        ),
    ]
