# Generated by Django 5.2.12 on 2026-06-28 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_hnsw_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentlink",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manuell verknüpft"),
                    ("embedding", "Embedding-basiert"),
                    ("ai_suggested", "KI-Vorschlag"),
                    ("duplicate_merged", "Duplikat zusammengeführt"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AiInteraction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("content_improve_text", "Text verbessern"),
                            ("content_suggest_tags", "Tags vorschlagen"),
                            ("content_refurbish", "Inhalt aufbereiten"),
                            ("content_generate_image", "Bild generieren"),
                            ("content_suggest_supplies", "Materialien vorschlagen"),
                            ("ingredient_ai_create", "Zutat erstellen"),
                            ("ingredient_ai_suggest_all", "Zutatenfelder vorschlagen"),
                            ("ingredient_import_url", "Zutat aus URL importieren"),
                            ("recipe_ai_create", "Rezept erstellen"),
                            ("recipe_ai_suggest_all", "Rezeptmetadaten vorschlagen"),
                            ("recipe_ai_suggest_ingredients", "Rezeptzutaten vorschlagen"),
                            ("packing_list_ai_suggest", "Packlistenvorschläge"),
                            ("event_generate_invitation", "Einladung generieren"),
                            ("documents_generate_text", "Dokumententext generieren"),
                        ],
                        max_length=50,
                    ),
                ),
                ("prompt", models.JSONField()),
                ("response", models.TextField(blank=True, default="")),
                ("model", models.CharField(max_length=100)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=50)),
                (
                    "vote",
                    models.CharField(blank=True, choices=[("up", "👍"), ("down", "👎")], max_length=10, null=True),
                ),
                ("voted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["context"], name="aiinteraction_context_idx"),
                    models.Index(fields=["user"], name="aiinteraction_user_idx"),
                    models.Index(fields=["created_at"], name="aiinteraction_created_at_idx"),
                    models.Index(fields=["vote"], name="aiinteraction_vote_idx"),
                ],
            },
        ),
    ]
