# Generated by Django 5.2.12 on 2026-06-28 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_alter_contentlink_link_type_aiinteraction"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("profiles", "0007_populate_user_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentCollaborator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField(verbose_name="Objekt-ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("viewer", "Betrachter"), ("editor", "Bearbeiter"), ("admin", "Admin")],
                        default="viewer",
                        max_length=10,
                        verbose_name="Rolle",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Inhaltstyp",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_collaborations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_collaborations",
                        to="profiles.usergroup",
                        verbose_name="Gruppe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_collaborations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inhaltsfreigabe",
                "verbose_name_plural": "Inhaltsfreigaben",
                "ordering": ["role", "created_at"],
                "indexes": [
                    models.Index(fields=["content_type", "object_id"], name="collab_content_idx"),
                    models.Index(fields=["user"], name="collab_user_idx"),
                    models.Index(fields=["group"], name="collab_group_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("user__isnull", False), ("group__isnull", False), _connector="OR"),
                        name="collab_user_or_group_required",
                    ),
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "user", "group"), name="unique_collab"
                    ),
                ],
            },
        ),
    ]
