# Generated by Django 5.2.12 on 2026-06-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_contentcollaborator"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="group",
            field=models.CharField(blank=True, default="general", max_length=50),
        ),
    ]
