# Generated by Django 5.2.12 on 2026-07-12 11:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_add_embedding_text_hash_and_alter_dimensions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="embedding",
        ),
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tag",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
