# Generated by Django 5.2.12 on 2026-07-12 11:59

import uuid
from django.db import migrations


def populate_uuids(apps, schema_editor):
    Tag = apps.get_model("content", "Tag")
    for tag in Tag.objects.all():
        tag.uuid = uuid.uuid4()
        tag.save(update_fields=["uuid"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_add_tag_uuid_description"),
    ]

    operations = [
        migrations.RunPython(populate_uuids, noop),
    ]
