# Generated by Django 5.2.12 on 2026-09-28 21:12

from django.conf import settings
from django.db import migrations, models


def backfill_tiers(apps, schema_editor):
    """Existing records: no user → system, staff users → staff, others keep `user`."""
    AiInteraction = apps.get_model("content", "AiInteraction")
    AiInteraction.objects.filter(user__isnull=True).update(tier="system")
    AiInteraction.objects.filter(user__is_staff=True).update(tier="staff")


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0015_buffet_role_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiBudgetBucket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=64, unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AiResultCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feature", models.CharField(max_length=50)),
                ("input_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="aiinteraction",
            name="anon_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="aiinteraction",
            name="reserved_cost_eur",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="aiinteraction",
            name="tier",
            field=models.CharField(
                choices=[("anonymous", "Anonym"), ("user", "Nutzer"), ("staff", "Staff"), ("system", "System")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="aiinteraction",
            index=models.Index(fields=["tier", "created_at"], name="aiinteraction_tier_created_idx"),
        ),
        migrations.AddIndex(
            model_name="aiinteraction",
            index=models.Index(fields=["anon_key", "created_at"], name="aiinteraction_anon_created_idx"),
        ),
        migrations.AddIndex(
            model_name="aiinteraction",
            index=models.Index(fields=["user", "created_at"], name="aiinteraction_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="airesultcache",
            index=models.Index(fields=["expires_at"], name="airesultcache_expires_idx"),
        ),
        migrations.AddConstraint(
            model_name="airesultcache",
            constraint=models.UniqueConstraint(
                fields=("feature", "input_hash"), name="airesultcache_feature_hash_uniq"
            ),
        ),
        migrations.RunPython(backfill_tiers, migrations.RunPython.noop),
    ]
