# Generated by Django 5.2.12 on 2026-10-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0016_ai_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiinteraction",
            name="anon_key",
            field=models.CharField(blank=True, db_default="", default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="aiinteraction",
            name="tier",
            field=models.CharField(
                choices=[("anonymous", "Anonym"), ("user", "Nutzer"), ("staff", "Staff"), ("system", "System")],
                db_default="user",
                default="user",
                max_length=10,
            ),
        ),
    ]
