# Generated by Django 5.2.12 on 2026-07-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_switch_tag_pk_to_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='completion_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='cost_eur',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='is_background',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='pricing_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='thoughts_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='total_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
