# Generated by Django 5.2.12 on 2026-10-03 10:19

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

NEW_BUFFET_ROLES = (
    ("buffet-cheese", "Käse", "dining"),
    ("buffet-salty-snack", "Knabbereien", "cookie"),
    ("buffet-sweet-snack", "Süßes & Kekse", "cake"),
    ("buffet-nuts", "Nüsse & Trockenobst", "grain"),
    ("buffet-dip", "Dips", "restaurant_menu"),
    ("buffet-salad", "Salate", "nutrition"),
    ("buffet-carb", "Beilagen", "grain"),
    ("buffet-main", "Hauptkomponente", "dinner_dining"),
    ("buffet-soup", "Suppen & Eintöpfe", "local_cafe"),
    ("buffet-topping", "Toppings & Extras", "add_circle"),
)


def add_buffet_roles(apps: Apps, schema_editor: BaseDatabaseSchemaEditor | None) -> None:
    Tag = apps.get_model("content", "Tag")
    parent, _ = Tag.objects.get_or_create(
        slug="buffet",
        defaults={"name": "Buffet", "icon": "grid_view", "group": "buffet", "sort_order": 0},
    )
    for sort_order, (slug, name, icon) in enumerate(NEW_BUFFET_ROLES, start=10):
        Tag.objects.get_or_create(
            slug=slug,
            defaults={
                "name": name,
                "icon": icon,
                "group": "buffet",
                "sort_order": sort_order,
                "parent": parent,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0017_ai_budget_db_defaults"),
    ]

    operations = [migrations.RunPython(add_buffet_roles, migrations.RunPython.noop)]
