# Generated by Django 5.2.12 on 2026-04-08 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("supply", "0003_alter_portion_options_portion_is_default_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "source_type",
                    models.CharField(
                        choices=[("manual", "Manuell"), ("recipe", "Rezept"), ("meal_event", "Essensplan")],
                        default="manual",
                        max_length=20,
                        verbose_name="Quelle",
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID des Rezepts oder MealEvents, aus dem die Liste erstellt wurde",
                        null=True,
                        verbose_name="Quell-ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_shopping_lists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Besitzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einkaufsliste",
                "verbose_name_plural": "Einkaufslisten",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("quantity_g", models.FloatField(default=0, verbose_name="Menge in Gramm")),
                ("unit", models.CharField(default="g", max_length=20, verbose_name="Einheit")),
                ("is_checked", models.BooleanField(default=False, verbose_name="Abgehakt")),
                ("checked_at", models.DateTimeField(blank=True, null=True, verbose_name="Abgehakt am")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sortierung")),
                ("note", models.CharField(blank=True, default="", max_length=500, verbose_name="Notiz")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_shopping_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Abgehakt von",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopping_list_items",
                        to="supply.ingredient",
                        verbose_name="Zutat",
                    ),
                ),
                (
                    "retail_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopping_list_items",
                        to="supply.retailsection",
                        verbose_name="Supermarkt-Abteilung",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shopping.shoppinglist",
                        verbose_name="Einkaufsliste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einkaufslisten-Eintrag",
                "verbose_name_plural": "Einkaufslisten-Einträge",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListCollaborator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("viewer", "Betrachter"), ("editor", "Bearbeiter"), ("admin", "Administrator")],
                        default="viewer",
                        max_length=10,
                        verbose_name="Rolle",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborators",
                        to="shopping.shoppinglist",
                        verbose_name="Einkaufsliste",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_collaborations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einkaufslisten-Mitglied",
                "verbose_name_plural": "Einkaufslisten-Mitglieder",
                "ordering": ["role", "user__username"],
                "unique_together": {("shopping_list", "user")},
            },
        ),
    ]
