# Generated by Django 5.2.12 on 2026-07-13 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenReminderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Küchenbedarf-Kategorie',
                'verbose_name_plural': 'Küchenbedarf-Kategorien',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItemSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_g', models.FloatField(default=0, verbose_name='Menge in Gramm')),
                ('recipe_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Rezeptname (cached)')),
                ('meal_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Mahlzeit-Label (cached)')),
                ('recipe_slug', models.CharField(blank=True, default='', max_length=255, verbose_name='Rezept-Slug (cached)')),
            ],
            options={
                'verbose_name': 'Einkaufslisten-Herkunft',
                'verbose_name_plural': 'Einkaufslisten-Herkünfte',
                'ordering': ['-quantity_g'],
            },
        ),
        migrations.CreateModel(
            name='KitchenReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sortierung')),
                ('is_published', models.BooleanField(default=False, verbose_name='Veröffentlicht')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_reminder_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Vorgeschlagen von')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='shopping.kitchenremindercategory', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Küchenbedarf-Erinnerung',
                'verbose_name_plural': 'Küchenbedarf-Erinnerungen',
                'ordering': ['category__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('source_type', models.CharField(choices=[('manual', 'Manuell'), ('recipe', 'Rezept'), ('meal_event', 'Essensplan')], default='manual', max_length=20, verbose_name='Quelle')),
                ('source_id', models.IntegerField(blank=True, help_text='ID des Rezepts oder MealPlans, aus dem die Liste erstellt wurde', null=True, verbose_name='Quell-ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shopping_lists', to=settings.AUTH_USER_MODEL, verbose_name='Besitzer')),
            ],
            options={
                'verbose_name': 'Einkaufsliste',
                'verbose_name_plural': 'Einkaufslisten',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReweExportToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(verbose_name='Läuft ab um')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewe_export_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Nutzer')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_tokens', to='shopping.shoppinglist', verbose_name='Einkaufsliste')),
            ],
            options={
                'verbose_name': 'REWE-Export-Token',
                'verbose_name_plural': 'REWE-Export-Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Betrachter'), ('editor', 'Bearbeiter'), ('admin', 'Administrator')], default='viewer', max_length=10, verbose_name='Rolle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='shopping.shoppinglist', verbose_name='Einkaufsliste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_collaborations', to=settings.AUTH_USER_MODEL, verbose_name='Nutzer')),
            ],
            options={
                'verbose_name': 'Einkaufslisten-Mitglied',
                'verbose_name_plural': 'Einkaufslisten-Mitglieder',
                'ordering': ['role', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('quantity_g', models.FloatField(default=0, verbose_name='Menge in Gramm')),
                ('unit', models.CharField(default='g', max_length=20, verbose_name='Einheit')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Abgehakt')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgehakt am')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sortierung')),
                ('note', models.CharField(blank=True, default='', max_length=500, verbose_name='Notiz')),
                ('rewe_added_at', models.DateTimeField(blank=True, null=True, verbose_name='Zu REWE übertragen am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_shopping_items', to=settings.AUTH_USER_MODEL, verbose_name='Abgehakt von')),
            ],
            options={
                'verbose_name': 'Einkaufslisten-Eintrag',
                'verbose_name_plural': 'Einkaufslisten-Einträge',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
