# Generated by Django 5.2.12 on 2026-04-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglist",
            name="source_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID des Rezepts oder MealPlans, aus dem die Liste erstellt wurde",
                null=True,
                verbose_name="Quell-ID",
            ),
        ),
    ]
