# Generated by Django 5.2.12 on 2026-07-13 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0002_initial'),
        ('recipe', '0002_initial'),
        ('shopping', '0001_initial'),
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_items', to='supply.ingredient', verbose_name='Zutat'),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='retail_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_items', to='supply.retailsection', verbose_name='Supermarkt-Abteilung'),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist', verbose_name='Einkaufsliste'),
        ),
        migrations.AddField(
            model_name='shoppinglistitemsource',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_item_sources', to='planner.meal', verbose_name='Mahlzeit'),
        ),
        migrations.AddField(
            model_name='shoppinglistitemsource',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_item_sources', to='recipe.recipe', verbose_name='Rezept'),
        ),
        migrations.AddField(
            model_name='shoppinglistitemsource',
            name='shopping_list_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='shopping.shoppinglistitem', verbose_name='Einkaufslisten-Eintrag'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppinglistcollaborator',
            unique_together={('shopping_list', 'user')},
        ),
    ]
