# Generated by Django 5.2.12 on 2026-05-26 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0007_meal_enhancements"),
        ("recipe", "0009_simple_meal_type"),
        ("shopping", "0002_alter_shoppinglist_source_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingListItemSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity_g", models.FloatField(default=0, verbose_name="Menge in Gramm")),
                (
                    "recipe_name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Rezeptname (cached)"),
                ),
                (
                    "meal_label",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Mahlzeit-Label (cached)"),
                ),
                (
                    "recipe_slug",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Rezept-Slug (cached)"),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopping_item_sources",
                        to="planner.meal",
                        verbose_name="Mahlzeit",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopping_item_sources",
                        to="recipe.recipe",
                        verbose_name="Rezept",
                    ),
                ),
                (
                    "shopping_list_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="shopping.shoppinglistitem",
                        verbose_name="Einkaufslisten-Eintrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einkaufslisten-Herkunft",
                "verbose_name_plural": "Einkaufslisten-Herkünfte",
                "ordering": ["-quantity_g"],
            },
        ),
    ]
