# Generated by Django 5.2.12 on 2026-05-31 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0003_shoppinglistitemsource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KitchenReminderCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sortierung")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Küchenbedarf-Kategorie",
                "verbose_name_plural": "Küchenbedarf-Kategorien",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="KitchenReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sortierung")),
                ("is_published", models.BooleanField(default=False, verbose_name="Veröffentlicht")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suggested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kitchen_reminder_suggestions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vorgeschlagen von",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="shopping.kitchenremindercategory",
                        verbose_name="Kategorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Küchenbedarf-Erinnerung",
                "verbose_name_plural": "Küchenbedarf-Erinnerungen",
                "ordering": ["category__sort_order", "sort_order", "name"],
            },
        ),
    ]
