# Generated by Django 5.2.12 on 2026-05-31 15:07

from django.db import migrations


INITIAL_DATA = {
    "Reinigung": [
        "Spülmittel",
        "Spülschwämme",
        "Küchenrolle",
        "Geschirrtücher",
        "Schwammtücher / Lappen",
        "Spültabs",
    ],
    "Hygiene": [
        "Klopapier",
        "Taschentücher",
        "Handseife",
        "Desinfektionsmittel",
        "Handschuhe (Einweg)",
    ],
    "Kochen": [
        "Gasflasche",
        "Alufolie",
        "Backpapier",
        "Feuerzeug / Streichhölzer",
        "Grillkohle / Grillanzünder",
    ],
    "Aufbewahrung": [
        "Frischhaltefolie",
        "Gefrierbeutel / Zip-Beutel",
    ],
    "Entsorgung": [
        "Müllbeutel (groß)",
        "Müllbeutel (klein)",
    ],
}


def create_initial_reminders(apps, schema_editor):
    KitchenReminderCategory = apps.get_model("shopping", "KitchenReminderCategory")
    KitchenReminder = apps.get_model("shopping", "KitchenReminder")

    for cat_order, (cat_name, items) in enumerate(INITIAL_DATA.items()):
        category = KitchenReminderCategory.objects.create(
            name=cat_name, sort_order=cat_order
        )
        for item_order, item_name in enumerate(items):
            KitchenReminder.objects.create(
                name=item_name,
                category=category,
                sort_order=item_order,
                is_published=True,
            )


def remove_initial_reminders(apps, schema_editor):
    KitchenReminderCategory = apps.get_model("shopping", "KitchenReminderCategory")
    KitchenReminderCategory.objects.filter(
        name__in=INITIAL_DATA.keys()
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0004_kitchenremindercategory_kitchenreminder"),
    ]

    operations = [
        migrations.RunPython(create_initial_reminders, remove_initial_reminders),
    ]
