# Generated by Django 5.2.12 on 2026-06-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopping", "0005_initial_kitchen_reminders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglist",
            name="source_type",
            field=models.CharField(
                choices=[("manual", "Manuell"), ("recipe", "Rezept"), ("meal_plan", "Essensplan")],
                default="manual",
                max_length=20,
                verbose_name="Quelle",
            ),
        ),
    ]
