# Generated by Django 5.2.12 on 2026-06-18 23:05

from django.db import migrations


def migrate_source_type(apps, schema_editor):
    ShoppingList = apps.get_model("shopping", "ShoppingList")
    ShoppingList.objects.filter(source_type="meal_event").update(source_type="meal_plan")


def reverse_source_type(apps, schema_editor):
    ShoppingList = apps.get_model("shopping", "ShoppingList")
    ShoppingList.objects.filter(source_type="meal_plan").update(source_type="meal_event")


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0006_rename_source_type_meal_event_to_meal_plan"),
    ]

    operations = [
        migrations.RunPython(migrate_source_type, reverse_source_type),
    ]
