# Generated by Django 5.2.12 on 2026-06-19 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopping", "0007_migrate_source_type_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShoppingListCollaborator",
        ),
    ]
