# Generated by Django 5.2.12 on 2026-06-21 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopping", "0008_drop_shoppinglist_collaborator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglist",
            name="source_type",
            field=models.CharField(
                choices=[("manual", "Manuell"), ("recipe", "Rezept"), ("meal_event", "Essensplan")],
                default="manual",
                max_length=20,
                verbose_name="Quelle",
            ),
        ),
        migrations.CreateModel(
            name="ShoppingListCollaborator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("viewer", "Betrachter"), ("editor", "Bearbeiter"), ("admin", "Administrator")],
                        default="viewer",
                        max_length=10,
                        verbose_name="Rolle",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborators",
                        to="shopping.shoppinglist",
                        verbose_name="Einkaufsliste",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_collaborations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einkaufslisten-Mitglied",
                "verbose_name_plural": "Einkaufslisten-Mitglieder",
                "ordering": ["role", "user__username"],
                "unique_together": {("shopping_list", "user")},
            },
        ),
    ]
