# Generated by Django 5.2.12 on 2026-07-11 16:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0009_alter_shoppinglist_source_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglistitem",
            name="rewe_added_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Zu REWE übertragen am"),
        ),
        migrations.CreateModel(
            name="ReweExportToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Token")),
                ("expires_at", models.DateTimeField(verbose_name="Läuft ab um")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_tokens",
                        to="shopping.shoppinglist",
                        verbose_name="Einkaufsliste",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewe_export_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "REWE-Export-Token",
                "verbose_name_plural": "REWE-Export-Tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
