"""Deterministic retail section classifier based on German compound head nouns.

German product names put the product type at the *end* of a compound
("Orangen**saft**", "Frucht**joghurt**", "Butter**keks**") and usually lead with
the product type ("Schokolade Espresso", "Thunfisch Zitrone"). The classifier
therefore scans the name token by token and, inside a token, prefers the
keyword that ends latest (the compound head), then the longest keyword.

Process markers override the base product type afterwards:
- frozen ("TK", "tiefgekühlt") -> one of the TK groups
- canned ("Dose", "Konserve", "eingelegt") -> "Konserven & Gläser"
- dried fruit -> "Nüsse, Samen & Trockenobst"
- ground/dried herbs -> "Gewürze & Trockenkräuter"
- vegan meat/sausage -> "Fleischersatz & Tofu"

Unclassifiable names return ``None`` and are left for the AI review.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from functools import lru_cache

OBST = "Obst"
GEMUESE = "Gemüse"
SALATE = "Salate & frische Kräuter"
BROT = "Brot & Backwaren"
FLEISCH = "Fleisch"
WURST = "Wurst & Aufschnitt"
FISCH = "Fisch & Meeresfrüchte"
MILCH = "Milch & Pflanzendrinks"
JOGHURT = "Joghurt, Quark & Desserts"
KAESE = "Käse"
EIER = "Eier"
BUTTER = "Butter & Margarine"
ERSATZ = "Fleischersatz & Tofu"
FEINKOST = "Feinkost & Kühltheke"
NUDELN = "Nudeln"
REIS = "Reis & Getreide"
HUELSEN = "Hülsenfrüchte"
NUESSE = "Nüsse, Samen & Trockenobst"
MUESLI = "Müsli & Cerealien"
BACKEN = "Mehl, Zucker & Backzutaten"
AUFSTRICH = "Brotaufstriche"
KONSERVE = "Konserven & Gläser"
OEL = "Öle & Essig"
SAUCE = "Saucen & Würzsaucen"
GEWUERZ = "Gewürze & Trockenkräuter"
FERTIG = "Brühen, Suppen & Fertiggerichte"
INTERNATIONAL = "Internationale Küche"
SUESS = "Süßwaren & Kekse"
KNABBER = "Knabberartikel"
KAFFEE = "Kaffee, Tee & Kakao"
SAFT = "Säfte & Smoothies"
WASSER = "Wasser & Erfrischungsgetränke"
ALKOHOL = "Alkoholische Getränke"
TK_OBST_GEMUESE = "TK Obst & Gemüse"
TK_FLEISCH_FISCH = "TK Fleisch & Fisch"
TK_FERTIG = "TK Fertiggerichte & Pizza"
TK_EIS = "TK Eis & Desserts"
SONSTIGES = "Sonstiges"

# Keyword -> section. Keywords are matched as substrings of a token (compound
# aware). A leading "=" restricts a keyword to whole tokens (for short words
# like "ei" that would otherwise match everywhere).
_KEYWORDS: dict[str, tuple[str, ...]] = {
    OBST: (
        "cranberries",
        "apfel",
        "äpfel",
        "birne",
        "banane",
        "orange",
        "mandarine",
        "clementine",
        "zitrone",
        "limette",
        "grapefruit",
        "pampelmuse",
        "kiwi",
        "mango",
        "ananas",
        "papaya",
        "melone",
        "traube",
        "erdbeere",
        "erdbeeren",
        "himbeere",
        "himbeeren",
        "heidelbeere",
        "heidelbeeren",
        "blaubeere",
        "blaubeeren",
        "brombeere",
        "brombeeren",
        "johannisbeere",
        "johannisbeeren",
        "stachelbeere",
        "kirsche",
        "kirschen",
        "pfirsich",
        "nektarine",
        "aprikose",
        "marille",
        "pflaume",
        "zwetschge",
        "zwetschgen",
        "feige",
        "granatapfel",
        "passionsfrucht",
        "maracuja",
        "physalis",
        "litschi",
        "rhabarber",
        "quitte",
        "obst",
        "beeren",
        "früchte",
        "avocado",
        "kaki",
        "sharon",
        "dattel",
        "datteln",
        "cranberry",
        "cranberrys",
        "holunderbeere",
        "obstsalat",
    ),
    GEMUESE: (
        "tomate",
        "tomaten",
        "gurke",
        "paprika",
        "zucchini",
        "aubergine",
        "karotte",
        "karotten",
        "möhre",
        "möhren",
        "kartoffel",
        "kartoffeln",
        "süßkartoffel",
        "zwiebel",
        "zwiebeln",
        "schalotte",
        "knoblauch",
        "lauch",
        "porree",
        "sellerie",
        "fenchel",
        "brokkoli",
        "broccoli",
        "blumenkohl",
        "kohlrabi",
        "kohl",
        "weißkohl",
        "rotkohl",
        "wirsing",
        "grünkohl",
        "rosenkohl",
        "chinakohl",
        "spitzkohl",
        "pak choi",
        "spinat",
        "mangold",
        "kürbis",
        "hokkaido",
        "butternut",
        "rote bete",
        "rote beete",
        "bete",
        "radieschen",
        "rettich",
        "pastinake",
        "petersilienwurzel",
        "steckrübe",
        "rübe",
        "spargel",
        "erbsen",
        "zuckerschoten",
        "bohnen",
        "prinzessbohnen",
        "brechbohnen",
        "mais",
        "maiskolben",
        "pilze",
        "champignon",
        "champignons",
        "pfifferlinge",
        "austernpilze",
        "shiitake",
        "ingwer",
        "chili",
        "chilischote",
        "peperoni",
        "okra",
        "artischocke",
        "gemüse",
        "suppengrün",
        "frühlingszwiebel",
        "frühlingszwiebeln",
        "lauchzwiebel",
        "topinambur",
        "schwarzwurzel",
        "edamame",
        "kurkumawurzel",
        "meerrettich",
    ),
    SALATE: (
        "salat",
        "eisbergsalat",
        "kopfsalat",
        "feldsalat",
        "rucola",
        "rauke",
        "romanasalat",
        "lollo",
        "radicchio",
        "chicorée",
        "endivie",
        "sprossen",
        "kresse",
        "petersilie",
        "schnittlauch",
        "basilikum",
        "dill",
        "koriandergrün",
        "minze",
        "pfefferminze",
        "rosmarin",
        "thymian",
        "salbei",
        "estragon",
        "kerbel",
        "zitronenmelisse",
        "kräuter",
        "babyspinat",
        "blattsalat",
        "salatmix",
        "salatmischung",
    ),
    BROT: (
        "piadina",
        "stuten",
        "panini",
        "brot",
        "brötchen",
        "semmel",
        "toast",
        "baguette",
        "ciabatta",
        "croissant",
        "brezel",
        "laugen",
        "bagel",
        "wrap",
        "wraps",
        "tortilla",
        "fladen",
        "fladenbrot",
        "pita",
        "naan",
        "knäckebrot",
        "zwieback",
        "kuchen",
        "torte",
        "berliner",
        "krapfen",
        "hefezopf",
        "stollen",
        "muffin",
        "muffins",
        "donut",
        "brioche",
        "burger buns",
        "buns",
        "brötchenhälften",
        "pumpernickel",
        "piada",
        "teigfladen",
        "blätterteig",
        "hörnchen",
        "schnecke",
        "streuselkuchen",
        "rosinenbrötchen",
        "milchbrötchen",
    ),
    FLEISCH: (
        "fleisch",
        "hackfleisch",
        "=hack",
        "gehacktes",
        "rind",
        "rindfleisch",
        "schwein",
        "schweinefleisch",
        "kalb",
        "lamm",
        "hähnchen",
        "hühnchen",
        "huhn",
        "hühnerbrust",
        "hähnchenbrust",
        "pute",
        "puten",
        "truthahn",
        "=ente",
        "entenbrust",
        "=gans",
        "=wild",
        "=reh",
        "hirsch",
        "steak",
        "schnitzel",
        "filet",
        "braten",
        "gulasch",
        "geschnetzeltes",
        "kotelett",
        "nacken",
        "rücken",
        "keule",
        "schenkel",
        "flügel",
        "wings",
        "rippchen",
        "spareribs",
        "frikadelle",
        "frikadellen",
        "bulette",
        "cevapcici",
        "gyros",
        "hähnchenschenkel",
        "leber",
        "roastbeef",
        "entrecote",
        "hüfte",
        "schulter",
        "bauch",
        "minutensteak",
        "medaillons",
        "geflügel",
        "kassler",
        "kasseler",
        "burger patty",
        "patty",
        "patties",
        "köttbullar",
        "nuggets",
        "klopse",
        "tenders",
        "kebab",
        "döner",
        "ćevapčići",
        "cevapcici",
        "chicken",
        "cheeseburger",
        "corned beef",
    ),
    WURST: (
        "debrecziner",
        "salame",
        "salsiccia",
        "sucuk",
        "knacker",
        "porchetta",
        "jamón",
        "kaminwurz",
        "bresaola",
        "wurst",
        "würstchen",
        "salami",
        "schinken",
        "speck",
        "bacon",
        "wiener",
        "frankfurter",
        "bratwurst",
        "bockwurst",
        "leberwurst",
        "leberkäse",
        "fleischwurst",
        "mortadella",
        "chorizo",
        "aufschnitt",
        "lyoner",
        "mettwurst",
        "teewurst",
        "cabanossi",
        "prosciutto",
        "serrano",
        "pancetta",
        "bierschinken",
        "kochschinken",
        "pastrami",
        "mett",
        "sülze",
        "debreziner",
        "krakauer",
        "wienerle",
        "nürnberger",
        "weißwurst",
        "geflügelwurst",
        "putenbrust aufschnitt",
        "hähnchenbrust aufschnitt",
    ),
    FISCH: (
        "fisch",
        "lachs",
        "thunfisch",
        "forelle",
        "hering",
        "makrele",
        "sardine",
        "sardinen",
        "sardellen",
        "anchovis",
        "kabeljau",
        "seelachs",
        "alaska-seelachs",
        "dorsch",
        "zander",
        "barsch",
        "pangasius",
        "tilapia",
        "scholle",
        "rotbarsch",
        "garnele",
        "garnelen",
        "shrimps",
        "krabben",
        "scampi",
        "muscheln",
        "miesmuscheln",
        "tintenfisch",
        "calamari",
        "oktopus",
        "matjes",
        "rollmops",
        "bismarckhering",
        "fischstäbchen",
        "surimi",
        "kaviar",
        "räucherlachs",
        "räucherforelle",
        "meeresfrüchte",
        "lachsfilet",
        "seafood",
        "sushi",
    ),
    MILCH: (
        "crème fine",
        "crèmefine",
        "crème légère",
        "creme fine",
        "schlagcreme",
        "proteinshake",
        "shake",
        "milch",
        "vollmilch",
        "h-milch",
        "frischmilch",
        "buttermilch",
        "sahne",
        "schlagsahne",
        "kochsahne",
        "schlagobers",
        "kondensmilch",
        "kaffeesahne",
        "haferdrink",
        "sojadrink",
        "mandeldrink",
        "reisdrink",
        "kokosdrink",
        "dinkeldrink",
        "erbsendrink",
        "drink",
        "haferdrink barista",
        "milchdrink",
        "kakaotrunk",
        "milchmischgetränk",
        "eiskaffee",
        "kefir",
        "ayran",
        "lassi",
        "molke",
        "sprühsahne",
        "sojasahne",
        "hafersahne",
        "pflanzensahne",
        "cuisine",
        "kochcreme",
    ),
    JOGHURT: (
        "sour cream",
        "topfen",
        "joghurt",
        "jogurt",
        "yoghurt",
        "quark",
        "skyr",
        "pudding",
        "grießpudding",
        "milchreis",
        "dessert",
        "dessertcreme",
        "mousse",
        "creme brulee",
        "panna cotta",
        "tiramisu",
        "götterspeise",
        "rote grütze",
        "grütze",
        "schmand",
        "saure sahne",
        "sauerrahm",
        "crème fraîche",
        "creme fraiche",
        "creme fraiche",
        "schichtdessert",
        "milchschnitte",
        "grießbrei",
        "kaltschale",
        "trinkjoghurt",
        "joghurtdrink",
        "fruchtzwerge",
        "protein-pudding",
        "high-protein-pudding",
    ),
    KAESE: (
        "comté",
        "caciotta",
        "manouri",
        "parmigiano",
        "tête de moine",
        "époisses",
        "obazda",
        "liptauer",
        "käse",
        "gouda",
        "emmentaler",
        "edamer",
        "cheddar",
        "mozzarella",
        "parmesan",
        "feta",
        "hirtenkäse",
        "schafskäse",
        "ziegenkäse",
        "camembert",
        "brie",
        "mascarpone",
        "ricotta",
        "frischkäse",
        "hüttenkäse",
        "körniger frischkäse",
        "halloumi",
        "grillkäse",
        "bergkäse",
        "tilsiter",
        "leerdammer",
        "maasdamer",
        "gorgonzola",
        "roquefort",
        "grana padano",
        "pecorino",
        "raclette",
        "reibekäse",
        "schmelzkäse",
        "butterkäse",
        "harzer",
        "limburger",
        "appenzeller",
        "manchego",
        "hartkäse",
        "weichkäse",
        "schnittkäse",
        "käsescheiben",
        "hobelkäse",
        "burrata",
        "cottage cheese",
        "provolone",
        "gruyère",
    ),
    EIER: ("=ei", "=eier", "hühnerei", "hühnereier", "freilandeier", "bio-eier", "eiklar", "eigelb", "wachteleier"),
    BUTTER: (
        "butter",
        "margarine",
        "süßrahmbutter",
        "sauerrahmbutter",
        "schmalz",
        "butterschmalz",
        "ghee",
        "kräuterbutter",
        "halbfettbutter",
        "streichfett",
        "pflanzenmargarine",
        "alsan",
    ),
    ERSATZ: (
        "jackfruit",
        "bratling",
        "pulled soja",
        "soja-granulat",
        "tofu",
        "tempeh",
        "seitan",
        "seitanfix",
        "sojaschnetzel",
        "sojagranulat",
        "veggie",
        "vegetarische",
        "fleischersatz",
        "lupine",
        "beyond",
        "veganes hack",
        "vegan hack",
        "falafel",
        "planted",
    ),
    FEINKOST: (
        "pinsateig",
        "quiche",
        "teigtaschen",
        "tarteteig",
        "taboulé",
        "vitello tonnato",
        "zaziki",
        "knöpfle",
        "eierknöpfle",
        "kässpatzen",
        "frische nudeln",
        "frische pasta",
        "tortellini",
        "ravioli",
        "gnocchi",
        "maultaschen",
        "spätzle",
        "schupfnudeln",
        "pizzateig",
        "blätterteig",
        "quicheteig",
        "flammkuchenteig",
        "hefeteig",
        "strudelteig",
        "yufka",
        "hummus",
        "guacamole",
        "tzatziki",
        "dip",
        "dips",
        "fleischsalat",
        "eiersalat",
        "kartoffelsalat",
        "nudelsalat",
        "krautsalat",
        "heringssalat",
        "thunfischsalat",
        "antipasti",
        "oliven",
        "aufstrich frisch",
        "feinkostsalat",
        "wraps frisch",
        "cappelletti",
    ),
    NUDELN: (
        "capellini",
        "fettuccelle",
        "lumaconi",
        "maccaroni",
        "spaghettoni",
        "pennoni",
        "pipe rigate",
        "eliche",
        "mezzelune",
        "nudeln",
        "nudel",
        "pasta",
        "spaghetti",
        "penne",
        "fusilli",
        "farfalle",
        "makkaroni",
        "maccheroni",
        "rigatoni",
        "tagliatelle",
        "linguine",
        "lasagne",
        "lasagneblätter",
        "lasagneplatten",
        "bandnudeln",
        "eiernudeln",
        "hörnchennudeln",
        "spirelli",
        "tortiglioni",
        "orecchiette",
        "conchiglie",
        "cannelloni",
        "suppennudeln",
        "buchstabennudeln",
        "vollkornnudeln",
        "glasnudeln",
        "reisnudeln",
        "mie-nudeln",
        "udon",
        "soba",
        "ramen",
        "gnocchetti",
        "orzo",
        "kritharaki",
        "fettuccine",
        "pappardelle",
    ),
    REIS: (
        "reis",
        "basmati",
        "jasmin",
        "jasminreis",
        "langkornreis",
        "vollkornreis",
        "risotto",
        "risottoreis",
        "parboiled",
        "wildreis",
        "couscous",
        "bulgur",
        "quinoa",
        "amaranth",
        "hirse",
        "grieß",
        "polenta",
        "graupen",
        "grünkern",
        "buchweizen",
        "dinkelreis",
        "express-reis",
        "kochbeutel",
        "getreide",
        "weizen",
        "dinkel",
        "roggen",
        "gerste",
        "hafer",
        "maisgrieß",
        "sushireis",
        "milchreis",
    ),
    HUELSEN: (
        "linsen",
        "rote linsen",
        "berglinsen",
        "belugalinsen",
        "kichererbsen",
        "kidneybohnen",
        "weiße bohnen",
        "schwarze bohnen",
        "limabohnen",
        "sojabohnen",
        "mungbohnen",
        "hülsenfrüchte",
        "erbsen getrocknet",
        "schälerbsen",
        "trockenerbsen",
        "bohnen getrocknet",
        "wachtelbohnen",
        "cannellini",
    ),
    NUESSE: (
        "leinsaat",
        "flohsamen",
        "flohsamenschalen",
        "nuss",
        "nüsse",
        "nusskerne",
        "haselnuss",
        "haselnüsse",
        "walnuss",
        "walnüsse",
        "mandel",
        "mandeln",
        "cashew",
        "cashewkerne",
        "erdnuss",
        "erdnüsse",
        "pistazie",
        "pistazien",
        "macadamia",
        "pekannuss",
        "paranuss",
        "pinienkerne",
        "sonnenblumenkerne",
        "kürbiskerne",
        "leinsamen",
        "chiasamen",
        "chia",
        "sesam",
        "hanfsamen",
        "mohn",
        "rosinen",
        "sultaninen",
        "korinthen",
        "trockenobst",
        "trockenfrüchte",
        "studentenfutter",
        "nussmischung",
        "kokosraspeln",
        "kokosflocken",
        "kokoschips",
        "saaten",
        "gebrannte mandeln",
        "dörrobst",
        "trockenpflaumen",
        "softaprikosen",
    ),
    MUESLI: (
        "müsli",
        "muesli",
        "granola",
        "knuspermüsli",
        "cornflakes",
        "flakes",
        "cerealien",
        "haferflocken",
        "flocken",
        "porridge",
        "haferbrei",
        "frühstückscerealien",
        "crunchy",
        "choco pops",
        "pops",
        "puffs",
        "gepufft",
        "haferfleks",
        "fleks",
        "müsliriegel",
        "kornflocken",
        "4-kornflocken",
    ),
    BACKEN: (
        "esspapier",
        "backdeko",
        "backmalz",
        "tonka",
        "süße nach wahl",
        "mehl",
        "weizenmehl",
        "dinkelmehl",
        "roggenmehl",
        "vollkornmehl",
        "zucker",
        "puderzucker",
        "rohrzucker",
        "brauner zucker",
        "vanillezucker",
        "vanillinzucker",
        "gelierzucker",
        "hagelzucker",
        "backpulver",
        "natron",
        "hefe",
        "trockenhefe",
        "frischhefe",
        "speisestärke",
        "stärke",
        "maisstärke",
        "kartoffelstärke",
        "gelatine",
        "agar-agar",
        "tortenguss",
        "backaroma",
        "aroma",
        "puddingpulver",
        "backmischung",
        "kuvertüre",
        "zuckerguss",
        "streusel",
        "zuckerstreusel",
        "schokotropfen",
        "backkakao",
        "marzipanrohmasse",
        "süßstoff",
        "süßungsmittel",
        "erythrit",
        "xylit",
        "stevia",
        "sirup backen",
        "vanilleschote",
        "bourbon-vanille",
        "paniermehl",
        "semmelbrösel",
        "backoblaten",
        "oblaten",
        "mandelmehl",
        "kokosmehl",
        "zuckerrübensirup",
        "ahornsirup",
        "agavendicksaft",
        "reissirup",
        "dattelsirup",
        "sahnesteif",
        "dessertpulver",
        "grießbreipulver",
    ),
    AUFSTRICH: (
        "maronencreme",
        "konfitüre",
        "marmelade",
        "gelee",
        "fruchtaufstrich",
        "honig",
        "nuss-nougat-creme",
        "nutella",
        "nougatcreme",
        "schokocreme",
        "erdnussbutter",
        "erdnusscreme",
        "mandelmus",
        "cashewmus",
        "nussmus",
        "sesammus",
        "tahin",
        "tahini",
        "brotaufstrich",
        "aufstrich",
        "apfelkraut",
        "rübenkraut",
        "zuckerrübensirup aufstrich",
        "lemon curd",
        "pflaumenmus",
        "apfelmus aufstrich",
    ),
    KONSERVE: (
        "peperoncini",
        "jalapeño",
        "ratatouille",
        "letscho",
        "schattenmorellen",
        "honey peppers",
        "weinblätter",
        "dolmadakia",
        "borschtsch",
        "konserve",
        "dosentomaten",
        "passata",
        "passierte tomaten",
        "tomatenmark",
        "stückige tomaten",
        "gehackte tomaten",
        "pizzatomaten",
        "sauerkraut",
        "rotkraut",
        "gewürzgurken",
        "gürkchen",
        "cornichons",
        "essiggurken",
        "apfelmus",
        "apfelmark",
        "kapern",
        "peperoni eingelegt",
        "jalapeños",
        "jalapenos",
        "pfirsiche dose",
        "mandarinen dose",
        "ananas dose",
        "obstkonserve",
        "fruchtcocktail",
        "kirschen im glas",
        "rote bete glas",
        "silberzwiebeln",
        "mixed pickles",
        "maiskörner",
        "gemüsemais",
        "erbsen und möhren",
        "kidneybohnen dose",
        "baked beans",
        "ravioli dose",
        "eintopf",
        "würstchen dose",
        "tomatensugo",
        "getrocknete tomaten",
        "cocktailtomaten glas",
    ),
    OEL: (
        "~öl",
        "olivenöl",
        "rapsöl",
        "sonnenblumenöl",
        "kokosöl",
        "sesamöl",
        "erdnussöl",
        "leinöl",
        "walnussöl",
        "kürbiskernöl",
        "bratöl",
        "frittierfett",
        "kokosfett",
        "palmin",
        "essig",
        "balsamico",
        "aceto",
        "apfelessig",
        "weinessig",
        "weißweinessig",
        "rotweinessig",
        "reisessig",
        "branntweinessig",
        "essigessenz",
        "zitronensaft",
        "limettensaft",
        "bratfett",
        "pflanzenfett",
    ),
    SAUCE: (
        "bolognese",
        "flüssigrauch",
        "liquid smoke",
        "bruschetta",
        "sauce",
        "soße",
        "ketchup",
        "senf",
        "mayonnaise",
        "mayo",
        "remoulade",
        "dressing",
        "pesto",
        "sojasauce",
        "sojasoße",
        "worcestersauce",
        "worcestershire",
        "tabasco",
        "sriracha",
        "chilisauce",
        "grillsauce",
        "bbq",
        "barbecue",
        "currysauce",
        "hollandaise",
        "sauce hollandaise",
        "bechamel",
        "tomatensauce",
        "pastasauce",
        "nudelsauce",
        "salatcreme",
        "salatsauce",
        "ajvar",
        "relish",
        "chutney",
        "sambal",
        "sambal oelek",
        "hoisin",
        "hoisinsauce",
        "teriyaki",
        "fischsauce",
        "austernsauce",
        "harissa",
        "aioli",
        "cocktailsauce",
        "knoblauchsauce",
        "senfsauce",
        "dip-sauce",
        "süß-sauer",
        "sweet chili",
        "würzsauce",
        "maggi",
        "würze",
    ),
    GEWUERZ: (
        "fleur de sel",
        "glutamat",
        "vegeta",
        "würzmischung",
        "geschmackspulver",
        "gewürz",
        "gewürze",
        "salz",
        "speisesalz",
        "meersalz",
        "jodsalz",
        "kräutersalz",
        "pfeffer",
        "paprikapulver",
        "edelsüß",
        "rosenscharf",
        "curry",
        "currypulver",
        "kurkuma",
        "kreuzkümmel",
        "kümmel",
        "cumin",
        "zimt",
        "zimtstangen",
        "muskat",
        "muskatnuss",
        "nelken",
        "gewürznelken",
        "piment",
        "lorbeer",
        "lorbeerblätter",
        "oregano",
        "majoran",
        "kardamom",
        "anis",
        "sternanis",
        "koriander",
        "fenchelsamen",
        "chiliflocken",
        "cayenne",
        "cayennepfeffer",
        "knoblauchpulver",
        "zwiebelpulver",
        "ingwerpulver",
        "vanille",
        "gemahlene vanille",
        "garam masala",
        "ras el hanout",
        "kräuter der provence",
        "italienische kräuter",
        "gewürzmischung",
        "grillgewürz",
        "rub",
        "senfkörner",
        "wacholder",
        "bockshornklee",
        "safran",
        "za'atar",
        "sumach",
        "gewürzsalz",
        "paprika edelsüß",
        "chilipulver",
        "kräutermischung",
        "tk-kräuter",
    ),
    FERTIG: (
        "bowl",
        "brühpulver",
        "markklößchen",
        "trinkmahlzeit",
        "instant-nudeln",
        "brühe",
        "gemüsebrühe",
        "hühnerbrühe",
        "rinderbrühe",
        "fond",
        "bouillon",
        "suppe",
        "fix",
        "fertiggericht",
        "instant",
        "5-minuten-terrine",
        "terrine",
        "kartoffelpüree",
        "püree",
        "kartoffelpüree-pulver",
        "knödel",
        "klöße",
        "kloßteig",
        "semmelknödel",
        "bratensaft",
        "bratensauce",
        "bratensoße",
        "soßenbinder",
        "saucenbinder",
        "mehlschwitze",
        "fertigsauce",
        "würzpaste",
        "gratin",
        "auflauf-fix",
        "fertigmischung",
        "kartoffelgratin",
        "kartoffelpuffer",
        "rösti",
        "reibekuchen",
        "suppeneinlage",
        "croutons",
        "eintopf",
        "chili con carne",
        "hühnerfrikassee",
        "frikassee",
        "ravioli in",
        "linseneintopf",
    ),
    INTERNATIONAL: (
        "gochujang",
        "tamari",
        "poppadums",
        "gyoza",
        "frühlingsrollen",
        "refried beans",
        "tempura",
        "adschika",
        "kokosmilch",
        "kokoscreme",
        "currypaste",
        "rote currypaste",
        "grüne currypaste",
        "tacos",
        "taco",
        "taco shells",
        "burrito",
        "enchilada",
        "salsa",
        "reispapier",
        "frühlingsrollenteig",
        "wasabi",
        "nori",
        "miso",
        "mirin",
        "sushi-ingwer",
        "kimchi",
        "tortilla chips",
        "fajita",
        "wan tan",
        "wonton",
        "tahinsauce",
        "tahini sauce",
        "falafelmischung",
        "couscous-mix",
    ),
    SUESS: (
        "chocolate",
        "shortbread",
        "madeleines",
        "linzer",
        "lutscher",
        "gummidrops",
        "süßigkeit",
        "überraschungsei",
        "überraschungs-ei",
        "schokolade",
        "schoko",
        "vollmilchschokolade",
        "zartbitter",
        "zartbitterschokolade",
        "praline",
        "pralinen",
        "fruchtgummi",
        "gummibärchen",
        "weingummi",
        "lakritz",
        "bonbon",
        "bonbons",
        "kaugummi",
        "marzipan",
        "nougat",
        "riegel",
        "schokoriegel",
        "keks",
        "kekse",
        "cookies",
        "cookie",
        "butterkeks",
        "gebäck",
        "buttergebäck",
        "dauergebäck",
        "waffel",
        "waffeln",
        "lebkuchen",
        "printen",
        "spekulatius",
        "dominosteine",
        "elisenlebkuchen",
        "zuckerwaffeln",
        "löffelbiskuit",
        "biskuit",
        "cracker süß",
        "schaumküsse",
        "marshmallow",
        "marshmallows",
        "kandis",
        "zuckerwatte",
        "dragee",
        "dragees",
        "weihnachtsmann",
        "osterhase",
        "schokoladenfigur",
        "schokoladeneier",
        "karamell",
        "toffee",
        "fudge",
        "brownie",
        "brownies",
        "makronen",
        "amarettini",
        "cantuccini",
        "baiser",
        "kokosmakronen",
        "nussecken",
        "müsliriegel süß",
        "proteinriegel",
        "nussriegel",
    ),
    KNABBER: (
        "chips",
        "kartoffelchips",
        "tortilla-chips",
        "nachos",
        "flips",
        "erdnussflips",
        "salzstangen",
        "brezeln",
        "salzbrezeln",
        "cracker",
        "crackers",
        "popcorn",
        "snack",
        "snacks",
        "knabber",
        "knabbergebäck",
        "erdnüsse geröstet",
        "erdnüsse gesalzen",
        "reiswaffeln",
        "maiswaffeln",
        "puffs",
        "stapelchips",
        "gemüsechips",
    ),
    KAFFEE: (
        "kaffee",
        "espresso",
        "cappuccino",
        "latte macchiato",
        "kaffeepads",
        "kaffeekapseln",
        "kaffeebohnen",
        "instantkaffee",
        "löslicher kaffee",
        "tee",
        "früchtetee",
        "kräutertee",
        "grüntee",
        "grüner tee",
        "schwarztee",
        "schwarzer tee",
        "pfefferminztee",
        "kamillentee",
        "rooibos",
        "chai",
        "matcha",
        "kakao",
        "kakaopulver",
        "trinkschokolade",
        "kaba",
        "nesquik",
        "teebeutel",
        "zitronenteepulver",
        "teepulver",
    ),
    SAFT: (
        "saft",
        "orangensaft",
        "apfelsaft",
        "multivitaminsaft",
        "traubensaft",
        "tomatensaft",
        "karottensaft",
        "gemüsesaft",
        "direktsaft",
        "nektar",
        "smoothie",
        "smoothies",
        "fruchtsaft",
        "apfelschorle",
        "saftschorle",
        "schorle",
        "mehrfruchtsaft",
        "kirschsaft",
        "ananassaft",
        "grapefruitsaft",
        "maracujasaft",
        "mangosaft",
    ),
    WASSER: (
        "wasser",
        "mineralwasser",
        "tafelwasser",
        "sprudel",
        "limonade",
        "fanta",
        "sprite",
        "brause",
        "eistee",
        "sirup",
        "=cola",
        "=limo",
        "holunderblütensirup",
        "holunderblütesirup",
        "fruchtsirup",
        "energydrink",
        "energy drink",
        "isotonisch",
        "bitter lemon",
        "tonic",
        "ginger ale",
        "spezi",
        "=mate",
        "kokoswasser",
        "sportgetränk",
        "erfrischungsgetränk",
        "getränkepulver",
    ),
    ALKOHOL: (
        "bier",
        "pils",
        "weizenbier",
        "radler",
        "rotwein",
        "weißwein",
        "rosé",
        "sekt",
        "prosecco",
        "champagner",
        "likör",
        "wodka",
        "vodka",
        "whisky",
        "whiskey",
        "schnaps",
        "amaretto",
        "cognac",
        "brandy",
        "grappa",
        "glühwein",
        "cidre",
        "portwein",
        "sherry",
        "marsala",
        "kochwein",
        "spirituose",
        "metaxa",
        "ouzo",
        "=wein",
        "=rum",
        "=gin",
        "=korn",
    ),
    TK_EIS: (
        "eis",
        "speiseeis",
        "eiscreme",
        "vanilleeis",
        "schokoeis",
        "sorbet",
        "eis am stiel",
        "wassereis",
        "frozen yogurt",
        "eistorte",
        "eiskonfekt",
    ),
    SONSTIGES: ("nahrungsergänzung", "proteinpulver", "whey", "hanfprotein", "designer whey"),
    TK_FERTIG: ("pinsa", "pizza", "flammkuchen", "baguette tk", "pommes", "kroketten", "wedges", "lasagne tk"),
}

# Keywords whose "win" must not be decided by the compound head rule because
# they are qualifiers rather than product types.
_QUALIFIER_TOKENS: frozenset[str] = frozenset(
    {
        "bio",
        "vegan",
        "vegane",
        "veganer",
        "veganes",
        "vegetarisch",
        "light",
        "leicht",
        "natur",
        "classic",
        "klassisch",
        "extra",
        "fein",
        "feine",
        "feines",
        "grob",
        "zart",
        "frisch",
        "frische",
        "mini",
        "maxi",
        "groß",
        "klein",
        "mittelgroß",
        "original",
        "premium",
        "gold",
        "family",
        "xxl",
        "protein",
        "high",
        "zuckerfrei",
        "laktosefrei",
        "glutenfrei",
        "weniger",
        "süß",
        "herzhaft",
        "pikant",
        "mild",
        "scharf",
        "weiß",
        "weiße",
        "weißer",
        "weißes",
        "rot",
        "rote",
        "roter",
        "grün",
        "grüne",
        "gelb",
        "schwarz",
        "schwarze",
        "vollkorn",
        "mittel",
        "dunkle",
        "helle",
        "hell",
        "dunkel",
        "gehackt",
        "gehackte",
        "gerieben",
        "geriebener",
        "geröstet",
        "geröstete",
        "gesalzen",
        "genuss",
        "hausgemacht",
    }
)

# Generic cuts that describe *how* something is cut, not *what* it is. When a
# token's head is a cut ("Thunfischfilet"), a fish/meat keyword earlier in
# the same token decides the section.
_CUT_KEYWORDS: frozenset[str] = frozenset(
    {"filet", "steak", "braten", "medaillons", "rücken", "keule", "schnitzel", "burger", "patty", "stäbchen"}
)

_TK_PATTERN = re.compile(r"(\btk\b|\(tk\)|tiefkühl|tiefgekühlt|tiefgefroren|gefroren|\bfrozen\b)")
_CAN_PATTERN = re.compile(
    r"(\(dose\)|\bdose\b|\bin der dose\b|konserve|\(glas\)|\bim glas\b|eingelegt|eingemacht|\bim eigenen saft\b)"
)
_DRIED_PATTERN = re.compile(r"(getrocknet|gedörrt|gedoerrt|\bsoft\b|\bdried\b)")
_GROUND_PATTERN = re.compile(r"(gemahlen|pulver|gerebelt|\bgetrocknet\b|flocken)")
_VEGAN_PATTERN = re.compile(r"(vegan|veggie|vegetarisch|pflanzlich|fleischlos|plant-based)")

_FRESH_PRODUCE = {OBST, GEMUESE, SALATE}
_MEAT = {FLEISCH, WURST}


@dataclass(frozen=True)
class RetailClassification:
    """Result of a deterministic classification."""

    section: str
    confidence: float
    rule: str


def _normalize(text: str) -> str:
    return re.sub(r"\s+", " ", text.lower().replace("ß", "ss")).strip()


@lru_cache(maxsize=1)
def _normalized_qualifiers() -> frozenset[str]:
    return frozenset(_normalize(word) for word in _QUALIFIER_TOKENS)


@lru_cache(maxsize=1)
def _keyword_index() -> tuple[tuple[str, str, str], ...]:
    """Return (normalized keyword, section, mode) sorted longest first.

    Mode is "=" (whole token only), "~" (token suffix only) or "" (substring).
    """
    entries: dict[str, tuple[str, str]] = {}
    for section, keywords in _KEYWORDS.items():
        for raw in keywords:
            whole = raw[0] if raw[0] in "=~" else ""
            keyword = _normalize(raw.lstrip("=~"))
            # First definition wins so the dict order above stays authoritative
            # for accidental duplicates across sections.
            entries.setdefault(keyword, (section, whole))
    return tuple(sorted(((k, s, w) for k, (s, w) in entries.items()), key=lambda item: len(item[0]), reverse=True))


def _match_phrase(text: str) -> tuple[str, str] | None:
    """Match multi-word keywords against the whole normalized name."""
    for keyword, section, _whole in _keyword_index():
        if " " in keyword and re.search(rf"(?<![\w-]){re.escape(keyword)}(?![\w])", text):
            return keyword, section
    return None


def _match_token(token: str) -> tuple[str, str] | None:
    """Return the compound-head keyword match inside a single token."""
    best: tuple[int, int, str, str] | None = None
    for keyword, section, whole in _keyword_index():
        if " " in keyword:
            continue
        if whole == "=":
            if token != keyword:
                continue
            end = len(token)
        elif whole == "~":
            if not token.endswith(keyword):
                continue
            end = len(token)
        else:
            end_index = token.rfind(keyword)
            if end_index < 0:
                continue
            end = end_index + len(keyword)
        candidate = (end, len(keyword), keyword, section)
        if best is None or candidate[:2] > best[:2]:
            best = candidate
    if best is None:
        return None
    if best[2] in _CUT_KEYWORDS:
        for keyword, section, whole in _keyword_index():
            if whole == "=" or " " in keyword or keyword == best[2] or keyword not in token:
                continue
            if section in (FISCH, ERSATZ):
                return keyword, section
    return best[2], best[3]


def _tokens(text: str) -> list[str]:
    return [token for token in re.split(r"[\s(),/+&:;]+", text) if token and not token.isdigit()]


def _base_section(text: str) -> tuple[str, float, str] | None:
    phrase = _match_phrase(text)
    tokens = _tokens(text)
    for index, token in enumerate(tokens):
        if token in _normalized_qualifiers():
            continue
        match = _match_token(token)
        if match is None:
            continue
        keyword, section = match
        # A multi-word phrase that starts at or before this token is more
        # specific ("saure sahne", "weiße bohnen") and wins.
        if phrase is not None and text.find(phrase[0]) <= text.find(token):
            return phrase[1], 0.9, f"phrase:{phrase[0]}"
        confidence = 0.9 if index == 0 else 0.75
        return section, confidence, f"head:{keyword}"
    if phrase is not None:
        return phrase[1], 0.8, f"phrase:{phrase[0]}"
    return None


def _apply_markers(text: str, base: str | None) -> tuple[str | None, str | None]:
    """Apply process markers. Returns (section, marker_rule)."""
    is_ready_meal = "fertiggericht" in text or "fertigpackung" in text
    if _TK_PATTERN.search(text):
        if base in _FRESH_PRODUCE:
            return TK_OBST_GEMUESE, "marker:tk-produce"
        if base in _MEAT or base == FISCH:
            return TK_FLEISCH_FISCH, "marker:tk-meat-fish"
        if base in (TK_EIS, JOGHURT, SUESS) or (base == BROT and "kuchen" in text):
            return TK_EIS, "marker:tk-dessert"
        if base == TK_FERTIG and "pommes" in text:
            return TK_OBST_GEMUESE, "marker:tk-fries"
        return TK_FERTIG, "marker:tk"
    if is_ready_meal:
        return FERTIG, "marker:ready-meal"
    if base == TK_FERTIG and ("pommes" in text or "kroketten" in text or "wedges" in text):
        return TK_OBST_GEMUESE, "marker:fries"
    if _CAN_PATTERN.search(text) and base in (_FRESH_PRODUCE | _MEAT | {FISCH, HUELSEN}):
        return KONSERVE, "marker:can"
    if _DRIED_PATTERN.search(text):
        if base == OBST:
            return NUESSE, "marker:dried-fruit"
        if base == SALATE:
            return GEWUERZ, "marker:dried-herb"
        if base == GEMUESE:
            return KONSERVE, "marker:dried-vegetable"
    if _GROUND_PATTERN.search(text) and base in (SALATE, GEMUESE) and "flocken" not in text:
        return GEWUERZ, "marker:ground"
    if base in (_MEAT | {FISCH}) and _VEGAN_PATTERN.search(text):
        return ERSATZ, "marker:vegan-meat"
    return None, None


def classify_retail_section(name: str) -> RetailClassification | None:
    """Classify an ingredient name into a catalog section, or ``None`` if unsure."""
    if not name or not name.strip():
        return None
    text = _normalize(name)
    base = _base_section(text)
    base_section = base[0] if base else None
    marked, marker_rule = _apply_markers(text, base_section)
    if marked is not None:
        confidence = base[1] if base else 0.7
        rule = f"{base[2]}+{marker_rule}" if base else marker_rule or "marker"
        return RetailClassification(section=marked, confidence=confidence, rule=rule)
    if base is None:
        return None
    return RetailClassification(section=base[0], confidence=base[1], rule=base[2])
