# Generated by Django 5.2.12 on 2026-04-06 18:46

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="scout_levels",
            field=models.ManyToManyField(blank=True, related_name="%(class)s_set", to="content.scoutlevel"),
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(class)s_set", to="content.tag"),
        ),
        migrations.AddField(
            model_name="blog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=django.contrib.postgres.indexes.GinIndex(fields=["search_vector"], name="blog_search_idx"),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["status", "created_at"], name="blog_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["like_score"], name="blog_like_score_idx"),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["view_count"], name="blog_view_count_idx"),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["blog_type"], name="blog_type_idx"),
        ),
    ]
