# Generated by Django 5.2.12 on 2026-06-07 19:40

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="embedding",
        ),
        migrations.AddField(
            model_name="blog",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
