# Generated by Django 5.2.12 on 2026-06-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("draft", "Entwurf"), ("verified", "Verifiziert")], default="draft", max_length=20
            ),
        ),
    ]
