# Generated by Django 5.2.12 on 2026-06-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_blog_is_deleted_alter_blog_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="is_deleted",
        ),
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("submitted", "Eingereicht"),
                    ("approved", "Genehmigt"),
                    ("rejected", "Abgelehnt"),
                    ("archived", "Archiviert"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
