# Generated by Django 5.2.12 on 2026-06-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_blog_is_deleted_alter_blog_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="costs_rating",
        ),
    ]
