# Generated by Django 5.2.12 on 2026-04-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("field_game", "Geländespiel"),
                    ("group_game", "Gruppenspiel"),
                    ("icebreaker", "Kennenlernspiel"),
                    ("cooperation", "Kooperationsspiel"),
                    ("night_game", "Nachtspiel"),
                    ("board_game", "Brettspiel"),
                    ("running_game", "Laufspiel"),
                    ("skill_game", "Geschicklichkeitsspiel"),
                ],
                default="group_game",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="play_area",
            field=models.CharField(
                choices=[
                    ("indoor", "Drinnen"),
                    ("outdoor", "Draußen"),
                    ("field", "Wiese / Feld"),
                    ("forest", "Wald"),
                    ("gym", "Turnhalle"),
                    ("any", "Überall"),
                ],
                default="any",
                max_length=20,
            ),
        ),
    ]
