# Generated by Django 5.2.12 on 2026-06-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_game_is_deleted_alter_game_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="min_players",
            new_name="min_participants",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="max_players",
            new_name="max_participants",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="play_area",
            new_name="location_type",
        ),
    ]
