# Generated by Django 5.2.12 on 2026-06-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_rename_game_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="max_participants",
            field=models.PositiveIntegerField(blank=True, help_text="Maximum number of participants.", null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="min_participants",
            field=models.PositiveIntegerField(blank=True, help_text="Minimum number of participants.", null=True),
        ),
    ]
