# Generated by Django 5.2.12 on 2026-06-21 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0007_remove_game_is_deleted_remove_game_location_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="costs_rating",
        ),
    ]
