export const AiContextChoices: Record<string, string> = {
  content_improve_text: 'Text verbessern',
  content_suggest_tags: 'Tags vorschlagen',
  content_refurbish: 'Inhalt aufbereiten',
  content_generate_image: 'Bild generieren',
  content_suggest_supplies: 'Materialien vorschlagen',
  ingredient_ai_create: 'Zutat erstellen',
  ingredient_ai_suggest_all: 'Zutatenfelder vorschlagen',
  ingredient_import_url: 'Zutat aus URL importieren',
  recipe_ai_create: 'Rezept erstellen',
  recipe_ai_suggest_all: 'Rezeptmetadaten vorschlagen',
  recipe_ai_suggest_ingredients: 'Rezeptzutaten vorschlagen',
  packing_list_ai_suggest: 'Packlistenvorschläge',
  event_generate_invitation: 'Einladung generieren',
  documents_generate_text: 'Dokumententext generieren',
  improve_text: 'Text verbessern',
  suggest_tags: 'Tags vorschlagen',
  refurbish: 'Inhalt aufbereiten',
  image_generation: 'Bild generieren',
  suggest_materials: 'Materialien vorschlagen',
  suggest_recipe_supplies: 'Rezeptmaterialien vorschlagen',
  recipe_step_generation: 'Schrittgenerierung',
  ingredient_assignment_suggestion: 'Zutatenzuordnung',
  recipe_markdown_conversion: 'Markdown-Konvertierung',
  recipe_step_improve: 'Schritt verbessern',
  ai_ingredients: 'KI-Zutaten',
  ai_quantity_estimation: 'Mengenschätzung',
  packing_list_suggestions: 'Packlistenvorschläge',
  generate_invitation: 'Einladung generieren',
  meal_plan_generation: 'Essensplan generieren',
  intelligent_suggestions_rerank: 'Vorschlags-Reranking',
  url_import_matching: 'URL-Import Matching',
  url_import_metadata: 'URL-Import Metadaten',
  ingredient_enrichment: 'Zutatenanreicherung',
  ingredient_parser: 'Zutaten-Parsing',
  classify_ingredients: 'Zutatenklassifikation',
  recipe_suggestions: 'Rezeptvorschläge',
};
