/**
 * Zustand store for the 8-step event creation wizard.
 * Manages step data, navigation, and validation state.
 * Server state (API calls) lives in TanStack Query hooks — this store is UI-only.
 */
import { create } from 'zustand';
import { differenceInCalendarDays, parseISO } from 'date-fns';
import type { WizardData, WizardStep1, WizardStep2, WizardStep3, WizardStep4, WizardStep5, WizardStep6, WizardStep7, WizardBookingOption } from '@/schemas/eventWizard';

const DAILY_RATE = 15;

function calculateDefaultBookingOption(startDate: string, endDate: string): WizardBookingOption {
  const days = differenceInCalendarDays(parseISO(endDate), parseISO(startDate)) + 1;
  const totalPrice = Math.max(days, 1) * DAILY_RATE;
  return {
    name: 'Teilnahme',
    description: 'Standardbeitrag pro Tag',
    price: totalPrice.toFixed(2),
    max_participants: 0,
    bookable_from: null,
    bookable_till: null,
    _isAutoGenerated: true,
  };
}

export const WIZARD_STEPS = [
  { label: 'Grunddaten', icon: 'edit_note' },
  { label: 'Gruppe', icon: 'group' },
  { label: 'Datum & Ort', icon: 'location_on' },
  { label: 'Anmeldung', icon: 'how_to_reg' },
  { label: 'Buchung', icon: 'payments' },
  { label: 'Packliste', icon: 'checklist' },
  { label: 'Einladung', icon: 'mail' },
  { label: 'Zusammenfassung', icon: 'visibility' },
] as const;

export const TOTAL_STEPS = WIZARD_STEPS.length;

interface EventWizardState {
  // Current step (0-indexed)
  currentStep: number;

  // Step data
  data: WizardData;

  // Validation tracking
  stepValidity: boolean[];

  // Template source (if created from template)
  templateId: number | null;

  // Actions
  setStep: (step: number) => void;
  nextStep: () => void;
  prevStep: () => void;
  updateStep1: (data: Partial<WizardStep1>) => void;
  updateStep2: (data: Partial<WizardStep2>) => void;
  updateStep3: (data: Partial<WizardStep3>) => void;
  updateStep4: (data: Partial<WizardStep4>) => void;
  updateStep5: (data: Partial<WizardStep5>) => void;
  updateStep6: (data: Partial<WizardStep6>) => void;
  updateStep7: (data: Partial<WizardStep7>) => void;
  setStepValid: (step: number, valid: boolean) => void;
  loadFromTemplate: (templateData: Partial<WizardData>, templateId: number) => void;
  reset: () => void;
  getCreatePayload: () => Record<string, unknown>;
}

const defaultData: WizardData = {
  // Step 1
  name: '',
  slug: undefined,
  color: 'blue',
  icon: 'tent',
  description: '',
  is_template: false,
  // Step 2
  invited_group_ids: [],
  invited_user_ids: [],
  // Step 3
  start_date: null,
  end_date: null,
  event_location_id: null,
  meeting_point_id: null,
  pickup_point_id: null,
  location: '',
  // Step 4
  registration_start: null,
  registration_deadline: null,
  is_public: false,
  guest_registration_enabled: false,
  // Step 5
  booking_options: [],
  // Step 6
  packing_list_id: null,
  // Step 7
  invitation_text: '',
  // Extra fields
  manual_phase: null,
  meal_plan_id: null,
};

export const useEventWizardStore = create<EventWizardState>((set, get) => ({
  currentStep: 0,
  data: { ...defaultData },
  stepValidity: new Array(TOTAL_STEPS).fill(false),
  templateId: null,

  setStep: (step) => {
    if (step >= 0 && step < TOTAL_STEPS) {
      set({ currentStep: step });
    }
  },

  nextStep: () => {
    const { currentStep } = get();
    if (currentStep < TOTAL_STEPS - 1) {
      set({ currentStep: currentStep + 1 });
    }
  },

  prevStep: () => {
    const { currentStep } = get();
    if (currentStep > 0) {
      set({ currentStep: currentStep - 1 });
    }
  },

  updateStep1: (partial) =>
    set((state) => ({
      data: { ...state.data, ...partial },
    })),

  updateStep2: (partial) =>
    set((state) => ({
      data: { ...state.data, ...partial },
    })),

  updateStep3: (partial) =>
    set((state) => {
      const newData = { ...state.data, ...partial };
      const startDate = newData.start_date;
      const endDate = newData.end_date;

      if (startDate && endDate) {
        const hasManualOptions = (newData.booking_options || []).some(
          (o) => !o._isAutoGenerated,
        );
        if (!hasManualOptions) {
          newData.booking_options = [calculateDefaultBookingOption(startDate, endDate)];
        }
      }

      return { data: newData };
    }),

  updateStep4: (partial) =>
    set((state) => ({
      data: { ...state.data, ...partial },
    })),

  updateStep5: (partial) =>
    set((state) => ({
      data: { ...state.data, ...partial },
    })),

  updateStep6: (partial) =>
    set((state) => ({
      data: { ...state.data, ...partial },
    })),

  updateStep7: (partial) =>
    set((state) => ({
      data: { ...state.data, ...partial },
    })),

  setStepValid: (step, valid) =>
    set((state) => {
      const stepValidity = [...state.stepValidity];
      stepValidity[step] = valid;
      return { stepValidity };
    }),

  loadFromTemplate: (templateData, templateId) =>
    set({
      data: { ...defaultData, ...templateData, name: '', slug: undefined, is_template: false },
      templateId,
      currentStep: 0,
      stepValidity: new Array(TOTAL_STEPS).fill(false),
    }),

  reset: () =>
    set({
      data: { ...defaultData },
      currentStep: 0,
      stepValidity: new Array(TOTAL_STEPS).fill(false),
      templateId: null,
    }),

  getCreatePayload: () => {
    const { data } = get();
    const payload: Record<string, unknown> = {
      name: data.name.trim(),
      description: data.description || '',
      color: data.color,
      icon: data.icon,
      is_template: data.is_template,
      is_public: data.is_public,
      guest_registration_enabled: data.guest_registration_enabled,
      invitation_text: data.invitation_text || '',
      location: data.location || '',
    };

    if (data.slug) payload.slug = data.slug;
    if (data.manual_phase) payload.manual_phase = data.manual_phase;
    if (data.invited_group_ids?.length) payload.invited_group_ids = data.invited_group_ids;
    if (data.invited_user_ids?.length) payload.invited_user_ids = data.invited_user_ids;
    if (data.start_date) payload.start_date = data.start_date;
    if (data.end_date) payload.end_date = data.end_date;
    if (data.registration_start) payload.registration_start = data.registration_start;
    if (data.registration_deadline) payload.registration_deadline = data.registration_deadline;
    if (data.event_location_id) payload.event_location_id = data.event_location_id;
    if (data.meeting_point_id) payload.meeting_point_id = data.meeting_point_id;
    if (data.pickup_point_id) payload.pickup_point_id = data.pickup_point_id;
    if (data.packing_list_id) payload.packing_list_id = data.packing_list_id;
    if (data.meal_plan_id) payload.meal_plan_id = data.meal_plan_id;
    if (data.booking_options?.length) {
      payload.booking_options = data.booking_options.map((o) => ({
        name: o.name,
        description: o.description || '',
        price: o.price || '0.00',
        max_participants: o.max_participants || 0,
        bookable_from: o.bookable_from || null,
        bookable_till: o.bookable_till || null,
        // _isAutoGenerated is intentionally excluded from payload
      }));
    }

    return payload;
  },
}));
