# Generated by Django 5.2.12 on 2026-04-06 18:46

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                ("summary", models.TextField(blank=True, default="")),
                ("summary_long", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "costs_rating",
                    models.CharField(
                        choices=[("free", "0 €"), ("less_1", "< 1 €"), ("1_2", "1 – 2 €"), ("more_2", "> 2 €")],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "execution_time",
                    models.CharField(
                        choices=[
                            ("less_30", "< 30 Minuten"),
                            ("30_60", "30 – 60 Minuten"),
                            ("60_90", "60 – 90 Minuten"),
                            ("more_90", "> 90 Minuten"),
                        ],
                        default="less_30",
                        max_length=20,
                    ),
                ),
                (
                    "preparation_time",
                    models.CharField(
                        choices=[
                            ("none", "Keine Vorbereitung"),
                            ("less_15", "< 15 Minuten"),
                            ("15_30", "15 – 30 Minuten"),
                            ("30_60", "30 – 60 Minuten"),
                            ("more_60", "> 60 Minuten"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "Einfach"), ("medium", "Mittel"), ("hard", "Schwer")],
                        default="easy",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("submitted", "Eingereicht"),
                            ("approved", "Genehmigt"),
                            ("rejected", "Abgelehnt"),
                            ("archived", "Archiviert"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="content/")),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ("embedding", models.BinaryField(blank=True, null=True)),
                ("embedding_updated_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
                ("like_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("scout_skills", "Pfadfindertechnik"),
                            ("navigation", "Navigation & Orientierung"),
                            ("nature_study", "Naturkunde"),
                            ("crafts", "Basteln & Werken"),
                            ("active_games", "Bewegungsspiele"),
                            ("outdoor_cooking", "Kochen & Backen"),
                            ("first_aid", "Erste Hilfe"),
                            ("community", "Gemeinschaft & Soziales"),
                            ("campfire_culture", "Lagerfeuer & Singerunde"),
                            ("exploration", "Erkundung & Abenteuer"),
                        ],
                        default="scout_skills",
                        max_length=20,
                    ),
                ),
                (
                    "min_participants",
                    models.PositiveIntegerField(blank=True, help_text="Minimum number of participants.", null=True),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(blank=True, help_text="Maximum number of participants.", null=True),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[("indoor", "Drinnen"), ("outdoor", "Draußen"), ("both", "Drinnen & Draußen")],
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True, related_name="authored_%(class)s_set", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scout_levels",
                    models.ManyToManyField(blank=True, related_name="%(class)s_set", to="content.scoutlevel"),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="%(class)s_set", to="content.tag")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gruppenstunde",
                "verbose_name_plural": "Gruppenstunden",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(fields=["search_vector"], name="session_search_idx"),
                    models.Index(fields=["status", "created_at"], name="session_status_created_idx"),
                    models.Index(fields=["like_score"], name="session_like_score_idx"),
                    models.Index(fields=["view_count"], name="session_view_count_idx"),
                ],
            },
        ),
    ]
