# Generated by Django 5.2.12 on 2026-07-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsession',
            name='costs_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per participant in Euros', max_digits=8, null=True),
        ),
    ]
