# Generated by Django 5.2.12 on 2026-06-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0004_remove_groupsession_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupsession",
            name="costs_rating",
        ),
    ]
