/**
 * Zod schemas for the event creation wizard steps.
 * Each step has its own validation schema.
 */
import { z } from 'zod';

// --- Step 1: Grunddaten ---

export const WizardStep1Schema = z.object({
  name: z.string().min(1, 'Name ist erforderlich'),
  slug: z.string().optional(),
  color: z.string().default('blue'),
  icon: z.string().default('tent'),
  description: z.string().optional().default(''),
  is_template: z.boolean().optional().default(false),
});
export type WizardStep1 = z.infer<typeof WizardStep1Schema>;

// --- Step 2: Gruppe & Einladung ---

export const WizardStep2Schema = z.object({
  invited_group_ids: z.array(z.number()).optional().default([]),
  invited_user_ids: z.array(z.number()).optional().default([]),
});
export type WizardStep2 = z.infer<typeof WizardStep2Schema>;

// --- Step 3: Datum & Ort ---

export const WizardStep3Schema = z.object({
  start_date: z.string().nullable().optional(),
  end_date: z.string().nullable().optional(),
  event_location_id: z.number().nullable().optional(),
  meeting_point_id: z.number().nullable().optional(),
  pickup_point_id: z.number().nullable().optional(),
  location: z.string().optional().default(''),
});
export type WizardStep3 = z.infer<typeof WizardStep3Schema>;

// --- Step 4: Anmeldung ---

export const WizardStep4Schema = z.object({
  registration_start: z.string().nullable().optional(),
  registration_deadline: z.string().nullable().optional(),
  is_public: z.boolean().optional().default(false),
  guest_registration_enabled: z.boolean().optional().default(false),
});
export type WizardStep4 = z.infer<typeof WizardStep4Schema>;

// --- Step 5: Buchungsoptionen ---

export const WizardBookingOptionSchema = z.object({
  name: z.string().min(1, 'Name ist erforderlich'),
  description: z.string().optional().default(''),
  price: z.string().optional().default('0.00'),
  max_participants: z.number().optional().default(0),
  bookable_from: z.string().nullable().optional(),
  bookable_till: z.string().nullable().optional(),
  _isAutoGenerated: z.boolean().optional(),
});
export type WizardBookingOption = z.infer<typeof WizardBookingOptionSchema>;

export const WizardStep5Schema = z.object({
  booking_options: z.array(WizardBookingOptionSchema).optional().default([]),
});
export type WizardStep5 = z.infer<typeof WizardStep5Schema>;

// --- Step 6: Packliste & Felder ---

export const WizardStep6Schema = z.object({
  packing_list_id: z.number().nullable().optional(),
  // Custom fields and labels are managed separately
});
export type WizardStep6 = z.infer<typeof WizardStep6Schema>;

// --- Step 7: Einladungstext ---

export const WizardStep7Schema = z.object({
  invitation_text: z.string().optional().default(''),
});
export type WizardStep7 = z.infer<typeof WizardStep7Schema>;

// --- Step 8: Zusammenfassung ---
// No separate schema needed — combines all previous steps

// --- Combined wizard data ---

export const WizardDataSchema = WizardStep1Schema
  .merge(WizardStep2Schema)
  .merge(WizardStep3Schema)
  .merge(WizardStep4Schema)
  .merge(WizardStep5Schema)
  .merge(WizardStep6Schema)
  .merge(WizardStep7Schema)
  .extend({
    // Extra fields not tied to a specific step
    manual_phase: z.string().nullable().optional(),
    meal_plan_id: z.number().nullable().optional(),
  });
export type WizardData = z.infer<typeof WizardDataSchema>;
