# Generated by Django 5.2.12 on 2026-04-03 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0005_remove_userprofile_eat_habits_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sortierung")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorien",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PackingItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("quantity", models.CharField(blank=True, default="", max_length=50, verbose_name="Menge")),
                ("description", models.CharField(blank=True, default="", max_length=500, verbose_name="Beschreibung")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sortierung")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="packinglist.packingcategory",
                        verbose_name="Kategorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Packlisten-Gegenstand",
                "verbose_name_plural": "Packlisten-Gegenstände",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PackingList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packing_lists",
                        to="profiles.usergroup",
                        verbose_name="Gruppe",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packing_lists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ersteller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Packliste",
                "verbose_name_plural": "Packlisten",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="packingcategory",
            name="packing_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="packinglist.packinglist",
                verbose_name="Packliste",
            ),
        ),
    ]
