# Generated by Django 5.2.12 on 2026-04-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sortierung")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorien",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PackingList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                (
                    "is_template",
                    models.BooleanField(
                        default=False,
                        help_text="Vorlagen können von allen Benutzern geklont werden.",
                        verbose_name="Vorlage",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Packliste",
                "verbose_name_plural": "Packlisten",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PackingItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("quantity", models.CharField(blank=True, default="", max_length=50, verbose_name="Menge")),
                ("description", models.CharField(blank=True, default="", max_length=500, verbose_name="Beschreibung")),
                ("is_checked", models.BooleanField(default=False, verbose_name="Gepackt")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sortierung")),
                ("supply_object_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="Ausrüstungs-ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="packinglist.packingcategory",
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "supply_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packing_items",
                        to="contenttypes.contenttype",
                        verbose_name="Ausrüstungstyp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Packlisten-Gegenstand",
                "verbose_name_plural": "Packlisten-Gegenstände",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
