# Generated by Django 5.2.12 on 2026-07-13 20:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('is_template', models.BooleanField(default=False, help_text='Vorlagen können von allen Benutzern geklont werden.', verbose_name='Vorlage')),
                ('visibility', models.CharField(choices=[('private', 'Privat'), ('link_only', 'Per Link zugänglich')], default='link_only', max_length=20, verbose_name='Sichtbarkeit')),
                ('activity_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Aktivitätstyp')),
                ('duration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dauer')),
                ('season', models.CharField(blank=True, max_length=20, null=True, verbose_name='Jahreszeit')),
                ('age_group', models.CharField(blank=True, max_length=20, null=True, verbose_name='Altersstufe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Packliste',
                'verbose_name_plural': 'Packlisten',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingListShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('label', models.CharField(blank=True, default='', help_text="z.B. 'Für Max' oder 'Trupplink'", max_length=100, verbose_name='Bezeichnung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Packlisten-Freigabe',
                'verbose_name_plural': 'Packlisten-Freigaben',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingListShareCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Gepackt')),
            ],
            options={
                'verbose_name': 'Freigabe-Check',
                'verbose_name_plural': 'Freigabe-Checks',
            },
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('quantity', models.CharField(blank=True, default='', max_length=50, verbose_name='Menge')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Beschreibung')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Gepackt')),
                ('is_do_not_bring', models.BooleanField(default=False, help_text='Markiert Gegenstände, die nicht mitgebracht werden sollen.', verbose_name='Nicht mitbringen')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sortierung')),
                ('supply_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ausrüstungs-ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packinglist.packingcategory', verbose_name='Kategorie')),
                ('supply_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_items', to='contenttypes.contenttype', verbose_name='Ausrüstungstyp')),
            ],
            options={
                'verbose_name': 'Packlisten-Gegenstand',
                'verbose_name_plural': 'Packlisten-Gegenstände',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
