# Generated by Django 5.2.12 on 2026-04-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packinglist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="packingitem",
            name="is_checked",
            field=models.BooleanField(default=False, verbose_name="Gepackt"),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="is_template",
            field=models.BooleanField(
                default=False, help_text="Vorlagen können von allen Benutzern geklont werden.", verbose_name="Vorlage"
            ),
        ),
    ]
