# Generated by Django 5.2.12 on 2026-04-06 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("packinglist", "0001_initial"),
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="packinglist",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packing_lists",
                to="profiles.usergroup",
                verbose_name="Gruppe",
            ),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packing_lists",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ersteller",
            ),
        ),
        migrations.AddField(
            model_name="packingcategory",
            name="packing_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="packinglist.packinglist",
                verbose_name="Packliste",
            ),
        ),
    ]
