# Generated by Django 5.2.12 on 2026-07-13 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packinglist', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_lists', to='profiles.usergroup', verbose_name='Gruppe'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_lists', to=settings.AUTH_USER_MODEL, verbose_name='Ersteller'),
        ),
        migrations.AddField(
            model_name='packingcategory',
            name='packing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='packinglist.packinglist', verbose_name='Packliste'),
        ),
        migrations.AddField(
            model_name='packinglistshare',
            name='packing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='packinglist.packinglist', verbose_name='Packliste'),
        ),
        migrations.AddField(
            model_name='packinglistsharecheck',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_checks', to='packinglist.packingitem', verbose_name='Gegenstand'),
        ),
        migrations.AddField(
            model_name='packinglistsharecheck',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='packinglist.packinglistshare', verbose_name='Freigabe'),
        ),
        migrations.AlterUniqueTogether(
            name='packinglistsharecheck',
            unique_together={('share', 'item')},
        ),
    ]
