# Generated by Django 5.2.12 on 2026-04-09 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packinglist", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="packingitem",
            name="is_do_not_bring",
            field=models.BooleanField(
                default=False,
                help_text="Markiert Gegenstände, die nicht mitgebracht werden sollen.",
                verbose_name="Nicht mitbringen",
            ),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Privat"), ("link_only", "Per Link zugänglich")],
                default="link_only",
                max_length=20,
                verbose_name="Sichtbarkeit",
            ),
        ),
        migrations.CreateModel(
            name="PackingListShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Token")),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="z.B. 'Für Max' oder 'Trupplink'",
                        max_length=100,
                        verbose_name="Bezeichnung",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "packing_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="packinglist.packinglist",
                        verbose_name="Packliste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Packlisten-Freigabe",
                "verbose_name_plural": "Packlisten-Freigaben",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackingListShareCheck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_checked", models.BooleanField(default=False, verbose_name="Gepackt")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_checks",
                        to="packinglist.packingitem",
                        verbose_name="Gegenstand",
                    ),
                ),
                (
                    "share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="packinglist.packinglistshare",
                        verbose_name="Freigabe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Freigabe-Check",
                "verbose_name_plural": "Freigabe-Checks",
                "unique_together": {("share", "item")},
            },
        ),
    ]
