# Generated by Django 5.2.12 on 2026-04-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packinglist", "0003_packingitem_is_do_not_bring_packinglist_visibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="packinglist",
            name="activity_type",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Aktivitätstyp"),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="age_group",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Altersstufe"),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="duration",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Dauer"),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="season",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Jahreszeit"),
        ),
    ]
