"""Recipe schemas package — re-exports all schemas for backward compatibility."""

from .cockpit import (
    CockpitDashboardOut,
    CockpitEvaluationOut,
    HealthRuleIn,
    HealthRuleOut,
    HealthRuleUpdateIn,
)
from .recipes import (
    NutritionalTagOut,
    PaginatedRecipeOut,
    RecipeAiCreateIn,
    RecipeCreateIn,
    RecipeDetailOut,
    RecipeFilterIn,
    RecipeListOut,
    RecipeSimilarOut,
    RecipeSuggestAllOut,
    RecipeUpdateIn,
    VisibilityUpdateIn,
)
from .items import (
    AiIngredientApplyIn,
    AiIngredientSuggestionOut,
    EstimateQuantitiesOut,
    EstimateQuantityItemOut,
    RecipeItemCreateIn,
    RecipeItemOut,
    RecipeItemUpdateIn,
)
from .dashboard import (
    DashboardInsightsOut,
    FoodDashboardOut,
    RecipeInsightOut,
)
from .nutrition import (
    ContributionOut,
    ImprovementListOut,
    ImprovementOut,
    LlmSuggestionOut,
    LlmSuggestionRequestIn,
    NutriScoreDetailOut,
    RecipeHintOut,
    RecipeItemNutritionOut,
    RecipeNutritionBreakdownOut,
    SuggestedIngredientOut,
)

__all__ = [
    "AiIngredientApplyIn",
    "DashboardInsightsOut",
    "FoodDashboardOut",
    "RecipeInsightOut",
    "AiIngredientSuggestionOut",
    "CockpitDashboardOut",
    "CockpitEvaluationOut",
    "ContributionOut",
    "EstimateQuantitiesOut",
    "EstimateQuantityItemOut",
    "HealthRuleIn",
    "HealthRuleOut",
    "HealthRuleUpdateIn",
    "ImprovementListOut",
    "ImprovementOut",
    "LlmSuggestionOut",
    "LlmSuggestionRequestIn",
    "NutriScoreDetailOut",
    "NutritionalTagOut",
    "PaginatedRecipeOut",
    "RecipeAiCreateIn",
    "RecipeCreateIn",
    "RecipeDetailOut",
    "RecipeFilterIn",
    "RecipeHintOut",
    "RecipeItemCreateIn",
    "RecipeItemNutritionOut",
    "RecipeItemOut",
    "RecipeItemUpdateIn",
    "RecipeListOut",
    "RecipeNutritionBreakdownOut",
    "RecipeSimilarOut",
    "RecipeSuggestAllOut",
    "RecipeUpdateIn",
    "SuggestedIngredientOut",
    "VisibilityUpdateIn",
]
