"""Recipe schemas package — re-exports all schemas for backward compatibility."""

from .rules import (
    RuleIn,
    RuleOut,
    RuleUpdateIn,
)
from .suggestions import (
    RecipeSuggestionOut,
    SuggestionDashboardOut,
    SuggestionOut,
)
from .recipes import (
    ForkRecipeIn,
    NutritionalTagOut,
    PaginatedRecipeOut,
    PaginatedRecipeSimilarOut,
    RecipeAiCreateIn,
    RecipeCreateIn,
    RecipeDetailOut,
    RecipeFilterIn,
    RecipeListOut,
    RecipeSimilarOut,
    RecipeSuggestAllOut,
    RecipeUpdateIn,
    VisibilityUpdateIn,
)
from .items import (
    AiIngredientApplyIn,
    AiIngredientSuggestionOut,
    EstimateQuantitiesOut,
    EstimateQuantityItemOut,
    RecipeItemCreateIn,
    RecipeItemOut,
    RecipeItemUpdateIn,
)
from .dashboard import (
    DashboardInsightsOut,
    FoodDashboardOut,
    RecipeInsightOut,
)
from .nutrition import (
    ContributionOut,
    ImprovementListOut,
    ImprovementOut,
    LlmSuggestionOut,
    LlmSuggestionRequestIn,
    NutriScoreDetailOut,
    RecipeItemNutritionOut,
    RecipeNutritionBreakdownOut,
    RecipeRuleResult,
    RecipeRulesOut,
    SuggestedIngredientOut,
)

__all__ = [
    "AiIngredientApplyIn",
    "AiIngredientSuggestionOut",
    "ContributionOut",
    "DashboardInsightsOut",
    "EstimateQuantitiesOut",
    "EstimateQuantityItemOut",
    "FoodDashboardOut",
    "ForkRecipeIn",
    "ImprovementListOut",
    "ImprovementOut",
    "LlmSuggestionOut",
    "LlmSuggestionRequestIn",
    "NutriScoreDetailOut",
    "NutritionalTagOut",
    "PaginatedRecipeOut",
    "PaginatedRecipeSimilarOut",
    "RecipeAiCreateIn",
    "RecipeCreateIn",
    "RecipeDetailOut",
    "RecipeFilterIn",
    "RecipeInsightOut",
    "RecipeItemCreateIn",
    "RecipeItemNutritionOut",
    "RecipeItemOut",
    "RecipeItemUpdateIn",
    "RecipeListOut",
    "RecipeNutritionBreakdownOut",
    "RecipeRuleResult",
    "RecipeRulesOut",
    "RecipeSimilarOut",
    "RecipeSuggestionOut",
    "RecipeSuggestAllOut",
    "RecipeUpdateIn",
    "RuleIn",
    "RuleOut",
    "RuleUpdateIn",
    "SuggestedIngredientOut",
    "SuggestionDashboardOut",
    "SuggestionOut",
    "VisibilityUpdateIn",
]
