# Generated by Django 5.2.12 on 2026-03-15 07:02

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Materialeinheit",
                "verbose_name_plural": "Materialeinheiten",
            },
        ),
        migrations.CreateModel(
            name="ScoutLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("sorting", models.IntegerField(default=0)),
                ("icon", models.CharField(blank=True, default="", max_length=100)),
            ],
            options={
                "verbose_name": "Pfadfinder-Stufe",
                "verbose_name_plural": "Pfadfinder-Stufen",
                "ordering": ["sorting"],
            },
        ),
        migrations.CreateModel(
            name="Idea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                ("summary", models.TextField(blank=True, default="", verbose_name="Kurzbeschreibung")),
                ("summary_long", models.TextField(blank=True, default="", verbose_name="Ausführliche Zusammenfassung")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                (
                    "costs_rating",
                    models.CharField(
                        choices=[("free", "0 €"), ("less_1", "< 1 €"), ("1_2", "1 – 2 €"), ("more_2", "> 2 €")],
                        default="free",
                        max_length=20,
                        verbose_name="Kosten",
                    ),
                ),
                (
                    "execution_time",
                    models.CharField(
                        choices=[
                            ("less_30", "< 30 Minuten"),
                            ("30_60", "30 – 60 Minuten"),
                            ("60_90", "60 – 90 Minuten"),
                            ("more_90", "> 90 Minuten"),
                        ],
                        default="less_30",
                        max_length=20,
                        verbose_name="Durchführungszeit",
                    ),
                ),
                (
                    "preparation_time",
                    models.CharField(
                        choices=[
                            ("none", "Keine Vorbereitung"),
                            ("less_15", "< 15 Minuten"),
                            ("15_30", "15 – 30 Minuten"),
                            ("30_60", "30 – 60 Minuten"),
                            ("more_60", "> 60 Minuten"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Vorbereitungszeit",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "Einfach"), ("medium", "Mittel"), ("hard", "Schwer")],
                        default="easy",
                        max_length=20,
                        verbose_name="Schwierigkeit",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("published", "Veröffentlicht"),
                            ("archived", "Archiviert"),
                            ("review", "In Prüfung"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="ideas/", verbose_name="Bild")),
                ("like_score", models.IntegerField(default=0, verbose_name="Beliebtheit")),
                ("view_count", models.IntegerField(default=0, verbose_name="Aufrufe")),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ("embedding", models.BinaryField(blank=True, null=True, verbose_name="Embedding")),
                (
                    "authors",
                    models.ManyToManyField(blank=True, related_name="authored_ideas", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("scout_levels", models.ManyToManyField(blank=True, related_name="ideas", to="idea.scoutlevel")),
            ],
            options={
                "verbose_name": "Idee",
                "verbose_name_plural": "Ideen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Emotion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "emotion_type",
                    models.CharField(
                        choices=[
                            ("in_love", "Begeistert"),
                            ("happy", "Gut"),
                            ("disappointed", "Enttäuscht"),
                            ("complex", "Zu komplex"),
                        ],
                        max_length=20,
                    ),
                ),
                ("session_key", models.CharField(blank=True, default="", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="emotions", to="idea.idea"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bewertung",
                "verbose_name_plural": "Bewertungen",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=True)),
                ("text", models.TextField(verbose_name="Kommentar")),
                ("author_name", models.CharField(blank=True, default="", max_length=100, verbose_name="Name (anonym)")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Ausstehend"), ("approved", "Freigegeben"), ("rejected", "Abgelehnt")],
                        default="pending",
                        max_length=20,
                        verbose_name="Moderations-Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="idea.comment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="idea.idea"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kommentar",
                "verbose_name_plural": "Kommentare",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IdeaOfTheWeek",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("release_date", models.DateField(unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="featured_weeks", to="idea.idea"
                    ),
                ),
            ],
            options={
                "verbose_name": "Idee der Woche",
                "verbose_name_plural": "Ideen der Woche",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="MaterialName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "default_unit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="idea.materialunit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Materialname",
                "verbose_name_plural": "Materialnamen",
            },
        ),
        migrations.CreateModel(
            name="MaterialItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.CharField(blank=True, default="", max_length=50)),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="materials", to="idea.idea"
                    ),
                ),
                (
                    "material_name",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="idea.materialname"
                    ),
                ),
                (
                    "material_unit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="idea.materialunit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materialien",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True, help_text="False für User-Vorschläge die noch nicht freigegeben sind"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="idea.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="idea",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="ideas", to="idea.tag"),
        ),
        migrations.CreateModel(
            name="TagSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions",
                        to="idea.tag",
                    ),
                ),
                (
                    "suggested_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag-Vorschlag",
                "verbose_name_plural": "Tag-Vorschläge",
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preferred_group_size_min", models.IntegerField(blank=True, null=True)),
                ("preferred_group_size_max", models.IntegerField(blank=True, null=True)),
                (
                    "preferred_difficulty",
                    models.CharField(
                        blank=True,
                        choices=[("easy", "Einfach"), ("medium", "Mittel"), ("hard", "Schwer")],
                        default="",
                        max_length=20,
                    ),
                ),
                ("preferred_location", models.CharField(blank=True, default="", max_length=50)),
                (
                    "preferred_scout_level",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="idea.scoutlevel"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Benutzereinstellungen",
                "verbose_name_plural": "Benutzereinstellungen",
            },
        ),
        migrations.CreateModel(
            name="IdeaView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("ip_hash", models.CharField(help_text="SHA-256 gehashte IP", max_length=64)),
                ("user_agent", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="views", to="idea.idea"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideenaufruf",
                "verbose_name_plural": "Ideenaufrufe",
                "indexes": [
                    models.Index(fields=["idea", "session_key", "created_at"], name="idea_ideavi_idea_id_8c40a1_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="idea",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="idea_idea_search__86ba10_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="idea",
            index=models.Index(fields=["status", "-created_at"], name="idea_idea_status_a21a73_idx"),
        ),
        migrations.AddIndex(
            model_name="idea",
            index=models.Index(fields=["-like_score"], name="idea_idea_like_sc_28a294_idx"),
        ),
        migrations.AddIndex(
            model_name="idea",
            index=models.Index(fields=["-view_count"], name="idea_idea_view_co_bbda72_idx"),
        ),
    ]
