# Generated by Django 5.2.12 on 2026-03-15 12:51

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Idea = apps.get_model("idea", "Idea")
    for idea in Idea.objects.all():
        base_slug = slugify(idea.title) or f"idea-{idea.pk}"
        slug = base_slug
        counter = 1
        while Idea.objects.filter(slug=slug).exclude(pk=idea.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        idea.slug = slug
        idea.save(update_fields=["slug"])


def add_unique_constraint(apps, schema_editor):
    schema_editor.execute(
        "CREATE UNIQUE INDEX idea_idea_slug_key ON idea_idea (slug);"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0001_initial"),
    ]

    operations = [
        # 1. Add slug field without unique constraint
        migrations.AddField(
            model_name="idea",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="URL-freundlicher Name, wird automatisch aus dem Titel generiert",
                max_length=280,
                verbose_name="Slug",
            ),
        ),
        # 2. Populate slugs for existing rows
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # 3. Add unique constraint via raw SQL
        migrations.RunPython(add_unique_constraint, migrations.RunPython.noop),
    ]
