# Generated by Django 5.2.12 on 2026-03-16 17:50

from django.db import migrations, models
from django.utils.text import slugify


def populate_material_slugs(apps, schema_editor):
    MaterialName = apps.get_model("idea", "MaterialName")
    for mat in MaterialName.objects.all():
        base_slug = slugify(mat.name, allow_unicode=False)
        if not base_slug:
            base_slug = "material"
        slug = base_slug
        counter = 1
        while MaterialName.objects.filter(slug=slug).exclude(pk=mat.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        mat.slug = slug
        mat.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0003_enable_pg_trgm"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialitem",
            name="quantity_type",
            field=models.CharField(
                choices=[("once", "Einmalig"), ("per_person", "Pro Person")],
                default="once",
                help_text="Einmalig = wird einmal benötigt, Pro Person = Menge pro Person",
                max_length=20,
                verbose_name="Mengenart",
            ),
        ),
        migrations.AddField(
            model_name="materialname",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        # Add slug without unique constraint first
        migrations.AddField(
            model_name="materialname",
            name="slug",
            field=models.SlugField(blank=True, max_length=280, default=""),
        ),
        # Populate slugs for existing records
        migrations.RunPython(populate_material_slugs, migrations.RunPython.noop),
    ]
