# Generated by Django 5.2.12 on 2026-03-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0006_idea_idea_type"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="idea",
            new_name="idea_idea_idea_ty_fa5270_idx",
            old_name="idea_idea_idea_ty_idx",
        ),
        migrations.AlterField(
            model_name="idea",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-freundlicher Name, wird automatisch aus dem Titel generiert",
                max_length=280,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
