# Generated by Django 5.2.12 on 2026-03-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0007_rename_idea_idea_idea_ty_idx_idea_idea_idea_ty_fa5270_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="embedding",
            field=models.BinaryField(blank=True, null=True, verbose_name="Embedding"),
        ),
    ]
