# Generated by Django 5.2.12 on 2026-03-24 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0008_tag_embedding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.CharField(max_length=500, verbose_name="Suchbegriff")),
                ("results_count", models.IntegerField(default=0, verbose_name="Ergebnisse")),
                ("session_key", models.CharField(blank=True, default="", max_length=40)),
                ("ip_hash", models.CharField(blank=True, default="", help_text="SHA-256 gehashte IP", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Suchanfrage",
                "verbose_name_plural": "Suchanfragen",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["-created_at"], name="idea_search_created_170928_idx")],
            },
        ),
    ]
