# Generated by Django 5.2.12 on 2026-03-25 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0009_searchlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="recipe_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("breakfast", "Frühstück"),
                    ("warm_meal", "Warme Mahlzeit"),
                    ("cold_meal", "Kalte Mahlzeit"),
                    ("dessert", "Nachtisch"),
                    ("side_dish", "Beilage"),
                    ("snack", "Snack"),
                    ("drink", "Getränk"),
                ],
                default="",
                help_text="Frühstück, Warme Mahlzeit, Snack, etc. (nur für Rezepte)",
                max_length=20,
                verbose_name="Rezepttyp",
            ),
        ),
        migrations.AddField(
            model_name="idea",
            name="servings",
            field=models.IntegerField(
                blank=True,
                default=4,
                help_text="Anzahl der Portionen (nur für Rezepte)",
                null=True,
                verbose_name="Portionen",
            ),
        ),
        migrations.CreateModel(
            name="MeasuringUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="Beschreibung")),
                ("quantity", models.FloatField(default=1, verbose_name="Umrechnungsfaktor")),
                (
                    "unit",
                    models.CharField(
                        choices=[("ml", "Milliliter"), ("g", "Gramm")],
                        default="g",
                        max_length=2,
                        verbose_name="Einheit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Maßeinheit",
                "verbose_name_plural": "Maßeinheiten",
            },
        ),
        migrations.CreateModel(
            name="NutritionalTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        help_text="z.B. 'Fleisch', 'Alkohol', 'Nüsse', 'Scharf'", max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "name_opposite",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="z.B. 'Vegan', 'Vegetarisch', 'Alkoholfrei'",
                        max_length=255,
                        verbose_name="Gegenbezeichnung",
                    ),
                ),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("rank", models.IntegerField(default=1)),
                (
                    "is_dangerous",
                    models.BooleanField(
                        default=False, help_text="Kennzeichnet potenziell gefährliche Inhaltsstoffe (Allergene)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ernährungstag",
                "verbose_name_plural": "Ernährungstags",
                "ordering": ["rank", "name"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                ("physical_density", models.FloatField(default=1, verbose_name="Dichte")),
                (
                    "physical_viscosity",
                    models.CharField(
                        choices=[("solid", "Essen"), ("beverage", "Getränk")],
                        default="solid",
                        max_length=10,
                        verbose_name="Aggregatzustand",
                    ),
                ),
                (
                    "standard_recipe_weight_g",
                    models.FloatField(
                        blank=True,
                        default=100,
                        help_text="Standard-Gewicht in Gramm für ein Rezept",
                        null=True,
                        verbose_name="Standard-Rezeptgewicht (g)",
                    ),
                ),
                ("energy_kj", models.FloatField(blank=True, default=0, null=True, verbose_name="Energie (kJ)")),
                ("protein_g", models.FloatField(blank=True, default=0, null=True, verbose_name="Eiweiß (g)")),
                ("fat_g", models.FloatField(blank=True, default=0, null=True, verbose_name="Fett (g)")),
                (
                    "carbohydrate_g",
                    models.FloatField(blank=True, default=0, null=True, verbose_name="Kohlenhydrate (g)"),
                ),
                ("sugar_g", models.FloatField(blank=True, default=0, null=True, verbose_name="Zucker (g)")),
                ("fibre_g", models.FloatField(blank=True, default=0, null=True, verbose_name="Ballaststoffe (g)")),
                ("salt_g", models.FloatField(blank=True, default=0, null=True, verbose_name="Salz (g)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("verified", "Verifiziert"),
                            ("user_content", "Benutzer erstellt"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingredient_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="idea.ingredient",
                        verbose_name="Referenz-Zutat",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nutritional_tags",
                    models.ManyToManyField(
                        blank=True, related_name="ingredients", to="idea.nutritionaltag", verbose_name="Ernährungstags"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zutat",
                "verbose_name_plural": "Zutaten",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="idea",
            name="nutritional_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ernährungshinweise wie vegan, vegetarisch, etc. (nur für Rezepte)",
                related_name="ideas",
                to="idea.nutritionaltag",
                verbose_name="Ernährungstags",
            ),
        ),
        migrations.CreateModel(
            name="Portion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=True)),
                ("name", models.CharField(blank=True, default="", max_length=255, verbose_name="Name")),
                ("quantity", models.FloatField(default=1, verbose_name="Menge")),
                ("weight_g", models.FloatField(blank=True, default=0, null=True, verbose_name="Gewicht (g)")),
                ("rank", models.IntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portions",
                        to="idea.ingredient",
                        verbose_name="Zutat",
                    ),
                ),
                (
                    "measuring_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="idea.measuringunit",
                        verbose_name="Maßeinheit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portion",
                "verbose_name_plural": "Portionen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecipeItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.FloatField(default=1, verbose_name="Menge")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Reihenfolge")),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="z.B. 'gehackt', 'in Scheiben', 'optional'",
                        max_length=255,
                        verbose_name="Anmerkung",
                    ),
                ),
                (
                    "quantity_type",
                    models.CharField(
                        choices=[("once", "Einmalig"), ("per_person", "Pro Person")],
                        default="once",
                        help_text="Einmalig = Gesamtmenge, Pro Person = Menge pro Person",
                        max_length=20,
                        verbose_name="Mengenart",
                    ),
                ),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_items",
                        to="idea.idea",
                        verbose_name="Rezept",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Direkte Zutat (wenn keine Portion gewählt)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipe_items",
                        to="idea.ingredient",
                        verbose_name="Zutat",
                    ),
                ),
                (
                    "measuring_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="idea.measuringunit",
                        verbose_name="Maßeinheit",
                    ),
                ),
                (
                    "portion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipe_items",
                        to="idea.portion",
                        verbose_name="Portion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezept-Zutat",
                "verbose_name_plural": "Rezept-Zutaten",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="IngredientAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Alternativer Name für die Zutat", max_length=100, verbose_name="Alternativname"
                    ),
                ),
                ("rank", models.IntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="aliases", to="idea.ingredient"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zutaten-Alias",
                "verbose_name_plural": "Zutaten-Aliase",
                "ordering": ["-rank", "name"],
                "unique_together": {("ingredient", "rank")},
            },
        ),
    ]
