# Generated by Django 5.2.12 on 2026-03-25 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0010_idea_recipe_type_idea_servings_measuringunit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialitem",
            name="material_unit",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="idea.measuringunit"
            ),
        ),
        migrations.AlterField(
            model_name="materialname",
            name="default_unit",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="idea.measuringunit"
            ),
        ),
        migrations.DeleteModel(
            name="MaterialUnit",
        ),
    ]
