# Generated by Django 5.2.12 on 2026-03-25 19:20

import django.db.models.deletion
from django.db import migrations, models


def migrate_material_units_to_measuring_units(apps, schema_editor):
    MaterialUnit = apps.get_model("idea", "MaterialUnit")
    MeasuringUnit = apps.get_model("idea", "MeasuringUnit")
    MaterialItem = apps.get_model("idea", "MaterialItem")
    MaterialName = apps.get_model("idea", "MaterialName")

    unit_id_map = {}

    for legacy_unit in MaterialUnit.objects.all().order_by("id"):
        measuring_unit = MeasuringUnit.objects.filter(id=legacy_unit.id).first()
        if measuring_unit is None:
            measuring_unit = MeasuringUnit.objects.filter(name=legacy_unit.name).first()

        if measuring_unit is None:
            measuring_unit = MeasuringUnit(id=legacy_unit.id, name=legacy_unit.name)
            measuring_unit.save(force_insert=True)

        unit_id_map[legacy_unit.id] = measuring_unit.id

    for old_id, new_id in unit_id_map.items():
        if old_id == new_id:
            continue

        MaterialItem.objects.filter(material_unit_id=old_id).update(material_unit_id=new_id)
        MaterialName.objects.filter(default_unit_id=old_id).update(default_unit_id=new_id)


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0010_idea_recipe_type_idea_servings_measuringunit_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_material_units_to_measuring_units, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="materialitem",
            name="material_unit",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="idea.measuringunit"
            ),
        ),
        migrations.AlterField(
            model_name="materialname",
            name="default_unit",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="idea.measuringunit"
            ),
        ),
        migrations.DeleteModel(
            name="MaterialUnit",
        ),
    ]
