# Generated by Django 5.2.12 on 2026-04-03 21:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0011_merge_materialunit_into_measuringunit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeHint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("energy_kj", "Energie (kJ)"),
                            ("sugar_g", "Zucker (g)"),
                            ("sodium_mg", "Natrium (mg)"),
                            ("fibre_g", "Ballaststoffe (g)"),
                            ("fat_g", "Fett (g)"),
                            ("fat_sat_g", "Gesättigte Fettsäuren (g)"),
                            ("protein_g", "Eiweiß (g)"),
                            ("carbohydrate_g", "Kohlenhydrate (g)"),
                            ("salt_g", "Salz (g)"),
                            ("fructose_g", "Fructose (g)"),
                            ("lactose_g", "Laktose (g)"),
                            ("fruit_factor", "Obst-/Gemüse-Anteil"),
                        ],
                        help_text="Nährwertfeld das geprüft wird",
                        max_length=20,
                        verbose_name="Parameter",
                    ),
                ),
                ("min_value", models.FloatField(blank=True, null=True, verbose_name="Mindestwert")),
                ("max_value", models.FloatField(blank=True, null=True, verbose_name="Höchstwert")),
                (
                    "min_max",
                    models.CharField(
                        choices=[("min", "Mindestens"), ("max", "Höchstens"), ("range", "Bereich")],
                        default="max",
                        max_length=10,
                        verbose_name="Regeltyp",
                    ),
                ),
                (
                    "hint_level",
                    models.CharField(
                        choices=[("info", "Information"), ("warning", "Warnung"), ("error", "Fehler")],
                        default="info",
                        max_length=10,
                        verbose_name="Hinweis-Stufe",
                    ),
                ),
                (
                    "recipe_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("breakfast", "Frühstück"),
                            ("warm_meal", "Warme Mahlzeit"),
                            ("cold_meal", "Kalte Mahlzeit"),
                            ("dessert", "Nachtisch"),
                            ("side_dish", "Beilage"),
                            ("snack", "Snack"),
                            ("drink", "Getränk"),
                        ],
                        default="",
                        help_text="Optional: Gilt nur für diesen Rezepttyp",
                        max_length=20,
                        verbose_name="Rezepttyp",
                    ),
                ),
                (
                    "recipe_objective",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("health", "Gesundheit"),
                            ("taste", "Geschmack"),
                            ("cost", "Kosten"),
                            ("fulfillment", "Sättigung"),
                        ],
                        default="",
                        help_text="Gesundheit, Geschmack, Kosten oder Sättigung",
                        max_length=20,
                        verbose_name="Bewertungsdimension",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezept-Hinweis",
                "verbose_name_plural": "Rezept-Hinweise",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RetailSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="Beschreibung")),
                ("rank", models.IntegerField(default=0, verbose_name="Sortierung")),
            ],
            options={
                "verbose_name": "Supermarkt-Abteilung",
                "verbose_name_plural": "Supermarkt-Abteilungen",
                "ordering": ["rank", "name"],
            },
        ),
        migrations.AddField(
            model_name="ingredient",
            name="child_score",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Kinderfreundlichkeit (1-10)",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="durability_in_days",
            field=models.IntegerField(blank=True, null=True, verbose_name="Haltbarkeit (Tage)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="ean",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="EAN-Barcode"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="environmental_score",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Umweltfreundlichkeit (1-10)",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="fat_sat_g",
            field=models.FloatField(blank=True, null=True, verbose_name="Gesättigte Fettsäuren (g)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="fdc_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="USDA FoodData Central ID"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="fructose_g",
            field=models.FloatField(blank=True, null=True, verbose_name="Fructose (g)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="fruit_factor",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Obst-/Gemüse-Anteil (0-1)",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="lactose_g",
            field=models.FloatField(blank=True, null=True, verbose_name="Laktose (g)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="max_storage_temperature",
            field=models.IntegerField(blank=True, null=True, verbose_name="Max. Lagertemperatur (°C)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="nova_score",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)],
                verbose_name="NOVA-Verarbeitungsgrad (1-4)",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="nutri_class",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                verbose_name="Nutri-Score Klasse (1=A bis 5=E)",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="nutri_score",
            field=models.IntegerField(blank=True, null=True, verbose_name="Nutri-Score (Punkte)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="price_per_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Preis pro kg (EUR)"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="scout_score",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Pfadfindereignung (1-10)",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="sodium_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Natrium (mg)"),
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=True)),
                ("price_eur", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Preis (EUR)")),
                (
                    "quantity",
                    models.IntegerField(
                        default=1, help_text="Wie viele Portionen in einer Packung", verbose_name="Anzahl pro Packung"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="z.B. '500g Packung'",
                        max_length=255,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "retailer",
                    models.CharField(
                        blank=True, default="", help_text="z.B. 'Aldi', 'Rewe'", max_length=255, verbose_name="Händler"
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="z.B. 'Bio', 'Standard'",
                        max_length=100,
                        verbose_name="Qualität",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "portion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="idea.portion",
                        verbose_name="Portion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preis",
                "verbose_name_plural": "Preise",
                "ordering": ["price_eur"],
            },
        ),
        migrations.AddField(
            model_name="ingredient",
            name="retail_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingredients",
                to="idea.retailsection",
                verbose_name="Supermarkt-Abteilung",
            ),
        ),
    ]
