# Generated by Django 5.2.12 on 2026-04-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0012_recipehint_retailsection_ingredient_child_score_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecipeHint",
        ),
        migrations.RemoveField(
            model_name="recipeitem",
            name="idea",
        ),
        migrations.RemoveField(
            model_name="recipeitem",
            name="ingredient",
        ),
        migrations.RemoveField(
            model_name="recipeitem",
            name="measuring_unit",
        ),
        migrations.RemoveField(
            model_name="recipeitem",
            name="portion",
        ),
        migrations.RemoveIndex(
            model_name="idea",
            name="idea_idea_idea_ty_fa5270_idx",
        ),
        migrations.RemoveField(
            model_name="idea",
            name="nutritional_tags",
        ),
        migrations.RemoveField(
            model_name="idea",
            name="recipe_type",
        ),
        migrations.RemoveField(
            model_name="idea",
            name="servings",
        ),
        migrations.AlterField(
            model_name="idea",
            name="idea_type",
            field=models.CharField(
                choices=[("idea", "Idee"), ("knowledge", "Wissensbeitrag")],
                default="idea",
                help_text="Idee oder Wissensbeitrag",
                max_length=20,
                verbose_name="Typ",
            ),
        ),
        migrations.DeleteModel(
            name="RecipeItem",
        ),
    ]
