"""Profiles schemas package — re-exports all schemas for backward compatibility."""

from .profile import (
    MyContentOut,
    ProfilePictureOut,
    PublicContentOut,
    PublicUserProfileOut,
    UserPreferenceIn,
    UserPreferenceOut,
    UserProfileOut,
    UserProfileUpdateIn,
)
from .groups import (
    AddMemberIn,
    GroupCorporateIdentityIn,
    GroupCorporateIdentityOut,
    GroupMemberOut,
    GroupParentOut,
    JoinByCodeIn,
    JoinRequestDecisionIn,
    JoinRequestIn,
    JoinRequestOut,
    UpdateMemberIn,
    UserGroupChildOut,
    UserGroupCreateIn,
    UserGroupDetailOut,
    UserGroupOut,
    UserGroupUpdateIn,
)
from .privacy import (
    AnalyticsDataSchema,
    CategorySchema,
    DataOverviewSchema,
    DeleteAccountRequestSchema,
)

__all__ = [
    "AddMemberIn",
    "AnalyticsDataSchema",
    "CategorySchema",
    "DataOverviewSchema",
    "DeleteAccountRequestSchema",
    "GroupCorporateIdentityIn",
    "GroupCorporateIdentityOut",
    "GroupMemberOut",
    "GroupParentOut",
    "JoinByCodeIn",
    "JoinRequestDecisionIn",
    "JoinRequestIn",
    "JoinRequestOut",
    "MyContentOut",
    "ProfilePictureOut",
    "PublicContentOut",
    "PublicUserProfileOut",
    "UpdateMemberIn",
    "UserGroupChildOut",
    "UserGroupCreateIn",
    "UserGroupDetailOut",
    "UserGroupOut",
    "UserGroupUpdateIn",
    "UserPreferenceIn",
    "UserPreferenceOut",
    "UserProfileOut",
    "UserProfileUpdateIn",
]
