# Generated by Django 5.2.12 on 2026-04-06 18:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasuringUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="Beschreibung")),
                ("quantity", models.FloatField(default=1, verbose_name="Umrechnungsfaktor")),
                (
                    "unit",
                    models.CharField(
                        choices=[("ml", "Milliliter"), ("g", "Gramm")],
                        default="g",
                        max_length=2,
                        verbose_name="Einheit",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Maßeinheit",
                "verbose_name_plural": "Maßeinheiten",
            },
        ),
        migrations.CreateModel(
            name="NutritionalTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="z.B. 'Fleisch', 'Alkohol', 'Nüsse', 'Scharf'", max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "name_opposite",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="z.B. 'Vegan', 'Vegetarisch', 'Alkoholfrei'",
                        max_length=255,
                        verbose_name="Gegenbezeichnung",
                    ),
                ),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("rank", models.IntegerField(default=1)),
                (
                    "is_dangerous",
                    models.BooleanField(
                        default=False, help_text="Kennzeichnet potenziell gefährliche Inhaltsstoffe (Allergene)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ernährungstag",
                "verbose_name_plural": "Ernährungstags",
                "ordering": ["rank", "name"],
            },
        ),
        migrations.CreateModel(
            name="RetailSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="Beschreibung")),
                ("rank", models.IntegerField(default=0, verbose_name="Sortierung")),
            ],
            options={
                "verbose_name": "Supermarkt-Abteilung",
                "verbose_name_plural": "Supermarkt-Abteilungen",
                "ordering": ["rank", "name"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                ("physical_density", models.FloatField(default=1, verbose_name="Dichte")),
                (
                    "physical_viscosity",
                    models.CharField(
                        choices=[("solid", "Essen"), ("beverage", "Getränk")],
                        default="solid",
                        max_length=10,
                        verbose_name="Aggregatzustand",
                    ),
                ),
                ("durability_in_days", models.IntegerField(blank=True, null=True, verbose_name="Haltbarkeit (Tage)")),
                (
                    "max_storage_temperature",
                    models.IntegerField(blank=True, null=True, verbose_name="Max. Lagertemperatur (°C)"),
                ),
                (
                    "standard_recipe_weight_g",
                    models.FloatField(
                        blank=True,
                        default=100,
                        help_text="Standard-Gewicht in Gramm für ein Rezept",
                        null=True,
                        verbose_name="Standard-Rezeptgewicht (g)",
                    ),
                ),
                ("energy_kj", models.FloatField(blank=True, default=0, null=True, verbose_name="Energie (kJ)")),
                ("protein_g", models.FloatField(blank=True, default=0, null=True, verbose_name="Eiweiß (g)")),
                ("fat_g", models.FloatField(blank=True, default=0, null=True, verbose_name="Fett (g)")),
                ("fat_sat_g", models.FloatField(blank=True, null=True, verbose_name="Gesättigte Fettsäuren (g)")),
                (
                    "carbohydrate_g",
                    models.FloatField(blank=True, default=0, null=True, verbose_name="Kohlenhydrate (g)"),
                ),
                ("sugar_g", models.FloatField(blank=True, default=0, null=True, verbose_name="Zucker (g)")),
                ("fibre_g", models.FloatField(blank=True, default=0, null=True, verbose_name="Ballaststoffe (g)")),
                ("salt_g", models.FloatField(blank=True, default=0, null=True, verbose_name="Salz (g)")),
                ("sodium_mg", models.FloatField(blank=True, null=True, verbose_name="Natrium (mg)")),
                ("fructose_g", models.FloatField(blank=True, null=True, verbose_name="Fructose (g)")),
                ("lactose_g", models.FloatField(blank=True, null=True, verbose_name="Laktose (g)")),
                (
                    "child_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Kinderfreundlichkeit (1-10)",
                    ),
                ),
                (
                    "scout_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Pfadfindereignung (1-10)",
                    ),
                ),
                (
                    "environmental_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Umweltfreundlichkeit (1-10)",
                    ),
                ),
                (
                    "nova_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="NOVA-Verarbeitungsgrad (1-4)",
                    ),
                ),
                (
                    "fruit_factor",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Obst-/Gemüse-Anteil (0-1)",
                    ),
                ),
                ("nutri_score", models.IntegerField(blank=True, null=True, verbose_name="Nutri-Score (Punkte)")),
                (
                    "nutri_class",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Nutri-Score Klasse (1=A bis 5=E)",
                    ),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Preis pro kg (EUR)"
                    ),
                ),
                ("fdc_id", models.IntegerField(blank=True, null=True, verbose_name="USDA FoodData Central ID")),
                ("ean", models.CharField(blank=True, default="", max_length=20, verbose_name="EAN-Barcode")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("verified", "Verifiziert"),
                            ("user_content", "Benutzer erstellt"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingredients_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingredient_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supply.ingredient",
                        verbose_name="Referenz-Zutat",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingredients_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nutritional_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ingredients",
                        to="supply.nutritionaltag",
                        verbose_name="Ernährungstags",
                    ),
                ),
                (
                    "retail_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingredients",
                        to="supply.retailsection",
                        verbose_name="Supermarkt-Abteilung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zutat",
                "verbose_name_plural": "Zutaten",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("image", models.ImageField(blank=True, null=True, upload_to="supplies/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material_category",
                    models.CharField(
                        choices=[
                            ("tools", "Werkzeuge"),
                            ("crafting", "Bastelmaterial"),
                            ("kitchen", "Küchengeräte"),
                            ("outdoor", "Outdoor-Ausrüstung"),
                            ("stationery", "Schreibwaren"),
                            ("other", "Sonstiges"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "is_consumable",
                    models.BooleanField(
                        default=False, help_text="True if the material is consumed during use (e.g., paper, glue)."
                    ),
                ),
                (
                    "purchase_links",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of purchase links: [{"url": "...", "shop_name": "...", "price": 9.99}]',
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materialien",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Portion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, default="", max_length=255, verbose_name="Name")),
                ("quantity", models.FloatField(default=1, verbose_name="Menge")),
                ("weight_g", models.FloatField(blank=True, default=0, null=True, verbose_name="Gewicht (g)")),
                ("rank", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portions",
                        to="supply.ingredient",
                        verbose_name="Zutat",
                    ),
                ),
                (
                    "measuring_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supply.measuringunit",
                        verbose_name="Maßeinheit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portions_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portion",
                "verbose_name_plural": "Portionen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price_eur", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Preis (EUR)")),
                (
                    "quantity",
                    models.IntegerField(
                        default=1, help_text="Wie viele Portionen in einer Packung", verbose_name="Anzahl pro Packung"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="z.B. '500g Packung'",
                        max_length=255,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "retailer",
                    models.CharField(
                        blank=True, default="", help_text="z.B. 'Aldi', 'Rewe'", max_length=255, verbose_name="Händler"
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="z.B. 'Bio', 'Standard'",
                        max_length=100,
                        verbose_name="Qualität",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "portion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="supply.portion",
                        verbose_name="Portion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prices_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preis",
                "verbose_name_plural": "Preise",
                "ordering": ["price_eur"],
            },
        ),
        migrations.CreateModel(
            name="IngredientAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Alternativer Name für die Zutat", max_length=100, verbose_name="Alternativname"
                    ),
                ),
                ("rank", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingredient_aliases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="aliases", to="supply.ingredient"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingredient_aliases_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zutaten-Alias",
                "verbose_name_plural": "Zutaten-Aliase",
                "ordering": ["-rank", "name"],
                "unique_together": {("ingredient", "rank")},
            },
        ),
        migrations.CreateModel(
            name="ContentMaterialItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("quantity", models.CharField(blank=True, default="", max_length=50)),
                (
                    "quantity_type",
                    models.CharField(
                        choices=[("once", "Einmalig"), ("per_person", "Pro Person")], default="once", max_length=20
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_items",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="content_usages", to="supply.material"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "indexes": [models.Index(fields=["content_type", "object_id"], name="contentmaterialitem_ct_oid_idx")],
            },
        ),
    ]
