# Generated by Django 5.2.12 on 2026-07-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_dedupe_and_enforce_unique_rank1_portion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
