# Generated by Django 5.2.12 on 2026-04-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0002_delete_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portion",
            options={
                "ordering": ["-priority", "rank", "name"],
                "verbose_name": "Portion",
                "verbose_name_plural": "Portionen",
            },
        ),
        migrations.AddField(
            model_name="portion",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Standard-Portion"),
        ),
        migrations.AddField(
            model_name="portion",
            name="priority",
            field=models.IntegerField(default=0, verbose_name="Priorität"),
        ),
    ]
