# Generated by Django 5.2.12 on 2026-07-17 21:28

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def migrate_system_portions(apps, schema_editor):
    """Migrate existing system portions to the new data model.

    - "Packung" portions → Package model
    - "g" portions → delete, rebind referencing RecipeItems to portion=NULL
    - "Stück" portions → keep as regular portions (is_system flag dropped separately)
    """
    Portion = apps.get_model("supply", "Portion")
    Package = apps.get_model("supply", "Package")
    RecipeItem = apps.get_model("recipe", "RecipeItem")

    system_portions = Portion.objects.filter(is_system=True)

    for portion in system_portions:
        name_lower = portion.name.strip().lower()

        if name_lower in ("packung", "packung (system)"):
            Package.objects.create(
                name=portion.name,
                weight_g=portion.weight_g,
                rank=portion.rank if portion.rank != 9999 else 1,
                ingredient=portion.ingredient,
                created_at=portion.created_at,
                updated_at=portion.updated_at,
                created_by=portion.created_by,
                updated_by=portion.updated_by,
            )

        elif name_lower == "g":
            RecipeItem.objects.filter(portion=portion).update(portion=None)
            portion.delete()

        elif name_lower == "stück":
            pass

    remaining_system = Portion.objects.filter(is_system=True)
    for portion in remaining_system:
        name_lower = portion.name.strip().lower()
        if name_lower not in ("packung", "g", "stück"):
            portion.is_system = False
            portion.save(update_fields=["is_system"])


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0003_ingredient_deleted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("weight_g", models.FloatField(blank=True, default=None, help_text="Gewicht einer Packung in Gramm. NULL = unbekannt.", null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name="Gewicht (g)")),
                ("rank", models.IntegerField(default=1, verbose_name="Rang (1 = Standardpackung)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="packages_created", to=settings.AUTH_USER_MODEL)),
                ("ingredient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="packages", to="supply.ingredient", verbose_name="Zutat")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="packages_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Packung",
                "verbose_name_plural": "Packungen",
                "ordering": ["rank"],
                "constraints": [
                    models.UniqueConstraint(django.db.models.functions.text.Lower("name"), models.F("ingredient_id"), condition=models.Q(("deleted_at__isnull", True)), name="unique_package_name_per_ingredient"),
                    models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("rank", 1)), fields=("ingredient",), name="unique_rank1_package_per_ingredient"),
                ],
            },
        ),
        migrations.RunPython(migrate_system_portions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="portion",
            name="is_system",
        ),
    ]
