# Generated by Django 5.2.12 on 2026-04-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0003_alter_portion_options_portion_is_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="biotin_ug",
            field=models.FloatField(blank=True, null=True, verbose_name="Biotin / Vitamin B7 (µg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="calcium_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Calcium (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="chromium_ug",
            field=models.FloatField(blank=True, null=True, verbose_name="Chrom (µg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="copper_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Kupfer (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="fluoride_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Fluorid (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="folate_ug",
            field=models.FloatField(blank=True, null=True, verbose_name="Folat / Folsäure (µg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="iodine_ug",
            field=models.FloatField(blank=True, null=True, verbose_name="Jod (µg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="iron_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Eisen (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="magnesium_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Magnesium (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="manganese_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Mangan (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="niacin_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Niacin / Vitamin B3 (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="pantothenic_acid_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Pantothensäure / Vitamin B5 (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="phosphorus_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Phosphor (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="potassium_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Kalium (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="selenium_ug",
            field=models.FloatField(blank=True, null=True, verbose_name="Selen (µg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="vitamin_a_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Vitamin A (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="vitamin_b12_ug",
            field=models.FloatField(blank=True, null=True, verbose_name="Vitamin B12 / Cobalamin (µg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="vitamin_b1_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Vitamin B1 / Thiamin (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="vitamin_b2_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Vitamin B2 / Riboflavin (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="vitamin_b6_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Vitamin B6 / Pyridoxin (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="vitamin_c_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Vitamin C (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="vitamin_d_ug",
            field=models.FloatField(blank=True, null=True, verbose_name="Vitamin D (µg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="vitamin_e_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Vitamin E (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="vitamin_k_ug",
            field=models.FloatField(blank=True, null=True, verbose_name="Vitamin K (µg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="zinc_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Zink (mg)"),
        ),
        migrations.CreateModel(
            name="DgeReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("age_min", models.IntegerField(verbose_name="Alter von")),
                ("age_max", models.IntegerField(verbose_name="Alter bis")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Männlich"), ("female", "Weiblich")], max_length=10, verbose_name="Geschlecht"
                    ),
                ),
                ("energy_kj", models.FloatField(blank=True, null=True, verbose_name="Energie (kJ)")),
                ("protein_g", models.FloatField(blank=True, null=True, verbose_name="Eiweiß (g)")),
                ("fat_g", models.FloatField(blank=True, null=True, verbose_name="Fett (g)")),
                ("carbohydrate_g", models.FloatField(blank=True, null=True, verbose_name="Kohlenhydrate (g)")),
                ("fibre_g", models.FloatField(blank=True, null=True, verbose_name="Ballaststoffe (g)")),
                ("sugar_g_max", models.FloatField(blank=True, null=True, verbose_name="Zucker max (g)")),
                ("salt_g_max", models.FloatField(blank=True, null=True, verbose_name="Salz max (g)")),
                (
                    "fat_sat_g_max",
                    models.FloatField(blank=True, null=True, verbose_name="Gesättigte Fettsäuren max (g)"),
                ),
                ("sodium_mg_max", models.FloatField(blank=True, null=True, verbose_name="Natrium max (mg)")),
                ("vitamin_a_mg", models.FloatField(blank=True, null=True, verbose_name="Vitamin A (mg)")),
                ("vitamin_b1_mg", models.FloatField(blank=True, null=True, verbose_name="Vitamin B1 (mg)")),
                ("vitamin_b2_mg", models.FloatField(blank=True, null=True, verbose_name="Vitamin B2 (mg)")),
                ("vitamin_b6_mg", models.FloatField(blank=True, null=True, verbose_name="Vitamin B6 (mg)")),
                ("vitamin_b12_ug", models.FloatField(blank=True, null=True, verbose_name="Vitamin B12 (µg)")),
                ("vitamin_c_mg", models.FloatField(blank=True, null=True, verbose_name="Vitamin C (mg)")),
                ("vitamin_d_ug", models.FloatField(blank=True, null=True, verbose_name="Vitamin D (µg)")),
                ("vitamin_e_mg", models.FloatField(blank=True, null=True, verbose_name="Vitamin E (mg)")),
                ("vitamin_k_ug", models.FloatField(blank=True, null=True, verbose_name="Vitamin K (µg)")),
                ("niacin_mg", models.FloatField(blank=True, null=True, verbose_name="Niacin (mg)")),
                ("folate_ug", models.FloatField(blank=True, null=True, verbose_name="Folat (µg)")),
                ("pantothenic_acid_mg", models.FloatField(blank=True, null=True, verbose_name="Pantothensäure (mg)")),
                ("biotin_ug", models.FloatField(blank=True, null=True, verbose_name="Biotin (µg)")),
                ("calcium_mg", models.FloatField(blank=True, null=True, verbose_name="Calcium (mg)")),
                ("iron_mg", models.FloatField(blank=True, null=True, verbose_name="Eisen (mg)")),
                ("magnesium_mg", models.FloatField(blank=True, null=True, verbose_name="Magnesium (mg)")),
                ("zinc_mg", models.FloatField(blank=True, null=True, verbose_name="Zink (mg)")),
                ("potassium_mg", models.FloatField(blank=True, null=True, verbose_name="Kalium (mg)")),
                ("phosphorus_mg", models.FloatField(blank=True, null=True, verbose_name="Phosphor (mg)")),
                ("iodine_ug", models.FloatField(blank=True, null=True, verbose_name="Jod (µg)")),
                ("selenium_ug", models.FloatField(blank=True, null=True, verbose_name="Selen (µg)")),
                ("copper_mg", models.FloatField(blank=True, null=True, verbose_name="Kupfer (mg)")),
                ("manganese_mg", models.FloatField(blank=True, null=True, verbose_name="Mangan (mg)")),
                ("chromium_ug", models.FloatField(blank=True, null=True, verbose_name="Chrom (µg)")),
                ("fluoride_mg", models.FloatField(blank=True, null=True, verbose_name="Fluorid (mg)")),
            ],
            options={
                "verbose_name": "DGE-Referenzwert",
                "verbose_name_plural": "DGE-Referenzwerte",
                "ordering": ["age_min", "gender"],
                "unique_together": {("age_min", "age_max", "gender")},
            },
        ),
    ]
