# Generated by Django 5.2.12 on 2026-07-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_remove_portion_is_system_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DgeReference',
        ),
    ]
