# Generated by Django 5.2.12 on 2026-05-26 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0005_enable_pg_trgm"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitConversion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="1 × Von-Einheit = factor × Zu-Einheit",
                        max_digits=10,
                        verbose_name="Umrechnungsfaktor",
                    ),
                ),
                (
                    "from_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions_from",
                        to="supply.measuringunit",
                        verbose_name="Von Einheit",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leer = generische Umrechnung",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_conversions",
                        to="supply.ingredient",
                        verbose_name="Zutat (optional)",
                    ),
                ),
                (
                    "to_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions_to",
                        to="supply.measuringunit",
                        verbose_name="Zu Einheit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einheiten-Umrechnung",
                "verbose_name_plural": "Einheiten-Umrechnungen",
                "ordering": ["from_unit__name", "to_unit__name"],
                "unique_together": {("from_unit", "to_unit", "ingredient")},
            },
        ),
    ]
