# Generated by Django 5.2.12 on 2026-09-15 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0006_cleanup_measuring_units"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortionRepairFinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "detection_reason",
                    models.CharField(
                        choices=[
                            ("piece_name_one_gram", "Stück-Name mit 1 g"),
                            ("piece_name_gram_unit", "Stück-Name mit Gramm-Einheit"),
                            ("one_gram_placeholder", "1-g-Platzhalter"),
                            ("missing_weight", "Fehlendes Gewicht"),
                            ("implausible_rank1", "Unplausibles rank-1-Gewicht"),
                        ],
                        max_length=40,
                        verbose_name="Erkennungsgrund",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "Kandidat"),
                            ("pending_review", "Prüffall"),
                            ("ready", "Bereit"),
                            ("applied", "Angewendet"),
                            ("rejected", "Abgelehnt"),
                            ("skipped", "Übersprungen"),
                        ],
                        default="candidate",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("before_snapshot", models.JSONField(default=dict, verbose_name="Vorher-Werte")),
                ("before_snapshot_hash", models.CharField(default="", max_length=64, verbose_name="Vorher-Werte-Hash")),
                (
                    "recipe_item_ids",
                    models.JSONField(
                        default=list,
                        help_text="RecipeItems, die die Portion zum Scan-Zeitpunkt referenzierten.",
                        verbose_name="RecipeItem-IDs",
                    ),
                ),
                ("ai_proposal", models.JSONField(default=dict, verbose_name="KI-Vorschlag")),
                ("confidence", models.FloatField(blank=True, null=True, verbose_name="Konfidenz")),
                ("prompt_version", models.CharField(default="1", max_length=20, verbose_name="Prompt-Version")),
                ("threshold", models.FloatField(blank=True, null=True, verbose_name="Schwellenwert")),
                ("ai_interaction_id", models.UUIDField(blank=True, null=True, verbose_name="KI-Interaktions-ID")),
                ("moved_recipe_item_ids", models.JSONField(default=list, verbose_name="Umgestellte RecipeItem-IDs")),
                ("affected_recipe_ids", models.JSONField(default=list, verbose_name="Betroffene Rezept-IDs")),
                ("applied_at", models.DateTimeField(blank=True, null=True, verbose_name="Angewendet am")),
                ("rejected_at", models.DateTimeField(blank=True, null=True, verbose_name="Abgelehnt am")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portion_repair_findings_applied",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Angewendet von",
                    ),
                ),
                (
                    "applied_portion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="supply.portion",
                        verbose_name="Korrigierte Portion",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portion_repair_findings",
                        to="supply.ingredient",
                        verbose_name="Zutat",
                    ),
                ),
                (
                    "portion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repair_findings",
                        to="supply.portion",
                        verbose_name="Portion",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portion_repair_findings_rejected",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Abgelehnt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portions-Reparatur-Befund",
                "verbose_name_plural": "Portions-Reparatur-Befunde",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["candidate", "pending_review", "ready"])),
                        fields=("portion",),
                        name="unique_open_portion_repair_finding",
                    )
                ],
            },
        ),
    ]
