from django.db import migrations
from django.utils.text import slugify


INGREDIENTS = {
    "Tomaten-Passata": "Konserven & Gläser",
    "Ingwer": "Gemüse",
    "Frischkäse": "Kühlung",
    "Spinat": "Gemüse",
    "Mozzarella": "Kühlung",
    "Tomatenmark": "Konserven & Gläser",
    "Frühlingszwiebeln": "Gemüse",
    "Parmesan": "Kühlung",
    "Lauch": "Gemüse",
    "Brokkoli": "Gemüse",
    "Champignons": "Gemüse",
    "Paprika (rot)": "Gemüse",
    "Paprika (gelb)": "Gemüse",
    "Paprika (grün)": "Gemüse",
    "Zucchini": "Gemüse",
    "Aubergine": "Gemüse",
    "Blumenkohl": "Gemüse",
    "Süßkartoffel": "Gemüse",
    "Kohlrabi": "Gemüse",
    "Fenchel": "Gemüse",
    "Sellerie (Knolle)": "Gemüse",
    "Rote Bete": "Gemüse",
    "Kürbis (Hokkaido)": "Gemüse",
    "Kürbis (Butternut)": "Gemüse",
    "Chinakohl": "Gemüse",
    "Pak Choi": "Gemüse",
    "Wirsing": "Gemüse",
    "Weißkohl": "Gemüse",
    "Rotkohl": "Gemüse",
    "Eisbergsalat": "Gemüse",
    "Feldsalat": "Gemüse",
    "Rucola": "Gemüse",
    "Babyspinat": "Gemüse",
    "Radieschen": "Gemüse",
    "Gurken": "Gemüse",
    "Kirschtomaten": "Gemüse",
    "Knoblauch": "Gemüse",
    "Zwiebel": "Gemüse",
    "Zwiebel (rot)": "Gemüse",
    "Schalotten": "Gemüse",
    "Karotte": "Gemüse",
    "Möhre": "Gemüse",
    "Pastinake": "Gemüse",
    "Schnittlauch": "Gemüse",
    "Basilikum (frisch)": "Gemüse",
    "Petersilie (frisch)": "Gemüse",
    "Rosmarin (frisch)": "Gemüse",
    "Thymian (frisch)": "Gemüse",
    "Dill (frisch)": "Gemüse",
    "Chili (frisch)": "Gemüse",
    "Kartoffel (Festkochend)": "Gemüse",
    "Kartoffel (Mehligkochend)": "Gemüse",
    "Spargel (grün)": "Gemüse",
    "Spargel (weiß)": "Gemüse",
    "Zuckerschoten": "Gemüse",
    "Maiskolben": "Gemüse",
    "Apfel": "Obst",
    "Banane": "Obst",
    "Birne": "Obst",
    "Orange": "Obst",
    "Zitrone": "Obst",
    "Limette": "Obst",
    "Mango": "Obst",
    "Ananas": "Obst",
    "Avocado": "Obst",
    "Erdbeeren": "Obst",
    "Himbeeren": "Obst",
    "Blaubeeren": "Obst",
    "Brombeeren": "Obst",
    "Kirschen": "Obst",
    "Trauben": "Obst",
    "Kiwi": "Obst",
    "Nektarine": "Obst",
    "Granatapfel": "Obst",
    "Grapefruit": "Obst",
    "Pflaumen": "Obst",
    "Hähnchenbrust": "Fleisch & Fisch",
    "Hähnchenschenkel": "Fleisch & Fisch",
    "Schweinefilet": "Fleisch & Fisch",
    "Schweinebauch": "Fleisch & Fisch",
    "Rinderhackfleisch": "Fleisch & Fisch",
    "Schweinehackfleisch": "Fleisch & Fisch",
    "Hackfleisch (gemischt)": "Fleisch & Fisch",
    "Lachsfilet (frisch)": "Fleisch & Fisch",
    "Räucherlachs": "Fleisch & Fisch",
    "Garnelen": "Fleisch & Fisch",
    "Thunfisch (Dose)": "Fleisch & Fisch",
    "Schinken": "Fleisch & Fisch",
    "Kochschinken": "Fleisch & Fisch",
    "Speck": "Fleisch & Fisch",
    "Chorizo": "Fleisch & Fisch",
    "Wiener Würstchen": "Fleisch & Fisch",
    "Bratwurst (frisch)": "Fleisch & Fisch",
    "Butter": "Kühlung",
    "Sahne": "Kühlung",
    "Schmand": "Kühlung",
    "Creme Fraiche": "Kühlung",
    "Joghurt": "Kühlung",
    "Griechischer Joghurt": "Kühlung",
    "Skyr": "Kühlung",
    "Quark (Magerquark)": "Milchprodukte & Käse",
    "Mascarpone": "Kühlung",
    "Ricotta": "Kühlung",
    "Feta": "Kühlung",
    "Gouda": "Kühlung",
    "Cheddar": "Kühlung",
    "Emmentaler": "Kühlung",
    "Halloumi": "Kühlung",
    "Hefe (frisch)": "Kühlung",
    "Tofu": "Kühlung",
    "Räuchertofu": "Kühlung",
    "Hafermilch": "Kühlung",
    "Buttermilch": "Kühlung",
    "Bacon": "Kühlung",
    "Salami": "Kühlung",
    "Mehl": "Brot & Backwaren",
    "Dinkelmehl": "Brot & Backwaren",
    "Backpulver": "Brot & Backwaren",
    "Hefe (trocken)": "Brot & Backwaren",
    "Zucker": "Brot & Backwaren",
    "Puderzucker": "Brot & Backwaren",
    "Vanillezucker": "Brot & Backwaren",
    "Speisestärke": "Brot & Backwaren",
    "Backkakao": "Brot & Backwaren",
    "Mandeln": "Brot & Backwaren",
    "Walnüsse": "Brot & Backwaren",
    "Haselnusskerne": "Brot & Backwaren",
    "Pinienkerne": "Brot & Backwaren",
    "Sonnenblumenkerne": "Brot & Backwaren",
    "Kürbiskerne": "Brot & Backwaren",
    "Sesam": "Brot & Backwaren",
    "Leinsamen": "Brot & Backwaren",
    "Chiasamen": "Brot & Backwaren",
    "Kokosraspeln": "Brot & Backwaren",
    "Rosinen": "Brot & Backwaren",
    "Schokolade (Zartbitter)": "Brot & Backwaren",
    "Schokolade (Vollmilch)": "Brot & Backwaren",
    "Brot": "Brot & Backwaren",
    "Brötchen": "Brot & Backwaren",
    "Wraps": "Brot & Backwaren",
    "Naan": "Brot & Backwaren",
    "Baguette": "Brot & Backwaren",
    "Burger Buns": "Brot & Backwaren",
    "Knäckebrot": "Brot & Backwaren",
    "Salz": "Gewürze & Kräuter",
    "Pfeffer": "Gewürze & Kräuter",
    "Paprikapulver edelsüß": "Gewürze & Kräuter",
    "Paprikapulver geräuchert": "Gewürze & Kräuter",
    "Currypulver": "Gewürze & Kräuter",
    "Kreuzkümmel": "Gewürze & Kräuter",
    "Kurkuma (Pulver)": "Gewürze & Kräuter",
    "Zimt": "Gewürze & Kräuter",
    "Muskatnuss": "Gewürze & Kräuter",
    "Oregano": "Gewürze & Kräuter",
    "Chilipulver": "Gewürze & Kräuter",
    "Chiliflocken": "Gewürze & Kräuter",
    "Knoblauchpulver": "Gewürze & Kräuter",
    "Zwiebelpulver": "Gewürze & Kräuter",
    "Ingwerpulver": "Gewürze & Kräuter",
    "Honig": "Gewürze & Kräuter",
    "Petersilie": "Gewürze & Kräuter",
    "Minze": "Gewürze & Kräuter",
    "Lorbeerblatt": "Gewürze & Kräuter",
    "Kardamom": "Gewürze & Kräuter",
    "Kümmel": "Gewürze & Kräuter",
    "Olivenöl": "Konserven & Gläser",
    "Rapsöl": "Konserven & Gläser",
    "Sonnenblumenöl": "Konserven & Gläser",
    "Passierte Tomaten": "Konserven & Gläser",
    "Tomaten (stückig, Dose)": "Konserven & Gläser",
    "Kidneybohnen": "Konserven & Gläser",
    "Kichererbsen (Dose)": "Konserven & Gläser",
    "Mais (Dose)": "Konserven & Gläser",
    "Kokosmilch (Dose)": "Konserven & Gläser",
    "Sojasauce": "Konserven & Gläser",
    "Senf": "Konserven & Gläser",
    "Ketchup": "Konserven & Gläser",
    "Balsamicoessig": "Konserven & Gläser",
    "Apfelessig": "Konserven & Gläser",
    "Ahornsirup": "Konserven & Gläser",
    "Erdnussbutter": "Konserven & Gläser",
    "Tahini": "Konserven & Gläser",
    "Sambal Oelek": "Konserven & Gläser",
    "Haferflocken": "Konserven & Gläser",
    "Reis": "Konserven & Gläser",
    "Nudeln": "Konserven & Gläser",
    "Couscous": "Konserven & Gläser",
    "Linsen (rot)": "Konserven & Gläser",
    "Eier": "Konserven & Gläser",
    "H-Milch": "Konserven & Gläser",
    "Oliven": "Konserven & Gläser",
    "Blätterteig": "Konserven & Gläser",
    "Quinoa": "Konserven & Gläser",
    "Bulgur": "Konserven & Gläser",
    "Reisnudeln": "Konserven & Gläser",
    "Glasnudeln": "Nudeln & Reis & Getreide",
    "Risottoreis": "Nudeln & Reis & Getreide",
    "Wasser": "Getränke",
    "Mineralwasser": "Getränke",
    "Orangensaft": "Getränke",
    "Zitronensaft": "Getränke",
    "Limettensaft": "Getränke",
    "Rotwein": "Getränke",
    "Weißwein": "Getränke",
    "Bier": "Getränke",
    "Worcestersauce": "Öle & Soßen",
    "Kokosöl": "Öle & Soßen",
    "Essig": "Öle & Soßen",
    "Balsamico-Creme": "Öle & Soßen",
    "Tiefkühlspinat": "Tiefkühl",
    "Erbsen (Tiefkühl)": "Tiefkühl",
}


def seed_ingredients(apps, schema_editor):
    Ingredient = apps.get_model("supply", "Ingredient")
    RetailSection = apps.get_model("supply", "RetailSection")

    section_cache = {}

    for name, category in INGREDIENTS.items():
        if category not in section_cache:
            section, _ = RetailSection.objects.get_or_create(name=category)
            section_cache[category] = section

        slug = slugify(name)
        Ingredient.objects.get_or_create(
            slug=slug,
            defaults={
                "name": name,
                "status": "verified",
                "retail_section": section_cache[category],
            },
        )


def reverse_seed(apps, schema_editor):
    Ingredient = apps.get_model("supply", "Ingredient")
    for name in INGREDIENTS:
        Ingredient.objects.filter(slug=slugify(name)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0007_seed_unit_conversions"),
    ]

    operations = [
        migrations.RunPython(seed_ingredients, reverse_seed),
    ]
