# Generated by Django 5.2.12 on 2026-09-15 21:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0007_portionrepairfinding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientPriceProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "proposed_price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Vorgeschlagener Preis pro kg (EUR)",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Konfidenz (0-1)",
                    ),
                ),
                ("rationale", models.TextField(blank=True, default="", verbose_name="Begründung")),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="gemini",
                        help_text="Herkunft des Vorschlags, z.B. 'gemini'",
                        max_length=50,
                        verbose_name="Quelle",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Ausstehend"), ("accepted", "Bestätigt"), ("rejected", "Abgelehnt")],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="Geprüft am")),
                (
                    "ai_interaction_id",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="KI-Interaktions-ID"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_proposals",
                        to="supply.ingredient",
                        verbose_name="Zutat",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_proposals_requested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Angefragt von",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_proposals_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geprüft von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preisvorschlag",
                "verbose_name_plural": "Preisvorschläge",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["ingredient", "status"], name="price_prop_ing_status_idx"),
                    models.Index(fields=["status", "-created_at"], name="price_prop_status_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("ingredient",),
                        name="unique_pending_price_proposal_per_ingredient",
                    )
                ],
            },
        ),
    ]
