# Generated by Django 5.2.12 on 2026-09-16 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0008_ingredientpriceproposal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientReplacementMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relation_kind",
                    models.CharField(
                        choices=[("generic_to_concrete", "Generisch → Konkret")],
                        default="generic_to_concrete",
                        max_length=32,
                        verbose_name="Beziehungsart",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inaktive Zuordnungen werden von der KI-Filterung ignoriert",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="z.B. 'seed:reviewed' oder 'seed:generic_terms'",
                        max_length=255,
                        verbose_name="Herkunft",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingredient_replacement_mappings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replacement_ingredient",
                    models.ForeignKey(
                        help_text="Konkrete Zutat, die stattdessen verwendet wird (z.B. 'Jodsalz')",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacement_mappings_as_replacement",
                        to="supply.ingredient",
                        verbose_name="Ersatz-Zutat",
                    ),
                ),
                (
                    "source_ingredient",
                    models.ForeignKey(
                        help_text="Generische Zutat, die ersetzt werden soll (z.B. 'Salz')",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacement_mappings_as_source",
                        to="supply.ingredient",
                        verbose_name="Quell-Zutat",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingredient_replacement_mappings_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zutaten-Ersatz-Zuordnung",
                "verbose_name_plural": "Zutaten-Ersatz-Zuordnungen",
                "ordering": ["source_ingredient__name", "replacement_ingredient__name"],
                "indexes": [
                    models.Index(fields=["replacement_ingredient", "is_active"], name="replacement_target_active_idx"),
                    models.Index(fields=["source_ingredient", "is_active"], name="replacement_source_active_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_ingredient", "replacement_ingredient"),
                        name="unique_ingredient_replacement_mapping",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_ingredient", models.F("replacement_ingredient")), _negated=True),
                        name="replacement_mapping_source_ne_replacement",
                    ),
                ],
            },
        ),
    ]
