# Generated by Django 5.2.12 on 2026-05-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0009_seed_portions_and_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="nan_art_id_rewe",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="REWE Artikelnummer"),
        ),
    ]
