# Generated by Django 5.2.12 on 2026-09-16 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0010_seed_ingredient_replacement_mappings"),
    ]

    operations = [
        migrations.AddField(
            model_name="portion",
            name="weight_confidence",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Gewichts-Konfidenz (0-1)",
            ),
        ),
        migrations.AddField(
            model_name="portion",
            name="weight_confirmed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Gewicht bestätigt am"),
        ),
        migrations.AddField(
            model_name="portion",
            name="weight_source",
            field=models.CharField(
                blank=True,
                choices=[("system", "System"), ("manual", "Manuell"), ("ai", "KI"), ("import", "Import")],
                max_length=20,
                null=True,
                verbose_name="Gewichtsquelle",
            ),
        ),
        migrations.AddField(
            model_name="portion",
            name="weight_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unknown", "Unbekannt"),
                    ("ai_proposed", "KI-Vorschlag"),
                    ("confirmed", "Bestätigt"),
                    ("imported", "Importiert"),
                ],
                help_text="confirmed/imported gelten als vertrauenswürdige Berechnungsbasis.",
                max_length=20,
                null=True,
                verbose_name="Gewichtsstatus",
            ),
        ),
    ]
