# Generated by Django 5.2.12 on 2026-05-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0010_add_nan_art_id_rewe"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="is_standalone_food",
            field=models.BooleanField(
                default=False,
                help_text="Kann roh/direkt gegessen werden (z.B. Obst, Getränke, Süßigkeiten)",
                verbose_name="Eigenständig konsumierbar",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="standalone_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("breakfast", "Frühstück"),
                    ("warm_meal", "Warme Mahlzeit"),
                    ("cold_meal", "Kalte Mahlzeit"),
                    ("dessert", "Nachtisch"),
                    ("side_dish", "Beilage"),
                    ("snack", "Snack"),
                    ("drink", "Getränk"),
                    ("simple_meal", "Einfache Mahlzeit"),
                ],
                help_text="Mahlzeittyp wenn eigenständig konsumiert",
                max_length=20,
                null=True,
                verbose_name="Standalone-Typ",
            ),
        ),
    ]
