# Generated by Django 5.2.12 on 2026-05-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0013_remove_material_quantity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="portion",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
