# Generated by Django 5.2.12 on 2026-09-19 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0014_rename_generic_portion_to_piece"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="portionrepairfinding",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Freigegeben am"),
        ),
        migrations.AddField(
            model_name="portionrepairfinding",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portion_repair_findings_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Freigegeben von",
            ),
        ),
    ]
