# Generated by Django 5.2.12 on 2026-09-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0015_portionrepairfinding_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="ai_review_notes",
            field=models.JSONField(blank=True, default=dict, verbose_name="KI-Prüfnotizen"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="ai_review_verdict",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ok", "Plausibel"),
                    ("corrected", "Korrigiert"),
                    ("rename", "Umbenennen"),
                    ("duplicate", "Duplikat"),
                    ("not_an_ingredient", "Keine Zutat"),
                ],
                default="",
                max_length=20,
                verbose_name="KI-Prüfergebnis",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="ai_reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="KI-geprüft am"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="retail_section_source",
            field=models.CharField(
                blank=True,
                choices=[("rule", "Regel"), ("ai", "KI"), ("manual", "Manuell")],
                default="",
                help_text="Manuell gesetzte Warengruppen werden von Regeln und KI nicht überschrieben.",
                max_length=10,
                verbose_name="Herkunft der Warengruppe",
            ),
        ),
    ]
