# Generated by Django 5.2.12 on 2026-05-29 06:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0015_fix_portions_create_base"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portion",
            name="measuring_unit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="supply.measuringunit",
                verbose_name="Maßeinheit",
            ),
        ),
        migrations.AlterField(
            model_name="portion",
            name="name",
            field=models.CharField(blank=True, default="g", max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="portion",
            name="weight_g",
            field=models.FloatField(
                default=1,
                help_text="Automatisch berechnet. Gewicht einer Portion in Gramm.",
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Gewicht (g)",
            ),
        ),
    ]
