# Generated by Django 5.2.12 on 2026-09-25 20:20

from django.conf import settings
from django.db import migrations, models


def normalize_ingredient_status(apps, schema_editor):
    """Map every legacy status (approved, user_content, …) to draft; verified stays."""
    Ingredient = apps.get_model("supply", "Ingredient")
    Ingredient.objects.exclude(status="verified").exclude(status="draft").update(status="draft")


def revert_public_visibility(apps, schema_editor):
    """Reverse step: public is unknown before this migration, fall back to private."""
    Ingredient = apps.get_model("supply", "Ingredient")
    Ingredient.objects.filter(visibility="public").update(visibility="private")


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0014_aiinteraction_structured_retry"),
        ("profiles", "0002_initial"),
        ("supply", "0015_portionrepairfinding_approved_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="status",
            field=models.CharField(
                choices=[("draft", "Entwurf"), ("verified", "Verifiziert")],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Privat"), ("shared", "Geteilt"), ("public", "Öffentlich")],
                default="private",
                help_text="Privat: nur für Owner + dessen Gruppe sichtbar. Geteilt: mit selected_groups. Öffentlich: nur über Verifizierung erreichbar.",
                max_length=20,
                verbose_name="Sichtbarkeit",
            ),
        ),
        migrations.RunPython(normalize_ingredient_status, revert_public_visibility),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "verified"])), name="ingredient_status_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("visibility", "public"), _negated=True), ("status", "verified"), _connector="OR"
                ),
                name="ingredient_public_requires_verified",
            ),
        ),
    ]
