# Generated by Django 5.2.12 on 2026-05-29 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0016_portion_fields_mandatory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portion",
            name="measuring_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="supply.measuringunit", verbose_name="Maßeinheit"
            ),
        ),
    ]
