# Generated by Django 5.2.12 on 2026-09-25 20:55

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def rename_colliding_superseded_portions_on_reverse(apps, schema_editor):
    """Reverse step only: before dropping ``superseded_by``, the old unique-name
    constraint (``deleted_at IS NULL`` only, no ``superseded_by`` exception) would
    reject a still-active superseded portion that shares its name with its own
    successor. Rename those to "{name} (alt)" so the reverse migration can apply
    the old constraint without failing.
    """
    from collections import Counter

    Portion = apps.get_model("supply", "Portion")
    active = Portion.objects.filter(deleted_at__isnull=True)
    name_counts = Counter(
        (portion.ingredient_id, portion.name.lower()) for portion in active.only("ingredient_id", "name")
    )
    for portion in active.filter(superseded_by__isnull=False).only("id", "name", "ingredient_id"):
        key = (portion.ingredient_id, portion.name.lower())
        if name_counts[key] > 1:
            Portion.objects.filter(pk=portion.pk).update(name=f"{portion.name} (alt)")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0016_ingredient_status_visibility_unification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="portion",
            name="unique_portion_name_per_ingredient",
        ),
        migrations.RemoveConstraint(
            model_name="portion",
            name="unique_rank1_portion_per_ingredient",
        ),
        migrations.AddField(
            model_name="portion",
            name="superseded_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Abgelöst am"),
        ),
        migrations.AddField(
            model_name="portion",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Gesetzt, wenn eine Gewichtsänderung diese referenzierte Portion nicht in place ändern durfte: verweist auf die neue Portion. Bestehende RecipeItems behalten diese Portion unverändert; sie erscheint aber nirgends mehr zur Auswahl.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="superseded_versions",
                to="supply.portion",
                verbose_name="Abgelöst durch",
            ),
        ),
        migrations.RunPython(noop, rename_colliding_superseded_portions_on_reverse),
        migrations.AddConstraint(
            model_name="portion",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("ingredient_id"),
                condition=models.Q(("deleted_at__isnull", True), ("superseded_by__isnull", True)),
                name="unique_portion_name_per_ingredient",
            ),
        ),
        migrations.AddConstraint(
            model_name="portion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("rank", 1), ("superseded_by__isnull", True)),
                fields=("ingredient",),
                name="unique_rank1_portion_per_ingredient",
            ),
        ),
    ]
