# Generated by Django 5.2.12 on 2026-09-26 14:11

"""Unique names for system ingredients.

Existing exact duplicates (same name, case/whitespace-insensitive, no owner)
are merged first so the constraint can be created on any database. The merge
uses the live service because it must move portions, recipe items, meal items
and aliases; it only runs when duplicates exist (never on fresh databases).
"""

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def merge_existing_duplicates(apps, schema_editor):
    Ingredient = apps.get_model("supply", "Ingredient")
    seen: dict[str, int] = {}
    has_duplicates = False
    for ingredient_id, name in Ingredient.objects.filter(deleted_at__isnull=True, owner__isnull=True).values_list(
        "id", "name"
    ):
        key = " ".join((name or "").lower().split())
        if key in seen:
            has_duplicates = True
            break
        seen[key] = ingredient_id
    if not has_duplicates:
        return

    from supply.models import Ingredient as LiveIngredient
    from supply.services.ingredient_merge import _merge_target_rank, merge_ingredient

    groups: dict[str, list] = {}
    for ingredient in LiveIngredient.objects.filter(owner__isnull=True):
        groups.setdefault(" ".join(ingredient.name.lower().split()), []).append(ingredient)
    for group in groups.values():
        if len(group) < 2:
            continue
        group.sort(key=_merge_target_rank)
        for duplicate in group[1:]:
            merge_ingredient(duplicate, group[0])


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0014_aiinteraction_structured_retry"),
        ("profiles", "0002_initial"),
        ("supply", "0017_retail_sections_v2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(merge_existing_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("deleted_at__isnull", True), ("owner__isnull", True)),
                name="uniq_system_ingredient_name",
            ),
        ),
    ]
