# Generated by Django 5.2.12 on 2026-09-27 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0017_portion_superseded_versions"),
        ("supply", "0018_unique_system_ingredient_name"),
    ]

    operations = []
