# Generated by Django 5.2.12 on 2026-09-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0019_merge_portion_versions_and_data_quality"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="viscosity_source",
            field=models.CharField(
                blank=True,
                choices=[("ai", "KI"), ("manual", "Manuell")],
                default="",
                help_text="Manuell gepflegte Werte werden von KI-Vorschlägen nicht überschrieben.",
                max_length=10,
                verbose_name="Herkunft von Aggregatzustand und Dichte",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="physical_viscosity",
            field=models.CharField(
                choices=[("solid", "Essen"), ("beverage", "Getränk"), ("liquid", "Flüssig")],
                default="solid",
                max_length=10,
                verbose_name="Aggregatzustand",
            ),
        ),
    ]
