# Generated by Django 5.2.12 on 2026-09-28 20:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0020_viscosity_liquid_and_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientPackageSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("package_name", models.CharField(max_length=255, verbose_name="Packungsname")),
                (
                    "weight_g",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.01)], verbose_name="Gewicht (g)"
                    ),
                ),
                (
                    "volume_ml",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Volumen (ml)",
                    ),
                ),
                (
                    "physical_viscosity",
                    models.CharField(
                        choices=[("solid", "Essen"), ("beverage", "Getränk"), ("liquid", "Flüssig")],
                        default="solid",
                        max_length=10,
                        verbose_name="Aggregatzustand",
                    ),
                ),
                (
                    "physical_density",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Dichte (g/ml)",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Konfidenz (0-1)",
                    ),
                ),
                ("reason", models.TextField(blank=True, default="", verbose_name="Begründung")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Offen"), ("accepted", "Übernommen"), ("rejected", "Verworfen")],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("model", models.CharField(blank=True, default="", max_length=100, verbose_name="KI-Modell")),
                (
                    "prompt_version",
                    models.CharField(blank=True, default="", max_length=30, verbose_name="Prompt-Version"),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True, verbose_name="Entschieden am")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="package_suggestions_decided",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entschieden von",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_suggestions",
                        to="supply.ingredient",
                        verbose_name="Zutat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Packungsvorschlag",
                "verbose_name_plural": "Packungsvorschläge",
                "ordering": ["-confidence", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("ingredient",),
                        name="unique_pending_package_suggestion_per_ingredient",
                    )
                ],
            },
        ),
    ]
