# Generated by Django 5.2.12 on 2026-10-03 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0021_ingredient_package_suggestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BuffetDataProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("add", "Rolle hinzufügen"),
                            ("untag", "Rolle entfernen"),
                            ("merge_into", "Zusammenführen"),
                            ("create", "Neu anlegen"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_kind", models.CharField(choices=[("ingredient", "Zutat"), ("recipe", "Rezept")], max_length=12)),
                ("source_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("source_expected_name", models.CharField(blank=True, default="", max_length=255)),
                ("target_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("target_expected_name", models.CharField(blank=True, default="", max_length=255)),
                ("role_slugs", models.JSONField(blank=True, default=list)),
                ("proposed_data", models.JSONField(blank=True, default=dict)),
                (
                    "origin",
                    models.CharField(
                        choices=[("manual", "Manuell"), ("ai", "KI"), ("mixed", "KI und manuell")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("ai_confidence", models.FloatField(blank=True, null=True)),
                ("rationale", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Ausstehend"), ("approved", "Freigegeben"), ("rejected", "Abgelehnt")],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True, default="")),
                ("preview_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("previewed_at", models.DateTimeField(blank=True, null=True)),
                ("preview_result", models.JSONField(blank=True, default=dict)),
                ("audit_log", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buffet_data_proposals_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buffet_data_proposals_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-updated_at", "id"],
                "indexes": [
                    models.Index(fields=["status", "updated_at"], name="buffet_prop_status_updated_idx"),
                    models.Index(fields=["action", "item_kind"], name="buffet_prop_action_kind_idx"),
                ],
            },
        ),
    ]
