# Generated by Django 5.2.12 on 2026-06-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0024_fix_portion_data_integrity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portion",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
    ]
