# Generated by Django 5.2.12 on 2026-06-04 15:56

from django.db import migrations


def ensure_default_portions(apps, schema_editor):
    MeasuringUnit = apps.get_model("supply", "MeasuringUnit")
    Ingredient = apps.get_model("supply", "Ingredient")
    Portion = apps.get_model("supply", "Portion")

    # Get or create base measuring units (g and ml)
    g_unit, _ = MeasuringUnit.objects.get_or_create(name="g", unit="g", quantity=1.0, defaults={"description": "Gramm"})
    ml_unit, _ = MeasuringUnit.objects.get_or_create(
        name="ml", unit="ml", quantity=1.0, defaults={"description": "Milliliter"}
    )

    # Find ingredients without any default portion
    ingredients_without_default = Ingredient.objects.exclude(
        portions__is_default=True,
        portions__deleted_at__isnull=True,
    ).distinct()

    portions_to_create = []
    for ingredient in ingredients_without_default:
        existing_base = Portion.objects.filter(
            ingredient=ingredient,
            name__in=["g", "ml", "Stück", "Gramm", "Milliliter"],
            deleted_at__isnull=True,
        ).first()

        if existing_base:
            existing_base.is_default = True
            existing_base.save(update_fields=["is_default"])
        else:
            if ingredient.physical_viscosity == "beverage":
                name = "ml"
                mu = ml_unit
                weight_g = ingredient.physical_density or 1.0
            else:
                name = "Stück"
                mu = g_unit
                weight_g = 1.0

            portions_to_create.append(
                Portion(
                    name=name,
                    measuring_unit=mu,
                    ingredient=ingredient,
                    quantity=1.0,
                    weight_g=weight_g,
                    is_default=True,
                    rank=1,
                    priority=0,
                )
            )

    if portions_to_create:
        Portion.objects.bulk_create(portions_to_create)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0025_alter_portion_name"),
    ]

    operations = [
        migrations.RunPython(ensure_default_portions, reverse),
    ]
