# Generated by Django 5.2.12 on 2026-06-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0026_ensure_default_portions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="standalone_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("breakfast", "Frühstück"),
                    ("warm_meal", "Warme Mahlzeit"),
                    ("cold_meal", "Kalte Mahlzeit"),
                    ("dessert", "Nachtisch"),
                    ("side_dish", "Beilage"),
                    ("drink", "Getränk"),
                    ("simple_meal", "Einfache Mahlzeit"),
                ],
                help_text="Mahlzeittyp wenn eigenständig konsumiert",
                max_length=20,
                null=True,
                verbose_name="Standalone-Typ",
            ),
        ),
    ]
