# Generated by Django 5.2.12 on 2026-06-07 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0028_remove_dgereference_energy_kj_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="camp_suitable",
            field=models.BooleanField(
                default=False,
                help_text="Fürs Zeltlager geeignet (haltbar, leicht, kein Kühlschrank)",
                verbose_name="Camp-geeignet",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="cooking_factor",
            field=models.FloatField(
                blank=True,
                default=1.0,
                help_text="Multiplikator Roh→Gekocht, z.B. 2.5 für Nudeln (aus 100g → 250g)",
                null=True,
                verbose_name="Kochfaktor",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="preparation_time_min",
            field=models.IntegerField(blank=True, null=True, verbose_name="Zubereitungsdauer (Minuten)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="season_end",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)],
                verbose_name="Saisonende (Monat 1-12)",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="season_start",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)],
                verbose_name="Saisonbeginn (Monat 1-12)",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="storage_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dry", "Trocken"),
                    ("refrigerated", "Kühlschrank"),
                    ("frozen", "Gefroren"),
                    ("ambient", "Raumtemperatur"),
                ],
                max_length=20,
                null=True,
                verbose_name="Lagerungsart",
            ),
        ),
    ]
