# Generated by Django 5.2.12 on 2026-06-07 19:40

import django.contrib.postgres.search
import django.core.validators
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0029_ingredient_camp_suitable_ingredient_cooking_factor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="embedding_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="quality_score",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name="Datenqualität (0-100)",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="quality_score_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
