# Generated by Django 5.2.12 on 2026-06-19 06:47

from django.db import migrations, models


def migrate_ingredient_status_forward(apps, schema_editor):
    Ingredient = apps.get_model("supply", "Ingredient")
    Ingredient.objects.filter(status="user_content").update(status="draft")


def migrate_ingredient_status_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0030_ingredient_embedding_ingredient_embedding_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(migrate_ingredient_status_forward, migrate_ingredient_status_reverse),
        migrations.AlterField(
            model_name="ingredient",
            name="status",
            field=models.CharField(
                choices=[("draft", "Entwurf"), ("verified", "Verifiziert")],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
