# Generated by Django 5.2.12 on 2026-06-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0031_material_is_deleted_alter_ingredient_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="usage_count",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text="Wie oft diese Zutat in Rezepten verwendet wird (denormalisiert)",
                verbose_name="Verwendungsanzahl",
            ),
        ),
    ]
