# Generated by Django 5.2.12 on 2026-06-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0032_add_ingredient_usage_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="physical_viscosity",
            new_name="food_category",
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="food_category",
            field=models.CharField(
                choices=[("solid", "Essen"), ("beverage", "Getränk")],
                default="solid",
                max_length=10,
                verbose_name="Lebensmittelkategorie",
            ),
        ),
    ]
