# Generated by Django 5.2.12 on 2026-06-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0033_rename_food_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="food_category",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="usage_count",
        ),
        migrations.RemoveField(
            model_name="material",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="physical_viscosity",
            field=models.CharField(
                choices=[("solid", "Essen"), ("beverage", "Getränk")],
                default="solid",
                max_length=10,
                verbose_name="Aggregatzustand",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="status",
            field=models.CharField(
                choices=[("draft", "Entwurf"), ("verified", "Verifiziert"), ("user_content", "Benutzer erstellt")],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
