# Generated by Django 5.2.12 on 2026-06-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0034_remove_ingredient_food_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='standalone_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Frühstück'), ('warm_meal', 'Warme Mahlzeit'), ('cold_meal', 'Kalte Mahlzeit'), ('dessert', 'Nachtisch'), ('recipe_part', 'Rezeptteil'), ('drink', 'Getränk'), ('snack', 'Snack'), ('ingredient', 'Zutat')], help_text='Mahlzeittyp wenn eigenständig konsumiert', max_length=20, null=True, verbose_name='Standalone-Typ'),
        ),
    ]
