# Generated by Django 5.2.12 on 2026-06-24 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0037_remove_ingredient_recipe_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="standalone_type",
        ),
    ]
