# Generated by Django 5.2.12 on 2026-06-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0038_remove_ingredient_standalone_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="portion",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Von der App erstellte Standardportionen (g, Packung, Stück) – nicht löschbar",
                verbose_name="System-Portion",
            ),
        ),
    ]
