# Generated by Django 5.2.12 on 2026-06-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_hnsw_indexes"),
        ("supply", "0040_seed_system_portions"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="ingredients", to="content.tag", verbose_name="Tags"),
        ),
    ]
