# Generated by Django 5.2.12 on 2026-06-29 10:16

from django.db import migrations


def reassign_portion_ranks(apps, schema_editor):
    """
    Reassign portion ranks according to the new system:
    1. Portion with is_default=True → rank=1
    2. All other portions → rank=2,3,... sorted by (priority desc, rank asc)
    3. Portion with name='g' → rank=9999
    """
    Portion = apps.get_model('supply', 'Portion')
    Ingredient = apps.get_model('supply', 'Ingredient')
    
    for ingredient in Ingredient.objects.all():
        portions = list(Portion.objects.filter(ingredient=ingredient, deleted_at__isnull=True).order_by('-priority', 'rank'))
        
        if not portions:
            continue
        
        # Find the is_default portion (should be at most 1 due to data quality check)
        default_portion = None
        other_portions = []
        
        for portion in portions:
            if portion.is_default:
                default_portion = portion
            else:
                other_portions.append(portion)
        
        # Assign ranks
        new_rank = 1
        
        if default_portion:
            default_portion.rank = new_rank
            default_portion.save(update_fields=['rank'])
            new_rank += 1
        
        # Assign ranks to other portions (excluding 'g' which gets 9999 later)
        for portion in other_portions:
            if portion.name == 'g':
                portion.rank = 9999
            else:
                portion.rank = new_rank
                new_rank += 1
            portion.save(update_fields=['rank'])


def reverse_reassign_portion_ranks(apps, schema_editor):
    """Reverse the rank reassignment - keep original behavior."""
    # This is a data migration, so we can't really reverse it perfectly
    # Just restore some sensible defaults
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0042_migrate_breakfast_tags'),
    ]

    operations = [
        migrations.RunPython(reassign_portion_ranks, reverse_reassign_portion_ranks),
    ]
