# Generated by Django 5.2.12 on 2026-06-29 10:16

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def deduplicate_portions(apps, schema_editor):
    Portion = apps.get_model("supply", "Portion")
    from django.db.models import Count, Min

    dupes = (
        Portion.objects.filter(deleted_at__isnull=True)
        .annotate(name_lower=django.db.models.functions.text.Lower("name"))
        .values("name_lower", "ingredient_id")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
    )
    for dupe in dupes:
        ids = Portion.objects.filter(
            deleted_at__isnull=True,
            ingredient_id=dupe["ingredient_id"],
        ).annotate(
            name_lower=django.db.models.functions.text.Lower("name"),
        ).filter(
            name_lower=dupe["name_lower"],
        ).order_by("id").values_list("id", flat=True)

        keep_id = ids.first()
        delete_ids = list(ids[1:])
        Portion.objects.filter(id__in=delete_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0043_reassign_portion_ranks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portion',
            options={'ordering': ['rank'], 'verbose_name': 'Portion', 'verbose_name_plural': 'Portionen'},
        ),
        migrations.RemoveField(
            model_name='portion',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='portion',
            name='priority',
        ),
        migrations.AlterField(
            model_name='portion',
            name='rank',
            field=models.IntegerField(default=1, verbose_name='Rang (1 = Normalportion)'),
        ),
        migrations.RunPython(
            deduplicate_portions,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='portion',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('ingredient_id'), condition=models.Q(('deleted_at__isnull', True)), name='unique_portion_name_per_ingredient'),
        ),
    ]
