# Generated by Django 5.2.12 on 2026-06-30 11:48

from django.db import migrations


def migrate_stueck_packung_to_piece(apps, schema_editor):
    """Bestehende 'Stück'- und 'Packung'-Einheiten von MASS ('g') auf PIECE ('stk') umstellen."""
    MeasuringUnit = apps.get_model("supply", "MeasuringUnit")
    # Alle Einheiten mit Stück-/Packung-Namen (case-insensitive) auf PIECE setzen
    updated = MeasuringUnit.objects.filter(
        name__in=["Stück", "Packung", "stück", "packung", "STÜCK", "PACKUNG"]
    ).update(unit="stk")
    # Breiter gefasst: auch Einheiten die 'stück' oder 'packung' im Namen haben (z.B. 'Stück (150g)')
    # Diese werden nur aktualisiert wenn sie noch auf 'g' stehen (MASS)
    MeasuringUnit.objects.filter(
        name__icontains="stück",
        unit="g",
    ).update(unit="stk")
    MeasuringUnit.objects.filter(
        name__icontains="packung",
        unit="g",
    ).update(unit="stk")


def reverse_stueck_packung_to_mass(apps, schema_editor):
    """Rollback: PIECE-Einheiten mit Stück-/Packung-Namen zurück auf MASS setzen."""
    MeasuringUnit = apps.get_model("supply", "MeasuringUnit")
    MeasuringUnit.objects.filter(
        name__icontains="stück",
        unit="stk",
    ).update(unit="g")
    MeasuringUnit.objects.filter(
        name__icontains="packung",
        unit="stk",
    ).update(unit="g")


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0045_add_piece_unit_type"),
    ]

    operations = [
        migrations.RunPython(
            migrate_stueck_packung_to_piece,
            reverse_stueck_packung_to_mass,
        ),
    ]
