# Generated by Django 5.2.12 on 2026-07-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0046_migrate_stueck_packung_to_piece"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Zutaten-Gruppe",
                "verbose_name_plural": "Zutaten-Gruppen",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="ingredient",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="ingredients", to="supply.ingredientgroup", verbose_name="Zutaten-Gruppen"
            ),
        ),
    ]
