# Generated by Django 5.2.12 on 2026-07-04 23:00

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def mark_duplicate_aliases_as_generic(apps, schema_editor):
    """Resolve pre-existing cross-ingredient alias name duplicates.

    Before this migration, `IngredientAlias.name` was only unique per ingredient,
    so the same name could already exist on multiple ingredients (e.g. "Nudeln").
    The new partial unique constraint requires non-generic alias names to be
    globally unique, so any existing duplicate is auto-promoted to generic
    (keeping the first occurrence as-is) to avoid a migration failure.
    """
    IngredientAlias = apps.get_model("supply", "IngredientAlias")
    from django.db.models import Count
    from django.db.models.functions import Lower

    duplicate_names = (
        IngredientAlias.objects.annotate(lower_name=Lower("name"))
        .values("lower_name")
        .annotate(count=Count("ingredient", distinct=True))
        .filter(count__gt=1)
        .values_list("lower_name", flat=True)
    )

    for lower_name in duplicate_names:
        aliases = list(
            IngredientAlias.objects.annotate(lower_name=Lower("name")).filter(lower_name=lower_name).order_by("id")
        )
        # Keep the first occurrence untouched; mark the rest as generic.
        for alias in aliases[1:]:
            alias.is_generic = True
            alias.save(update_fields=["is_generic"])


def noop_reverse(apps, schema_editor):
    """No-op reverse — data cleanup is not reversible."""


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0047_ingredientgroup_ingredient_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredientalias",
            name="is_generic",
            field=models.BooleanField(
                default=False,
                help_text="Generische Aliase (z.B. 'Salz', 'Pfeffer', 'Nudeln') dürfen an mehreren Zutaten hängen und unterliegen keiner Namens-Eindeutigkeit.",
                verbose_name="Generisch",
            ),
        ),
        migrations.RunPython(mark_duplicate_aliases_as_generic, noop_reverse),
        migrations.AddConstraint(
            model_name="ingredientalias",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("is_generic", False)),
                name="unique_alias_name_when_not_generic",
            ),
        ),
    ]
