# Generated by Django 5.2.12 on 2026-07-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0048_ingredientalias_is_generic"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ingredientalias",
            name="unique_alias_name_per_ingredient",
        ),
    ]
