# Generated by Django 5.2.12 on 2026-07-05 15:58

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0049_remove_ingredientalias_unique_alias_name_per_ingredient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingredientalias",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("ingredient"),
                name="unique_alias_name_per_ingredient",
            ),
        ),
    ]
