# Generated by Django 5.2.12 on 2026-07-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0050_ingredientalias_unique_alias_name_per_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='embedding_text_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the simplified embedding text (name+description+retail_section). Used to detect changes.', max_length=64, null=True),
        ),
    ]
