# Generated by Django 5.2.12 on 2026-07-07 23:08

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0053_alter_ingredient_embedding_to_384"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
