# Generated by Django 5.2.12 on 2026-07-08 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0054_alter_ingredient_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientSeason",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ],
                        help_text="Monat (1-12) in dem die Zutat Saison hat",
                        verbose_name="Monat",
                    ),
                ),
                (
                    "is_high_season",
                    models.BooleanField(
                        default=True, help_text="True = Haupterntezeit, False = Nebensaison", verbose_name="Hauptsaison"
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="supply.ingredient",
                        verbose_name="Zutat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zutaten-Saison",
                "verbose_name_plural": "Zutaten-Saisons",
                "ordering": ["ingredient", "month"],
                "unique_together": {("ingredient", "month")},
            },
        ),
    ]
