# Generated by Django 5.2.12 on 2026-07-11 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_populate_user_roles"),
        ("supply", "0058_seed_breakfast_extras"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ingredient",
            name="supply_ingr_visib_owner_idx",
        ),
        migrations.RemoveIndex(
            model_name="ingredient",
            name="supply_ingr_status_idx",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="usage_count",
            field=models.IntegerField(default=0, verbose_name="Verwendungshäufigkeit"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = System-Zutat, gesetzt = Nutzer-Zutat",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingredients_owned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Besitzer",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="shared_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Gruppen, mit denen diese Zutat geteilt wird (relevante wenn visibility=shared)",
                related_name="shared_ingredients",
                to="profiles.usergroup",
                verbose_name="Geteilte Gruppen",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Privat"), ("shared", "Geteilt")],
                default="private",
                help_text="Privat: nur für Owner + dessen Gruppe sichtbar. Geteilt: mit selected_groups",
                max_length=20,
                verbose_name="Sichtbarkeit",
            ),
        ),
    ]
