# Generated by Django 5.2.12 on 2026-07-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0059_usage_count"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE supply_ingredient si SET usage_count = (
                    SELECT COUNT(*) FROM recipe_recipeitem ri
                    JOIN supply_portion sp ON ri.portion_id = sp.id
                    WHERE sp.ingredient_id = si.id
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
