# Generated by Django 5.2.12 on 2026-07-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0060_populate_usage_count"),
    ]

    operations = [
        # Recreate the embedding column with 768 dimensions
        # The existing 384-dim embeddings will be discarded and regenerated via signals
        migrations.RunSQL(
            sql="""
            ALTER TABLE supply_ingredient
            DROP COLUMN embedding;
            
            ALTER TABLE supply_ingredient
            ADD COLUMN embedding vector(768);
            """,
            reverse_sql="""
            ALTER TABLE supply_ingredient
            DROP COLUMN embedding;
            
            ALTER TABLE supply_ingredient
            ADD COLUMN embedding vector(384);
            """,
        ),
    ]
