# Generated by Django 5.2.12 on 2026-07-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0063_seed_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionaltag',
            name='name',
            field=models.CharField(help_text="z.B. 'Vegan', 'Eiallergie', 'Laktoseunverträglichkeit'", max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='nutritionaltag',
            name='name_opposite',
            field=models.CharField(blank=True, default='', help_text="z.B. 'Tierische Produkte', 'Ei und Eierzeugnisse', 'Laktose'", max_length=255, verbose_name='Gegenbezeichnung'),
        ),
    ]
