# Generated by Django 5.2.12 on 2026-07-13 20:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scout_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Pfadfindername')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nachname')),
                ('gender', models.CharField(choices=[('male', 'Männlich'), ('female', 'Weiblich'), ('diverse', 'Divers'), ('no_answer', 'Keine Angabe')], default='no_answer', max_length=20, verbose_name='Geschlecht')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Geburtstag')),
                ('about_me', models.TextField(blank=True, default='', max_length=500, verbose_name='Über mich')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profilbild')),
                ('is_public', models.BooleanField(default=False, help_text='Wenn aktiv, kann das Profil von allen Nutzern gefunden werden', verbose_name='Öffentlich sichtbar')),
                ('slug', models.SlugField(blank=True, help_text='Human-readable Identifier für die Profil-URL', null=True, unique=True, verbose_name='Slug')),
                ('role', models.CharField(choices=[('user', 'Benutzer'), ('staff', 'Mitarbeiter'), ('admin', 'Administrator')], default='user', max_length=20, verbose_name='Rolle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Benutzerprofil',
                'verbose_name_plural': 'Benutzerprofile',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Gruppenname')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Sichtbar')),
                ('free_to_join', models.BooleanField(default=False, help_text='Wenn aktiv, können Benutzer ohne Einladung beitreten', verbose_name='Frei beitreten')),
                ('join_code', models.CharField(blank=True, default='', help_text='Optionaler Code zum Beitreten der Gruppe', max_length=20, verbose_name='Beitrittscode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Gelöscht')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Löschdatum')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='profiles.usergroup', verbose_name='Übergruppe')),
            ],
            options={
                'verbose_name': 'Benutzergruppe',
                'verbose_name_plural': 'Benutzergruppen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Mitglied'), ('admin', 'Admin')], default='member', max_length=20, verbose_name='Rolle')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='profiles.usergroup')),
            ],
            options={
                'verbose_name': 'Gruppenmitgliedschaft',
                'verbose_name_plural': 'Gruppenmitgliedschaften',
            },
        ),
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', verbose_name='Nachricht')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(blank=True, help_text='Null = ausstehend, True = genehmigt, False = abgelehnt', null=True, verbose_name='Genehmigt')),
                ('date_checked', models.DateTimeField(blank=True, null=True, verbose_name='Datum der Prüfung')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='Geprüft von')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_join_requests', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='profiles.usergroup')),
            ],
            options={
                'verbose_name': 'Beitrittsanfrage',
                'verbose_name_plural': 'Beitrittsanfragen',
                'ordering': ['-date_requested'],
            },
        ),
        migrations.CreateModel(
            name='GroupCorporateIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#4a3a6b', max_length=7, validators=[django.core.validators.RegexValidator(message='Farbe muss ein gültiger Hex-Wert sein (z.B. #4a3a6b)', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Primärfarbe')),
                ('secondary_color', models.CharField(default='#e8e4f0', max_length=7, validators=[django.core.validators.RegexValidator(message='Farbe muss ein gültiger Hex-Wert sein (z.B. #4a3a6b)', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Sekundärfarbe')),
                ('logo', models.ImageField(blank=True, default='', help_text='Max. 500KB', upload_to='groups/logos/', verbose_name='Logo')),
                ('slogan', models.CharField(blank=True, default='', max_length=200, verbose_name='Slogan')),
                ('greeting_text', models.TextField(blank=True, default='', help_text='Anrede-Textbaustein für Briefe und E-Mails', verbose_name='Anrede-Text')),
                ('footer_text', models.TextField(blank=True, default='', help_text='Impressum / Kontakt-Fußzeile', verbose_name='Fußzeile')),
                ('payment_info', models.TextField(blank=True, default='', help_text='Kontodaten, PayPal, etc.', verbose_name='Zahlungsdaten')),
                ('signature_text', models.TextField(blank=True, default='', help_text='Unterschrift-Text für Briefe', verbose_name='Unterschrift')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_identity', to='profiles.usergroup', verbose_name='Gruppe')),
            ],
            options={
                'verbose_name': 'Corporate Identity',
                'verbose_name_plural': 'Corporate Identities',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_group_size_min', models.IntegerField(blank=True, null=True, verbose_name='Min. Gruppengröße')),
                ('preferred_group_size_max', models.IntegerField(blank=True, null=True, verbose_name='Max. Gruppengröße')),
                ('preferred_difficulty', models.CharField(blank=True, default='', max_length=20, verbose_name='Bevorzugte Schwierigkeit')),
                ('preferred_location', models.CharField(blank=True, default='', max_length=50, verbose_name='Bevorzugter Ort')),
                ('preferred_scout_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.scoutlevel', verbose_name='Bevorzugte Stufe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benutzereinstellung',
                'verbose_name_plural': 'Benutzereinstellungen',
            },
        ),
    ]
