# Generated by Django 5.2.12 on 2026-03-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Wenn aktiv, kann das Profil von allen Nutzern gefunden werden",
                verbose_name="Öffentlich sichtbar",
            ),
        ),
    ]
