# Generated by Django 5.2.12 on 2026-09-28 21:02

from django.db import migrations, models
from django.db.models import F


def mark_existing_profiles_onboarded(apps, schema_editor):
    """Existing users already know the platform; only new social signups see onboarding."""
    UserProfile = apps.get_model("profiles", "UserProfile")
    UserProfile.objects.filter(onboarded_at__isnull=True).update(onboarded_at=F("created_at"))


def verify_staff_email_addresses(apps, schema_editor):
    """Keep the /admin/ emergency password of staff when they first link a provider.

    allauth wipes the local password when email authentication matches an
    address that is not verified. Staff accounts are known team members, so
    their address is marked verified up front.
    """
    User = apps.get_model("auth", "User")
    EmailAddress = apps.get_model("account", "EmailAddress")
    for user in User.objects.filter(is_staff=True).exclude(email=""):
        EmailAddress.objects.update_or_create(
            user=user,
            email=user.email.lower(),
            defaults={"verified": True, "primary": True},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_emailaddress_unique_primary_email"),
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="onboarded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Gesetzt, sobald der Willkommensdialog nach dem ersten Login abgeschlossen wurde",
                null=True,
                verbose_name="Onboarding abgeschlossen",
            ),
        ),
        migrations.RunPython(mark_existing_profiles_onboarded, migrations.RunPython.noop),
        migrations.RunPython(verify_staff_email_addresses, migrations.RunPython.noop),
    ]
