# Generated by Django 5.2.12 on 2026-04-09 21:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupCorporateIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "primary_color",
                    models.CharField(
                        default="#4a3a6b",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Farbe muss ein gültiger Hex-Wert sein (z.B. #4a3a6b)",
                                regex="^#[0-9a-fA-F]{6}$",
                            )
                        ],
                        verbose_name="Primärfarbe",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#e8e4f0",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Farbe muss ein gültiger Hex-Wert sein (z.B. #4a3a6b)",
                                regex="^#[0-9a-fA-F]{6}$",
                            )
                        ],
                        verbose_name="Sekundärfarbe",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default="",
                        help_text="Max. 500KB, wird zu WebP konvertiert",
                        upload_to="groups/logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("slogan", models.CharField(blank=True, default="", max_length=200, verbose_name="Slogan")),
                (
                    "greeting_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Anrede-Textbaustein für Briefe und E-Mails",
                        verbose_name="Anrede-Text",
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True, default="", help_text="Impressum / Kontakt-Fußzeile", verbose_name="Fußzeile"
                    ),
                ),
                (
                    "payment_info",
                    models.TextField(
                        blank=True, default="", help_text="Kontodaten, PayPal, etc.", verbose_name="Zahlungsdaten"
                    ),
                ),
                (
                    "signature_text",
                    models.TextField(
                        blank=True, default="", help_text="Unterschrift-Text für Briefe", verbose_name="Unterschrift"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporate_identity",
                        to="profiles.usergroup",
                        verbose_name="Gruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corporate Identity",
                "verbose_name_plural": "Corporate Identities",
            },
        ),
    ]
