# Generated by Django 5.2.12 on 2026-03-24 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_userprofile_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="profiles.usergroup",
                verbose_name="Übergruppe",
            ),
        ),
    ]
