# Generated by Django 5.2.12 on 2026-03-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_usergroup_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="eat_habits",
            field=models.CharField(
                choices=[("vegetarian", "Vegetarisch"), ("vegan", "Vegan"), ("all", "Alles")],
                default="all",
                max_length=20,
                verbose_name="Essgewohnheiten",
            ),
        ),
    ]
