# Generated by Django 5.2.12 on 2026-04-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_groupcorporateidentity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupcorporateidentity",
            name="logo",
            field=models.ImageField(
                blank=True, default="", help_text="Max. 500KB", upload_to="groups/logos/", verbose_name="Logo"
            ),
        ),
    ]
