# Generated by Django 5.2.12 on 2026-03-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0011_merge_materialunit_into_measuringunit"),
        ("profiles", "0004_userprofile_eat_habits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="eat_habits",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="nutritional_tags",
            field=models.ManyToManyField(
                blank=True, related_name="user_profiles", to="idea.nutritionaltag", verbose_name="Ernährungstags"
            ),
        ),
    ]
