# Generated by Django 5.2.12 on 2026-06-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_groupcorporateidentity_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Human-readable Identifier für die Profil-URL",
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
