# Generated by Django 5.2.12 on 2026-06-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_userprofile_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("user", "Benutzer"), ("staff", "Mitarbeiter"), ("admin", "Administrator")],
                default="user",
                max_length=20,
                verbose_name="Rolle",
            ),
        ),
    ]
