# Generated by Django 5.2.12 on 2026-06-19 06:47

from django.db import migrations


def populate_user_roles(apps, schema_editor):
    UserProfile = apps.get_model("profiles", "UserProfile")
    User = apps.get_model("auth", "User")

    # is_staff=True users get admin role
    staff_user_ids = User.objects.filter(is_staff=True).values_list("id", flat=True)
    UserProfile.objects.filter(user_id__in=staff_user_ids).update(role="admin")

    # Everyone else stays user (default)


def reverse_populate_user_roles(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_userprofile_role"),
    ]

    operations = [
        migrations.RunPython(populate_user_roles, reverse_populate_user_roles),
    ]
