"""Import ingredients from Rezeptkalkulator DEFAULT_INGREDIENT_DB.

For each ingredient:
1. Check if a similar ingredient already exists (fuzzy match)
2. If not, create it via ai_create_ingredient (AI fills all fields)
"""

import time

from django.contrib.postgres.search import TrigramSimilarity
from django.core.management.base import BaseCommand

from supply.models import Ingredient
from supply.services.ingredient_ai_suggest_service import ai_create_ingredient

# Extracted from https://rezeptkalkulator-2.web.app DEFAULT_INGREDIENT_DB
REZEPTKALKULATOR_INGREDIENTS = [
    "Tomaten-Passata",
    "Kokosraspeln",
    "Natron",
    "Cashewmus",
    "Nachos",
    "Ingwer",
    "Frischkäse",
    "Lasagneblätter",
    "Mohn",
    "Hähnchenflügel",
    "Edamer",
    "Schwarze Bohnen",
    "Kokosmehl",
    "Cranberrys",
    "Feta",
    "Agar-Agar",
    "Spinat",
    "Mozzarella",
    "Ingwerpulver",
    "Tomatenmark",
    "Frühlingszwiebeln",
    "Sesamöl",
    "Nelken",
    "Parmesan",
    "Lauch",
    "Hoisinsauce",
    "Cashewkerne",
    "Erdnussöl",
    "Vegeta",
    "Pinienkerne",
    "Sojasauce",
    "Mandelmus",
    "Nektarine",
    "Passionsfrucht",
    "Nüsse gemischt",
    "Kandierte Orangenschale",
    "Weißweinessig",
    "Sauerrahm",
    "Brokkoli",
    "Oregano",
    "Tomaten (geschält, Dose)",
    "Backaroma (Bittermandel)",
    "Quinoa",
    "Mayo Light",
    "Erdnüsse",
    "Erdbeeren",
    "Ajvar",
    "Kekse",
    "Senf",
    "Pastinake",
    "Banane",
    "Blaubeeren",
    "Zuckerschoten",
    "Worcestersauce",
    "Sauce Hollandaise light",
    "Schinken",
    "Chiasamen",
    "Schokolade (Vollmilch)",
    "Getrocknete Aprikosen",
    "Griechischer Joghurt",
    "Kokosöl",
    "Reisessig",
    "Chinakohl",
    "Pizzamehl Tipo 00",
    "Champignons",
    "Miracel Whip Balance",
    "Kochschinken",
    "Hummus",
    "Sojagranulat",
    "Wraps",
    "Pesto grün",
    "Apfelmus",
    "Marmelade",
    "Schalotten",
    "Thunfisch (Dose)",
    "Wirsing",
    "Kümmel",
    "Apfelessig",
    "Leberwurst",
    "H-Milch",
    "Paniermehl",
    "Eisbergsalat",
    "Speck",
    "Reisnudeln",
    "Gemüsefond",
    "Kreuzkümmel",
    "Vanilleextrakt",
    "Rote Bete",
    "Panko",
    "Bulgur",
    "Brühe (Rind, Pulver)",
    "Aubergine",
    "Wiener Würstchen",
    "Mais (Dose)",
    "Birne",
    "Spekulatius",
    "Olivenöl",
    "Zwiebel",
    "Krokant",
    "Oliven",
    "Puddingpulver",
    "Kürbis (Butternut)",
    "Sweet-Chili-Sauce",
    "Räuchertofu",
    "Chili (frisch)",
    "Haferflocken",
    "Kuvertüre",
    "Crèmefine 7%",
    "Glasnudeln",
    "Sellerie (Knolle)",
    "Getrocknete Feigen",
    "Sambal Oelek",
    "Walnüsse",
    "Limette",
    "Spargel (grün)",
    "Toastbrot",
    "Chicorée",
    "Reis",
    "Möhre",
    "Pfifferlinge",
    "Leinsamen",
    "Kurkuma (frisch)",
    "Vanilleschote",
    "Erbsen (Dose)",
    "Chorizo",
    "Avocado",
    "Mayonnaise",
    "Vanillezucker",
    "Haferdrink (ungesüßt)",
    "Kefir",
    "Marzipanrohmasse",
    "Ricotta",
    "Kohlrabi",
    "Chunky Flavour",
    "Tomatensaft",
    "Béchamelsauce",
    "Mineralwasser",
    "Pistazien",
    "Sojamilch",
    "Burger Buns",
    "Reiswaffeln",
    "Petersilie",
    "Nudeln",
    "Petersilie (frisch)",
    "Teriyaki-Sauce",
    "Gelatine",
    "Trauben",
    "Weißkohl",
    "Blumenkohl",
    "Balsamicoessig",
    "Kekse (z.B. Oreo)",
    "Spargel (weiß)",
    "Brühe (Huhn, Pulver)",
    "Tiefkühlspinat",
    "Brombeeren",
    "Couscous",
    "Kandierte Zitronenschale",
    "Mandelmilch",
    "Schoko-Chunks",
    "Schokolade (Zartbitter)",
    "Zwiebelpulver",
    "Blätterteig",
    "Kürbiskerne",
    "Essig",
    "Kapern",
    "Gnocchi (Vakuum)",
    "Zuckeralternative",
    "Mandelsplitter",
    "Zitronensaft",
    "Zucchini",
    "Mortadella",
    "Paprikapulver edelsüß",
    "Seidentofu",
    "Hafermilch",
    "Designer Whey Vanille",
    "Schokodrops (Vollmilch)",
    "Datteln (getrocknet)",
    "Räucherlachs",
    "Exquisa 0,2%",
    "Pesto rot",
    "Bacon",
    "Zucker",
    "Chilisauce",
    "Feige",
    "Orange",
    "Gouda",
    "Schnittlauch",
    "Kirschtomaten",
    "Speisestärke",
    "Orangensaft",
    "Getrocknete Pflaumen",
    "Grüne Currypaste",
    "Apfelsaft",
    "Creme Fraiche",
    "Butter",
    "Weißwein",
    "Halloumi",
    "Mango",
    "Kondensmilch (gezuckert)",
    "Rote Currypaste",
    "Salami",
    "Schweine Nacken",
    "Macadamianüsse",
    "Hefe (trocken)",
    "Gebrannte Mandeln",
    "Mehl",
    "Salsa-Sauce",
    "Knäckebrot",
    "Honig",
    "Babyspinat",
    "Erdnüsse (ungesalzen)",
    "Karamellsirup",
    "Granatapfelkerne",
    "Metaxa",
    "Kartoffelstärke",
    "Paprika (grün)",
    "Paprikapulver geräuchert",
    "Bratwurst (frisch)",
    "Kopfsalat",
    "Garnelen",
    "Linsen (rot)",
    "Gelbe Currypaste",
    "Wasser",
    "Joghurt",
    "Schweinefilet",
    "Zwieback",
    "Kiwi",
    "Mandeln",
    "Süßkartoffel",
    "Pfeffer",
    "Thymian (frisch)",
    "Sahne",
    "Quark (Magerquark)",
    "Rinderfond (Glas)",
    "Schmand",
    "Burgersoße",
    "Kaki",
    "Backaroma (Zitrone)",
    "Pflaumen",
    "Erythrit",
    "Chilipulver",
    "Hähnchenkeule",
    "Flohsamenschalen",
    "Erdnussbutter",
    "Tahini",
    "Sauerkraut",
    "Preiselbeeren",
    "Pektin",
    "Backpulver",
    "Eier",
    "Rapsöl",
    "Margarine",
    "Gurken",
    "Karotte",
    "Limettensaft",
    "Pizza Gewürz",
    "Brötchen",
    "Bambussprossen (Glas)",
    "Basilikum (frisch)",
    "Himbeeren",
    "Mascarpone",
    "Sonnenblumenkerne",
    "Tofu",
    "Dinkelmehl",
    "Weiße Bohnen (Dose)",
    "Cayennepfeffer",
    "Haselnusscreme",
    "Kirschen",
    "Paprika (orange)",
    "Hefe (frisch)",
    "Brauner Zucker",
    "Cheddar",
    "Pekannüsse",
    "Buttermilch",
    "Puderzucker",
    "Sesam",
    "Rotwein",
    "Kokosnuss (frisch)",
    "Naan",
    "Hähnchenbrust",
    "Radieschen",
    "Rote Bete (Glas)",
    "Datteln (frisch)",
    "Rotkohl",
    "Fenchel",
    "Currypulver",
    "Zitrone",
    "Mandelmehl",
    "Kokoszucker",
    "Feldsalat",
    "Maisstärke",
    "Muskatnuss",
    "Pita",
    "Grapefruit",
    "Granatapfel",
    "Skyr",
    "Maiskolben",
    "Austernsauce",
    "Ciabatta",
    "Rosmarin (frisch)",
    "Ananas",
    "Kürbis (Hokkaido)",
    "Ketchup",
    "Bohnen",
    "Rohrzucker (fein)",
    "Lorbeerblatt",
    "Mett",
    "Ananas (Dose)",
    "Rotweinessig",
    "Getrocknete Mangos",
    "Schweinebauch",
    "Zimt",
    "Miracle Whip light",
    "Backstreusel",
    "Glutamat",
    "Kidneybohnen",
    "Hartweizengrieß",
    "Paprika (gelb)",
    "Minze",
    "Schlagsahne",
    "Tomaten (stückig, Dose)",
    "Apfel",
    "Chiliflocken",
    "Backkakao",
    "Flavor Drops Vanilla",
    "Essiggurken",
    "Risottoreis",
    "Pizzateig",
    "Emmentaler",
    "Brot",
    "Rosinen",
    "Romanasalat",
    "Salz",
    "Kardamom",
    "Pak Choi",
    "Bier",
    "Knoblauch",
    "Hühnerfond (Glas)",
    "Tabasco",
    "Linsen",
    "Sonnenblumenöl",
    "Hähnchenschenkel",
    "Guarkernmehl",
    "BBQ-Sauce",
    "Ahornsirup",
    "Sellerie (Stange)",
    "High Protein Wrap",
    "Passierte Tomaten",
    "Knoblauchpulver",
    "Baguette",
    "Balsamico-Creme",
    "Rucola",
    "Schokodrops (Zartbitter)",
    "Kondensmilch",
    "Brötchen (Aufback)",
    "Mandel (gehackt)",
    "Mandel (gehobelt)",
    "Haselnusskerne",
    "Kakaopulver (Trinken)",
    "Kokosnussmilch (Dose)",
    "Kokosdrink",
    "Laugenbrezel (Tiefkühl)",
    "Laugenbrezel (frisch)",
    "Rinderhackfleisch",
    "Schweinehackfleisch",
    "Hackfleisch (gemischt)",
    "Lachsfilet (frisch)",
    "Rindergulasch (frisch)",
    "Dill (frisch)",
    "Dill (getrocknet)",
    "Erbsen (Tiefkühl)",
    "Erbsen (getrocknet)",
    "Kichererbsen (Dose)",
    "Tomate (Rispe)",
    "Jalapenos (Glas)",
    "Kartoffel (Festkochend)",
    "Kartoffel (vorw. Festkochend)",
    "Kartoffel (Mehligkochend)",
    "Kurkuma (Pulver)",
    "Basilikum (Streuer)",
    "Paprika (rot)",
    "Zwiebel (rot)",
    "Röstzwiebeln",
    "Rosmarin (getrocknet)",
    "Rotkohl (gegart)",
    "Thymian (getrocknet)",
    "Brühe (Gemüse)",
    "Brühe (vegan)",
    "Spätzle (frisch)",
    "Spätzle (trocken)",
    "Miracle Whip (classic)",
    "Quark 20% Fett",
    "Quark 40% Fett",
    "Hüttenkäse",
    "Fischsauce",
]


class Command(BaseCommand):
    help = "Import ingredients from Rezeptkalkulator, skip if similar exists, fill with AI"

    def add_arguments(self, parser):
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Only show what would be imported without creating",
        )
        parser.add_argument(
            "--threshold",
            type=float,
            default=0.4,
            help="Trigram similarity threshold for duplicate detection (default: 0.4)",
        )
        parser.add_argument(
            "--start-at",
            type=int,
            default=0,
            help="Start at index N (for resuming after errors)",
        )

    def handle(self, *args, **options):
        dry_run = options["dry_run"]
        threshold = options["threshold"]
        start_at = options["start_at"]

        ingredients = REZEPTKALKULATOR_INGREDIENTS[start_at:]
        total = len(ingredients)
        created = 0
        skipped = 0

        self.stdout.write(f"Processing {total} ingredients (threshold={threshold})...")
        if dry_run:
            self.stdout.write(self.style.WARNING("DRY RUN - no changes will be made"))

        for i, name in enumerate(ingredients, start=start_at):
            # Check for similar existing ingredient
            matches = (
                Ingredient.objects.annotate(
                    similarity=TrigramSimilarity("name", name),
                )
                .filter(similarity__gt=threshold)
                .order_by("-similarity")[:1]
            )

            if matches.exists():
                match = matches.first()
                self.stdout.write(
                    f"  [{i}/{start_at + total}] SKIP '{name}' (similar: '{match.name}', score={match.similarity:.2f})"
                )
                skipped += 1
                continue

            if dry_run:
                self.stdout.write(f"  [{i}/{start_at + total}] WOULD CREATE '{name}'")
                created += 1
                continue

            # Create via AI
            try:
                ingredient = ai_create_ingredient(name, bypass_limits=True)
                self.stdout.write(
                    self.style.SUCCESS(
                        f"  [{i}/{start_at + total}] CREATED '{ingredient.name}' (slug={ingredient.slug})"
                    )
                )
                created += 1
                # Rate limit - avoid hammering Gemini
                time.sleep(2)
            except Exception as e:
                self.stdout.write(self.style.ERROR(f"  [{i}/{start_at + total}] ERROR '{name}': {e}"))

        self.stdout.write(self.style.SUCCESS(f"\nDone! Created: {created}, Skipped: {skipped}"))
