/**
 * Shared icon component (food-design-system spec): Lucide only, sizes
 * 16/20/24/48 px, stroke width 2.
 *
 * `name` accepts the legacy Material Symbols names that are still stored in
 * data (tag icons, filter options, meal types) and maps them to Lucide via
 * `ICONS`. Names without a mapping render a neutral circle; the mapping test
 * (`icon.test.tsx`) keeps every name used in the source code covered.
 */
import type { CSSProperties } from 'react';
import {
  Activity,
  Apple,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowUp,
  ArrowUpDown,
  Award,
  Backpack,
  BadgeCheck,
  Ban,
  Bike,
  BookOpen,
  Bot,
  Building2,
  Cake,
  Calculator,
  Calendar,
  CalendarDays,
  CalendarRange,
  ChartBar,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleCheckBig,
  CircleHelp,
  CirclePlay,
  CirclePlus,
  CircleX,
  Clock,
  Coffee,
  Compass,
  Cookie,
  CookingPot,
  Copy,
  Croissant,
  Droplet,
  Dumbbell,
  Egg,
  EggFried,
  EllipsisVertical,
  Euro,
  Eye,
  FilePen,
  FileText,
  Flame,
  FlaskConical,
  Footprints,
  Gamepad2,
  Globe,
  Heading,
  Heart,
  House,
  Info,
  LayoutGrid,
  Leaf,
  Lightbulb,
  Link,
  List,
  ListFilter,
  ListOrdered,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Minus,
  Moon,
  Mountain,
  Music,
  NotebookPen,
  Package,
  PawPrint,
  Pencil,
  PiggyBank,
  Pill,
  Plus,
  Printer,
  RefreshCw,
  Reply,
  Rocket,
  RotateCcw,
  Sailboat,
  Sandwich,
  Save,
  Scale,
  Search,
  SearchX,
  Send,
  Settings,
  Shapes,
  Share2,
  ShieldCheck,
  ShieldPlus,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Signal,
  SlidersHorizontal,
  Snowflake,
  Sparkles,
  Star,
  StickyNote,
  Store,
  Sun,
  Tag,
  Tent,
  Text,
  Timer,
  ToggleLeft,
  ToggleRight,
  Trash2,
  TreePine,
  TrendingUp,
  TriangleAlert,
  Truck,
  User,
  UserMinus,
  UserPlus,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  WandSparkles,
  Wheat,
  WifiOff,
  X,
  type LucideIcon,
} from 'lucide-react';
import { cn } from '@/lib/utils';

/** Allowed icon sizes in px: 16 inline/small buttons, 20 buttons/navigation, 24 headers, 48 empty states. */
export type IconSize = 16 | 20 | 24 | 48;

/** Legacy Material Symbols name → Lucide icon. */
export const ICONS: Record<string, LucideIcon> = {
  ac_unit: Snowflake,
  add: Plus,
  add_circle: CirclePlus,
  admin_panel_settings: ShieldCheck,
  analytics: ChartColumn,
  apps: LayoutGrid,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_upward: ArrowUp,
  article: FileText,
  auto_awesome: Sparkles,
  auto_fix_high: WandSparkles,
  award_star: Award,
  backpack: Backpack,
  bakery_dining: Croissant,
  balance: Scale,
  bar_chart: ChartBar,
  block: Ban,
  cabin: House,
  cake: Cake,
  calculate: Calculator,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  calendar_view_week: CalendarRange,
  camping: Tent,
  cancel: CircleX,
  category: Shapes,
  check: Check,
  check_circle: CircleCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  content_copy: Copy,
  cookie: Cookie,
  cooking: CookingPot,
  cottage: House,
  delete: Trash2,
  description: FileText,
  dining: Utensils,
  dinner_dining: Moon,
  directions_bike: Bike,
  draft: FilePen,
  eco: Leaf,
  edit: Pencil,
  edit_note: NotebookPen,
  egg: Egg,
  egg_alt: EggFried,
  error: CircleAlert,
  euro: Euro,
  event: CalendarDays,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  explore: Compass,
  favorite: Heart,
  filter_list: ListFilter,
  fitness_center: Dumbbell,
  format_list_numbered: ListOrdered,
  free_breakfast: Coffee,
  grain: Wheat,
  grid_view: LayoutGrid,
  grocery: ShoppingBasket,
  group: Users,
  groups: Users,
  health_and_safety: ShieldPlus,
  help: CircleHelp,
  hiking: Footprints,
  home: House,
  info: Info,
  inventory_2: Package,
  kayaking: Sailboat,
  label: Tag,
  landscape: Mountain,
  lightbulb: Lightbulb,
  link: Link,
  list: List,
  local_cafe: Coffee,
  local_fire_department: Flame,
  local_shipping: Truck,
  location_city: Building2,
  lock: Lock,
  login: LogIn,
  logout: LogOut,
  lunch_dining: Sandwich,
  medication: Pill,
  menu_book: BookOpen,
  monitoring: Activity,
  more_vert: EllipsisVertical,
  music_note: Music,
  nutrition: Apple,
  park: TreePine,
  payments: Wallet,
  person: User,
  person_add: UserPlus,
  person_remove: UserMinus,
  pets: PawPrint,
  play_circle: CirclePlay,
  print: Printer,
  progress_activity: LoaderCircle,
  public: Globe,
  refresh: RefreshCw,
  remove: Minus,
  reply: Reply,
  restart_alt: RotateCcw,
  restaurant: Utensils,
  restaurant_menu: UtensilsCrossed,
  rocket_launch: Rocket,
  save: Save,
  savings: PiggyBank,
  scale: Scale,
  schedule: Clock,
  science: FlaskConical,
  search: Search,
  search_off: SearchX,
  sell: Tag,
  send: Send,
  settings: Settings,
  share: Share2,
  shopping_cart: ShoppingCart,
  short_text: Text,
  signal_cellular_alt: Signal,
  skillet: CookingPot,
  smart_toy: Bot,
  sort: ArrowUpDown,
  sports_esports: Gamepad2,
  star: Star,
  stars: Sparkles,
  sticky_note_2: StickyNote,
  store: Store,
  swap_horiz: ArrowLeftRight,
  swap_vert: ArrowUpDown,
  takeout_dining: ShoppingBag,
  task_alt: CircleCheckBig,
  terrain: Mountain,
  timer: Timer,
  tips_and_updates: Lightbulb,
  title: Heading,
  toggle_off: ToggleLeft,
  toggle_on: ToggleRight,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  verified: BadgeCheck,
  view_list: List,
  visibility: Eye,
  warning: TriangleAlert,
  warning_amber: TriangleAlert,
  water_drop: Droplet,
  wb_sunny: Sun,
  wifi_off: WifiOff,
};

/** Lucide icon for a (legacy Material Symbols) name; unknown names get a neutral circle. */
export function resolveIcon(name: string | null | undefined): LucideIcon {
  return (name && ICONS[name]) || Circle;
}

interface IconProps {
  /** Icon name (see `ICONS`) or a Lucide icon component. */
  name: string | LucideIcon;
  size?: IconSize;
  className?: string;
  style?: CSSProperties;
  /** Accessible label; without it the icon is decorative (`aria-hidden`). */
  label?: string;
}

export function Icon({ name, size = 20, className, style, label }: IconProps) {
  const Component = typeof name === 'string' ? resolveIcon(name) : name;
  return (
    <Component
      size={size}
      strokeWidth={2}
      className={cn('shrink-0', className)}
      style={style}
      aria-hidden={label ? undefined : true}
      aria-label={label}
      role={label ? 'img' : undefined}
    />
  );
}

export default Icon;
