# Generated by Django 5.2.12 on 2026-04-03 22:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("idea", "0013_delete_recipehint_remove_recipeitem_idea_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeHint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("energy_kj", "Energie (kJ)"),
                            ("sugar_g", "Zucker (g)"),
                            ("sodium_mg", "Natrium (mg)"),
                            ("fibre_g", "Ballaststoffe (g)"),
                            ("fat_g", "Fett (g)"),
                            ("fat_sat_g", "Gesättigte Fettsäuren (g)"),
                            ("protein_g", "Eiweiß (g)"),
                            ("carbohydrate_g", "Kohlenhydrate (g)"),
                            ("salt_g", "Salz (g)"),
                            ("fructose_g", "Fructose (g)"),
                            ("lactose_g", "Laktose (g)"),
                            ("fruit_factor", "Obst-/Gemüse-Anteil"),
                        ],
                        help_text="Nährwertfeld das geprüft wird",
                        max_length=20,
                        verbose_name="Parameter",
                    ),
                ),
                ("min_value", models.FloatField(blank=True, null=True, verbose_name="Mindestwert")),
                ("max_value", models.FloatField(blank=True, null=True, verbose_name="Höchstwert")),
                (
                    "min_max",
                    models.CharField(
                        choices=[("min", "Mindestens"), ("max", "Höchstens"), ("range", "Bereich")],
                        default="max",
                        max_length=10,
                        verbose_name="Regeltyp",
                    ),
                ),
                (
                    "hint_level",
                    models.CharField(
                        choices=[("info", "Information"), ("warning", "Warnung"), ("error", "Fehler")],
                        default="info",
                        max_length=10,
                        verbose_name="Hinweis-Stufe",
                    ),
                ),
                (
                    "recipe_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("breakfast", "Frühstück"),
                            ("warm_meal", "Warme Mahlzeit"),
                            ("cold_meal", "Kalte Mahlzeit"),
                            ("dessert", "Nachtisch"),
                            ("side_dish", "Beilage"),
                            ("snack", "Snack"),
                            ("drink", "Getränk"),
                        ],
                        default="",
                        help_text="Optional: Gilt nur für diesen Rezepttyp",
                        max_length=20,
                        verbose_name="Rezepttyp",
                    ),
                ),
                (
                    "recipe_objective",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("health", "Gesundheit"),
                            ("taste", "Geschmack"),
                            ("cost", "Kosten"),
                            ("fulfillment", "Sättigung"),
                        ],
                        default="",
                        help_text="Gesundheit, Geschmack, Kosten oder Sättigung",
                        max_length=20,
                        verbose_name="Bewertungsdimension",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezept-Hinweis",
                "verbose_name_plural": "Rezept-Hinweise",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-freundlicher Name, wird automatisch aus dem Titel generiert",
                        max_length=280,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("summary", models.TextField(blank=True, default="", verbose_name="Kurzbeschreibung")),
                ("summary_long", models.TextField(blank=True, default="", verbose_name="Ausführliche Zusammenfassung")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung / Anleitung")),
                (
                    "costs_rating",
                    models.CharField(
                        choices=[("free", "0 €"), ("less_1", "< 1 €"), ("1_2", "1 – 2 €"), ("more_2", "> 2 €")],
                        default="free",
                        max_length=20,
                        verbose_name="Kosten",
                    ),
                ),
                (
                    "execution_time",
                    models.CharField(
                        choices=[
                            ("less_30", "< 30 Minuten"),
                            ("30_60", "30 – 60 Minuten"),
                            ("60_90", "60 – 90 Minuten"),
                            ("more_90", "> 90 Minuten"),
                        ],
                        default="less_30",
                        max_length=20,
                        verbose_name="Zubereitungszeit",
                    ),
                ),
                (
                    "preparation_time",
                    models.CharField(
                        choices=[
                            ("none", "Keine Vorbereitung"),
                            ("less_15", "< 15 Minuten"),
                            ("15_30", "15 – 30 Minuten"),
                            ("30_60", "30 – 60 Minuten"),
                            ("more_60", "> 60 Minuten"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Vorbereitungszeit",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "Einfach"), ("medium", "Mittel"), ("hard", "Schwer")],
                        default="easy",
                        max_length=20,
                        verbose_name="Schwierigkeit",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("published", "Veröffentlicht"),
                            ("archived", "Archiviert"),
                            ("review", "In Prüfung"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="recipes/", verbose_name="Bild")),
                ("like_score", models.IntegerField(default=0, verbose_name="Beliebtheit")),
                ("view_count", models.IntegerField(default=0, verbose_name="Aufrufe")),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ("embedding", models.BinaryField(blank=True, null=True, verbose_name="Embedding")),
                (
                    "recipe_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("breakfast", "Frühstück"),
                            ("warm_meal", "Warme Mahlzeit"),
                            ("cold_meal", "Kalte Mahlzeit"),
                            ("dessert", "Nachtisch"),
                            ("side_dish", "Beilage"),
                            ("snack", "Snack"),
                            ("drink", "Getränk"),
                        ],
                        default="",
                        help_text="Frühstück, Warme Mahlzeit, Snack, etc.",
                        max_length=20,
                        verbose_name="Rezepttyp",
                    ),
                ),
                (
                    "servings",
                    models.IntegerField(
                        blank=True, default=4, help_text="Anzahl der Portionen", null=True, verbose_name="Portionen"
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True, related_name="authored_recipes", to=settings.AUTH_USER_MODEL, verbose_name="Autoren"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nutritional_tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Ernährungshinweise wie vegan, vegetarisch, etc.",
                        related_name="recipes",
                        to="idea.nutritionaltag",
                        verbose_name="Ernährungstags",
                    ),
                ),
                (
                    "scout_levels",
                    models.ManyToManyField(
                        blank=True, related_name="recipes", to="idea.scoutlevel", verbose_name="Pfadfinder-Stufen"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="recipes", to="idea.tag", verbose_name="Tags"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezept",
                "verbose_name_plural": "Rezepte",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecipeComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=True)),
                ("text", models.TextField(verbose_name="Kommentar")),
                ("author_name", models.CharField(blank=True, default="", max_length=100, verbose_name="Name (anonym)")),
                ("status", models.CharField(default="pending", max_length=20, verbose_name="Moderations-Status")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="recipe.recipecomment",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="recipe.recipe"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipe_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezept-Kommentar",
                "verbose_name_plural": "Rezept-Kommentare",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecipeEmotion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "emotion_type",
                    models.CharField(
                        choices=[
                            ("in_love", "Begeistert"),
                            ("happy", "Gut"),
                            ("disappointed", "Enttäuscht"),
                            ("complex", "Zu komplex"),
                        ],
                        max_length=20,
                    ),
                ),
                ("session_key", models.CharField(blank=True, default="", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="emotions", to="recipe.recipe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezept-Bewertung",
                "verbose_name_plural": "Rezept-Bewertungen",
            },
        ),
        migrations.CreateModel(
            name="RecipeItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.FloatField(default=1, verbose_name="Menge")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Reihenfolge")),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="z.B. 'gehackt', 'in Scheiben', 'optional'",
                        max_length=255,
                        verbose_name="Anmerkung",
                    ),
                ),
                (
                    "quantity_type",
                    models.CharField(
                        choices=[("once", "Einmalig"), ("per_person", "Pro Person")],
                        default="once",
                        help_text="Einmalig = Gesamtmenge, Pro Person = Menge pro Person",
                        max_length=20,
                        verbose_name="Mengenart",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Direkte Zutat (wenn keine Portion gewählt)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipe_items",
                        to="idea.ingredient",
                        verbose_name="Zutat",
                    ),
                ),
                (
                    "measuring_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="idea.measuringunit",
                        verbose_name="Maßeinheit",
                    ),
                ),
                (
                    "portion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipe_items",
                        to="idea.portion",
                        verbose_name="Portion",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_items",
                        to="recipe.recipe",
                        verbose_name="Rezept",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezept-Zutat",
                "verbose_name_plural": "Rezept-Zutaten",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="RecipeView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("ip_hash", models.CharField(help_text="SHA-256 gehashte IP", max_length=64)),
                ("user_agent", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="views", to="recipe.recipe"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezeptaufruf",
                "verbose_name_plural": "Rezeptaufrufe",
            },
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="recipe_reci_search__f79904_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["status", "-created_at"], name="recipe_reci_status_e43bd1_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["recipe_type", "status", "-created_at"], name="recipe_reci_recipe__d607a9_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["-like_score"], name="recipe_reci_like_sc_12728a_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["-view_count"], name="recipe_reci_view_co_5672b9_idx"),
        ),
        migrations.AddIndex(
            model_name="recipeview",
            index=models.Index(fields=["recipe", "session_key", "created_at"], name="recipe_reci_recipe__ace1ed_idx"),
        ),
    ]
