# Generated by Django 5.2.12 on 2026-04-06 18:46

import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeHint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("energy_kj", "Energie (kJ)"),
                            ("sugar_g", "Zucker (g)"),
                            ("sodium_mg", "Natrium (mg)"),
                            ("fibre_g", "Ballaststoffe (g)"),
                            ("fat_g", "Fett (g)"),
                            ("fat_sat_g", "Gesättigte Fettsäuren (g)"),
                            ("protein_g", "Eiweiß (g)"),
                            ("carbohydrate_g", "Kohlenhydrate (g)"),
                            ("salt_g", "Salz (g)"),
                            ("fructose_g", "Fructose (g)"),
                            ("lactose_g", "Laktose (g)"),
                            ("fruit_factor", "Obst-/Gemüse-Anteil"),
                        ],
                        help_text="Nährwertfeld das geprüft wird",
                        max_length=20,
                        verbose_name="Parameter",
                    ),
                ),
                ("min_value", models.FloatField(blank=True, null=True, verbose_name="Mindestwert")),
                ("max_value", models.FloatField(blank=True, null=True, verbose_name="Höchstwert")),
                (
                    "min_max",
                    models.CharField(
                        choices=[("min", "Mindestens"), ("max", "Höchstens"), ("range", "Bereich")],
                        default="max",
                        max_length=10,
                        verbose_name="Regeltyp",
                    ),
                ),
                (
                    "hint_level",
                    models.CharField(
                        choices=[("info", "Information"), ("warning", "Warnung"), ("error", "Fehler")],
                        default="info",
                        max_length=10,
                        verbose_name="Hinweis-Stufe",
                    ),
                ),
                (
                    "recipe_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("breakfast", "Frühstück"),
                            ("warm_meal", "Warme Mahlzeit"),
                            ("cold_meal", "Kalte Mahlzeit"),
                            ("dessert", "Nachtisch"),
                            ("side_dish", "Beilage"),
                            ("snack", "Snack"),
                            ("drink", "Getränk"),
                        ],
                        default="",
                        help_text="Optional: Gilt nur für diesen Rezepttyp",
                        max_length=20,
                        verbose_name="Rezepttyp",
                    ),
                ),
                (
                    "recipe_objective",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("health", "Gesundheit"),
                            ("taste", "Geschmack"),
                            ("cost", "Kosten"),
                            ("fulfillment", "Sättigung"),
                        ],
                        default="",
                        help_text="Gesundheit, Geschmack, Kosten oder Sättigung",
                        max_length=20,
                        verbose_name="Bewertungsdimension",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezept-Hinweis",
                "verbose_name_plural": "Rezept-Hinweise",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecipeItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.FloatField(default=1, verbose_name="Menge")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Reihenfolge")),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="z.B. 'gehackt', 'in Scheiben', 'optional'",
                        max_length=255,
                        verbose_name="Anmerkung",
                    ),
                ),
                (
                    "quantity_type",
                    models.CharField(
                        choices=[("once", "Einmalig"), ("per_person", "Pro Person")],
                        default="once",
                        help_text="Einmalig = Gesamtmenge, Pro Person = Menge pro Person",
                        max_length=20,
                        verbose_name="Mengenart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezept-Zutat",
                "verbose_name_plural": "Rezept-Zutaten",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                ("summary", models.TextField(blank=True, default="")),
                ("summary_long", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "costs_rating",
                    models.CharField(
                        choices=[("free", "0 €"), ("less_1", "< 1 €"), ("1_2", "1 – 2 €"), ("more_2", "> 2 €")],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "execution_time",
                    models.CharField(
                        choices=[
                            ("less_30", "< 30 Minuten"),
                            ("30_60", "30 – 60 Minuten"),
                            ("60_90", "60 – 90 Minuten"),
                            ("more_90", "> 90 Minuten"),
                        ],
                        default="less_30",
                        max_length=20,
                    ),
                ),
                (
                    "preparation_time",
                    models.CharField(
                        choices=[
                            ("none", "Keine Vorbereitung"),
                            ("less_15", "< 15 Minuten"),
                            ("15_30", "15 – 30 Minuten"),
                            ("30_60", "30 – 60 Minuten"),
                            ("more_60", "> 60 Minuten"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "Einfach"), ("medium", "Mittel"), ("hard", "Schwer")],
                        default="easy",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("submitted", "Eingereicht"),
                            ("approved", "Genehmigt"),
                            ("rejected", "Abgelehnt"),
                            ("archived", "Archiviert"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="content/")),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ("embedding", models.BinaryField(blank=True, null=True)),
                ("embedding_updated_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
                ("like_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipe_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("breakfast", "Frühstück"),
                            ("warm_meal", "Warme Mahlzeit"),
                            ("cold_meal", "Kalte Mahlzeit"),
                            ("dessert", "Nachtisch"),
                            ("side_dish", "Beilage"),
                            ("snack", "Snack"),
                            ("drink", "Getränk"),
                        ],
                        default="",
                        help_text="Frühstück, Warme Mahlzeit, Snack, etc.",
                        max_length=20,
                        verbose_name="Rezepttyp",
                    ),
                ),
                (
                    "servings",
                    models.IntegerField(
                        blank=True, default=4, help_text="Anzahl der Portionen", null=True, verbose_name="Portionen"
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True, related_name="authored_%(class)s_set", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezept",
                "verbose_name_plural": "Rezepte",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
