# Generated by Django 5.2.12 on 2026-07-13 20:13

import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rezept-Ordner',
                'verbose_name_plural': 'Rezept-Ordner',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1, verbose_name='Menge')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('note', models.CharField(blank=True, default='', help_text="z.B. 'gehackt', 'in Scheiben', 'optional'", max_length=255, verbose_name='Anmerkung')),
                ('is_optional', models.BooleanField(default=False, help_text='Beim Einplanen entscheidet der Planer, ob die Zutat dabei ist', verbose_name='Optional')),
                ('exchange_position', models.IntegerField(blank=True, help_text='0 = Original/Default', null=True, verbose_name='Position in der Austausch-Gruppe')),
            ],
            options={
                'verbose_name': 'Rezept-Zutat',
                'verbose_name_plural': 'Rezept-Zutaten',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItemExchangeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text="z.B. 'Käse-Ersatz' — nur im Editor sichtbar", max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Austausch-Gruppe',
                'verbose_name_plural': 'Austausch-Gruppen',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0, help_text='Sortierung der Schritte (0-indexed)', verbose_name='Reihenfolge')),
                ('instruction', models.TextField(help_text='Schritt-Text mit Platzhaltern: {ingredient_name} oder {uuid}', verbose_name='Anleitung')),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Ungefähre Dauer für diesen Schritt', null=True, verbose_name='Dauer (Minuten)')),
                ('section', models.CharField(blank=True, default='', help_text="Optional: Gruppierung (z.B. 'Vorbereitung', 'Kochen')", max_length=255, verbose_name='Sektion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert')),
            ],
            options={
                'verbose_name': 'Rezept-Schritt',
                'verbose_name_plural': 'Rezept-Schritte',
                'ordering': ['recipe', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStepIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_modifier', models.FloatField(default=1.0, help_text='Multiplikator: z.B. 0.5 = halbe Menge, 2.0 = doppelte Menge', verbose_name='Mengenmodifizierer')),
                ('preparation', models.CharField(blank=True, default='', help_text="Schritt-spezifische Vorbereitung: z.B. 'würfeln', 'geraffelt'", max_length=255, verbose_name='Vorbereitung')),
                ('sort_order', models.IntegerField(default=0, help_text='Sortierung innerhalb des Schritts', verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert')),
            ],
            options={
                'verbose_name': 'Schritt-Zutat',
                'verbose_name_plural': 'Schritt-Zutaten',
                'ordering': ['step', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeTypeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_type', models.CharField(help_text='Einer der RecipeTypeChoices', max_length=20, unique=True, verbose_name='Rezepttyp')),
                ('count', models.IntegerField(default=0, verbose_name='Anzahl Rezepte')),
                ('price_min', models.FloatField(blank=True, null=True)),
                ('price_max', models.FloatField(blank=True, null=True)),
                ('price_avg', models.FloatField(blank=True, null=True)),
                ('price_median', models.FloatField(blank=True, null=True)),
                ('energy_min', models.FloatField(blank=True, null=True)),
                ('energy_max', models.FloatField(blank=True, null=True)),
                ('energy_avg', models.FloatField(blank=True, null=True)),
                ('energy_median', models.FloatField(blank=True, null=True)),
                ('protein_avg', models.FloatField(blank=True, null=True)),
                ('fat_avg', models.FloatField(blank=True, null=True)),
                ('carbs_avg', models.FloatField(blank=True, null=True)),
                ('weight_min', models.FloatField(blank=True, null=True)),
                ('weight_max', models.FloatField(blank=True, null=True)),
                ('weight_avg', models.FloatField(blank=True, null=True)),
                ('weight_median', models.FloatField(blank=True, null=True)),
                ('nutri_score_dist', models.JSONField(blank=True, default=dict, help_text='{"A": 5, "B": 12, "C": 18, "D": 8, "E": 4}', verbose_name='Nutri-Score Verteilung')),
                ('price_buckets', models.JSONField(blank=True, default=list, help_text='Array of bucket objects: [{"min": 0, "max": 10, "count": 5}, ...]', verbose_name='Preis-Buckets')),
                ('energy_buckets', models.JSONField(blank=True, default=list, help_text='Array of bucket objects with kcal ranges', verbose_name='Energie-Buckets')),
                ('protein_buckets', models.JSONField(blank=True, default=list, help_text='Array of bucket objects with gram ranges', verbose_name='Protein-Buckets')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rezepttyp-Statistik',
                'verbose_name_plural': 'Rezepttyp-Statistiken',
                'db_table': 'recipe_recipetypestats',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="z.B. 'Zuckergehalt pro Tag'", max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('parameter', models.CharField(help_text="z.B. 'energy_kcal', 'sugar_g', 'protein_g'", max_length=50, verbose_name='Parameter')),
                ('scope', models.CharField(choices=[('meal_event', 'Essensplan'), ('day', 'Tag'), ('meal', 'Mahlzeit'), ('recipe', 'Rezept')], help_text='Auf welcher Ebene wird die Regel ausgewertet', max_length=20, verbose_name='Geltungsbereich')),
                ('rule_type', models.CharField(choices=[('nutrition', 'Nährwert')], default='nutrition', max_length=20, verbose_name='Regeltyp')),
                ('min_green', models.FloatField(blank=True, help_text='Untergrenze für grünen Status (Wert muss >= sein)', null=True, verbose_name='Min Grün')),
                ('min_yellow', models.FloatField(blank=True, help_text='Untergrenze für gelben Status (darunter = rot)', null=True, verbose_name='Min Gelb')),
                ('max_green', models.FloatField(blank=True, help_text='Obergrenze für grünen Status (Wert muss <= sein)', null=True, verbose_name='Max Grün')),
                ('max_yellow', models.FloatField(blank=True, help_text='Obergrenze für gelben Status (darüber = rot)', null=True, verbose_name='Max Gelb')),
                ('unit', models.CharField(blank=True, default='', help_text="z.B. 'g', 'kcal', 'mg'", max_length=20, verbose_name='Einheit')),
                ('hint_level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warnung'), ('error', 'Fehler')], default='warn', max_length=10, verbose_name='Hinweis-Stufe')),
                ('tip_text', models.TextField(blank=True, default='', help_text='Empfehlung bei Gelb/Rot-Status', verbose_name='Tipp-Text')),
                ('improvement_text', models.TextField(blank=True, default='', help_text='Konkreter, umsetzbarer Verbesserungsvorschlag', verbose_name='Verbesserungsvorschlag')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sortierung')),
            ],
            options={
                'verbose_name': 'Regel',
                'verbose_name_plural': 'Regeln',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('summary_long', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('execution_time', models.CharField(choices=[('less_30', '< 30 Minuten'), ('30_60', '30 – 60 Minuten'), ('60_90', '60 – 90 Minuten'), ('more_90', '> 90 Minuten')], default='less_30', max_length=20)),
                ('preparation_time', models.CharField(choices=[('none', 'Keine Vorbereitung'), ('less_15', '< 15 Minuten'), ('15_30', '15 – 30 Minuten'), ('30_60', '30 – 60 Minuten'), ('more_60', '> 60 Minuten')], default='none', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Einfach'), ('medium', 'Mittel'), ('hard', 'Schwer')], default='easy', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('submitted', 'Eingereicht'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('archived', 'Archiviert')], default='draft', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('embedding_updated_at', models.DateTimeField(blank=True, null=True)),
                ('embedding_text_hash', models.CharField(blank=True, help_text='SHA-256 hash of the embedding text. Used to detect changes and avoid unnecessary regeneration.', max_length=64, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('like_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe_type', models.CharField(blank=True, choices=[('breakfast', 'Frühstück'), ('warm_meal', 'Warme Mahlzeit'), ('cold_meal', 'Kalte Mahlzeit'), ('dessert', 'Nachtisch'), ('recipe_part', 'Rezeptteil'), ('drink', 'Getränk'), ('snack', 'Snack')], default='', help_text='Frühstück, Warme Mahlzeit, etc.', max_length=20, verbose_name='Rezepttyp')),
                ('portions', models.IntegerField(blank=True, default=1, help_text='Basis-Portionsanzahl (Normportionen)', null=True, verbose_name='Portionen')),
                ('visibility', models.CharField(blank=True, choices=[('private', 'Privat'), ('group', 'Gruppe'), ('public', 'Öffentlich')], help_text='Nur relevant wenn owner gesetzt: private/group/public', max_length=10, null=True, verbose_name='Sichtbarkeit')),
                ('usage_count', models.IntegerField(db_index=True, default=0, help_text='Wie oft dieses Rezept in Menüpläne eingefügt wurde (denormalisiert)', verbose_name='Verwendungsanzahl')),
                ('source_url', models.URLField(blank=True, default='', help_text='Original-URL bei importierten Rezepten', max_length=500, verbose_name='Quell-URL')),
                ('cached_energy_kcal', models.FloatField(blank=True, null=True, verbose_name='Energie (kcal, cached)')),
                ('cached_energy_total_kcal', models.FloatField(blank=True, null=True, verbose_name='Gesamtenergie (kcal, cached)')),
                ('cached_weight_g', models.FloatField(blank=True, null=True, verbose_name='Gesamtgewicht (g, cached)')),
                ('cached_protein_g', models.FloatField(blank=True, null=True, verbose_name='Eiweiß (g, cached)')),
                ('cached_fat_g', models.FloatField(blank=True, null=True, verbose_name='Fett (g, cached)')),
                ('cached_carbohydrate_g', models.FloatField(blank=True, null=True, verbose_name='Kohlenhydrate (g, cached)')),
                ('cached_sugar_g', models.FloatField(blank=True, null=True, verbose_name='Zucker (g, cached)')),
                ('cached_fibre_g', models.FloatField(blank=True, null=True, verbose_name='Ballaststoffe (g, cached)')),
                ('cached_salt_g', models.FloatField(blank=True, null=True, verbose_name='Salz (g, cached)')),
                ('cached_nutri_class', models.IntegerField(blank=True, help_text='1=A, 2=B, 3=C, 4=D, 5=E', null=True, verbose_name='Nutri-Score Klasse (cached)')),
                ('cached_price_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gesamtpreis (cached)')),
                ('cached_vitamin_c_mg', models.FloatField(blank=True, null=True, verbose_name='Vitamin C (mg, cached)')),
                ('cached_at', models.DateTimeField(blank=True, help_text='Wann die gecachten Werte zuletzt berechnet wurden', null=True, verbose_name='Cache-Zeitpunkt')),
                ('quality_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Datenqualität (0-100)')),
                ('quality_score_updated_at', models.DateTimeField(blank=True, null=True)),
                ('preparation_method', models.CharField(blank=True, choices=[('cooking', 'Kochen'), ('baking', 'Backen'), ('frying', 'Braten'), ('grilling', 'Grillen'), ('raw', 'Rohkost'), ('none', 'Keine Zubereitung')], default='', max_length=50, verbose_name='Zubereitungsart')),
                ('authors', models.ManyToManyField(blank=True, related_name='authored_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rezept',
                'verbose_name_plural': 'Rezepte',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
