# Generated by Django 5.2.12 on 2026-07-13 20:13

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
        ('profiles', '0002_initial'),
        ('recipe', '0001_initial'),
        ('supply', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='supply.equipment', verbose_name='Equipment'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='forked_from',
            field=models.ForeignKey(blank=True, help_text='Referenz zum Original-Rezept bei persönlichen Kopien', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='recipe.recipe', verbose_name='Ursprungsrezept'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='manual_nutritional_tags',
            field=models.ManyToManyField(blank=True, help_text='Manuell gesetzte Ernährungshinweise, bleiben bei Sync erhalten', related_name='manual_recipes', to='supply.nutritionaltag', verbose_name='Ernährungstags (manuell)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutritional_tags',
            field=models.ManyToManyField(blank=True, help_text='Aus Zutaten berechnete Ernährungshinweise (auto-synchronisiert)', related_name='recipes', to='supply.nutritionaltag', verbose_name='Ernährungstags (auto-synchronisiert)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Null = Inspi-verifiziertes Rezept, gesetzt = persönliches Rezept', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Besitzer'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='scout_levels',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='content.scoutlevel'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='shared_groups',
            field=models.ManyToManyField(blank=True, help_text='Gruppen, mit denen dieses Rezept geteilt wird (relevant für breakfast wizard)', related_name='shared_recipes', to='profiles.usergroup', verbose_name='Geteilte Gruppen'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='content.tag'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipefolder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_folders', to=settings.AUTH_USER_MODEL, verbose_name='Besitzer'),
        ),
        migrations.AddField(
            model_name='recipefolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='recipe.recipefolder', verbose_name='Überordner'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Optionaler Ordner für persönliche Rezepte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipe.recipefolder', verbose_name='Ordner'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='portion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='supply.portion', verbose_name='Portion'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='recipe.recipe', verbose_name='Rezept'),
        ),
        migrations.AddField(
            model_name='recipeitemexchangegroup',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_groups', to='recipe.recipe', verbose_name='Rezept'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='exchange_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='recipe.recipeitemexchangegroup', verbose_name='Austausch-Gruppe'),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipe.recipe', verbose_name='Rezept'),
        ),
        migrations.AddField(
            model_name='recipestepingredient',
            name='recipe_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_assignments', to='recipe.recipeitem', verbose_name='Rezept-Zutat'),
        ),
        migrations.AddField(
            model_name='recipestepingredient',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_ingredients', to='recipe.recipestep', verbose_name='Schritt'),
        ),
        migrations.AlterUniqueTogether(
            name='recipefolder',
            unique_together={('owner', 'name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='recipe_search_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['status', 'created_at'], name='recipe_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['recipe_type', 'status', 'created_at'], name='recipe_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['like_score'], name='recipe_like_score_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['view_count'], name='recipe_view_count_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['owner', 'visibility', 'status'], name='recipe_owner_vis_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='recipe_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.CheckConstraint(condition=models.Q(('is_optional', True), ('exchange_group__isnull', False), _negated=True), name='recipe_item_optional_xor_exchange'),
        ),
        migrations.AddIndex(
            model_name='recipestep',
            index=models.Index(fields=['recipe', 'sort_order'], name='recipe_step_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipestep',
            constraint=models.UniqueConstraint(fields=('recipe', 'sort_order'), name='unique_recipe_step_sort_order'),
        ),
        migrations.AddIndex(
            model_name='recipestepingredient',
            index=models.Index(fields=['step', 'sort_order'], name='step_ingredient_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='recipestepingredient',
            index=models.Index(fields=['recipe_item'], name='recipe_item_steps_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipestepingredient',
            constraint=models.UniqueConstraint(fields=('step', 'recipe_item'), name='unique_step_recipe_item'),
        ),
    ]
