# Generated by Django 5.2.12 on 2026-04-06 18:46

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("recipe", "0001_initial"),
        ("supply", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="nutritional_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ernährungshinweise wie vegan, vegetarisch, etc.",
                related_name="recipes",
                to="supply.nutritionaltag",
                verbose_name="Ernährungstags",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="scout_levels",
            field=models.ManyToManyField(blank=True, related_name="%(class)s_set", to="content.scoutlevel"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(class)s_set", to="content.tag"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recipeitem",
            name="ingredient",
            field=models.ForeignKey(
                blank=True,
                help_text="Direkte Zutat (wenn keine Portion gewählt)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipe_items",
                to="supply.ingredient",
                verbose_name="Zutat",
            ),
        ),
        migrations.AddField(
            model_name="recipeitem",
            name="measuring_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="supply.measuringunit",
                verbose_name="Maßeinheit",
            ),
        ),
        migrations.AddField(
            model_name="recipeitem",
            name="portion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipe_items",
                to="supply.portion",
                verbose_name="Portion",
            ),
        ),
        migrations.AddField(
            model_name="recipeitem",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_items",
                to="recipe.recipe",
                verbose_name="Rezept",
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=django.contrib.postgres.indexes.GinIndex(fields=["search_vector"], name="recipe_search_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["status", "created_at"], name="recipe_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["recipe_type", "status", "created_at"], name="recipe_type_status_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["like_score"], name="recipe_like_score_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["view_count"], name="recipe_view_count_idx"),
        ),
    ]
