# Generated by Django 5.2.12 on 2026-07-17 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
        ('supply', '0004_remove_portion_is_system_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='portion',
            field=models.ForeignKey(blank=True, help_text='NULL = Gramm (quantity wird direkt als Gramm interpretiert)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='supply.portion', verbose_name='Portion'),
        ),
    ]
