# Generated by Django 5.2.12 on 2026-04-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cached_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Wann die gecachten Werte zuletzt berechnet wurden",
                null=True,
                verbose_name="Cache-Zeitpunkt",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_carbohydrate_g",
            field=models.FloatField(blank=True, null=True, verbose_name="Kohlenhydrate (g, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_energy_kj",
            field=models.FloatField(blank=True, null=True, verbose_name="Energie (kJ, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_fat_g",
            field=models.FloatField(blank=True, null=True, verbose_name="Fett (g, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_fibre_g",
            field=models.FloatField(blank=True, null=True, verbose_name="Ballaststoffe (g, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_nutri_class",
            field=models.IntegerField(
                blank=True, help_text="1=A, 2=B, 3=C, 4=D, 5=E", null=True, verbose_name="Nutri-Score Klasse (cached)"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_price_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Gesamtpreis (cached)"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_protein_g",
            field=models.FloatField(blank=True, null=True, verbose_name="Eiweiß (g, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_salt_g",
            field=models.FloatField(blank=True, null=True, verbose_name="Salz (g, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_sugar_g",
            field=models.FloatField(blank=True, null=True, verbose_name="Zucker (g, cached)"),
        ),
    ]
