# Generated by Django 5.2.12 on 2026-04-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_recipe_cache_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="z.B. 'Zuckergehalt pro Tag'", max_length=100, verbose_name="Name"),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                (
                    "parameter",
                    models.CharField(
                        help_text="z.B. 'energy_kj', 'sugar_g', 'price_total', 'nutri_class'",
                        max_length=50,
                        verbose_name="Parameter",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("meal_event", "Essensplan"),
                            ("day", "Tag"),
                            ("meal", "Mahlzeit"),
                            ("recipe", "Rezept"),
                            ("ingredient", "Zutat"),
                        ],
                        help_text="Auf welcher Ebene wird die Regel ausgewertet",
                        max_length=20,
                        verbose_name="Geltungsbereich",
                    ),
                ),
                (
                    "threshold_green",
                    models.FloatField(
                        help_text="Bis zu diesem Wert ist der Status grün", verbose_name="Schwellenwert Grün"
                    ),
                ),
                (
                    "threshold_yellow",
                    models.FloatField(
                        help_text="Bis zu diesem Wert ist der Status gelb, darüber rot",
                        verbose_name="Schwellenwert Gelb",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, default="", help_text="z.B. 'g', 'kJ', 'EUR'", max_length=20, verbose_name="Einheit"
                    ),
                ),
                (
                    "tip_text",
                    models.TextField(
                        blank=True, default="", help_text="Empfehlung bei Gelb/Rot-Status", verbose_name="Tipp-Text"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sortierung")),
            ],
            options={
                "verbose_name": "Gesundheitsregel",
                "verbose_name_plural": "Gesundheitsregeln",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
