# Generated by Django 5.2.12 on 2026-09-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0004_recipe_costs_per_person"),
        ("supply", "0006_cleanup_measuring_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeitem",
            name="client_request_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="recipeitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_request_id__isnull", False)),
                fields=("recipe", "client_request_id"),
                name="unique_recipe_item_client_request",
            ),
        ),
    ]
