# Generated by Django 5.2.12 on 2026-09-07 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0005_recipeitem_client_request_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeItemIdempotencyRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "operation",
                    models.CharField(
                        choices=[("create", "Create")], default="create", max_length=32, verbose_name="Operation"
                    ),
                ),
                ("request_key", models.CharField(max_length=64, verbose_name="Request-Key")),
                ("payload_hash", models.CharField(max_length=64, verbose_name="Payload-Hash")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_records",
                        to="recipe.recipe",
                        verbose_name="Rezept",
                    ),
                ),
                (
                    "recipe_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_records",
                        to="recipe.recipeitem",
                        verbose_name="Rezept-Zutat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_item_idempotency_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezept-Zutat Idempotenz-Eintrag",
                "verbose_name_plural": "Rezept-Zutat Idempotenz-Einträge",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "recipe", "operation", "request_key"),
                        name="unique_recipe_item_idempotency_scope",
                    )
                ],
            },
        ),
    ]
