# Generated by Django 5.2.12 on 2026-04-09 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_pg_trgm"),
        ("recipe", "0005_normalize_servings"),
        ("supply", "0003_alter_portion_options_portion_is_default_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="forked_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Referenz zum Original-Rezept bei persönlichen Kopien",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="recipe.recipe",
                verbose_name="Ursprungsrezept",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = Inspi-verifiziertes Rezept, gesetzt = persönliches Rezept",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Besitzer",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="visibility",
            field=models.CharField(
                blank=True,
                choices=[("private", "Privat"), ("group", "Gruppe"), ("public", "Öffentlich")],
                help_text="Nur relevant wenn owner gesetzt: private/group/public",
                max_length=10,
                null=True,
                verbose_name="Sichtbarkeit",
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["owner", "visibility", "status"], name="recipe_owner_vis_status_idx"),
        ),
    ]
