# Generated by Django 5.2.12 on 2026-04-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0006_recipe_forked_from_recipe_owner_recipe_visibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cached_calcium_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Calcium (mg, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_folate_ug",
            field=models.FloatField(blank=True, null=True, verbose_name="Folat (µg, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_iron_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Eisen (mg, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_magnesium_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Magnesium (mg, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_potassium_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Kalium (mg, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_vitamin_a_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Vitamin A (mg, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_vitamin_b12_ug",
            field=models.FloatField(blank=True, null=True, verbose_name="Vitamin B12 (µg, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_vitamin_c_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Vitamin C (mg, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_vitamin_d_ug",
            field=models.FloatField(blank=True, null=True, verbose_name="Vitamin D (µg, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_zinc_mg",
            field=models.FloatField(blank=True, null=True, verbose_name="Zink (mg, cached)"),
        ),
        migrations.AddField(
            model_name="recipehint",
            name="improvement_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Konkreter, umsetzbarer Verbesserungsvorschlag auf Deutsch",
                verbose_name="Verbesserungsvorschlag",
            ),
        ),
        migrations.AlterField(
            model_name="recipehint",
            name="parameter",
            field=models.CharField(
                choices=[
                    ("energy_kj", "Energie (kJ)"),
                    ("sugar_g", "Zucker (g)"),
                    ("sodium_mg", "Natrium (mg)"),
                    ("fibre_g", "Ballaststoffe (g)"),
                    ("fat_g", "Fett (g)"),
                    ("fat_sat_g", "Gesättigte Fettsäuren (g)"),
                    ("protein_g", "Eiweiß (g)"),
                    ("carbohydrate_g", "Kohlenhydrate (g)"),
                    ("salt_g", "Salz (g)"),
                    ("fructose_g", "Fructose (g)"),
                    ("lactose_g", "Laktose (g)"),
                    ("fruit_factor", "Obst-/Gemüse-Anteil"),
                    ("weight_g", "Gewicht (g)"),
                    ("nutri_class", "Nutri-Score Klasse"),
                    ("vitamin_a_mg", "Vitamin A (mg)"),
                    ("vitamin_c_mg", "Vitamin C (mg)"),
                    ("vitamin_d_ug", "Vitamin D (µg)"),
                    ("vitamin_b12_ug", "Vitamin B12 (µg)"),
                    ("folate_ug", "Folat (µg)"),
                    ("calcium_mg", "Calcium (mg)"),
                    ("iron_mg", "Eisen (mg)"),
                    ("magnesium_mg", "Magnesium (mg)"),
                    ("zinc_mg", "Zink (mg)"),
                    ("potassium_mg", "Kalium (mg)"),
                ],
                help_text="Nährwertfeld das geprüft wird",
                max_length=20,
                verbose_name="Parameter",
            ),
        ),
    ]
