# Generated by Django 5.2.12 on 2026-09-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0007_migrate_energy_kj_rules_to_energy_kcal"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cached_price_ingredient_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Anzahl Zutaten (Preisabdeckung, cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_price_missing_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Anzahl Zutaten ohne Preis (cached)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cached_price_priced_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Anzahl bepreiste Zutaten (cached)"),
        ),
    ]
