# Generated by Django 5.2.12 on 2026-05-26 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0007_recipe_cached_calcium_mg_recipe_cached_folate_ug_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeFolder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sortierung")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Besitzer",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="recipe.recipefolder",
                        verbose_name="Überordner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezept-Ordner",
                "verbose_name_plural": "Rezept-Ordner",
                "ordering": ["sort_order", "name"],
                "unique_together": {("owner", "name", "parent")},
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                help_text="Optionaler Ordner für persönliche Rezepte",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipes",
                to="recipe.recipefolder",
                verbose_name="Ordner",
            ),
        ),
    ]
