# Generated by Django 5.2.12 on 2026-05-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0008_recipe_folder_and_folder_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("breakfast", "Frühstück"),
                    ("warm_meal", "Warme Mahlzeit"),
                    ("cold_meal", "Kalte Mahlzeit"),
                    ("dessert", "Nachtisch"),
                    ("side_dish", "Beilage"),
                    ("snack", "Snack"),
                    ("drink", "Getränk"),
                    ("simple_meal", "Einfache Mahlzeit"),
                ],
                default="",
                help_text="Frühstück, Warme Mahlzeit, Snack, etc.",
                max_length=20,
                verbose_name="Rezepttyp",
            ),
        ),
        migrations.AlterField(
            model_name="recipehint",
            name="recipe_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("breakfast", "Frühstück"),
                    ("warm_meal", "Warme Mahlzeit"),
                    ("cold_meal", "Kalte Mahlzeit"),
                    ("dessert", "Nachtisch"),
                    ("side_dish", "Beilage"),
                    ("snack", "Snack"),
                    ("drink", "Getränk"),
                    ("simple_meal", "Einfache Mahlzeit"),
                ],
                default="",
                help_text="Optional: Gilt nur für diesen Rezepttyp",
                max_length=20,
                verbose_name="Rezepttyp",
            ),
        ),
    ]
