# Generated by Django 5.2.12 on 2026-09-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0008_recipe_cached_price_ingredient_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeitemidempotencyrecord",
            name="operation",
            field=models.CharField(
                choices=[("create", "Create"), ("replace", "Replace")],
                default="create",
                max_length=32,
                verbose_name="Operation",
            ),
        ),
    ]
