# Generated by Django 5.2.12 on 2026-09-26 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0014_aiinteraction_structured_retry"),
        ("profiles", "0002_initial"),
        ("recipe", "0009_alter_recipeitemidempotencyrecord_operation"),
        ("supply", "0017_portion_superseded_versions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="creation_idempotency_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Verhindert doppelte Rezepte bei wiederholtem Absenden.",
                max_length=100,
                verbose_name="Idempotenz-Schlüssel der Anlage",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="source_servings",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Personenzahl des Originalrezepts; Mengen sind trotzdem pro Portion gespeichert.",
                null=True,
                verbose_name="Original-Personenzahl",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                condition=models.Q(("creation_idempotency_key", ""), _negated=True),
                fields=("owner", "creation_idempotency_key"),
                name="unique_recipe_creation_idempotency_key",
            ),
        ),
    ]
