# Generated by Django 5.2.12 on 2026-05-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0009_simple_meal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrule",
            name="rule_type",
            field=models.CharField(
                choices=[("max", "Maximum (zu viel = schlecht)"), ("min", "Minimum (zu wenig = schlecht)")],
                default="max",
                help_text="'max' = Obergrenze (zu viel ist schlecht), 'min' = Untergrenze (zu wenig ist schlecht)",
                max_length=10,
                verbose_name="Regeltyp",
            ),
        ),
    ]
