# Generated by Django 5.2.12 on 2026-05-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0010_healthrule_rule_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthrule",
            name="rule_type",
        ),
        migrations.RemoveField(
            model_name="healthrule",
            name="threshold_green",
        ),
        migrations.RemoveField(
            model_name="healthrule",
            name="threshold_yellow",
        ),
        migrations.AddField(
            model_name="healthrule",
            name="max_green",
            field=models.FloatField(
                blank=True,
                help_text="Obergrenze für grünen Status (Wert muss <= sein)",
                null=True,
                verbose_name="Max Grün",
            ),
        ),
        migrations.AddField(
            model_name="healthrule",
            name="max_yellow",
            field=models.FloatField(
                blank=True, help_text="Obergrenze für gelben Status (darüber = rot)", null=True, verbose_name="Max Gelb"
            ),
        ),
        migrations.AddField(
            model_name="healthrule",
            name="min_green",
            field=models.FloatField(
                blank=True,
                help_text="Untergrenze für grünen Status (Wert muss >= sein)",
                null=True,
                verbose_name="Min Grün",
            ),
        ),
        migrations.AddField(
            model_name="healthrule",
            name="min_yellow",
            field=models.FloatField(
                blank=True,
                help_text="Untergrenze für gelben Status (darunter = rot)",
                null=True,
                verbose_name="Min Gelb",
            ),
        ),
    ]
