# Generated by Django 5.2.12 on 2026-10-10 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0010_recipe_source_servings"),
        ("supply", "0022_buffet_data_proposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeitem",
            name="ingredient",
            field=models.ForeignKey(
                blank=True,
                help_text="Zutat für direkte Gramm-Mengen ohne Portion",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="direct_recipe_items",
                to="supply.ingredient",
                verbose_name="Direkte Zutat",
            ),
        ),
    ]
