# Generated by Django 5.2.12 on 2026-05-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0011_health_rule_range_thresholds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="cached_calcium_mg",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cached_folate_ug",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cached_iron_mg",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cached_magnesium_mg",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cached_potassium_mg",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cached_vitamin_a_mg",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cached_vitamin_b12_ug",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cached_vitamin_d_ug",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cached_zinc_mg",
        ),
    ]
