# Generated by Django 5.2.12 on 2026-05-27 21:09

from django.db import migrations

REMOVED_PARAMETERS = [
    "vitamin_a_mg",
    "vitamin_b1_mg",
    "vitamin_b2_mg",
    "vitamin_b6_mg",
    "vitamin_b12_ug",
    "vitamin_d_ug",
    "vitamin_e_mg",
    "vitamin_k_ug",
    "niacin_mg",
    "folate_ug",
    "pantothenic_acid_mg",
    "biotin_ug",
    "calcium_mg",
    "iron_mg",
    "magnesium_mg",
    "zinc_mg",
    "potassium_mg",
    "phosphorus_mg",
    "iodine_ug",
    "selenium_ug",
    "copper_mg",
    "manganese_mg",
    "chromium_ug",
    "fluoride_mg",
]


def delete_micronutrient_rules(apps, schema_editor):
    HealthRule = apps.get_model("recipe", "HealthRule")
    HealthRule.objects.filter(parameter__in=REMOVED_PARAMETERS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0012_remove_recipe_cached_calcium_mg_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_micronutrient_rules, migrations.RunPython.noop),
    ]
