# Generated by Django 5.2.12 on 2026-05-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0013_delete_micronutrient_health_rules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipehint",
            name="max_value",
        ),
        migrations.RemoveField(
            model_name="recipehint",
            name="min_value",
        ),
        migrations.AddField(
            model_name="recipehint",
            name="hint",
            field=models.CharField(
                default="",
                help_text="Kurzer Text der dem User angezeigt wird, z.B. 'viel mehr Gewicht'",
                max_length=255,
                verbose_name="Hinweis-Text",
            ),
        ),
        migrations.AddField(
            model_name="recipehint",
            name="value",
            field=models.FloatField(default=0, help_text="Grenzwert für die Regel", verbose_name="Schwellenwert"),
        ),
        migrations.AlterField(
            model_name="recipehint",
            name="hint_level",
            field=models.CharField(
                choices=[("info", "Information"), ("warn", "Warnung"), ("error", "Fehler")],
                default="info",
                max_length=10,
                verbose_name="Hinweis-Stufe",
            ),
        ),
        migrations.AlterField(
            model_name="recipehint",
            name="min_max",
            field=models.CharField(
                choices=[("min", "Mindestens"), ("max", "Höchstens")],
                default="max",
                max_length=10,
                verbose_name="Regeltyp",
            ),
        ),
        migrations.AlterField(
            model_name="recipehint",
            name="parameter",
            field=models.CharField(
                choices=[
                    ("energy_kj", "Energie (kJ)"),
                    ("sugar_g", "Zucker (g)"),
                    ("sodium_mg", "Natrium (mg)"),
                    ("fibre_g", "Ballaststoffe (g)"),
                    ("fat_g", "Fett (g)"),
                    ("fat_sat_g", "Gesättigte Fettsäuren (g)"),
                    ("protein_g", "Eiweiß (g)"),
                    ("carbohydrate_g", "Kohlenhydrate (g)"),
                    ("salt_g", "Salz (g)"),
                    ("fructose_g", "Fructose (g)"),
                    ("lactose_g", "Laktose (g)"),
                    ("fruit_factor", "Obst-/Gemüse-Anteil"),
                    ("weight_g", "Gewicht (g)"),
                    ("nutri_class", "Nutri-Score Klasse"),
                    ("vitamin_c_mg", "Vitamin C (mg)"),
                ],
                help_text="Nährwertfeld das geprüft wird",
                max_length=20,
                verbose_name="Parameter",
            ),
        ),
        migrations.AlterField(
            model_name="recipehint",
            name="recipe_objective",
            field=models.CharField(
                choices=[
                    ("health", "Gesundheit"),
                    ("taste", "Geschmack"),
                    ("cost", "Kosten"),
                    ("fulfillment", "Sättigung"),
                ],
                default="",
                max_length=20,
                verbose_name="Bewertungsdimension",
            ),
        ),
        migrations.AlterField(
            model_name="recipehint",
            name="recipe_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Frühstück"),
                    ("warm_meal", "Warme Mahlzeit"),
                    ("cold_meal", "Kalte Mahlzeit"),
                    ("dessert", "Nachtisch"),
                    ("side_dish", "Beilage"),
                    ("snack", "Snack"),
                    ("drink", "Getränk"),
                    ("simple_meal", "Einfache Mahlzeit"),
                ],
                default="",
                max_length=20,
                verbose_name="Rezepttyp",
            ),
        ),
    ]
