# Generated by Django 5.2.12 on 2026-05-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0014_remove_recipehint_max_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipehint",
            name="parameter",
            field=models.CharField(
                choices=[
                    ("energy_kj", "Energie (kJ)"),
                    ("sugar_g", "Zucker (g)"),
                    ("sodium_mg", "Natrium (mg)"),
                    ("fibre_g", "Ballaststoffe (g)"),
                    ("fat_g", "Fett (g)"),
                    ("fat_sat_g", "Gesättigte Fettsäuren (g)"),
                    ("protein_g", "Eiweiß (g)"),
                    ("carbohydrate_g", "Kohlenhydrate (g)"),
                    ("salt_g", "Salz (g)"),
                    ("fructose_g", "Fructose (g)"),
                    ("lactose_g", "Laktose (g)"),
                    ("fruit_factor", "Obst-/Gemüse-Anteil"),
                    ("weight_g", "Gewicht (g)"),
                    ("nutri_class", "Nutri-Score Klasse"),
                    ("vitamin_c_mg", "Vitamin C (mg)"),
                    ("vitamin_a_mg", "Vitamin A (mg)"),
                    ("vitamin_d_ug", "Vitamin D (µg)"),
                    ("vitamin_b12_ug", "Vitamin B12 (µg)"),
                    ("calcium_mg", "Calcium (mg)"),
                    ("iron_mg", "Eisen (mg)"),
                    ("magnesium_mg", "Magnesium (mg)"),
                    ("potassium_mg", "Kalium (mg)"),
                    ("zinc_mg", "Zink (mg)"),
                    ("folate_ug", "Folsäure (µg)"),
                ],
                help_text="Nährwertfeld das geprüft wird",
                max_length=20,
                verbose_name="Parameter",
            ),
        ),
    ]
