# Generated by Django 5.2.12 on 2026-05-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0015_alter_recipehint_parameter"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="source_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Original-URL bei importierten Rezepten",
                max_length=500,
                verbose_name="Quell-URL",
            ),
        ),
    ]
