# Generated by Django 5.2.12 on 2026-05-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0019_recipe_item_portion_mandatory"),
        ("supply", "0017_fix_quantity_constraint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recipeitem",
            name="recipe_item_quantity_positive",
        ),
        migrations.AddConstraint(
            model_name="recipeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="recipe_item_quantity_positive"
            ),
        ),
    ]
