# Generated by Django 5.2.12 on 2026-05-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0020_fix_quantity_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="z.B. 'Zuckergehalt pro Tag'", max_length=100, verbose_name="Name"),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                (
                    "parameter",
                    models.CharField(
                        help_text="z.B. 'energy_kj', 'sugar_g', 'protein_g'", max_length=50, verbose_name="Parameter"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("meal_event", "Essensplan"),
                            ("day", "Tag"),
                            ("meal", "Mahlzeit"),
                            ("recipe", "Rezept"),
                        ],
                        help_text="Auf welcher Ebene wird die Regel ausgewertet",
                        max_length=20,
                        verbose_name="Geltungsbereich",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[("nutrition", "Nährwert")], default="nutrition", max_length=20, verbose_name="Regeltyp"
                    ),
                ),
                (
                    "min_green",
                    models.FloatField(
                        blank=True,
                        help_text="Untergrenze für grünen Status (Wert muss >= sein)",
                        null=True,
                        verbose_name="Min Grün",
                    ),
                ),
                (
                    "min_yellow",
                    models.FloatField(
                        blank=True,
                        help_text="Untergrenze für gelben Status (darunter = rot)",
                        null=True,
                        verbose_name="Min Gelb",
                    ),
                ),
                (
                    "max_green",
                    models.FloatField(
                        blank=True,
                        help_text="Obergrenze für grünen Status (Wert muss <= sein)",
                        null=True,
                        verbose_name="Max Grün",
                    ),
                ),
                (
                    "max_yellow",
                    models.FloatField(
                        blank=True,
                        help_text="Obergrenze für gelben Status (darüber = rot)",
                        null=True,
                        verbose_name="Max Gelb",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, default="", help_text="z.B. 'g', 'kJ', 'mg'", max_length=20, verbose_name="Einheit"
                    ),
                ),
                (
                    "hint_level",
                    models.CharField(
                        choices=[("info", "Info"), ("warn", "Warnung"), ("error", "Fehler")],
                        default="warn",
                        max_length=10,
                        verbose_name="Hinweis-Stufe",
                    ),
                ),
                (
                    "tip_text",
                    models.TextField(
                        blank=True, default="", help_text="Empfehlung bei Gelb/Rot-Status", verbose_name="Tipp-Text"
                    ),
                ),
                (
                    "improvement_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Konkreter, umsetzbarer Verbesserungsvorschlag",
                        verbose_name="Verbesserungsvorschlag",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sortierung")),
            ],
            options={
                "verbose_name": "Regel",
                "verbose_name_plural": "Regeln",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
