# Generated by Django 5.2.12 on 2026-05-31 13:50

from django.db import migrations


def migrate_health_rules(apps, schema_editor):
    """Migrate HealthRule entries to Rule model."""
    HealthRule = apps.get_model("recipe", "HealthRule")
    Rule = apps.get_model("recipe", "Rule")

    for hr in HealthRule.objects.all():
        Rule.objects.create(
            name=hr.name,
            description=hr.description,
            parameter=hr.parameter,
            scope=hr.scope,
            rule_type="nutrition",
            min_green=hr.min_green,
            min_yellow=hr.min_yellow,
            max_green=hr.max_green,
            max_yellow=hr.max_yellow,
            unit=hr.unit,
            hint_level="warn",
            tip_text=hr.tip_text,
            improvement_text="",
            is_active=hr.is_active,
            sort_order=hr.sort_order,
        )


def migrate_recipe_hints(apps, schema_editor):
    """Migrate RecipeHint entries to Rule model with scope=recipe."""
    RecipeHint = apps.get_model("recipe", "RecipeHint")
    Rule = apps.get_model("recipe", "Rule")

    for hint in RecipeHint.objects.all():
        # Map single-value threshold to range fields
        if hint.min_max == "min":
            # "min" means value should be >= threshold
            # hint_level "warn" → use as min_green, "error" → use as min_yellow
            if hint.hint_level == "error":
                min_yellow = hint.value
                min_green = None
            else:
                min_yellow = None
                min_green = hint.value
            max_green = None
            max_yellow = None
        else:
            # "max" means value should be <= threshold
            if hint.hint_level == "error":
                max_yellow = hint.value
                max_green = None
            else:
                max_yellow = None
                max_green = hint.value
            min_green = None
            min_yellow = None

        Rule.objects.create(
            name=hint.name or hint.hint,
            description=hint.description,
            parameter=hint.parameter,
            scope="recipe",
            rule_type="nutrition",
            min_green=min_green,
            min_yellow=min_yellow,
            max_green=max_green,
            max_yellow=max_yellow,
            unit="g" if hint.parameter.endswith("_g") else ("kJ" if "kj" in hint.parameter else "mg"),
            hint_level=hint.hint_level,
            tip_text=hint.hint,
            improvement_text=hint.improvement_text,
            is_active=True,
            sort_order=0,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0021_create_rule_model"),
    ]

    operations = [
        migrations.RunPython(migrate_health_rules, migrations.RunPython.noop),
        migrations.RunPython(migrate_recipe_hints, migrations.RunPython.noop),
    ]
