# Generated by Django 5.2.12 on 2026-05-31 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0022_migrate_healthrule_recipehint_to_rule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HealthRule",
        ),
        migrations.DeleteModel(
            name="RecipeHint",
        ),
    ]
