# Generated by Django 5.2.12 on 2026-05-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0023_remove_healthrule_recipehint"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="usage_count",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text="Wie oft dieses Rezept in Menüpläne eingefügt wurde (denormalisiert)",
                verbose_name="Verwendungsanzahl",
            ),
        ),
    ]
