# Generated by Django 5.2.12 on 2026-06-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0024_add_usage_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cached_energy_total_kj",
            field=models.FloatField(blank=True, null=True, verbose_name="Gesamtenergie (kJ, cached)"),
        ),
    ]
