# Generated by Django 5.2.12 on 2026-06-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0025_recipe_cached_energy_total_kj"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cached_weight_g",
            field=models.FloatField(blank=True, null=True, verbose_name="Gesamtgewicht (g, cached)"),
        ),
    ]
