# Generated by Django 5.2.12 on 2026-06-03 18:53

from django.db import migrations


def scale_energy_rules_to_kcal(apps, schema_editor):
    Rule = apps.get_model("recipe", "Rule")
    for rule in Rule.objects.filter(parameter="energy_kj").exclude(unit="kcal"):
        if rule.min_yellow is not None:
            rule.min_yellow = round(rule.min_yellow / 4.184, 1)
        if rule.min_green is not None:
            rule.min_green = round(rule.min_green / 4.184, 1)
        if rule.max_green is not None:
            rule.max_green = round(rule.max_green / 4.184, 1)
        if rule.max_yellow is not None:
            rule.max_yellow = round(rule.max_yellow / 4.184, 1)

        rule.unit = "kcal"

        if rule.tip_text:
            rule.tip_text = rule.tip_text.replace("kJ", "kcal")
        if rule.description:
            rule.description = rule.description.replace("kJ", "kcal")

        rule.save()


def unscale_energy_rules_from_kcal(apps, schema_editor):
    Rule = apps.get_model("recipe", "Rule")
    for rule in Rule.objects.filter(parameter="energy_kj").exclude(unit="kJ"):
        if rule.min_yellow is not None:
            rule.min_yellow = round(rule.min_yellow * 4.184, 1)
        if rule.min_green is not None:
            rule.min_green = round(rule.min_green * 4.184, 1)
        if rule.max_green is not None:
            rule.max_green = round(rule.max_green * 4.184, 1)
        if rule.max_yellow is not None:
            rule.max_yellow = round(rule.max_yellow * 4.184, 1)

        rule.unit = "kJ"

        if rule.tip_text:
            rule.tip_text = rule.tip_text.replace("kcal", "kJ")
        if rule.description:
            rule.description = rule.description.replace("kcal", "kJ")

        rule.save()


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0026_recipe_cached_weight_g"),
    ]

    operations = [
        migrations.RunPython(scale_energy_rules_to_kcal, unscale_energy_rules_from_kcal),
    ]
