# Generated by Django 5.2.12 on 2026-06-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0027_scale_energy_rules_to_kcal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("breakfast", "Frühstück"),
                    ("warm_meal", "Warme Mahlzeit"),
                    ("cold_meal", "Kalte Mahlzeit"),
                    ("dessert", "Nachtisch"),
                    ("side_dish", "Beilage"),
                    ("drink", "Getränk"),
                    ("simple_meal", "Einfache Mahlzeit"),
                ],
                default="",
                help_text="Frühstück, Warme Mahlzeit, etc.",
                max_length=20,
                verbose_name="Rezepttyp",
            ),
        ),
    ]
