# Generated by Django 5.2.12 on 2026-06-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0031_recipe_quality_score_recipe_quality_score_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="scope",
            field=models.CharField(
                choices=[("meal_plan", "Essensplan"), ("day", "Tag"), ("meal", "Mahlzeit"), ("recipe", "Rezept")],
                help_text="Auf welcher Ebene wird die Regel ausgewertet",
                max_length=20,
                verbose_name="Geltungsbereich",
            ),
        ),
    ]
