# Generated by Django 5.2.12 on 2026-06-18 23:05

from django.db import migrations


def migrate_rule_scope(apps, schema_editor):
    Rule = apps.get_model("recipe", "Rule")
    Rule.objects.filter(scope="meal_event").update(scope="meal_plan")


def reverse_rule_scope(apps, schema_editor):
    Rule = apps.get_model("recipe", "Rule")
    Rule.objects.filter(scope="meal_plan").update(scope="meal_event")


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0032_rename_rule_scope_meal_event_to_meal_plan"),
    ]

    operations = [
        migrations.RunPython(migrate_rule_scope, reverse_rule_scope),
    ]
