# Generated by Django 5.2.12 on 2026-06-19 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_contentcollaborator"),
        ("recipe", "0035_migrate_recipe_owner"),
        ("supply", "0031_material_is_deleted_alter_ingredient_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="recipe",
            name="recipe_owner_vis_status_idx",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="visibility",
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="status",
            field=models.CharField(
                choices=[("draft", "Entwurf"), ("verified", "Verifiziert")], default="draft", max_length=20
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["created_by", "status"], name="recipe_created_by_status_idx"),
        ),
    ]
