# Generated by Django 5.2.12 on 2026-06-20 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0034_remove_recipe_recipe_owner_vis_status_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="servings",
            new_name="portions",
        ),
    ]
