# Generated by Django 5.2.12 on 2026-06-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0035_rename_servings_to_portions"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeTypeStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "recipe_type",
                    models.CharField(
                        help_text="Einer der RecipeTypeChoices", max_length=20, unique=True, verbose_name="Rezepttyp"
                    ),
                ),
                ("count", models.IntegerField(default=0, verbose_name="Anzahl Rezepte")),
                ("price_min", models.FloatField(blank=True, null=True)),
                ("price_max", models.FloatField(blank=True, null=True)),
                ("price_avg", models.FloatField(blank=True, null=True)),
                ("price_median", models.FloatField(blank=True, null=True)),
                ("energy_min", models.FloatField(blank=True, null=True)),
                ("energy_max", models.FloatField(blank=True, null=True)),
                ("energy_avg", models.FloatField(blank=True, null=True)),
                ("energy_median", models.FloatField(blank=True, null=True)),
                ("protein_avg", models.FloatField(blank=True, null=True)),
                ("fat_avg", models.FloatField(blank=True, null=True)),
                ("carbs_avg", models.FloatField(blank=True, null=True)),
                ("weight_min", models.FloatField(blank=True, null=True)),
                ("weight_max", models.FloatField(blank=True, null=True)),
                ("weight_avg", models.FloatField(blank=True, null=True)),
                ("weight_median", models.FloatField(blank=True, null=True)),
                (
                    "nutri_score_dist",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"A": 5, "B": 12, "C": 18, "D": 8, "E": 4}',
                        verbose_name="Nutri-Score Verteilung",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rezepttyp-Statistik",
                "verbose_name_plural": "Rezepttyp-Statistiken",
                "db_table": "recipe_recipetypestats",
            },
        ),
    ]
