# Generated by Django 5.2.12 on 2026-06-21 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_delete_contentcollaborator"),
        ("recipe", "0036_recipetypestats"),
        ("supply", "0034_remove_ingredient_food_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecipeTypeStats",
        ),
        migrations.RemoveIndex(
            model_name="recipe",
            name="recipe_created_by_status_idx",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="recipe",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = Inspi-verifiziertes Rezept, gesetzt = persönliches Rezept",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Besitzer",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="visibility",
            field=models.CharField(
                blank=True,
                choices=[("private", "Privat"), ("group", "Gruppe"), ("public", "Öffentlich")],
                help_text="Nur relevant wenn owner gesetzt: private/group/public",
                max_length=10,
                null=True,
                verbose_name="Sichtbarkeit",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("submitted", "Eingereicht"),
                    ("approved", "Genehmigt"),
                    ("rejected", "Abgelehnt"),
                    ("archived", "Archiviert"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="scope",
            field=models.CharField(
                choices=[("meal_event", "Essensplan"), ("day", "Tag"), ("meal", "Mahlzeit"), ("recipe", "Rezept")],
                help_text="Auf welcher Ebene wird die Regel ausgewertet",
                max_length=20,
                verbose_name="Geltungsbereich",
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["owner", "visibility", "status"], name="recipe_owner_vis_status_idx"),
        ),
    ]
