# Generated by Django 5.2.12 on 2026-06-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0041_alter_recipe_recipe_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="costs_rating",
        ),
    ]
