# Generated by Django 5.2.12 on 2026-06-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0043_migrate_ingredient_recipes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("breakfast", "Frühstück"),
                    ("warm_meal", "Warme Mahlzeit"),
                    ("cold_meal", "Kalte Mahlzeit"),
                    ("dessert", "Nachtisch"),
                    ("recipe_part", "Rezeptteil"),
                    ("drink", "Getränk"),
                    ("snack", "Snack"),
                ],
                default="",
                help_text="Frühstück, Warme Mahlzeit, etc.",
                max_length=20,
                verbose_name="Rezepttyp",
            ),
        ),
    ]
