# Generated by Django 5.2.12 on 2026-06-24 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0044_alter_recipe_recipe_type"),
        ("supply", "0037_remove_ingredient_recipe_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeitem",
            name="exchange_position",
            field=models.IntegerField(
                blank=True, help_text="0 = Original/Default", null=True, verbose_name="Position in der Austausch-Gruppe"
            ),
        ),
        migrations.AddField(
            model_name="recipeitem",
            name="is_optional",
            field=models.BooleanField(
                default=False,
                help_text="Beim Einplanen entscheidet der Planer, ob die Zutat dabei ist",
                verbose_name="Optional",
            ),
        ),
        migrations.CreateModel(
            name="RecipeItemExchangeGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="z.B. 'Käse-Ersatz' — nur im Editor sichtbar",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_groups",
                        to="recipe.recipe",
                        verbose_name="Rezept",
                    ),
                ),
            ],
            options={
                "verbose_name": "Austausch-Gruppe",
                "verbose_name_plural": "Austausch-Gruppen",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="recipeitem",
            name="exchange_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="recipe.recipeitemexchangegroup",
                verbose_name="Austausch-Gruppe",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_optional", True), ("exchange_group__isnull", False), _negated=True),
                name="recipe_item_optional_xor_exchange",
            ),
        ),
    ]
