# Generated by Django 5.2.12 on 2026-06-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0045_recipeitem_exchange_position_recipeitem_is_optional_and_more"),
        ("supply", "0042_migrate_breakfast_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="manual_nutritional_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Manuell gesetzte Ernährungshinweise, bleiben bei Sync erhalten",
                related_name="manual_recipes",
                to="supply.nutritionaltag",
                verbose_name="Ernährungstags (manuell)",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="nutritional_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Aus Zutaten berechnete Ernährungshinweise (auto-synchronisiert)",
                related_name="recipes",
                to="supply.nutritionaltag",
                verbose_name="Ernährungstags (auto-synchronisiert)",
            ),
        ),
    ]
