# Generated by Django 5.2.12 on 2026-07-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0046_recipe_manual_nutritional_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='embedding_text_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the embedding text. Used to detect changes and avoid unnecessary regeneration.', max_length=64, null=True),
        ),
    ]
