# Generated by Django 5.2.12 on 2026-07-09 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_populate_user_roles'),
        ('recipe', '0048_recipe_shared_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='shared_groups',
            field=models.ManyToManyField(blank=True, help_text='Gruppen, mit denen dieses Rezept geteilt wird (relevant für breakfast wizard)', related_name='shared_recipes', to='profiles.usergroup', verbose_name='Geteilte Gruppen'),
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0, help_text='Sortierung der Schritte (0-indexed)', verbose_name='Reihenfolge')),
                ('instruction', models.TextField(help_text='Schritt-Text mit Platzhaltern: {ingredient_name} oder {uuid}', verbose_name='Anleitung')),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Ungefähre Dauer für diesen Schritt', null=True, verbose_name='Dauer (Minuten)')),
                ('section', models.CharField(blank=True, default='', help_text="Optional: Gruppierung (z.B. 'Vorbereitung', 'Kochen')", max_length=255, verbose_name='Sektion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipe.recipe', verbose_name='Rezept')),
            ],
            options={
                'verbose_name': 'Rezept-Schritt',
                'verbose_name_plural': 'Rezept-Schritte',
                'ordering': ['recipe', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStepIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_modifier', models.FloatField(default=1.0, help_text='Multiplikator: z.B. 0.5 = halbe Menge, 2.0 = doppelte Menge', verbose_name='Mengenmodifizierer')),
                ('preparation', models.CharField(blank=True, default='', help_text="Schritt-spezifische Vorbereitung: z.B. 'würfeln', 'geraffelt'", max_length=255, verbose_name='Vorbereitung')),
                ('sort_order', models.IntegerField(default=0, help_text='Sortierung innerhalb des Schritts', verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert')),
                ('recipe_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_assignments', to='recipe.recipeitem', verbose_name='Rezept-Zutat')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_ingredients', to='recipe.recipestep', verbose_name='Schritt')),
            ],
            options={
                'verbose_name': 'Schritt-Zutat',
                'verbose_name_plural': 'Schritt-Zutaten',
                'ordering': ['step', 'sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='recipestep',
            index=models.Index(fields=['recipe', 'sort_order'], name='recipe_step_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipestep',
            constraint=models.UniqueConstraint(fields=('recipe', 'sort_order'), name='unique_recipe_step_sort_order'),
        ),
        migrations.AddIndex(
            model_name='recipestepingredient',
            index=models.Index(fields=['step', 'sort_order'], name='step_ingredient_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='recipestepingredient',
            index=models.Index(fields=['recipe_item'], name='recipe_item_steps_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipestepingredient',
            constraint=models.UniqueConstraint(fields=('step', 'recipe_item'), name='unique_step_recipe_item'),
        ),
    ]
