# Generated by Django 5.2.12 on 2026-07-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0050_normalize_invalid_recipe_types"),
        ("supply", "0063_seed_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="equipment",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="supply.equipment", verbose_name="Equipment"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="preparation_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cooking", "Kochen"),
                    ("baking", "Backen"),
                    ("frying", "Braten"),
                    ("grilling", "Grillen"),
                    ("raw", "Rohkost"),
                    ("none", "Keine Zubereitung"),
                ],
                default="",
                max_length=50,
                verbose_name="Zubereitungsart",
            ),
        ),
    ]
