"""Seed comprehensive DGE-based rules for the suggestion system.

Values are based on DGE (Deutsche Gesellschaft für Ernährung) recommendations
for adolescents aged 13-18, which is the primary target group for scout camps.

Usage:
    uv run python manage.py seed_rules
    uv run python manage.py seed_rules --clear  # Remove all existing rules first
"""

from django.core.management.base import BaseCommand

from recipe.models import Rule


# DGE reference values for 13-18 year olds, per day
RULES_DATA = [
    # --- Day-level rules (most important) ---
    {
        "name": "Energie",
        "parameter": "energy_kj",
        "scope": "day",
        "min_green": 1912,
        "min_yellow": 1554,
        "max_green": 2629,
        "max_yellow": 3107,
        "unit": "kcal",
        "sort_order": 1,
        "tip_text": "DGE empfiehlt 1912-2629 kcal/Tag für 13-18-Jährige bei moderater Aktivität",
    },
    {
        "name": "Eiweiß",
        "parameter": "protein_g",
        "scope": "day",
        "min_green": 45,
        "min_yellow": 35,
        "max_green": 80,
        "max_yellow": 100,
        "unit": "g",
        "sort_order": 2,
        "tip_text": "45-80g Eiweiß pro Tag sind empfohlen. Hülsenfrüchte, Milchprodukte und Fleisch sind gute Quellen.",
    },
    {
        "name": "Fett",
        "parameter": "fat_g",
        "scope": "day",
        "min_green": 55,
        "min_yellow": 40,
        "max_green": 85,
        "max_yellow": 100,
        "unit": "g",
        "sort_order": 3,
        "tip_text": "55-85g Fett pro Tag (max 30% der Energie). Pflanzliche Öle bevorzugen.",
    },
    {
        "name": "Kohlenhydrate",
        "parameter": "carbohydrate_g",
        "scope": "day",
        "min_green": 250,
        "min_yellow": 200,
        "max_green": 400,
        "max_yellow": 450,
        "unit": "g",
        "sort_order": 4,
        "tip_text": "250-400g Kohlenhydrate pro Tag (mind. 50% der Energie). Vollkornprodukte bevorzugen.",
    },
    {
        "name": "Zucker",
        "parameter": "sugar_g",
        "scope": "day",
        "min_green": None,
        "min_yellow": None,
        "max_green": 50,
        "max_yellow": 75,
        "unit": "g",
        "sort_order": 5,
        "tip_text": "Max 50g freier Zucker pro Tag (WHO). Süße Getränke und Süßigkeiten reduzieren.",
    },
    {
        "name": "Ballaststoffe",
        "parameter": "fibre_g",
        "scope": "day",
        "min_green": 25,
        "min_yellow": 18,
        "max_green": None,
        "max_yellow": None,
        "unit": "g",
        "sort_order": 6,
        "tip_text": "Mind. 25g Ballaststoffe pro Tag. Vollkorn, Gemüse und Hülsenfrüchte helfen.",
    },
    {
        "name": "Salz",
        "parameter": "salt_g",
        "scope": "day",
        "min_green": None,
        "min_yellow": None,
        "max_green": 5,
        "max_yellow": 7,
        "unit": "g",
        "sort_order": 7,
        "tip_text": "Max 5g Salz pro Tag (WHO). Fertigprodukte und Wurst enthalten viel Salz.",
    },
    {
        "name": "Gesättigte Fettsäuren",
        "parameter": "fat_sat_g",
        "scope": "day",
        "min_green": None,
        "min_yellow": None,
        "max_green": 25,
        "max_yellow": 35,
        "unit": "g",
        "sort_order": 8,
        "tip_text": "Gesättigte Fettsäuren niedrig halten. Pflanzliche Öle, Nüsse und Gemüsegerichte bevorzugen.",
    },
    {
        "name": "Natrium",
        "parameter": "sodium_mg",
        "scope": "day",
        "min_green": None,
        "min_yellow": None,
        "max_green": 2000,
        "max_yellow": 2800,
        "unit": "mg",
        "sort_order": 9,
        "tip_text": "Maximal etwa 2000mg Natrium pro Tag. Würzmischungen, Brühe und Fertigprodukte sparsam verwenden.",
    },
    {
        "name": "Preis pro Tag",
        "parameter": "price_total",
        "scope": "day",
        "min_green": None,
        "min_yellow": None,
        "max_green": 4.5,
        "max_yellow": 6.0,
        "unit": "€",
        "sort_order": 20,
        "tip_text": "Der Tagespreis pro Person sollte im Lagerbudget bleiben. Teure Zutaten durch günstigere Alternativen ersetzen.",
    },
    {
        "name": "Lebensmittelmenge pro Tag",
        "parameter": "weight_g",
        "scope": "day",
        "min_green": 1500,
        "min_yellow": 1200,
        "max_green": 2400,
        "max_yellow": 2800,
        "unit": "g",
        "sort_order": 21,
        "tip_text": "Die Tagesmenge sollte satt machen, aber realistisch bleiben. Snacks, Getränke und Beilagen mitdenken.",
    },
    {
        "name": "Nutri-Score (Tag)",
        "parameter": "nutri_class",
        "scope": "day",
        "min_green": None,
        "min_yellow": None,
        "max_green": 2.5,
        "max_yellow": 3.5,
        "unit": "",
        "sort_order": 22,
        "tip_text": "Der Tagesdurchschnitt sollte bei A bis B liegen. Gemüse, Vollkorn und Hülsenfrüchte verbessern den Schnitt.",
    },
    # Micronutrients (day-level)
    {
        "name": "Calcium",
        "parameter": "calcium_mg",
        "scope": "day",
        "min_green": 1000,
        "min_yellow": 750,
        "max_green": None,
        "max_yellow": None,
        "unit": "mg",
        "sort_order": 10,
        "tip_text": "Mind. 1000mg Calcium pro Tag. Milchprodukte, grünes Gemüse, Mineralwasser.",
    },
    {
        "name": "Eisen",
        "parameter": "iron_mg",
        "scope": "day",
        "min_green": 12,
        "min_yellow": 8,
        "max_green": None,
        "max_yellow": None,
        "unit": "mg",
        "sort_order": 11,
        "tip_text": "Mind. 12mg Eisen pro Tag. Fleisch, Hülsenfrüchte, Vollkorn. Vitamin C fördert Aufnahme.",
    },
    {
        "name": "Vitamin C",
        "parameter": "vitamin_c_mg",
        "scope": "day",
        "min_green": 90,
        "min_yellow": 60,
        "max_green": None,
        "max_yellow": None,
        "unit": "mg",
        "sort_order": 12,
        "tip_text": "Mind. 90mg Vitamin C pro Tag. Frisches Obst und Gemüse bei jeder Mahlzeit.",
    },
    # --- Event-level rules (averages) ---
    {
        "name": "Energie (Durchschnitt)",
        "parameter": "energy_kj",
        "scope": "meal_event",
        "min_green": 1912,
        "min_yellow": 1554,
        "max_green": 2629,
        "max_yellow": 3107,
        "unit": "kcal",
        "sort_order": 1,
        "tip_text": "Der Energiedurchschnitt über alle Tage sollte im Zielbereich von 1912-2629 kcal liegen.",
    },
    {
        "name": "Eiweiß (Durchschnitt)",
        "parameter": "protein_g",
        "scope": "meal_event",
        "min_green": 45,
        "min_yellow": 35,
        "max_green": 80,
        "max_yellow": 100,
        "unit": "g",
        "sort_order": 2,
        "tip_text": "Der Eiweißdurchschnitt über alle Tage sollte 45-80g betragen.",
    },
    {
        "name": "Zucker (Durchschnitt)",
        "parameter": "sugar_g",
        "scope": "meal_event",
        "min_green": None,
        "min_yellow": None,
        "max_green": 50,
        "max_yellow": 75,
        "unit": "g",
        "sort_order": 3,
        "tip_text": "Der tägliche Zuckerdurchschnitt sollte unter 50g pro Person liegen.",
    },
    {
        "name": "Ballaststoffe (Durchschnitt)",
        "parameter": "fibre_g",
        "scope": "meal_event",
        "min_green": 25,
        "min_yellow": 18,
        "max_green": None,
        "max_yellow": None,
        "unit": "g",
        "sort_order": 4,
        "tip_text": "Der Ballaststoffdurchschnitt sollte mindestens 25g pro Tag erreichen.",
    },
    {
        "name": "Preis (Durchschnitt)",
        "parameter": "price_total",
        "scope": "meal_event",
        "min_green": None,
        "min_yellow": None,
        "max_green": 4.5,
        "max_yellow": 5.5,
        "unit": "€",
        "sort_order": 5,
        "tip_text": "Der durchschnittliche Tagespreis pro Person sollte im Zielbereich bleiben.",
    },
    {
        "name": "Nutri-Score (Durchschnitt)",
        "parameter": "nutri_class",
        "scope": "meal_event",
        "min_green": None,
        "min_yellow": None,
        "max_green": 2.5,
        "max_yellow": 3.5,
        "unit": "",
        "sort_order": 6,
        "tip_text": "Der durchschnittliche Nutri-Score des Plans sollte bei A bis B liegen.",
    },
    # --- Meal-level rules ---
    {
        "name": "Energie (Mahlzeit)",
        "parameter": "energy_kj",
        "scope": "meal",
        "min_green": 478,
        "min_yellow": 359,
        "max_green": 956,
        "max_yellow": 1195,
        "unit": "kcal",
        "sort_order": 1,
        "tip_text": "Eine Mahlzeit sollte 478-956 kcal liefern.",
    },
    {
        "name": "Zucker (Mahlzeit)",
        "parameter": "sugar_g",
        "scope": "meal",
        "min_green": None,
        "min_yellow": None,
        "max_green": 20,
        "max_yellow": 30,
        "unit": "g",
        "sort_order": 2,
        "tip_text": "Max 20g Zucker pro Mahlzeit. Süße Soßen und Desserts beachten.",
    },
    {
        "name": "Eiweiß (Mahlzeit)",
        "parameter": "protein_g",
        "scope": "meal",
        "min_green": 15,
        "min_yellow": 8,
        "max_green": None,
        "max_yellow": None,
        "unit": "g",
        "sort_order": 3,
        "tip_text": "Eine Mahlzeit sollte ausreichend Eiweiß liefern. Hülsenfrüchte, Milchprodukte, Eier oder Fleisch ergänzen.",
    },
    {
        "name": "Ballaststoffe (Mahlzeit)",
        "parameter": "fibre_g",
        "scope": "meal",
        "min_green": 6,
        "min_yellow": 3,
        "max_green": None,
        "max_yellow": None,
        "unit": "g",
        "sort_order": 4,
        "tip_text": "Mehr Ballaststoffe durch Vollkorn, Gemüse oder Hülsenfrüchte einplanen.",
    },
    {
        "name": "Gesättigte Fettsäuren (Mahlzeit)",
        "parameter": "fat_sat_g",
        "scope": "meal",
        "min_green": None,
        "min_yellow": None,
        "max_green": 10,
        "max_yellow": 15,
        "unit": "g",
        "sort_order": 5,
        "tip_text": "Gesättigte Fettsäuren pro Mahlzeit begrenzen. Sahne, Käse und Wurst sparsam einsetzen.",
    },
    {
        "name": "Natrium (Mahlzeit)",
        "parameter": "sodium_mg",
        "scope": "meal",
        "min_green": None,
        "min_yellow": None,
        "max_green": 700,
        "max_yellow": 1000,
        "unit": "mg",
        "sort_order": 6,
        "tip_text": "Natrium pro Mahlzeit reduzieren. Kräuter, Gemüse und selbstgemachte Soßen bevorzugen.",
    },
    {
        "name": "Preis (Mahlzeit)",
        "parameter": "price_total",
        "scope": "meal",
        "min_green": None,
        "min_yellow": None,
        "max_green": 2.5,
        "max_yellow": 4.0,
        "unit": "€",
        "sort_order": 7,
        "tip_text": "Die Mahlzeit ist teuer. Günstigere Proteinquellen oder saisonales Gemüse prüfen.",
    },
    {
        "name": "Gewicht (Mahlzeit)",
        "parameter": "weight_g",
        "scope": "meal",
        "min_green": 450,
        "min_yellow": 300,
        "max_green": 850,
        "max_yellow": 1100,
        "unit": "g",
        "sort_order": 8,
        "tip_text": "Die Mahlzeit sollte als Gesamtportion realistisch sättigen, ohne zu groß zu werden.",
    },
    {
        "name": "Nutri-Score (Mahlzeit)",
        "parameter": "nutri_class",
        "scope": "meal",
        "min_green": None,
        "min_yellow": None,
        "max_green": 2.5,
        "max_yellow": 3.5,
        "unit": "",
        "sort_order": 9,
        "tip_text": "Die Mahlzeit sollte im Schnitt A bis B erreichen. Gemüse und Vollkorn als Ausgleich nutzen.",
    },
    # --- Recipe-level rules ---
    {
        "name": "Eiweiß (Rezept)",
        "parameter": "protein_g",
        "scope": "recipe",
        "min_green": 30,
        "min_yellow": 20,
        "max_green": None,
        "max_yellow": None,
        "unit": "g",
        "sort_order": 1,
        "tip_text": "Rezepte sollten mind. 30g Eiweiß pro Portion enthalten.",
    },
    {
        "name": "Zucker (Rezept)",
        "parameter": "sugar_g",
        "scope": "recipe",
        "min_green": None,
        "min_yellow": None,
        "max_green": 20,
        "max_yellow": 30,
        "unit": "g",
        "sort_order": 2,
        "tip_text": "Max 20g Zucker pro Portion. Natürliche Süße bevorzugen.",
    },
    {
        "name": "Gesättigte Fettsäuren (Rezept)",
        "parameter": "fat_sat_g",
        "scope": "recipe",
        "min_green": None,
        "min_yellow": None,
        "max_green": 20,
        "max_yellow": 25,
        "unit": "g",
        "sort_order": 3,
        "tip_text": "Max 20g gesättigte Fettsäuren pro Portion. Pflanzliche Fette bevorzugen.",
    },
    {
        "name": "Natrium (Rezept)",
        "parameter": "sodium_mg",
        "scope": "recipe",
        "min_green": None,
        "min_yellow": None,
        "max_green": 500,
        "max_yellow": 700,
        "unit": "mg",
        "sort_order": 4,
        "tip_text": "Max 500mg Natrium pro Portion. Kräuter statt Salz verwenden.",
    },
    {
        "name": "Ballaststoffe (Rezept)",
        "parameter": "fibre_g",
        "scope": "recipe",
        "min_green": 5,
        "min_yellow": 3,
        "max_green": None,
        "max_yellow": None,
        "unit": "g",
        "sort_order": 5,
        "tip_text": "Mind. 5g Ballaststoffe pro Portion. Vollkorn und Gemüse verwenden.",
    },
    {
        "name": "Preis (Rezept)",
        "parameter": "price_total",
        "scope": "recipe",
        "min_green": None,
        "min_yellow": None,
        "max_green": 1.5,
        "max_yellow": 2.5,
        "unit": "€",
        "sort_order": 6,
        "tip_text": "Das Rezept ist pro Portion teuer. Saisonale Zutaten oder günstigere Proteinquellen prüfen.",
    },
    {
        "name": "Gewicht (Rezept)",
        "parameter": "weight_g",
        "scope": "recipe",
        "min_green": 350,
        "min_yellow": 250,
        "max_green": 750,
        "max_yellow": 950,
        "unit": "g",
        "sort_order": 7,
        "tip_text": "Eine Portion sollte realistisch sättigen. Bei sehr kleinen Portionen Beilage ergänzen.",
    },
    {
        "name": "Nutri-Score (Rezept)",
        "parameter": "nutri_class",
        "scope": "recipe",
        "min_green": None,
        "min_yellow": None,
        "max_green": 2,
        "max_yellow": 3,
        "unit": "",
        "sort_order": 8,
        "tip_text": "Rezepte sollten möglichst Nutri-Score A oder B erreichen. Gemüse, Hülsenfrüchte und Vollkorn verbessern den Score.",
    },
    {
        "name": "Energie (Rezept)",
        "parameter": "energy_kj",
        "scope": "recipe",
        "min_green": 430,
        "min_yellow": 287,
        "max_green": 1004,
        "max_yellow": 1243,
        "unit": "kcal",
        "sort_order": 9,
        "tip_text": "Eine Hauptmahlzeit sollte genug Energie liefern (430-1004 kcal), aber nicht zu schwer werden.",
    },
    {
        "name": "Fett (Rezept)",
        "parameter": "fat_g",
        "scope": "recipe",
        "min_green": 8,
        "min_yellow": 4,
        "max_green": 35,
        "max_yellow": 50,
        "unit": "g",
        "sort_order": 10,
        "tip_text": "Fettmenge ausgewogen halten. Pflanzliche Öle bevorzugen und sehr fettige Zutaten reduzieren.",
    },
]


class Command(BaseCommand):
    help = "Seed DGE-based rules for the suggestion system"

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Remove all existing rules before seeding",
        )

    def handle(self, *args, **options):
        if options["clear"]:
            count = Rule.objects.count()
            Rule.objects.all().delete()
            self.stdout.write(f"Deleted {count} existing rules.")

        created = 0
        updated = 0

        for rule_data in RULES_DATA:
            obj, was_created = Rule.objects.update_or_create(
                parameter=rule_data["parameter"],
                scope=rule_data["scope"],
                name=rule_data["name"],
                defaults={
                    "min_green": rule_data.get("min_green"),
                    "min_yellow": rule_data.get("min_yellow"),
                    "max_green": rule_data.get("max_green"),
                    "max_yellow": rule_data.get("max_yellow"),
                    "unit": rule_data.get("unit", ""),
                    "sort_order": rule_data.get("sort_order", 0),
                    "tip_text": rule_data.get("tip_text", ""),
                    "is_active": True,
                    "rule_type": "nutrition",
                },
            )
            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded {created} new rules, updated {updated} existing rules. "
                f"Total: {Rule.objects.count()} rules."
            )
        )
